Error correction methods for creating Bicycle and Unicycle codes + belief decoder code evaluation
QuantumSavory/QuantumClifford.jl pull request #195
Opened 2023-10-31 23:45 UTC by Benzillaist

Added multiple methods:

code_generation:
- Methods for creating Bicycle and Unicycle codes
- Methods for assembling CSS codes
- Utility methods for working with codes

code_evaluation:
- Methods for evaluating codes with a belief propagation decoder
- Methods for plotting codes given error rates

ECC.jl was modified to include the required imports for the two added files.

2023-11-02 19:34 UTC, Krastanov commented on src/ecc/ECC.jl
> +    isdegenerate, faults_matrix, CSS_Code, Bicycle_Code, Unicycle_Code, Circ2BicycleH0,
some naming conventions: `CSS_Code` should be `CSSCode`, same for Bicycle and Unicycle; use `To` not `2`

2023-11-02 19:35 UTC, Krastanov commented on src/ecc/ECC.jl
> +    create_lookup_table, evaluate_code_decoder_w_ecirc_pf, plot_code_performance, pf_encoding_plot
Exporting all these new things implies they are part of the public stable API, and we can not modify them without making a breaking release; I would prefer to be much more conservative in what we export. Which of these are things that the end user definitely needs? The "maybe needs" and "does not need" should not be exported for now.

2023-11-02 19:37 UTC, Krastanov commented on src/ecc/code_generation.jl
> +    - d: Code distance"""
there does not seem to be a `d` parameter in the struct. Also distance is usually unknown for most codes

2023-11-02 19:37 UTC, Krastanov commented on src/ecc/code_generation.jl
> +    - n: Block length
n can be deduced from tab or stab, so no need to keep it here. There is a `code_n` you can define a method for

2023-11-02 19:38 UTC, Krastanov commented on src/ecc/code_generation.jl
> +    - stab: Stabilizer of the parity check matrix
stab can be deduced from tab, so let's just keep tab for now, no need to duplicate it

2023-11-02 19:39 UTC, Krastanov commented on src/ecc/code_generation.jl
> +function ReduceBicycle(H0::Matrix{Bool})
naming conventions: keep functions in `snake_case`, not `CamelCase` (unless they are constructors)

2023-11-02 19:40 UTC, Krastanov commented on src/ecc/code_generation.jl
> +function AssembleCSS(H::Matrix{Bool}, G::Matrix{Bool})::CSS
This should be just a CCS constructor, no need to introduce a new function. I.e. rename `AssembleCSS` to `CSS`

2023-11-02 19:42 UTC, Krastanov commented on src/ecc/code_generation.jl
> +function GetCodeTableau(ecc::Matrix{Bool})
do not create a string just to parse it afterwards, it is much simpler to directly use a `Tableau` or `Stabilizer` constructor (there is one that takes two boolean matrices)

2023-11-02 19:43 UTC, Krastanov commented on src/ecc/code_generation.jl
> +function GetXTableau(ecc::Matrix{Bool})
You can just do `ecc[:, 1:end÷2]` which would also have the benefit of being sufficiently easy to write/read that you do not need a dedicated function for it.

2023-11-02 19:45 UTC, Krastanov commented on src/ecc/code_generation.jl
> +tableau(c::CSS) = c.tab
this word (`tableau`) usually refers to a matrix made of Pauli operators, not a matrix made of booleans

2023-11-02 19:46 UTC, Krastanov commented on src/ecc/ECC.jl
> +    create_lookup_table, evaluate_code_decoder_w_ecirc_pf, plot_code_performance, pf_encoding_plot
also, I think you are exporting a few names that are not actually defined here (e.g. `pf_encoding_plot`)

2023-11-02 19:49 UTC, Krastanov commented
This is pretty exciting! I left a bunch of comments in, but they are mostly on coding conventions, not on the substance of the PR.

I would suggest putting the CCS things in a separate file called `css.jl` and then the bicycle and unicycle codes in a file `uni_bi_cycle_codes.jl` or something like that. The name `code_generation.jl` is much too general, while the content is just for a few specific codes.

We should think of adding some tests, but we can discuss this later.

2023-11-08 18:45 UTC, Krastanov commented on src/ecc/css.jl
> +    - tab: Boolean matrix with the X part taking up the left side and the Z part taking up the right side"""
The inside components of a struct should be considered private (and thus not documented in user-facing documentation). Only get/set-like interfaces should be considered public because (a) they are more universal, (b) internal structure can now change without breaking user code.

2023-11-08 18:49 UTC, Krastanov commented on src/ecc/css.jl
> +function CSS(H::Matrix{Bool}, G::Matrix{Bool})::CSS
avoid adding too much type constraints in methods. Maybe someone would define an object that has the `Matrix{Bool}` interface but is of different type. That object could in principle still work here. Type signatures in methods are there to specify dispatch rules, nothing more -- the compiler can then infer types that this works with and compile a fast version for each type.

2023-11-08 18:50 UTC, Krastanov commented on src/ecc/css.jl
> +function CSS end
not necessary. `CSS` already exists as a default constructor, and you can just define extra methods for it (as you do below)

2023-11-08 18:51 UTC, Krastanov commented on src/ecc/css.jl
> +get_xzs(c::CSS) = c.tab
it does not seem this is used anywhere, so I am deleting it

2023-11-08 18:52 UTC, Krastanov commented on src/ecc/css.jl
> +    pcm_stab = Stabilizer(fill(0x0, Hy+Gy), GetXTableau(comp_matrix), GetZTableau(comp_matrix))
it does not seem getxtableau and so on are defined

2023-11-08 19:01 UTC, Krastanov commented
I did some minor cleanup along the lines of the comments I just posted. Make sure you pull locally before you continue modifying.

Also, it is helpful to always create a separate branch when making modifications. Currently all of this seems to be on your master branch which makes it difficult for you to experiment with multiple things at the same time.

I think there are still some things not functional in simple_sparse_codes.jl

When you address a comment, please also click "resolve" on it, as it makes it easier for me to review.

I will mark this as a draft. When you are ready for the next round of reviews, just mark it back to not-a-draft.

2023-12-16 07:37 UTC, Krastanov commented
Ben, I just now noticed that you had actually marked this as ready for review for quite a while. I apologize for my oversight! Could you click "resolve conversation" on the comments you have addressed in the follow-up edits? That would make it much easier for me to finish the review.

2023-12-17 21:29 UTC, Benzillaist commented
Hi Stefan, I apologize for not informing you that I pushed an update. I believe that my most recent commits should resolve any problems. I also tested my code to ensure it works, but please let me know if I've made any glaring errors!

2023-12-18 18:23 UTC, Krastanov requested changes
I added a few more comments. This will also need tests before we can merge it. In particular, tests for whether the generated codes are valid.

One possible type of tests is to just check exactly for the parity check matrix of known small codes.

Another type of tests to add is tests for random large codes verifying they produce valid tableaux.

2023-12-18 18:23 UTC, Krastanov commented on src/ecc/css.jl
> +    Stabilizer(fill(0x0, size(c.tab, 2)), c.tab[:,1:end÷2], c.tab[:,end÷2+1:end])
This will probably just take the code that is currently in your constructor above

2023-12-18 18:23 UTC, Krastanov commented on src/ecc/simple_sparse_codes.jl
> +Circ2UnicycleH0([1, 2, 4], 7)
```suggestion
`Circ2UnicycleH0([1, 2, 4], 7)`
```

2023-12-18 18:23 UTC, Krastanov commented on src/ecc/ECC.jl
> +using LinearAlgebra: rank
```suggestion
```

Already imported above

2023-12-18 18:23 UTC, Krastanov commented on src/ecc/ECC.jl
> +include("simple_sparse_codes.jl")
move these two to the `codes` folder

2023-12-18 18:23 UTC, Krastanov commented on src/ecc/simple_sparse_codes.jl
> +ReduceUnicycle(Circ2UnicycleH0(array_indices, block length) )"""
```suggestion
`ReduceUnicycle(Circ2UnicycleH0(array_indices, block length) )`"""
```

2023-12-18 18:24 UTC, Krastanov commented
I also noticed that you are working on your master branch. That makes work generally more difficult, as it is cumbersome to keep things in sync with the main repository.

2023-12-18 18:27 UTC, Krastanov commented
@amicciche , skim through the CSS definition that Ben is making here. Just making sure you guys are not duplicating work that is done by the other.

2023-12-18 19:11 UTC, amicciche commented
> @amicciche , skim through the CSS definition that Ben is making here. Just making sure you guys are not duplicating work that is done by the other.

My definition of a CSS struct was the bare minimum to get the idea of the functionality implemented quickly. In other words, it was sort of a functional placeholder. Here it is in its entirety:
```julia
struct CSS; tableau; cx; cz; end
```
Ben's version seems to be a bit more detailed and fleshed out, and could easily just replace my version. I do have some code that was not included in my pull request that coverts the matrices into a stabilizer tableau, and perhaps could be part of the CSS struct?

2023-12-19 07:15 UTC, Benzillaist commented on src/ecc/css.jl
> +    tab
Will do, I made some slight modifications to what you wrote which is why I didn't immediately commit your changes.

2023-12-19 07:15 UTC, Benzillaist commented on src/ecc/css.jl
> +code_n(c::CSS) = size(c.tab,2)÷2
Thank you, fixed

2023-12-19 07:16 UTC, Benzillaist commented on src/ecc/css.jl
> +    Hy, Hx = size(H)
I updated this to work with the updated struct

2023-12-19 07:17 UTC, Benzillaist commented on src/ecc/css.jl
> +    Stabilizer(fill(0x0, size(c.tab, 2)), c.tab[:,1:end÷2], c.tab[:,end÷2+1:end])
Modified to work with updated struct

2023-12-19 07:18 UTC, Benzillaist commented on src/ecc/ECC.jl
> +include("simple_sparse_codes.jl")
They have been moved

2023-12-19 07:28 UTC, Benzillaist commented
Thank you for the review! I have implemented all the changes you requested. 
I can definitely prepare some codes, but I'm unsure how to prove that they are valid. Do you know where I might be able to come across some existing bicycle codes for comparison?

Additionally, I will be using new branches for all future commits. Thank you for that recommendation as well!

2024-01-25 03:54 UTC, Krastanov commented
After #212, a lot of the functionality here has already been implemented. I will close this one for now, but please consider opening a new one that adds the new codes you have defined -- they are not in #212 and will be greatly appreciated.

2024-01-25 03:54 UTC, closed without merging