Iterative Decoder + Some Documentation: First Step for creating a Zoo of QEC codes and Decoders
QuantumSavory/QuantumClifford.jl pull request #238
Opened 2024-02-28 20:39 UTC by Fe-r-oz

### **Implement Iterative Decoder with Belief Propagation**

**Description**
This pull request introduces the IterativeDecoder struct and its associated functions for performing iterative decoding using the Belief Propagation (BP) algorithm. Further, useful references for foundational and base papers for quantum error correction codes are added.

**Key Points**
1. Leverages LDPCDecoders.jl for BP calculations.
2. Handles syndrome recalculation using QuantumClifford.jl's comm_all function.
3. Includes a basic test case demonstrating functionality

**To Do**
1. Update the provided stabilizer matrix (H) with the actual matrix.
2. Implement additional test cases
4. Consider incorporating documentation for the IterativeDecoder

**_Also, Documentation with references for_**

-  2D Color code
-  3D color code
- 2D surface code
-  3D surface code
- QLDPC code
- Floquent code
- Bias-tailored QLDPC  
- Hyper graph produce code.

2024-03-01 20:37 UTC, Krastanov reviewed
This is a pretty good start, thank you! I would suggest focusing just on implementing QHamming here, leave the rest for other PRs. Add tests and documentation, make sure it actually works. I left some stylistic comments in as well.

2024-03-01 20:37 UTC, Krastanov commented on src/ecc/codes/code833.jl
> +# TODO [[8,1,3]] qubit code
I guess this file can now be removed given that you have added a more general one

2024-03-01 20:37 UTC, Krastanov commented on src/ecc/codes/code422.jl
> +# TODO [[4,2,2]] qubit code (Simplest Surface Code)
It would probably make sense to remove this one too. We have the Toric code. I guess it can be useful to define a surface code too, but similarly to QHamming, it should be a general family, not just an instance.

2024-03-01 20:37 UTC, Krastanov commented on src/ecc/decoder_pipeline.jl
> +    # Stores the stabilizer matrix
it would be better to use docstrings, not comments, here, for documenting the slots

2024-03-01 20:37 UTC, Krastanov commented on src/ecc/decoder_pipeline.jl
> +"using QuantumClifford, Distances, JuMP"
this docstring does not make much sense to me

2024-03-01 20:37 UTC, Krastanov commented on src/ecc/decoder_pipeline.jl
> +# Function to initialize an `IterativeDecoder` object
Use docstrings, not comments, for documenting code.

This particular one probably does not need a docstring/comment anyway.

Also, in julia these are usually called Constructors, not Initializers.

2024-03-01 20:37 UTC, Krastanov commented on src/ecc/decoder_pipeline.jl
> +function test_iterative_decoder()
tests should be in the test suite, not interspersed among the code

2024-03-01 20:37 UTC, Krastanov commented on src/ecc/codes/QHammingcode.jl
> +#how to use
this should be documentation, not comments hidden in the library

2024-03-01 20:54 UTC, Krastanov commented
To keep this easier for me, I will mark this back to "draft" stage. When you are ready, please click "resolve" on my comments above and re-request a review.

2024-03-02 15:17 UTC, Krastanov commented on src/ecc/codes/qhammingcode.jl
> +      K[i, bit2int(Integer.tobits(j - 1)[end])] = 1
`Integer` is a type. I am extremely surprised this has worked locally for you -- you must have imported a package that has done something very weird to the Integer symbol.

It would probably work better with a call to `digits` (see here https://discourse.julialang.org/t/convert-integer-to-bits-array/26663 )

ALso, I think this works only for r up to 64, right? If that is the case, this should check and raise an error, e.g. `r < whatever && error(lazy"`QHamming` currently supports only block sizes up to 2^something. You requested a block size of ...")`

2024-03-02 17:21 UTC, Fe-r-oz commented on src/ecc/codes/qhammingcode.jl
> +      K[i, bit2int(Integer.tobits(j - 1)[end])] = 1
Hi Stephan,

Actually, on the local machine, there is a much better version rather than using Integer. I  forgot to commit  last night on github so you saw the earlier version. I have committed the lastest version which is working as individual file on local machine!

2024-03-02 17:29 UTC, Fe-r-oz commented
Hi Stephan,

Actually, last night, I forgot to update the git version so you were seeing
the wrong version. I have committed the latest version with which I got the
results. Please see and let me know. Thanks for adding Qhammig to various
places.


On Sat, Mar 2, 2024 at 8:17 PM Stefan Krastanov ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/ecc/codes/qhammingcode.jl
> <https://github.com/QuantumSavory/QuantumClifford.jl/pull/238#discussion_r1509991239>
> :
>
> > @@ -0,0 +1,25 @@
> +struct QHamming
> +  r::Int
> +end
> +
> +function parity_checks(code::QHamming)
> +  r = code.r
> +  n = 2^r
> +
> +  # Construct the K matrix (refer to Gottesman-Chuang codes for details)
> +  K = zeros(Int, (n - r - 2), r)
> +  for i in 1:n-r-2
> +    j = i + 1
> +    while j <= n
> +      K[i, bit2int(Integer.tobits(j - 1)[end])] = 1
>
> Integer is a type. I am extremely surprised this has worked locally for
> you -- you must have imported a package that has done something very weird
> to the Integer symbol.
>
> It would probably work better with a call to digits (see here
> https://discourse.julialang.org/t/convert-integer-to-bits-array/26663 )
>
> ALso, I think this works only for r up to 64, right? If that is the case,
> this should check and raise an error, e.g. r < whatever && error(lazy"
> QHamming currently supports only block sizes up to 2^something. You
> requested a block size of ...")
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/QuantumSavory/QuantumClifford.jl/pull/238#pullrequestreview-1912677926>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWMHEJZMLYDQH3YLZHFLZT3YWHUPZAVCNFSM6AAAAABD6XEXMWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMJSGY3TOOJSGY>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***
> com>
>

2024-03-02 22:37 UTC, Fe-r-oz commented
The code is working with the QuatumClifford Package now!
![Screenshot_select-area_20240303033505]

(https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/cbd18a4d-69e6-47c5-8721-202046d3abc2)

2024-03-03 13:50 UTC, Fe-r-oz commented
There are some general thoughts I would like to share. Please provide your
perspective after you have reviewed the changes.

So, I was curious about the circuits.jl. I wanted to see whether the
QHamming Encoding Circuit would be generated from the already available
encoding circuits?

I believe when we add new codes, we would also have to make some
modifications to the encoding circuits (naive_encoding_circuit) or build
separate ones for each? I read an exception in the naive encoding circuit
function that works for CSS codes only as we have to separate both x parts
and z parts of the stabilizer.

In the naive_encoding_circuit, it separates the x part and the z part
explicitly and when Steane7 code is called, since in its implementation,
the parts are already separated, the naive encoding circuit works for the
steane code.

On Sat, Mar 2, 2024 at 1:54 AM Stefan Krastanov ***@***.***>
wrote:

> To keep this easier for me, I will mark this back to "draft" stage. When
> you are ready, please click "resolve" on my comments above and re-request a
> review.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/QuantumSavory/QuantumClifford.jl/pull/238#issuecomment-1973905538>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWMHEJ3HGIEDMBG45736BZLYWDTKDAVCNFSM6AAAAABD6XEXMWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNZTHEYDKNJTHA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-03-03 16:06 UTC, Krastanov commented on test/test_ecc.jl
> +    QHamming(),
The `QHamming` constructor needs an argument, right?

2024-03-03 16:06 UTC, Krastanov commented on test/test_ecc_encoding.jl
> +        :QHamming(),
I do not think this would parse. `:QHamming()` is a quoted symbol that you are then trying to call. Compare to `:(Perfect())` which is a quoted functional call expression.

2024-03-03 16:08 UTC, Krastanov commented
Could you show me the output of `Pkg.status()` for your work environment?

2024-03-03 16:30 UTC, Krastanov commented
> So, I was curious about the circuits.jl. I wanted to see whether the
QHamming Encoding Circuit would be generated from the already available
encoding circuits?

`naive_encoding_circuit(QHamming(3))` should already work, yes. If it does not, that is probably a bug in it.

>
> I believe when we add new codes, we would also have to make some
modifications to the encoding circuits (naive_encoding_circuit) or build
separate ones for each? I read an exception in the naive encoding circuit
function that works for CSS codes only as we have to separate both x parts
and z parts of the stabilizer.

No, these should be universal, for any code. Maybe there is some issue currently that should be fixed, but these functions should be written in a way that works for all codes, without needing modifications when a new code is added. Post the stacktrace for your error and we can discuss it.

2024-03-03 16:50 UTC, Fe-r-oz commented
Dear Stefan,

Thank you very much for your comments.
I will post the stacktrace and show the Pkg. status () after reviewing all
the suggested changes.


On Sun, Mar 3, 2024 at 9:30 PM Stefan Krastanov ***@***.***>
wrote:

> So, I was curious about the circuits.jl. I wanted to see whether the
> QHamming Encoding Circuit would be generated from the already available
> encoding circuits?
>
> naive_encoding_circuit(QHamming(3)) should already work, yes. If it does
> not, that is probably a bug in it.
>
> I believe when we add new codes, we would also have to make some
> modifications to the encoding circuits (naive_encoding_circuit) or build
> separate ones for each? I read an exception in the naive encoding circuit
> function that works for CSS codes only as we have to separate both x parts
> and z parts of the stabilizer.
>
> No, these should be universal, for any code. Maybe there is some issue
> currently that should be fixed, but these functions should be written in a
> way that works for all codes, without needing modifications when a new code
> is added. Post the stacktrace for your error and we can discuss it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/QuantumSavory/QuantumClifford.jl/pull/238#issuecomment-1975222789>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWMHEJ4GEH7W64EEUQUYEXTYWNF3TAVCNFSM6AAAAABD6XEXMWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNZVGIZDENZYHE>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-03-03 17:02 UTC, Fe-r-oz commented on docs/src/references.bib
>  }
Sorry for that! Thanks!

2024-03-03 17:15 UTC, Fe-r-oz commented on src/ecc/codes/qhammingcode.jl
> +        throw(InvalidRError())  # Throw the exception if r is out of bounds
> Why is the upper limit 15?
15 works but The results gets slowed down from 15 onwards. r=16  give outofmemory() error.

![Screenshot_select-area_20240303221433](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/87780619-de39-4c02-8404-8f6bcffd8fb9)

2024-03-03 17:35 UTC, Fe-r-oz commented on src/ecc/codes/qhammingcode.jl
> +        throw(InvalidRError())  # Throw the exception if r is out of bounds
> also, a `@test_throws` should be added for this in the test suite

Thank you!  will add for lower bound.

Should I add Argment Error test throw for upper bound as well?

2024-03-03 17:43 UTC, Fe-r-oz commented on docs/src/references.bib
>  }
There as unnecessary line in references.md which I removed. But in reference.bib, lines are 1-227, the same in the original repo (no extra line in references.bib)

2024-03-03 17:44 UTC, Fe-r-oz commented
> Could you show me the output of `Pkg.status()` for your work environment?

![Screenshot_select-area_20240303224422](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/b5d51557-7ca0-42c3-bbb6-f75b1c03319c)

2024-03-03 19:05 UTC, Fe-r-oz commented
> `naive_encoding_circuit(QHamming(3))` should already work, yes. If it does not, that is probably a bug in it.

![Screenshot_select-area_20240304000328](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/4bd67d71-92c1-4951-8a03-6a067a88a2c9)

2024-03-03 20:54 UTC, Krastanov commented
It helps to copy-paste the actual text of the stack traces (the entire stack traces, not just a screenshot of only the top).

Here it says you are lacking a `code_n` method for your new type. Declare that method and see what the next broken thing shows up, and one by one you will have all necessary methods implemented.

2024-03-03 20:57 UTC, Krastanov commented
also, it currently does not seem like your new implementation is actually included in the rest of the codebase. See how all other files that implement a code are already included in the ECC.jl file which itself is included in QuantumClifford.jl.

2024-03-03 21:02 UTC, Fe-r-oz commented
> also, it currently does not seem like your new implementation is actually included in the rest of the codebase. See how all other files that implement a code are already included in the ECC.jl file which itself is included in QuantumClifford.jl.

I included the necessary lines in the ECC.jl file in the local codebase but didn't commit the changes yet! 
I will look into the first message. Thanks a lot. Learning a lot.

Thank you for your message. In the your review,  (I thought I had to undo that as well so I removed that from ECC.jl). Will commit the changes in ECC.jl file

2024-03-04 07:02 UTC, Fe-r-oz commented
The code_s, code n errors removed after adding these lines in `QHamming:
```
code_s(c::QHamming) = code_s(parity_checks(c))
code_n(c::QHamming) = code_n(parity_checks(c))
```
But, this new error emerges:
![Screenshot_select-area_20240304120050](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/a58a4828-0eb3-4d8b-aa26-e3e390d99bee)

Do we explicitly need to separate the parity check `H_x` part and the parity check `H_z `part of the stabilizer so that whem `MixedDestabilizer `is called in naive_encoding_circuit,  `md, r, permx, permz = MixedDestabilizer(code, undoperm=false, reportperm=true);`, it can get out these 4 arguments? This has been done in the definition of` Shor(), Steane(), Toric(), CSS() `so I think it's the standard procedure.

In the QHamming, I am using H which is getting the combined parity check matrix H, not separating out `H_x, H_z` from `H.`

2024-03-04 14:36 UTC, Krastanov commented on docs/src/references.bib
>  }
When you are done with a fix, click "resolve" so it is easier for me to read through my past comments.

2024-03-04 14:41 UTC, Krastanov commented
I do not think what you have here is what you are running on your computer, so it is rather difficult to comment on why you might have an issue. Keep this always in sync with your local branch (if it takes you more than 5 seconds to ensure they are in sync, there is probably something that we can do to streamline your workflow -- this should basically be instantaneous)

The functions you are reporting as having issues do not need any special support for new codes -- they should work directly.

You do not need these `try catch` blocks to report errors. Whenever you have an error (and the stacktrace related to that error) simply copy-paste it as text.

2024-03-04 15:11 UTC, Fe-r-oz commented
Thank you. You are spot on. I will make sure that the local repo is what I have here in next 20 min

2024-03-04 15:22 UTC, Fe-r-oz commented
I deleted my local repo and download the one that is here. Now, I will make sure that sync is instanteous, and will try my best to make sure that my work is convenient. 

This is the error that appeared. 

```
julia> e=naive_encoding_circuit(QHamming(3))
ERROR: MethodError: no method matching QuantumClifford.MixedDestabilizer(::Matrix{Int64}; undoperm::Bool, reportperm::Bool)

Closest candidates are:
  QuantumClifford.MixedDestabilizer(::T, ::Int64) where T<:QuantumClifford.Tableau got unsupported keyword arguments "undoperm", "reportperm"                                 
   @ QuantumClifford ~/Desktop/New/QuantumClifford.jl/src/QuantumClifford.jl:517
  QuantumClifford.MixedDestabilizer(::QuantumClifford.MixedDestabilizer) got unsupported keyword arguments "undoperm", "reportperm"
   @ QuantumClifford ~/Desktop/New/QuantumClifford.jl/src/QuantumClifford.jl:586
  QuantumClifford.MixedDestabilizer(::QuantumClifford.Stabilizer{T}; undoperm, reportperm) where T
   @ QuantumClifford ~/Desktop/New/QuantumClifford.jl/src/QuantumClifford.jl:522
  ...

Stacktrace:
 [1] QuantumClifford.MixedDestabilizer(c::QHamming; kwarg::@Kwargs{undoperm::Bool, reportperm::Bool})
   @ QuantumClifford.ECC ~/Desktop/New/QuantumClifford.jl/src/ecc/ECC.jl:55
 [2] naive_encoding_circuit(code::QHamming; undoperm::Bool)
   @ QuantumClifford.ECC ~/Desktop/New/QuantumClifford.jl/src/ecc/circuits.jl:21
 [3] naive_encoding_circuit(code::QHamming)
   @ QuantumClifford.ECC ~/Desktop/New/QuantumClifford.jl/src/ecc/circuits.jl:18
 [4] top-level scope
   @ REPL[11]:1
```

2024-03-04 15:25 UTC, Krastanov commented on src/ecc/codes/qhammingcode.jl
> +    return H
This should be a stabilizer tableau object, not just a matrix. Play with the other codes and see what they return in these situations.

2024-03-04 15:40 UTC, Fe-r-oz commented
`git log `

![Screenshot_select-area_20240304204001](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/4d67b389-da7a-4fe7-a56e-11f2774f8dab)
`
git status`
![Screenshot_select-area_20240304203935](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/54222b8e-513e-4863-aa52-aec3071c4d2c)

2024-03-04 15:41 UTC, Fe-r-oz commented on src/ecc/codes/qhammingcode.jl
> +    return H
Thank you, I noticed that. Excited to see!!

2024-03-05 04:50 UTC, Fe-r-oz commented
Made Progress! I saw the Stabilizer Tableau of the already implemented code! I now have idea how of to implement Non-CSS code using Stabilizer constructor!

I learnt that some codes that `S` defined in it and only `parity check x `and `parity check z` were called for them , namely for `Shor9, Cleave`, etc. while other codes used the `CSS `such as toric and used` `xz parity check`, then `parity check x `and `parity check z.` Also, there is an inbuilt warning which says that `parity check x` and `parity check z` can't be used for Non-CSS codes.

Am I extracting the `Hx` and `Hz` matrices correctly for `QHamming?`
```
parity_checks(QHamming(3))
+ XZX_X
+ ZYX__
+ ZZ_XX
Error showing value of type QuantumClifford.Stabilizer{QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}}:
ERROR: BoundsError: attempt to access 2×3 Matrix{UInt64} at index [1:2, 4]
Stacktrace:
  [1] throw_boundserror(A::Matrix{UInt64}, I::Tuple{Base.Slice{Base.OneTo{Int64}}, Int64})
    @ Base ./abstractarray.jl:737
  [2] checkbounds
    @ ./abstractarray.jl:702 [inlined]
  [3] _getindex
    @ ./multidimensional.jl:888 [inlined]
  [4] getindex
    @ ./abstractarray.jl:1291 [inlined]
  [5] getindex(tab::QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}, i::Int64)
    @ QuantumClifford ~/Desktop/New/QuantumClifford.jl/src/QuantumClifford.jl:171
  [6] _show(io::IOContext{Base.TTY}, t::QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}, limit::Int64, limit_vertical::Int64)
    @ QuantumClifford ~/Desktop/New/QuantumClifford.jl/src/tableau_show.jl:37
  [7] show(io::IOContext{Base.TTY}, t::QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}})
    @ QuantumClifford ~/Desktop/New/QuantumClifford.jl/src/tableau_show.jl:49
  [8] show(io::IOContext{Base.TTY}, s::QuantumClifford.Stabilizer{QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}})
    @ QuantumClifford ~/Desktop/New/QuantumClifford.jl/src/tableau_show.jl:60
  [9] show(io::IOContext{Base.TTY}, ::MIME{Symbol("text/plain")}, x::QuantumClifford.Stabilizer{QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}})
    @ Base.Multimedia ./multimedia.jl:47
 [10] (::REPL.var"#55#56"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::Any)
    @ REPL ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:273
 [11] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:569
 [12] display(d::REPL.REPLDisplay, mime::MIME{Symbol("text/plain")}, x::Any)
    @ REPL ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:259
 [13] display
    @ ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:278 [inlined]
 [14] display(x::Any)
    @ Base.Multimedia ./multimedia.jl:340
 [15] #invokelatest#2
    @ ./essentials.jl:892 [inlined]
 [16] invokelatest
    @ ./essentials.jl:889 [inlined]
 [17] print_response(errio::IO, response::Any, show_value::Bool, have_color::Bool, specialdisplay::Union{Nothing, AbstractDisplay})
    @ REPL ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:315
 [18] (::REPL.var"#57#58"{REPL.LineEditREPL, Pair{Any, Bool}, Bool, Bool})(io::Any)
    @ REPL ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:284
 [19] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:569
 [20] print_response(repl::REPL.AbstractREPL, response::Any, show_value::Bool, have_color::Bool)
    @ REPL ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:282
 [21] (::REPL.var"#do_respond#80"{Bool, Bool, REPL.var"#93#103"{…}, REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::Any, ok::Bool)
    @ REPL ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:911
 [22] #invokelatest#2
    @ ./essentials.jl:892 [inlined]
 [23] invokelatest
    @ ./essentials.jl:889 [inlined]
 [24] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/LineEdit.jl:2656
 [25] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:1312
 [26] (::REPL.var"#62#68"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/REPL/src/REPL.jl:386
Some type information was truncated. Use `show(err)` to see complete types.

```

Similarly, 

```
parity_checks(QHamming(6))
+ Y_Y_Y_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_
+ ZXXZZXX__XX__XX__XX__XX__XX__XX__XX__XX__XX__XX__XX__XX__X
+ _ZZYYXX____XXXX____XXXX____XXXX____XXXX____XXXX____XXXX___
+ ZZZZZ__XXXXXXXX________XXXXXXXX________XXXXXXXX________XXX
+ ZZZZZ__________XXXXXXXXXXXXXXXX________________XXXXXXXXXXX
+ ZZZZZ__________________________XXXXXXXXXXXXXXXXXXXXXXXXXXX
+ _____Z____________________________________________________
 ⋮
Error showing value of type QuantumClifford.Stabilizer{QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}}:
ERROR: BoundsError: attempt to access 2×56 Matrix{UInt64} at index [1:2, 107]
```

2024-03-05 05:09 UTC, Krastanov commented on src/ecc/codes/qhammingcode.jl
> +    Stabilizer(fill(0x0, 2k), Hx, Hz)
Could you give examples of a few small codes, so that I can understand whether what you are writing here is what you want.

2024-03-05 07:20 UTC, Fe-r-oz commented on src/ecc/codes/qhammingcode.jl
> +    Stabilizer(fill(0x0, 2k), Hx, Hz)
I believe size of  `Hx `and `Hz` is wrong. I will correct the logic there.  

When r=3,  [[8,3,3]] code and it's Stabilizer Matrix should be like this. I believe this is a good lead! Previously, I was doing it the other way by using the `H `matrix that was given in Preskills notes as starting point. I will just have to make sure from the `Hx` part and `Hz`, correct stabilizer is shown

`m`=5 (number of generators as shown)
`n`=9

total columns (`Hx` part an `Hz` part) = 2*8=16

Stabilizer should be of size `mxn` 5*8

Also, `stim` and `stac` are using methodology for representing the stabilizer tableau. What are your thoughts?

![Screenshot_select-area_20240305120900](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/a9bc2ba8-9422-4b6a-b940-c8dfeb6a9fc1)

2024-03-05 07:23 UTC, Fe-r-oz commented on src/ecc/codes/qhammingcode.jl
> +    Stabilizer(fill(0x0, 2k), Hx, Hz)
> Could you give examples of a few small codes, so that I can understand whether what you are writing here is what you want.

I believe size of  `Hx `and `Hz` is wrong. I will correct the logic there.  

When r=3,  [[8,3,3]] code and it's Stabilizer Matrix should be like this. I believe this is a good lead! Previously, I was doing it the other way by using the `H `matrix that was given in Preskills notes as starting point. I will just have to make sure from the `Hx` part and `Hz`, correct stabilizer is shown

`m`=5 (number of generators as shown)
`n`=8

total columns (`Hx` part an `Hz` part) = 2*8=16

Stabilizer should be of size `mxn` 5*8

Also, `stim` and `stac` are using this representation methodology for construct the stabilizer tableau. What are your thoughts?

![Screenshot_select-area_20240305120900](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/a9bc2ba8-9422-4b6a-b940-c8dfeb6a9fc1)

2024-03-05 10:18 UTC, Fe-r-oz commented
EightQubit Code [[8,3,3]]

```

julia> naive_encoding_circuit(EightQubit())
30-element Vector{QuantumClifford.AbstractOperation}:
 QuantumClifford.sCNOT(6,5)
 QuantumClifford.sCNOT(7,5)
 QuantumClifford.sCNOT(8,5)
 QuantumClifford.sHadamard(1)
 QuantumClifford.sPhase(1)
 QuantumClifford.sZCX(1,5)
 QuantumClifford.sZCX(1,6)
 QuantumClifford.sZCY(1,7)
 ⋮
 QuantumClifford.sZCZ(4,2)
 QuantumClifford.sZCX(4,6)
 QuantumClifford.sZCY(4,7)
 QuantumClifford.sZCY(4,8)
 QuantumClifford.sZ(3)
 QuantumClifford.sZ(4)
 QuantumClifford.sSWAP(5,4)

julia> parity_checks(EightQubit())
+ XXXXXXXX
+ ZZZZZZZZ
+ _X_XYZYZ
+ _XZY_XZY
+ _YXZXZ_Y
```

We can next work on  [[16,10,3]] code so we add it in the zoo as well!!

2024-03-05 19:59 UTC, Fe-r-oz commented
I have also installed CLI to make the my workflow as convenient as possible! :) 
```
~/Desktop/New/QuantumClifford.jl$ git pull origin master
From https://github.com/Fe-r-oz/QuantumClifford.jl
 * branch            master     -> FETCH_HEAD
Already up to date.
```

2024-03-06 23:13 UTC, Krastanov commented
Tests do not pass (see just above the comment box). You can run the tests locally by going to package mode (pressing `]`) and typing `test QuantumClifford`. Let's have the tests fixed and then we can get back to doing a review.

Also, why did you change this from implementing the family of quantum Hamming codes to implementing just two specific codes? Any reason for preferring these?

Lastly, are these the **only** 8 qubit and 16 qubit codes in existance? If they are not, we should have better names for them.

2024-03-06 23:18 UTC, Krastanov commented on test/test_ecc_decoder_all_setups.jl
> -        Cleve8(),
you should test all of the code you are adding, not just one of them

2024-03-06 23:19 UTC, Krastanov commented on test/test_qhamming_code.jl
> +
this file should be deleted if not in use (although I prefer we get back to what was originally in this PR, implementing a family of codes)

2024-03-06 23:19 UTC, Krastanov commented
when finishing a PR, it is useful to check the "files changed" tab to make sure everything is in order

2024-03-06 23:21 UTC, Krastanov commented on src/ecc/ECC.jl
> +    EightQubit, SixteenQubit
there is a missing comma here

2024-03-07 00:17 UTC, Fe-r-oz commented
> Tests do not pass (see just above the comment box). You can run the tests locally by going to package mode (pressing `]`) and typing `test QuantumClifford`. Let's have the tests fixed and then we can get back to doing a review.
> 
> Also, why did you change this from implementing the family of quantum Hamming codes to implementing just two specific codes? Any reason for preferring these?
> 
> Lastly, are these the **only** 8 qubit and 16 qubit codes in existance? If they are not, we should have better names for them.

I provide a valid really reason After reading the Gottesman Thesis above! KIndly please see the

 https://github.com/QuantumSavory/QuantumClifford.jl/pull/238#issuecomment-1978149795

I will add better names. Thanks!

2024-03-07 00:19 UTC, Fe-r-oz commented on test/test_ecc_decoder_all_setups.jl
> -        Cleve8(),
I hesitated from changing all the other files as above you said to not make any spurious and cosmetic changes. I will make sure test pass. Thanks!

2024-03-07 02:10 UTC, Fe-r-oz commented
[[16,10,3]] gives Assertion Error ```
is Conda ok   | None  1.0s
table decoder: Error During Test at /home/Transcendence/Desktop/New/QuantumClifford.jl/test/test_ecc_decoder_all_setups.jl:14
  Got exception outside of a @test
  AssertionError: max(e...) < noise / 4
```

```
73-element Vector{QuantumClifford.AbstractOperation}:
 QuantumClifford.sCNOT(7,6)
 QuantumClifford.sCNOT(8,6)
 QuantumClifford.sCNOT(9,6)
 QuantumClifford.sCNOT(10,6)
 QuantumClifford.sCNOT(11,6)
 QuantumClifford.sCNOT(12,6)
 QuantumClifford.sCNOT(13,6)
 QuantumClifford.sCNOT(14,6)
 ⋮
 QuantumClifford.sZCX(5,15)
 QuantumClifford.sZCX(5,16)
 QuantumClifford.sSWAP(9,5)
 QuantumClifford.sSWAP(8,5)
 QuantumClifford.sSWAP(7,5)
 QuantumClifford.sSWAP(6,5)
 QuantumClifford.sSWAP(5,4)

```

```
julia> parity_checks(NKD16103())
+ XXXXXXXXXXXXXXXX
+ ZZZZZZZZZZZZZZZZ
+ _X_X_X_XZYZYZYZY
+ _X_XZYZYX_X_YZYZ
+ _XZYX_YZ_XZYX_YZ
+ _YXZ_YXZ_YXZ_YXZ

```

2024-03-07 02:28 UTC, Krastanov commented
> Furthermore, is it right approach to have a general instance of quantum hamming code to generate the [[8,3,3]] code and [[16,10,3]] code, and others etc. from one class. In the Gottesman thesis (https://thesis.library.caltech.edu/2900/2/THESIS.pdf), he mentions that _The eight-qubit code of table 3.3 is just one of a class of codes with parameters [2^j , 2^j − j − 2, 3]_ but [[16,10,3]] have different checks which he goes onto mention at page **91.**

I assume you are talking about a [[16,10,3]] code because that is the r=4 quantum hamming code as described here: https://errorcorrectionzoo.org/c/quantum_hamming. There might or might not be some other [[16,10,3]] code that the thesis is talking about. But let's first make sure that one single family of codes is properly implemented -- there is little value to hardcoding parity check matrices of specific code instances. The valuable thing is something that can generate whole families of codes. Sure the reference you have might be talking about codes from two different families or about special instances that do not belong to families, but that does not change the fact that there are well-defined methods to construct specific families.

> Maybe it's better to implement them as separate ones? Maybe we are trying to complicate stuff by a general class which constructs [[8,3,3]], [16,10,3]], [[32,25,3]]... etc. from one class. What are your thoughts?

Implementing specific instances is not particularly useful. It is the general families that are of interest.

2024-03-07 02:30 UTC, Krastanov commented
> Pedagogical [[16,10,3]] gives **_Assertion Error_** while the `table_decoder` test function runs it. Encoding works fine though. Why?

Read through the rest of the test. It seems to be a test that checks the logical error rate. A few posibilities: an inappropriate decoder is being used, the test is too optimistic about the noise-fighting capabilities of the code, or the parity check matrix is simply wrong.

2024-03-07 02:34 UTC, Fe-r-oz commented
> Implementing specific instances is not particularly useful. It is the general families that are of interest.

Thank you for your comments! You are right that only a family of `QGottesman`will suffice. Let's name it as `QGottesman ` as that's better than QHamming.

I will start working on it!

2024-03-07 02:56 UTC, Fe-r-oz commented
> Read through the rest of the test. It seems to be a test that checks the logical error rate. A few posibilities: an inappropriate decoder is being used, the test is too optimistic about the noise-fighting capabilities of the code, or the parity check matrix is simply wrong.

Read the full error. It seems the second one is more likely as the Stabilizer code is correct. What to be done in this first two case? Is the `noise=0.001` anad `noise/4   applies to all. What's the criteria for this? Kindly please attach some reference so I can look it up as well!

2024-03-07 03:01 UTC, Krastanov commented
The ECC zoo seems to refer to them both as Quantum Hamming codes and as Gottesman codes. Both seem fine to me. If you stick to Gottesman, maybe remove the Q from the name.

If you are unsure about what performance the code should have, what you can try to do is to run a few simulations and make a plot where the x axis is the physical level of noise and the y axis is the logical level of noise. Like here: https://quantumsavory.github.io/QuantumClifford.jl/dev/ECC_evaluating/ From these plots you can see whether something is broken.

2024-03-07 03:05 UTC, Krastanov commented
To be clear, the numbers I choose in these tests were pretty arbitrary, simply setting them up to make sure the code is not completely broken.

2024-03-07 03:14 UTC, Fe-r-oz commented
> To be clear, the numbers I choose in these tests were pretty arbitrary, simply setting them up to make sure the code is not completely broken.

Thanks! The assertion error disappears when I run the tests for arbitrary  `20000000` steps.

2024-03-08 07:09 UTC, Fe-r-oz commented
Finally! 

Designed the Algorithm using stabilizer formalism;)
```
julia> parity_checks(QHamming(3))
+ XXXXXXXX
+ ZZZZZZZZ
+ _X_XZYZY
+ _XZY_XZY
+ _ZXY_ZXY

julia> parity_checks(QHamming(4))
+ XXXXXXXXXXXXXXXX
+ ZZZZZZZZZZZZZZZZ
+ _X_X_X_XZYZYZYZY
+ _X_XZYZY_X_XZYZY
+ _XZY_XZY_XZY_XZY
+ _ZXY_ZXY_ZXY_ZXY
```

```
 naive_encoding_circuit(QHamming(10))
7147-element Vector{QuantumClifford.AbstractOperation}:
 QuantumClifford.sCNOT(13,5)
 QuantumClifford.sCNOT(14,6)
 QuantumClifford.sCNOT(15,7)
 QuantumClifford.sCNOT(16,5)
 QuantumClifford.sCNOT(16,6)
 QuantumClifford.sCNOT(16,7)
 QuantumClifford.sCNOT(17,5)
 QuantumClifford.sCNOT(17,6)
 ⋮
 QuantumClifford.sSWAP(14,10)
 QuantumClifford.sSWAP(13,11)
 QuantumClifford.sSWAP(12,8)
 QuantumClifford.sSWAP(11,9)
 QuantumClifford.sSWAP(10,8)
 QuantumClifford.sSWAP(9,7)
 QuantumClifford.sSWAP(7,6)
```

```
 parity_checks(QHamming(20))
+ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX⋯XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
+ ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ⋯ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
+ _X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_⋯ZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZY
+ _X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_⋯ZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZY
+ _X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_⋯ZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZY
+ _X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_⋯ZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZY
+ _X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_⋯ZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZY
 ⋮
+ _X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_XZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZY_X_X_X_X_X_X_X_⋯ZYZYZYZYZYZYZYZY_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_XZYZYZYZYZYZYZYZYZYZYZYZYZYZYZYZY
+ _X_X_X_X_X_X_X_XZYZYZYZYZYZYZYZY_X_X_X_X_X_X_X_XZYZYZYZYZYZYZYZY_X_X_X_X_X_X_X_⋯ZYZYZYZYZYZYZYZY_X_X_X_X_X_X_X_XZYZYZYZYZYZYZYZY_X_X_X_X_X_X_X_XZYZYZYZYZYZYZYZY
+ _X_X_X_XZYZYZYZY_X_X_X_XZYZYZYZY_X_X_X_XZYZYZYZY_X_X_X_XZYZYZYZY_X_X_X_XZYZYZYZ⋯_X_X_X_XZYZYZYZY_X_X_X_XZYZYZYZY_X_X_X_XZYZYZYZY_X_X_X_XZYZYZYZY_X_X_X_XZYZYZYZY
+ _X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZ⋯_X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZY_X_XZYZY
+ _XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZ⋯_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY_XZY
+ _ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZX⋯_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY_ZXY

```

2024-03-09 07:13 UTC, Krastanov requested changes
this is much more polished, good job

please check the faling tests and see whether they are related to your work

2024-03-09 07:13 UTC, Krastanov commented on test/test_ecc_syndromes.jl
> +    QHamming(3),
just so we are a bit more thorough, I would suggest adding `QHamming(5)` as well

2024-03-09 07:13 UTC, Krastanov commented on test/test_ecc.jl
> +end
In a bunch of the files you have edited you will now see this new-line warning. Could you undo it, especially in files that are otherwise untouched?

2024-03-09 07:13 UTC, Krastanov commented on test/test_ecc_syndromes.jl
> +    QHamming(3),
to all tests, not only here

2024-03-09 07:13 UTC, Krastanov commented on src/ecc/codes/gottesman.jl
> +struct QHamming <: AbstractECC
add a brief docstring with a link to the source (e.g. Gottesman's thesis which is already in our bib file). See Cleve8 for example https://github.com/QuantumSavory/QuantumClifford.jl/blob/master/src/ecc/codes/clevecode.jl

2024-03-09 07:13 UTC, Krastanov commented on src/ecc/codes/gottesman.jl
> +        end
```suggestion
        (j >= 3 && j < 16) || error("In `QHamming(j)`, `j` must be ≥  3 in order to obtain a valid code and `j` must be < 16 to remain tractable")
```

Your check was only for upper limit, but not for lower limits. I updated it and shortened the syntax

2024-03-09 07:13 UTC, Krastanov commented on src/ecc/codes/gottesman.jl
> +    extended_Hz = Matrix{Bool}(Hx)
why is the casting necessary, why not start with booleans from the begining?

2024-03-09 08:18 UTC, Fe-r-oz commented on src/ecc/codes/gottesman.jl
> +        end
Thanks! For the upper bound, QHamming (16) works for j=16 a well!  I added a demonstration of QHamming (20) above! What should be the upper bound in this case? Should I check the cases for latest upper bound?

2024-03-09 08:24 UTC, Fe-r-oz commented on src/ecc/codes/gottesman.jl
> +    extended_Hz = Matrix{Bool}(Hx)
I started with Matrix{Bool} approach, but in the end, this proved to be more convenient as this resolved the Type Errors  which with Stabilizer Constructor.

2024-03-09 08:29 UTC, Fe-r-oz commented
> this is much more polished, good job
> 
> please check the faling tests and see whether they are related to your work

Thank you! I checked the performance tracking test and its seems to be related to the LDPC Belief Propagation Decoder.
This are the results before commiting suggestions. I will see again the tests after adding all the changes!

```
[351 onwards] ERROR: LoadError: MethodError: no method matching LDPCDecoders.BeliefPropagationDecoder(::Matrix{Bool}, ::Int64, ::Int64)
The type `LDPCDecoders.BeliefPropagationDecoder` exists, but no method is defined for this combination of argument types when trying to construct it.
Closest candidates are:
  LDPCDecoders.BeliefPropagationDecoder(::Any, ::Any, ::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any)
   @ LDPCDecoders ~/.julia/packages/LDPCDecoders/lRVSm/src/decoders/belief_propogation.jl:25
...
Stacktrace:
  [1] QuantumCliffordLDPCDecodersExt.BeliefPropDecoder(c::Shor9, p_init::Int64, max_iters::Int64)
    @ QuantumCliffordLDPCDecodersExt ~/work/QuantumClifford.jl/QuantumClifford.jl/ext/
```

Change Log CLI
` [12] Error: No update to CHANGELOG.md found!`

Documentation CLI
```
[1142, 1143] ERROR: LoadError: `makedocs` encountered an error [:example_block] -- terminating build before rendering.
Stacktrace:

2024-03-09 08:52 UTC, Fe-r-oz commented on test/test_ecc.jl
> +end
Sure, I will undo these changes!

2024-03-09 13:03 UTC, Fe-r-oz commented on src/ecc/codes/gottesman.jl
> +         Hx[rows, a] = (a % 4 == 1) || (a % 4 == 2) ? 0 : 1
Thanks!

2024-03-11 04:17 UTC, Krastanov commented
I do not think the conda-related failures in the tests are related to your code. Just make sure the other tests pass before submitting for review.

2024-03-11 14:05 UTC, Fe-r-oz commented
All these failing tests have a common conda error: 

```
ERROR: The following 2 direct dependencies failed to precompile:

PyQDecoders [17f5de1a-9b79-4409-a58d-4d45812840f7]

Failed to precompile PyQDecoders [17f5de1a-9b79-4409-a58d-4d45812840f7] to "/home/runner/.julia/compiled/v1.10/PyQDecoders/jl_yluyP8".
ERROR: LoadError: ArgumentError: Path to conda environment is not valid: /home/runner/.julia/conda/3/x86_64
```

I verified the results with the Gottesman Thesis, They align fully! Added further checks in Hx!  [Table 8.1 Page 91 ](https://thesis.library.caltech.edu/2900/2/THESIS.pdf)

```
julia> parity_checks(QHamming(4))
+ XXXXXXXXXXXXXXXX
+ ZZZZZZZZZZZZZZZZ
+ _X_X_X_XZYZYZYZY
+ _X_XZYZYX_X_YZYZ
+ _XZYX_YZ_XZYX_YZ
+ _YXZ_YXZ_YXZ_YXZ

```

2024-03-11 22:21 UTC, Fe-r-oz commented
All the failing tests have conda related errors. Therefore, submitting for review 🤞🏻!

2024-03-16 02:04 UTC, Krastanov requested changes
I fixed the conda issue separately. Now it should be fine.

I had to bring in the changes from the master branch. Because you are working on the master branch of your own repository, this will probably cause you some annoyance. In the future, always use separate branches for new work, not the master branch.

You will probably need to pull these changes (notice the extra commit from me that is now listed here).

As you mentioned, there are still failing tests. Those should be investigated. If none of the decoders show any improvement with these codes, even with the smallest ones, I would be worried about bugs in the code generation routines. I added an empty example of a third decoder that you can try out. Here is also some documentation on the topic: https://quantumsavory.github.io/QuantumClifford.jl/dev/ECC_evaluating/

We can do another round of review when the tests are passing. Do not worry about the changelog, nightly, and performance tests, just about the others.

2024-03-16 02:15 UTC, Krastanov commented
I relaxed the testing requirements for the codes you implemented. With the larger Gottesman codes the issue is indeed that they are simply not that great. I think tests will now pass.

You need to pull to get the changes I made. Check for any other test failures and address the comments I made and this should be nearly ready for merging.

Do not forget to update the CHANGELOG file

2024-03-16 04:03 UTC, Fe-r-oz commented on test/test_ecc_decoder_all_setups.jl
> +end
Thank you for your comments. You are very right. I was being careful to not have any of the whitespaces but this skipped my attention. I believe the test_decoder.jl is the only file that had these trailing errors.

Actually, for sometime, I use a version of Linux explicitly developed for mainland China currently, their Editor does not have remove trailing local whitespaces option! So, I have to manually see if any extra whitespaces are present since they have 'show whitespaces' option.

Certainly will download Notepad++ which have the trim whitespace option

2024-03-16 09:03 UTC, Fe-r-oz commented
Thanks a lot for your comments!

Indeed, only the first two members, namely [[8,3,3]] and [[16,10,3]] of Gottesman Family are nice. As j>4, max assertion error happens.

Now, the tests are passing for all-1 decoders in some iterations. I commented that out for a whole . 

`Py Belief Decoders` has this issue 

`Python: ValueError: The input to the ldpc.bp_decoder.decode must be a syndrome (of length=5). The inputted vector has length=4. Valid formats are np.ndarray or scipy.sparse.spmatrix`. 

I checked out the recent commited changes, it seems that the decode function was changed, maybe that's what this error is occuring?

2024-03-16 10:59 UTC, Fe-r-oz commented
I tried to update the changelog.mg but I think I don't have write access to it because I got conflict error.

2024-03-16 11:08 UTC, Fe-r-oz commented on test/test_ecc_decoder_all_setups.jl
> +            e = evaluate_decoder(PyMatchingDecoder(c), s, 100000)
Sorry for that. Forgot to untweak.

2024-03-16 12:22 UTC, Krastanov commented on test/test_ecc_decoder_all_setups.jl
> +end
If it is a gnome linux distribution you probably have gedit. It is an ok editor for modifying a couple of lines, but I would avoid using it for anything more than that.

Any linux distribution would have emacs and vim. Both of these are great editors, but they require significant setup.

Atom is a deprecated project that is not seeing any updates, I would suggest avoiding it. It used to be pretty great but MS/Github canceled the project.

VS Code is probably the best tool for your skillset. Make sure to install the Julia plugin in it.

Please read through this https://modernjuliaworkflows.github.io/writing/ -- in it there are probably other things you can make better for your setup.

2024-03-16 12:26 UTC, Krastanov commented on src/ecc/codes/gottesmancode.jl
> +parity_checks_z(c::Gottesman) = stab_to_gf2(parity_checks(Gottesman(c.j)))[1:end,end÷2+1:end]
These are wrong. The Gottesman code is not a CSS code, is it? It mixes X and Z parity checks and as such it can not be written as two separate classical codes.

2024-03-16 12:26 UTC, Krastanov commented on test/test_ecc.jl
> +    Cleve8(), Gottesman(3), Gottesman(5),
```suggestion
    Cleve8(),
    Gottesman(3),
    Gottesman(5),
```

Whenever possible, follow the formatting conventions of the code around you

2024-03-16 12:45 UTC, Fe-r-oz commented on src/ecc/codes/gottesmancode.jl
> +parity_checks_z(c::Gottesman) = stab_to_gf2(parity_checks(Gottesman(c.j)))[1:end,end÷2+1:end]
Indeed. I looked at the stabilizer matrix and thought that maybe I can include rows from 0 to end, and divide the columns appropriately so that it may work. 

The other approach is to define the functions for parity check separately, or I need to define them separately becauze the decoders requires the Hz and Hx. This is actually assigning Hz and Hz since Hx is all zeros 0: half to columns and Hz is all 0s after half to end column.

` throw(lazy"Codes of type $(typeof(code)) do not have separate X and Z parity checks...`

2024-03-16 12:51 UTC, Krastanov commented on src/ecc/codes/gottesmancode.jl
> +parity_checks_z(c::Gottesman) = stab_to_gf2(parity_checks(Gottesman(c.j)))[1:end,end÷2+1:end]
If it is not a CSS code, then a decoder that requires Hz and Hx simply will not work. You can call the matrices that you define Hz and Hx, but this is just using the same name for a different object, so it will still not work.

Yes, the matrices you define here can be useful for some things, but if the user needs them, they will just use `stab_to_gf2` themselves.

2024-03-16 13:01 UTC, Fe-r-oz commented
You are right.  After Hz and Hx are sent to stabilizer, they mix. Mixed
approaches. Thanks.

I will use the approach for assigning the values.

On Sat, Mar 16, 2024, 5:27 PM Stefan Krastanov ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In test/test_ecc.jl
> <https://github.com/QuantumSavory/QuantumClifford.jl/pull/238#discussion_r1527165883>
> :
>
> > @@ -8,7 +8,7 @@ codes = [
>      Steane7(),
>      Shor9(),
>      Perfect5(),
> -    Cleve8(),
> +    Cleve8(), Gottesman(3), Gottesman(5),
>
> ⬇️ Suggested change
>
> -    Cleve8(), Gottesman(3), Gottesman(5),
> +    Cleve8(),
> +    Gottesman(3),
> +    Gottesman(5),
>
> Whenever possible, follow the formatting conventions of the code around you
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/QuantumSavory/QuantumClifford.jl/pull/238#pullrequestreview-1941026823>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWMHEJ2ZM64LUMIDFSPWW6LYYQ3CHAVCNFSM6AAAAABD6XEXMWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNBRGAZDMOBSGM>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***
> com>
>

2024-03-16 13:32 UTC, Fe-r-oz commented
Since the decoders are defined for CSS code, and they need Hz and Hx
separately in their definition when the code is called, when they are
called, that might be the reason for j>4, we are getting the assertion
errors due to high noise?

 If I correctly send the Hx and Hz, as you suggested, will that actually
work for decoders correctly? I will try the other approach and  let you
know.

On Sat, Mar 16, 2024, 6:01 PM Feroz Ahmad ***@***.***> wrote:

> You are right.  After Hz and Hx are sent to stabilizer, they mix. Mixed
> approaches. Thanks.
>
> I will use the approach for assigning the values.
>
> On Sat, Mar 16, 2024, 5:27 PM Stefan Krastanov ***@***.***>
> wrote:
>
>> ***@***.**** commented on this pull request.
>> ------------------------------
>>
>> In test/test_ecc.jl
>> <https://github.com/QuantumSavory/QuantumClifford.jl/pull/238#discussion_r1527165883>
>> :
>>
>> > @@ -8,7 +8,7 @@ codes = [
>>      Steane7(),
>>      Shor9(),
>>      Perfect5(),
>> -    Cleve8(),
>> +    Cleve8(), Gottesman(3), Gottesman(5),
>>
>> ⬇️ Suggested change
>>
>> -    Cleve8(), Gottesman(3), Gottesman(5),
>> +    Cleve8(),
>> +    Gottesman(3),
>> +    Gottesman(5),
>>
>> Whenever possible, follow the formatting conventions of the code around
>> you
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/QuantumSavory/QuantumClifford.jl/pull/238#pullrequestreview-1941026823>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AWMHEJ2ZM64LUMIDFSPWW6LYYQ3CHAVCNFSM6AAAAABD6XEXMWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNBRGAZDMOBSGM>
>> .
>> You are receiving this because you modified the open/close state.Message
>> ID: ***@***.***
>> com>
>>
>

2024-03-16 14:17 UTC, Krastanov commented
There is no such thing as Hz and Hx for these codes. Hz and Hx are defined only for CSS codes, i.e. codes where the X and Z checks are completely separate.

2024-03-16 14:19 UTC, Fe-r-oz commented
> There is no such thing as Hz and Hx for these codes. Hz and Hx are defined only for CSS codes, i.e. codes where the X and Z checks are completely separate.

You are right, The decoders are working removing the stab_to_gf2. I think there is no need to define the x and z checks in this case!

2024-03-16 14:30 UTC, Fe-r-oz commented
The Belief Propogation Decoder required Hx and Hz, and as you mentioned, it won't work in the non-CSS case. Every other decoder is working!

2024-03-16 15:10 UTC, Krastanov commented
> You are right, The decoders are working after removing the `stab_to_gf2.` I think there is no need to define the x and z checks in the non-CSS case when you can send the complete stabilizer!

I want us to be a bit more careful with phrasing here. It is not "there is no need", rather it is "it is impossible to".

This seems nearly ready to merge. Just ping me when you have the superficial cosmetic comments addressed.

2024-03-16 15:20 UTC, Fe-r-oz commented
> I want us to be a bit more careful with phrasing here. It is not "there is no need", rather it is "it is impossible to".
> 
> This seems nearly ready to merge. Just ping me when you have the superficial cosmetic comments addressed.

Indeed! Thanks. Last time I tried to update changelog.md, I got resolve conflicts error.  I don't think I have write access to changelog.

The file changed decreased from 9 to 7 as I removed the cosmetic superficial changes. I will go through the code and ping you.

Thanks for latest PyQDecoders!

2024-03-16 16:46 UTC, Fe-r-oz commented
I got a conflict when I updated changelog.md again which is that only those with write access can merge this repo. Since, I am working with master, that might be the reason I can't update changelog. 

12/15 checks were passing, now 10/15 checks are passing!

```
## v0.8.23 - 2024-03-16

- Implemented the first family of non-CSS [[2^j, 2^j - j - 2, 3]] Gottesman codes, also known as [[2^j, 2^j - j - 2, 3]] quantum Hamming codes 
```
Anyhow, I believe that it's ready to merge. @Krastanov.

2024-03-16 17:04 UTC, Krastanov reviewed
There are a few files that still have cosmetic issues. It is a good habit to open the "files changed" tab in the PR page to make sanity checks for stuff like this (and for more important stuff) before submitting.

![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/198ed437-5909-4d62-99cd-8c99076feb11)

2024-03-16 17:04 UTC, Krastanov commented on src/ecc/ECC.jl
> +end #module
please fix this file ending (as I mentioned a few times, it is not a big deal, but I insist that we build up good habits first on a first PR)

2024-03-16 17:04 UTC, Krastanov commented on docs/src/references.bib
> +}
please fix this file ending (as I mentioned a few times, it is not a big deal, but I insist that we build up good habits first on a first PR)

2024-03-16 17:04 UTC, Krastanov commented on test/test_ecc_syndromes.jl
> +end
please fix this file ending (as I mentioned a few times, it is not a big deal, but I insist that we build up good habits first on a first PR)

2024-03-16 17:06 UTC, Krastanov commented
To fix the issue with the difference between master here and master on your repo, make a pull on your end, but pull from this remote. Would would look something like:

```
git pull NAME_OF_REMOTE_CORRESPONDING_TO_<github.com/QuantumSavory/QuantumClifford.jl>
```

You can see what remotes you have set up like this

2024-03-16 19:04 UTC, Fe-r-oz commented
> If you have not set this up as a remote, you can do it as follows:
> 
> ```
> git remote add https://github.com/QuantumSavory/QuantumClifford.jl.git
> ```

Thanks a lot for your comments! Sorry, that this whitespace confusion is causing annoyance and repeated checks.

Actually, I was indeed looking at the File Changed section for many days as I was reviewing the changes from there.  It was the File Changed section that helped me in tracking and removing whitespaces. 

Unfortunately, I didn't removed them all. Since Gottesman(3), Gottesman(4) was added, 2 lines were added and the lines below were pushed down by 2. In the reference.bib, I add two citation as requested, so I am confused as you commented to remove extra line. 

I hope that all the extralines are removed.  Good this is that I have resolved the changelog thanks to your comments.

2024-03-16 19:31 UTC, Krastanov commented
this looks good. I will read through, make some edits, and merge in the next hour or so

2024-03-16 19:56 UTC, Krastanov commented
I made a few changes:

- different filename, for consistency
- different bibtex names for the reference entries, for consistency (picked from google scholar)
- tightened up the writing a bit, in particular:
  - deleted `This class implements` -- no need for such introductions, get straight to the point. Also, this is not a class, rather a type. Julia does not have classes (not object oriented)
  - deleted much of the docstring -- it was a difficult mix between very technical and very nontechnical information. I do not think there was enough introduction to understand the technical information about the construction (some of the symbols were not defined) and the nontechnical information was too vague or informal
  - used unicode in the docstring to render better
- removed some unnecessary comments from the test file
- reverted some of the tests
- edited the changelog. I am pretty confused by the `(Add details from remote branch changes for v0.8.21)` entry. Why did you add that?

I will wait for the tests and then I will merge this.

2024-03-16 20:04 UTC, Krastanov commented
I ran some quick benchmarks on your routines. Here are plots of performance of the 3, 4, and 5 codes

![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/cc1bb198-076e-424d-978e-48db2ab8f741)

3 and 4 look great, but I am a bit worried that there must be something wrong with 5. They all should have the same slope (the slope depends on the distance which is 3 for all Gottesman codes). I will need to do some debugging...

2024-03-16 20:09 UTC, Fe-r-oz commented
Thanks for refinement. By class, I meant the error code class, but it's a family. 

Since the changes v.0.8.22 were not added from my branch on the master, so I thought to add this sentence.

2024-03-16 20:12 UTC, Krastanov commented
I see you are making a special case for j=3. Why?

Which algorithm exactly did you use? The one in Gottesman's thesis or another one?

2024-03-16 20:19 UTC, Fe-r-oz commented
> I see you are making a special case for j=3. Why?
> 
> Which algorithm exactly did you use? The one in Gottesman's thesis or another one?

I mentioned this point in my earlier comment when I mentioned about pedagogical details. 
>>In his thesis, Gottesman presenting "possible" checks/"similar possible" checks and that too for even j and odd j. That is >>why the smallest case for even j is [[16,10,3]]. The convenient way is to utilize the structure which automatically satisfies >>the all even and odd j checks for j>=4! The case j==3 is a special case which leads to [[8,3,3]]

I utilized the symmetric structure and developed the algorithm myself that satisfied the checks  for j>=4. Thus, defined j==3 as special case. This was convenient and much faster approach.  I designed the algorithm by hand as I did draw many tables for j>=4, so I saw a visible symmetric structure. Hence, the algorithm proved correct when it satisfied j==4, and the symmetric structure is visible as well.

Then I read his thesis again, the 4 pages from page 90 to 91, that Gottesman were describing some of the checks (not all), but I ended up implementing all the checks. This verified not only the results but the theory.

2024-03-16 20:26 UTC, Krastanov commented
It is really cool that you tried to design it by hand, but at this point I am fairly certain there is a mistake in. Do not get discouraged though, you have done it exactly the way in which you get to learn the most out of your mistake. One word of caution though: if you design something yourself, you have to always be extremely mistrustful of your own implementation.

The issue does not seem to be particularly consistent. Maybe it fails only for odd powers. Here is the test including j=6.

![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/898405c9-c7d9-491f-b9a7-34c206af5322)

It works exactly as expected for j=6.

Now the goal is to figure out what is the error for j=5. One way to try to figure that out is to implement someone else's version of the algorithm. Gottesman spells out exactly all the steps in section 3, paragraph 3-5, of this paper https://arxiv.org/pdf/quant-ph/9604038.pdf

For the moment I will turn this again into a draft. We can not merge it with the j=5 bug.

Also, it is possible there is no bug here. Maybe the bug is in the tool I use to test. I will make that one public later today.

2024-03-16 21:06 UTC, Fe-r-oz commented
> For the moment I will turn this again into a draft. We can not merge it with the j=5 bug.
>
> Also, it is possible there is no bug here. Maybe the bug is in the tool I use to test. I will make that one public later today.

Please test for j=7, j=9, odd powers etc. as well. 

I am certain that the symmetric structure and algorithm holds otherwise, it would not have worked at all because it has to be spot on to get configuration in j==4 is somewhat complicated symmetry. I drew the tables by hand to verify the algorithm. 

I read details of section 3, paragraph 3-5, but the details he provides are not complete to implement a general class  for works for all j values. 

The Question is: How do one expand from j==3 to j==4 or 5 onwards without implementing diffferent checks? 

That's why he suggests different checks in his thesis.  He discuss the even and odd j details in his thesis [Table 8.1 Page 91](https://thesis.library.caltech.edu/2900/2/THESIS.pdf) from pages **90 to 95**. Also, there is a 3x7 Hamming matrix inner structure as well which is not mentioned in the details. Gottesman Hamming codes are called extended hamming for this very reason. This inner hamming matrix 3x7 structure is missing for j==3 (another point that tells it's a special case).

2024-03-16 23:34 UTC, Krastanov commented
I probably will not be able to get a check for j>7, these are expensive to run.

I disagree about the paper. It lists the complete algorithm. It is something like this:

consider a fixed j and then set n=2^j (number of physical qubits) and k = n-j-2 (number of logical qubits) and c = j+2 (number of checks)

1. First, prepare three tables of neatly ordered bitstrings. I will call them tableX, tableY, tableZ. The paper goes into details of how to prepare these tables. These tables have n rows and c columns. Using the nomenclature in the paper, row r of table"E" would be the syndrome that your code is supposed to have if it experiences single qubit error E acting on qubit r.

2. These tables are enough to figure out what your parity checks are. Each of the c columns of the tables corresponds to one parity check (one row of the stabilizer).

More explicitly: For parity check row R and qubit column Q you have to put the following Pauli:

- if tableX(row = Q, column = R)==1 and tableZ(row = Q, column=R)==1 then put Y
- elseif tableX(row = Q, column = R)==1 and tableY(row = Q, column=R)==1 then put Z
- elseif tableZ(row = Q, column = R)==1 and tableY(row = Q, column=R)==1 then put Y
- else put Identity

This can be done easily with our library. You do not need to actually compute the three tables in advance, you can do everything on the fly:

```
parity_checks = zero(Stabilizer, n, c)
for e in 1:2^j # the row of the error tableE
    for b in 3:n # the bit of the integer we are working with (the first two bits are constante "true")
        z = the b-th bit of the e-th row of tableZ
        x = the b-th bit of the e-th row of tableX 
        parity_checks[error_row,bit] = z, x # note that they are flipped
    end
end
```

By the way, in case you have not seen it before, extracting a bit from an integer can be done as: `isone((integer >> (bit-1)) & 0x1)`

2024-03-17 05:59 UTC, Fe-r-oz commented
Thanks. I read the appendix of paper that you mentioned https://arxiv.org/pdf/quant-ph/9604038.pdf. The **Table V** gives Xi, Zi, and Yi. The algorithm produces the same Xi and Zi checks! I will recheck Yi (seem similar though, but I will check).

_Some details in the appendix of same paper:_
For s = r + 1, the general case gives 4 blocks with normal disagreements and 2 blocks with reversed disagreements. When r = 3, there are 2 blocks with normal disagreements and 2 blocks with reversed disagreements. When s = a, and j is even, there are 2 blocks with normal disagreements and 0 blocks with reversed disagreements. When s = a and j is odd, there are also 2 blocks with normal disagreements and 0 blocks with reversed disagreements. **Because a ≥ 5, we do not need to consider the combined special case**

My question is that although I agree that the paper you referenced provided similar starting details as in thesis, but the way Gottesman entertain [16,10,3]] adds new set of different details on top of the details the he provides in the previous paper. Why does he start from the same set of details and expound further in his thesis needs to be investigated?

Kindly please have a look at the pages **90 to 95** as well. I will read both of the papers again, and try to find the hidden incongrueny!

If it is possible to check somehow j==7, 9 etc. , kindly please test as that might give us more information!

2024-03-17 07:35 UTC, Fe-r-oz commented
I have tried to fixed the bug. 

There was assumption that about the last row that I assumed to hold for all cases. Kindly please check the graph for j=5 (odd js) and let me know. Everything else is the same

2024-03-17 13:43 UTC, Fe-r-oz commented
Please see the Fresh Results :)


![display](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/9d72f535-d02b-4407-a9c3-95b39079a244)

![display](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/e279c6c6-64e3-40ad-a557-c7ebfb1802d1)

2024-03-17 13:46 UTC, Krastanov commented
> Thanks. I read the appendix of paper that you mentioned https://arxiv.org/pdf/quant-ph/9604038.pdf. The **Table V** gives Xi, Zi, and Yi. The algorithm produces the same Xi, Zi checks! I will recheck Yi (seem similar though, but I will check). It seems the the last row for odd js is not assumed to be same as even js which was assumed! It means that the last row for odd js as same as even js that's why - which can be fixed!!

I am unsure what you are saying -- I do not know whether you are talking about your algorithm or about the algorithm in the paper.

> _Some details in the appendix of same paper:_ For s = r + 1, the general case gives 4 blocks with normal disagreements and 2 blocks with reversed disagreements. When r = 3, there are 2 blocks with normal disagreements and 2 blocks with reversed disagreements. When s = a, and j is even, there are 2 blocks with normal disagreements and 0 blocks with reversed disagreements. When s = a and j is odd, there are also 2 blocks with normal disagreements and 0 blocks with reversed disagreements. **Because a ≥ 5, we do not need to consider the combined special case**

I have not read the appendix. It seems to be about a proof that the algorithm described earlier in the paper is correct. I was just looking at the definition of the algorithm in section 3.

> My question is that although I agree that the paper you referenced provided similar starting details as in thesis, but the way Gottesman entertain [16,10,3]] adds new set of different details on top of the details the he provides in the previous paper. Why does he start from the same set of details and expound further in his thesis needs to be investigated?

That is pretty normal when someone writes a thesis that includes one of their paper from a few years earlier. I imagine (I am not sure), that the author simply wanted to provide some additional insight, so they structured the presentation a bit differently and choose a slightly different convention for bit ordering or error ordering.

> Kindly please have a look at the pages **90 to 95** as well. I will read both of the papers again, and try to find the hidden incongrueny!

I do not think there is mismatch in what they are doing in the two publications. One might have slightly different conventions from the other, but you already found other papers that also had slightly different conventions.


I am very impressed you were able to find your bug so quickly! However I also need to worry about the maintainability of this piece of code (in a year or two you might not be involved in the project to fix other bugs). Because of this, I prefer we switch to the algorithm as described in Gottesman's paper:

1. it is a standard reference, not homegrown
2. it is shorter (probably 20ish lines instead of 75 lines)
3. it does not have special cases

Presumably the two should give the same answers (up to some reordering). At the end, that is the only way to be sure (or at least "a bit less unsure") that there is no other bug here.

2024-03-17 14:38 UTC, Fe-r-oz commented
> I am unsure what you are saying -- I do not know whether you are talking about your algorithm or about the algorithm in the paper. [Table V, Page 17.](https://arxiv.org/pdf/quant-ph/9604038.pdf.)

I am talking about the algorithm that is presented in the paper. The homegrown algorithm produces the same Xi, Zi checks.

![Screenshot_select-area_20240317185542](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/f12baf23-12a3-4b11-9512-cee4e60c8fbf)

> That is pretty normal when someone writes a thesis that includes one of their paper from a few years earlier. I imagine (I am not sure), that the author simply wanted to provide some additional insight, so they structured the presentation a bit differently and choose a slightly different convention for bit ordering or error ordering.

I think that even and odd checks in Pages 92 and 95 are necessary, as in the paper, he does not consider that [[16,10,3]] even case and how its differs from the the initial odd case [[8,3,3]] that he describes in earlier paper prior to thesis. But he goes into detail in his thesis. 

> I do not think there is mismatch in what they are doing in the two publications. One might have slightly different conventions from the other, but you already found other papers that also had slightly different conventions.

It's not about convention but about the type of the even and odd checks that results in a slightly differeny symmetric structure for even j values and odd j values. He dedicates 3 pages to the checks, meaning they are significant part of the algoritm!. My homegrown algorithm satisfies that.

> I am very impressed you were able to find your bug so quickly! However I also need to worry about the maintainability of this piece of code (in a year or two you might not be involved in the project to fix other bugs). Because of this, I prefer we switch to the algorithm as described in Gottesman's paper:

> 1. it is a standard reference, not homegrown
> 2. it is shorter (probably 20ish lines instead of 75 lines)
> 3. it does not have special cases

> Presumably the two should give the same answers (up to some reordering). At the end, that is the only way to be sure (or at least "a bit less unsure") that there is no other bug here.

While I understand your concens, Please rest assured as I have faith in the symmetry and intuition, it holds nicely and with accuracy as  it does satisfies the `[Table 8.1 on Page 91](https://thesis.library.caltech.edu/2900/2/THESIS.pdf)` of his thesis!  That is a good cross-verification! I will always be available to maintain this code as I would like to keep on contributing to this initiative.  It's just more fun to follow my intuitive approach as I makes me happy as it makes the learning more fun!

The slight bug was there in my assumption of combining even and odd check at one place which I took care of. I knew about the assumption so it was not luck.

 Since, I approached the design from methodolody of his thesis, it's a standard reference! I don't think the shorter version will be bug free if checks are not included, otherwise he would not have dedicated 3 pages to them in his thesis. 
I will always be present to maintain this code. It's just exciting to come up with a intuitive algorithm.  I have faith in the homegrown algorithm as it incorporates the theory and literature, including his thesis as I approach the design from symmetric structure point of view. 

Please be assured!

2024-03-17 15:19 UTC, Krastanov commented
> Please be assured!

Your work is impressive, but this is not how assurances work, especially not in math and computer science. **You should never trust your own code**. The amount of trust you put in yours is how bugs happen. Verifying one case against a table is not a good verification (as we have seen already).

There is never a way to be completely sure in the correctness of a piece of code, but there are reasonable ways to increase the probability that the code is correct. Here there are two pretty straightforward ways to do it:

1. Add tests that verify the properties expected from the code. The main one is "every single-qubit error should have a different syndrome". That one is relatively easy and it will actually provide the same type of guarantees :
```
syndromes = Set([]) # the set automatically removes repeated entries
for error_type in (single_x, single_y, single_z)
    for bit_index in 1:n
        syndrome = comm(parity_check_tableau, error_type(n, bit_index))
        @test any(==(0x1), syndrome) # checking the syndrome is not trivially zero
        push!(syndromes, syndrome)
    end
end
@test length(syndromes) == 3*n # checking that each single-qubit error has a unique syndrome
```

2. Implement the very short algorithm from Gottesman's paper that I shared -- which would have the extremely important added benefit that this will be something that other people can also debug in the future, and is much shorter than your current implementation.

Both of these are necessary before this gets merged. Obviously, you work as a volunteer for this and I can not demand anything -- you have already made a very helpful and valued contribution and I am grateful for it. You also shared a lot of resources that were very interesting, and this discussion has certainly been valuable for me. I thank you for all of these contributions!!! I will be happy to finish this on my own if you disagree about the approach I am taking.

2024-03-17 15:20 UTC, Krastanov commented
And there is a pretty easy way to convince me that the algorithm I am suggesting, the one from the paper, needs these extra checks -- write it and show that it does not pass the tests I just mentioned (the one with the length of the set of syndromes).

2024-03-17 16:04 UTC, Fe-r-oz commented
> And there is a pretty easy way to convince me that the algorithm I am suggesting, the one from the paper, needs these extra checks -- write it and show that it does not pass the tests I just mentioned.

Thanks for the two points.

I'll read the paper that you referred and implement it. Can I include these two points in initial weeks of my proposal (to write an algorithm for the paper) as I need time to carefully to read the paper and then focus on implementation as you want a exact paper implementation? That will help in more literature survey as I will spend next month in literature survey.

2024-03-17 18:44 UTC, Fe-r-oz commented
> 1. First, prepare three tables of neatly ordered bitstrings. I will call them tableX, tableY, tableZ. The paper goes into details of how to prepare these tables. These tables have n rows and c columns. 

Where are exactly the details for generating tables you are referring to? Please specify them from the paper.

If you are talking about this:
After reading the section three: Tables can be generated by  **generating all possible bitstrings of length n**

```
Select Binary Numbers:
    Pick (j+2)-bit binary numbers for Xi and Zi (for i=1,2,...,ni=1,2,...,n).
    Ensure numbers for Yi​ (XOR of Xi and Zi​) are all different.
```

For explicit construction of [[8,3,3]] code: he presents
![Screenshot_select-area_20240317233438](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/4cbf730a-b4b0-4ef3-b5a0-aff3395b4d2d)



> 2. These tables are enough to figure out what your parity checks are. Each of the c columns of the tables corresponds to one parity check (one row of the stabilizer).

Please specify the tables you are referring. 


> This can be done easily with our library. You do not need to actually compute the three tables in advance, you can do everything on the fly:

There is a contradiction here: If we don't need to compute the tables, then there is no need to define them in memory either. Also, how does this make sure that size of Stabilizer code matrix correct given the definitions here?
>parity_checks = zero(Stabilizer, n, c). 
Examle: n=2^j, j=3, then n=8, and j+2= 5. This will give 8x5. When the size should be 5 Rows and 8 columns. So, to say ther are c checks seems incorrect?

for j=6, the matix should be: 8x64. The resulting matrix size from this algorithm seems to be incorrect.

I don't this the implementation is 20is lines or efficient and how is this general for all js?

2024-03-17 19:03 UTC, Krastanov commented
> Where are exactly the details for generating tables you are referring to? Please specify them from the paper.

![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/b3e87cd2-863c-4b36-a76f-864c98322553)
![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/2c2b7145-c709-4a76-84dd-eb5f9b8d21ff)
 
> Please specify the tables you are referring.

The tables I defined in my comment.

> Using the nomenclature in the paper, row r of table"E" would be the syndrome that your code is supposed to have if it experiences single qubit error E acting on qubit r.

> > This can be done easily with our library. You do not need to actually compute the three tables in advance, you can do everything on the fly:
> 
> There is a contradiction here: If we don't need to compute the tables, then there is no need to define them in memory either. Also, how does this make sure that size of Stabilizer code matrix correct given the definitions here?

You do not need to compute the tables **in advance**, i.e. no need to store them in memory. You do need to loop through the rows and columns, but entries can be computed on the fly.

> Example: n=2^j, j=3, then n=8, and j+2= 5. This will give 8x5 which is wrong. When the size should be 5 Rows and 8 columns. So, to say ther are c checks seems incorrect?

For j=3, we have n=8 physical qubits, k=n-j-2=3 logical qubits, c=n-k=5 checks, which means the parity check tableau should indeed have 5 rows and 8 columns.

> I don't think the implementation is 20ish lines.

I will write it and upload it here in a couple of days when I get around to it. It is just 20ish lines.

2024-03-17 19:54 UTC, Fe-r-oz commented
> The tables I defined in my comment.

Thanks! I mixed the Tables provided in the algorithm that you mentioned namely tableX, tableY, tableZ  tables on Page 17. That's why I was confused about where were the tables! 

> You do not need to compute the tables **in advance**, i.e. no need to store them in memory. You do need to loop through the rows and columns, but entries can be computed on the fly.

I see, then it will be way less lines since we are Pauli operators based on error type!! 

Indeed, it might be very short code them. I thought we needed to compute all the different combinations as were described in table 1. Thanks for clarification!

2024-03-17 20:25 UTC, Krastanov commented
here is the code

```
function parity_checks(c::Gottesman)
    j = c.j
    s = j+2
    n = 2^j

    H = zero(Stabilizer, s, n)
    for i in 1:n
        H[1, i] = (true, false)
        H[2, i] = (false, true)
    end
    for i in 0:n-1 # column of H, corresponds to a single qubit error that is detectable)
        Xⁱ = i
        Zⁱ = i÷2
        jeven = j%2 == 0
        ieven = i%2 == 0
        if (jeven && ieven) || (!jeven && ieven && i < n÷2) || (!jeven && !ieven && i ≥ n÷2)
            Zⁱ = ~Zⁱ
        end
        for b in 0:j-1 # which check to consider (row of H), also which bit to extract
            H[s-b,i+1] = isone((Zⁱ>>b)&0x1), isone((Xⁱ>>b)&0x1)
        end
    end
    H
end
```

and here is the checks for it


```
H = parity_checks(Gottesman(j))
syndromes = Set([]) # the set automatically removes repeated entries
for error_type in (single_x, single_y, single_z)
    for bit_index in 1:nqubits(H)
        syndrome = comm(H, error_type(nqubits(H), bit_index))
        @assert any(==(0x1), syndrome) # checking the syndrome is not trivially zero
        push!(syndromes, syndrome)
    end
end
@assert length(syndromes) == 3*nqubits(H)
```

2024-03-17 21:05 UTC, Fe-r-oz commented
Dear Professor

Please see the output of j==4 [[16,10,4]] it seems it does not match with what is presented in his thesis [Table 8.1 Page 91](https://thesis.library.caltech.edu/2900/2/THESIS.pdf)

2024-03-17 21:09 UTC, Fe-r-oz commented
In fact, the first two bits of Xi must always be 01 but the out is showing 10.
This is the output from the code you presented:

 parity_checks(Gottesman(4))
+ XXXXXXXXXXXXXXXX
+ ZZZZZZZZZZZZZZZZ
+ X_X_X_X_YZYZYZYZ
+ X_X_YZYZ_X_XZYZY
+ X_YZ_XZYX_YZ_XZY
+ XZ_YXZ_YXZ_YXZ_Y

But there is a fundamental design error, M1..Mj , first digit can't be X. Please see his comments below:

![Screenshot_select-area_20240318020645](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/c3e6596a-6976-40c5-bd26-cde40cffcba5)

2024-03-17 22:12 UTC, Krastanov commented
Hi Feroz! I answer that question in the linked pull request. The stabilizers are equivalent because you can obtain one from the other by performing a row operation.

2024-03-18 00:10 UTC, Krastanov commented
Closing in favor of #240 which is a slightly updated version of this.

2024-03-18 00:10 UTC, closed without merging