adding iscss for issue #212
QuantumSavory/QuantumClifford.jl pull request #241
Opened 2024-03-18 14:54 UTC by Fe-r-oz

Hi Stefan,

Given the stabilizer has the knowledge, the `isscss` function is implemented.

2024-03-18 15:33 UTC, Krastanov commented
And this probably needs some tests. E.g. for each code check what `iscss` says and then check whether their parity check matrix is indeed in CSS form. The check would be expensive, it will have to go through the entire tableau of a specific code instance, but it will be happening only when running the test suite.

2024-03-18 17:56 UTC, Fe-r-oz commented
> And this probably needs some tests. E.g. for each code check what `iscss` says and then check whether their parity check matrix is indeed in CSS form. The check would be expensive, it will have to go through the entire tableau of a specific code instance, but it will be happening only when running the test suite.

I thought this was not needed because the stabilizer has the knowledge as you said.  Only, tests are to be remaining.

Please have a look at modifications.

so, now I need to use an algorithm that check whether H matrix is in CSS form? Can the stabilizer knowledge can be used here or it's an expensive method, I need to look for a general algorithm in literature?

2024-03-18 18:27 UTC, Krastanov commented
> I thought this was not needed because the stabilizer has the knowledge as you said. Only, tests are to be remaining.

The point of tests is to check whether such assumptions or internal constants are correct. It is not something that runs when the user is using the library, rather it is for the developers to check whether they have made an error (e.g. like setting `iscss(::SomeCode) = true` when it should not be).

2024-03-18 18:28 UTC, Krastanov commented
> I need to look for a general algorithm in literature?

It is a simple check, not something that you need to look up in the literature. For each row of a parity check tableau check whether it contains a mix of X and Z. As long as they do not, it is a CSS code.

2024-03-18 18:30 UTC, Krastanov commented on src/ecc/ECC.jl
> +function iscss(::Type{T}) where T<:AbstractECC
it would make sense to have a check for an instance of a type, not just a check for the type. Something like `iscss(c::AbstractECC) = iscss(typeof(c))`

2024-03-18 18:31 UTC, Krastanov commented on CHANGELOG.md
> +- adding iscss function
this is not resolved, do not mark it as resolved until done

2024-03-19 02:57 UTC, Fe-r-oz commented
> It is a simple check, not something that you need to look up in the literature. For each row of a parity check tableau check whether it contains a mix of X and Z. As long as they do not, it is a CSS code.

Prepared according to desired functionality.

2024-03-19 03:28 UTC, Fe-r-oz commented
I added tests for Gottesman(3) and some other CSS codes. The results are correct in the DownGrade Test!

2024-03-19 04:38 UTC, Krastanov commented on test/test_iscss.jl
> +function is_css_matrix(H)
I think this test will claim that 
```
YI
IY
```
is a CSS matrix.

I believe the following would be much cleaner and correct:

```
has_x |= H[i,j][1]
has_z |= H[i,j][2]
```

2024-03-19 04:39 UTC, Krastanov commented on test/test_iscss.jl
> +            end
```suggestion
            has_x |= H[i,j][1]
            has_z |= H[i,j][2]
            has_x && has_z && return false
```

2024-03-19 04:40 UTC, Krastanov commented on test/test_iscss.jl
> +    println("Is CSS: ", is_css)
do not print in tests, this would significantly pollute the logs, making them difficult to read

2024-03-19 04:41 UTC, Krastanov commented on test/test_iscss.jl
> +end
rework this in the form of:
```
for code in known_css_codes
    @test iscss(code) == is_css_matrix(parity_checks(code))
end
for code in known_noncss_codes
...
```

2024-03-19 04:42 UTC, Krastanov commented on test/test_iscss.jl
> +end
Currently your tests are just printing things, not actually testing for properties. It should be the opposite, a human should not need to read the tests, rather the test runner will notify the human if the tests fail.

2024-03-19 04:43 UTC, Krastanov commented on CHANGELOG.md
> +- adding iscss function
Add a full sentence and proper formatting. E.g. use backticks to mark `iscss` as code and explain what it is for.

2024-03-19 04:44 UTC, Krastanov commented on test/runtests.jl
> +@doset "iscss"
let's call it `ecc_iscss` to keep the convention followed by the other ECC-related files

2024-03-19 04:46 UTC, Krastanov commented on test/test_iscss.jl
> +end
actually, no, the tests should be more thorough than what I wrote above and there is no need to split it in two separate lists. You want this tested for all codes and the equality will be valid no matter whether the code is css or not.

2024-03-19 19:27 UTC, Krastanov requested changes
Thank you! This is getting pretty close. I left a few comments.

2024-03-19 19:27 UTC, Krastanov commented on src/ecc/codes/clevecode.jl
> +
```suggestion
```

This is not needed because of the default you have already set for all subtypes of AbstractECC

2024-03-19 19:27 UTC, Krastanov commented on test/test_ecc_iscss.jl
> +        @assert is_css_matrix_result == true "If code is CSS, then parity_check_matrix must be in CSS form."
this should be `@test` not `@assert`

2024-03-19 19:27 UTC, Krastanov commented on test/test_ecc_iscss.jl
> +            test_code(code)
you seem to be running the same test twice. You can just keep line 32-34 and delete the rest of the unused stuff.

2024-03-19 19:27 UTC, Krastanov commented on CHANGELOG.md
> +- Added `iscss` function to determine whether a given code is a CSS (Calderbank-Shor-Steane) code and to verify if its parity check matrix is indeed in CSS form.
This does not seem like a correct description. It is not verifying its parity check matrices. It just says whether the code is known to be a CSS code. The tests are running actual verifications of course, but that is not part of the function.

This matters, because the way it is currently written it sounds like `iscss` is a slow function that needs to read the matrix.

2024-03-19 21:54 UTC, Krastanov commented
I also see you are making a ton of small commits just as you are working through things.

It helps to do the following:

- try to make commits that are somewhat selfcontained and tell a clear story of how the work is evolving
- use the `--amend` flag to just add to the last commit instead of creating a new commit, if they are not logically separated
- aim to push in one big batch, not after each commit, because each time you push, fairly expensive automated testing is being run on your code. No need to test code you know is unfinished. Generally, run the tests locally (with the `]test QuantumClifford` command) before pushing, to make sure the tests pass for you first

2024-03-19 22:37 UTC, Fe-r-oz commented on src/ecc/codes/gottesman.jl
> +end
You are very right!

2024-03-19 22:38 UTC, Fe-r-oz commented on test/test_ecc_iscss.jl
> +            test_code(code)
You are right!

2024-03-19 22:53 UTC, Krastanov commented
do not worry about the buildkite failure -- it will work again after a few new version registrations get propagated through the ecosystem

2024-03-19 23:18 UTC, Fe-r-oz commented
> I also see you are making a ton of small commits just as you are working through things.

Thanks for your comments. I will keep this in mind. Actually, this one had merge conflicts, and commit from other branches got mixed with this branch.

2024-03-20 03:16 UTC, Krastanov commented on test/test_ecc_iscss.jl
> +    end
this does not make much sense to me. If line 23 is correct, then line 25 will also be correct. The test can be much simpler (we do not even need a separate function for this, it can all be in line 33)

2024-03-20 03:16 UTC, Krastanov commented on test/test_ecc_iscss.jl
> +            has_z |= H[i,j][2]
`e` is not used here

2024-03-20 03:19 UTC, Krastanov commented
There are two rather minor issues, but they are also issues that are simply due to inattentiveness, not to some big conceptual problem. Please make sure you reread your code closely before submitting for reviews -- It is important to build up the habit to detect this type of minor issues on your own.

2024-03-20 03:23 UTC, Fe-r-oz commented on test/test_ecc_iscss.jl
> +            has_z |= H[i,j][2]
this e is from the previous approach!

2024-03-20 03:24 UTC, Fe-r-oz commented on test/test_ecc_iscss.jl
> +    end
yes, it's seem line 24 to 25 does any difference since line 23 asks the same thing!

2024-03-20 03:26 UTC, Fe-r-oz commented on test/test_ecc_iscss.jl
> +    end
yeah, we can put 22 and 23 at line 33 34, delete line 33. no use in calling the function

2024-03-20 03:38 UTC, Fe-r-oz commented
> There are two rather minor issues

Minor issues are dealth with

2024-03-20 03:45 UTC, Krastanov commented
I made a minor rephrasing in the changelog. I will wait for the tests and then merge. Thank you, having this done is very helpful!

2024-03-20 04:09 UTC, merged

2024-03-20 04:12 UTC, Krastanov commented
Be more careful with title and references. This closes issue 222, not issue 212. A bit too late to change the commit message now, so we can just close it manually.

2024-03-20 08:16 UTC, Fe-r-oz commented
> I made a minor rephrasing in the changelog. I will wait for the tests and then merge. Thank you, having this done is very helpful!

Thank you as well!