adding classical Reed-Muller Code
QuantumSavory/QuantumClifford.jl pull request #244
Opened 2024-03-20 11:54 UTC by Fe-r-oz

Hi, Prof. Stefan,

Adding Classical Reed Muller Code. This code is the second addition after Rep Code which is a important subroutine in alrealy implemented codes such as` Shor9.`

Reed Muller Code will have a similar objective, as classical reed muller codes can be used to create quantum codes.

While updating the changelog, I found something odd.  It has ****(breaking)** and ****(fix)** appears in the main master branch. Please see to it.

I tested locally:

```
Reed-Muller Code Parameters: ReedMuller(2, 3)
Parity Matrix:
[1 1 1 1 1 1 1 1; 1 1 1 1 0 0 0 0; 1 1 0 0 1 1 0 0; 1 0 1 0 1 0 1 0; 1 1 0 0 0 0 0 0; 1 0 1 0 0 0 0 0; 1 0 0 0 1 0 0 0]

Reed-Muller Code Parameters: ReedMuller(1, 3)
Parity Matrix:
[1 1 1 1 1 1 1 1; 1 1 1 1 0 0 0 0; 1 1 0 0 1 1 0 0; 1 0 1 0 1 0 1 0]
```

I will find the tests where `RepCode` is defined and add similar test for Reed Muller code there

2024-03-20 20:13 UTC, Krastanov commented
This is great! Thank you! I will leave some superficial comments today, just on style or more obvious things. I will try to review the more sophisticated math content later

2024-03-20 20:19 UTC, Krastanov requested changes
Some minor style comments, nothing particularly significant.

It needs tests.

Could you let me know what you used as a reference when implementing this?

> While updating the changelog, I found something odd. It has **(breaking) and **(fix) appears in the main master branch. Please see to it.

I do not see anything, let me know if I have missed something.

2024-03-20 20:19 UTC, Krastanov commented on src/ecc/ECC.jl
> +    ReedMuller,
Let's not export it for now, until we see where it will be used.

2024-03-20 20:19 UTC, Krastanov commented on src/ecc/codes/reedmullercode.jl
> +function construct(m, i)
rename this so it is not confusing when people see it in a listing out of context. Maybe something like `_construct_reedmuller`, maybe even with a leading underscore to mark it is some private function

2024-03-20 20:19 UTC, Krastanov commented on src/ecc/codes/reedmullercode.jl
> +function parity_checks(c::ReedMuller)
There does not seem to be any tests or correctness checks for this. How can someone know it is correct? Are there some properties or examples that can be verified? Is there a reference on which you based this code?

2024-03-20 20:19 UTC, Krastanov commented on test/test_throws.jl
> +@test_throws ArgumentError ReedMuller(-1, 3)
could you make a new file for these, so that it is easy to keep track what is coming from a submodule. Otherwise this will become difficult to manage. E.g. `test_ecc_throws.jl`

2024-03-20 20:19 UTC, Krastanov commented on src/ecc/ECC.jl
> +include("codes/reedmullercode.jl")
to keep things consistent with the rest of the filenames, let's name it `reedmuller` instead of `reedmullercode`. Actually, maybe a whole new folder `classical` would make sense here.

2024-03-20 20:48 UTC, Fe-r-oz commented on src/ecc/codes/reedmullercode.jl
> +function parity_checks(c::ReedMuller)
You are right. I tested all these functions locally, I will add all of their tests, I didn't added their tests as I  wanted to ask you which files to add their tests. 

But it seems I will create a new file for reed muller to add their tests as you pointed out!

2024-03-20 20:48 UTC, Fe-r-oz commented
> This is great! Thank you! I will leave some superficial comments today, just on style or more obvious things. I will try to review the more sophisticated math content later


I verified the results of R(2,3) and R(1,3) from wiki: They have the complete[ matrices ](https://en.wikipedia.org/wiki/Reed%E2%80%93Muller_code)

As the the logic and how we generate these codes, here is a proper reference from [Google Scholar](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=BRN7EZMAAAAJ&citation_for_view=BRN7EZMAAAAJ:Tyk-4Ss8FVUC). This has been very helpful as it explained them very simply.

2024-03-20 20:57 UTC, Fe-r-oz commented
> It needs tests.

I will create a test file. I was looking were were Rep Code tests were defined, but as you pointed out, I will tests all the functions. 

As for changelog, I see this **breaking** at some lines,.

![Screenshot_select-area_20240321015410](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/28be798c-c660-48d3-9f76-98b53f09d5ff)

2024-03-20 21:08 UTC, Krastanov commented
on "breaking": The changelog is there to tell other people about what has changed so they do not need to look at the git history. Last night I released version 0.9.0 (a "breaking" release as defined in SemVer https://semver.org/ ) and so the changelog has these breaking changes clearly marked up so that users know if they need to change something about their use of the library.

on references: Add that paper to the bibtex and reference it in the docstring. Also, due to a current limitation of how bibtex references are managed, add a mention of it in the list at the bottom of references.md

on tests: yeah, it is possible that `test_throws.jl` contains things that would have been better put in a different file. This will happen frequently, situations where someone reviews your code and asks you to do something to a better standard than what is already done in the library. It is the "leave a place better than you found it" principle, and it is the only way to not devolve into a mess, but it can be understandably annoying to the new contributor.

When you add the tests, mark in comments where the "correct" results in the comparisons are coming from.

2024-03-21 07:14 UTC, Fe-r-oz commented on src/ecc/codes/reedmullercode.jl
> +function construct(m, i)
This function generates the binanry variables xi which are building blocks of Rm codes. I will name it appropriately,

2024-03-21 17:27 UTC, Fe-r-oz commented on src/ecc/ECC.jl
> +    ReedMuller,
For testing purpose, I need to export it so that I can used it in `test_ecc_reedmuller.jl`

2024-03-21 17:43 UTC, Krastanov commented
I mentioned this before but just a reminder: do not send a ton of small commits one after the other. That causes a ton of emails and a ton of expensive test runs on unfinished code. Do a push when you have something ready.

2024-03-21 17:49 UTC, Fe-r-oz commented
> I mentioned this before but just a reminder: do not send a ton of small commits one after the other. 

Sorry for that. I did send the first commit will most files. Actually, I missed some changes.

2024-03-21 19:00 UTC, Krastanov commented on docs/src/references.bib
> +@incollection{DJORDJEVIC2021193,
For the reference label, could you keep them in google scholar format, just for consistency? The content of the reference here is much more thorough than what google scholar gives you, but just for the label, keep their format. E.g. `djordjevic2021information`

2024-03-21 19:00 UTC, Krastanov commented on docs/src/references.bib
> +title = {Chapter 6 - Information Theory and Classical Error Correcting Codes},
remove "Chapter 6" from the title

2024-03-21 19:02 UTC, Krastanov commented on src/ecc/codes/classical/reedmuller.jl
> +"""The family of `[[2ᵐ, ∑ⱼ₌₀ʳ ᵐC₍ⱼ₎, 2ᵐ⁻ʳ`]] Reed-Muller codes, as described in [Raaphorst's 2003 paper](@cite raaphorst2003reed).
The backtick seems to be in the wrong location.

The reference here is kinda wrong. You can say you can consult Raaphorst's tutorial, but they simply have the equivalent of lecture notes on the topic. They are not the ones that have introduced these codes.

2024-03-21 19:02 UTC, Krastanov commented on src/ecc/codes/classical/reedmuller.jl
> +"""The family of `[[2ᵐ, ∑ⱼ₌₀ʳ ᵐC₍ⱼ₎, 2ᵐ⁻ʳ`]] Reed-Muller codes, as described in [Raaphorst's 2003 paper](@cite raaphorst2003reed).
I would also suggest deleting the `[[...]]` string -- it is not legible and understandable.

2024-03-21 19:05 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedmuller.jl
> +"""The family of `[[2ᵐ, ∑ⱼ₌₀ʳ ᵐC₍ⱼ₎, 2ᵐ⁻ʳ`]] Reed-Muller codes, as described in [Raaphorst's 2003 paper](@cite raaphorst2003reed).
Then, we can use the [second reference,](https://arxiv.org/abs/quant-ph/9608026) it's much more pedagogical. 

Yes, this first reference is more like Preskill notes.

2024-03-21 19:08 UTC, Krastanov commented on test/test_ecc_reedmuller.jl
> +@testset "Testing common examples RM(r,m) codes [raaphorst2003reed](@cite) and [abbe2020reed](cite)" begin
this is great!

I am trying to think trough what would be a more universal way to test these. I am think potentially checking the rank of the matrices would make sense. You can try something like:

```
for r in ... for m in ...
    H = parity_checks(ReedMuler...)
    @test size(H) == something that depends on r and m
    mat = Nemo.matrix(Nemo.GF(2), H) # necessary to convert to a matrix type for which `rank` works correctly
    @test LinearAlgebra.rank(mat) == ...
end
```

The weird conversion from `H` to `mat` is because `rank` by default assumes you are asking for the matrix rank over the real numbers, not for the rank over the boolean field.

2024-03-21 19:12 UTC, Krastanov commented on src/ecc/codes/classical/reedmuller.jl
> +"""The family of `[[2ᵐ, ∑ⱼ₌₀ʳ ᵐC₍ⱼ₎, 2ᵐ⁻ʳ`]] Reed-Muller codes, as described in [Raaphorst's 2003 paper](@cite raaphorst2003reed).
It is more about phrasing. The reference you have here already is good pedagogical reference. Rather, my point is that your current phrasing makes it sound like these guys invented the RM code.

One possible solution about the phrasing: You can remove this reference from the header and just include it as one of the other "consult also" references. Including the latest one from your last comment also makes sense.

2024-03-21 20:04 UTC, Fe-r-oz commented on test/test_ecc_reedmuller.jl
> +@testset "Testing common examples RM(r,m) codes [raaphorst2003reed](@cite) and [abbe2020reed](cite)" begin
Yes!

We can compute the rank using the standard formula for Reed Muller codes that is given in the refernce which is that `rank = sum from i to r  [m choose i]` and compare it with rank calculated via Nemo. It's working. I tested locally!

2024-03-21 20:08 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedmuller.jl
> +"""The family of `[[2ᵐ, ∑ⱼ₌₀ʳ ᵐC₍ⱼ₎, 2ᵐ⁻ʳ`]] Reed-Muller codes, as described in [Raaphorst's 2003 paper](@cite raaphorst2003reed).
Point noted. I will do all these suggested changes and do a single commit.

2024-03-22 00:46 UTC, Krastanov commented
you do not need to make a single commit, but please make sure you are making a single push, not a ton of frequent pushes

2024-03-22 00:54 UTC, Krastanov commented on src/ecc/codes/classical/reedmuller.jl
> +The ECC Zoo has an [entry for this family](https://errorcorrectionzoo.org/c/reed_muller)
wonderfully written docstring

2024-03-22 00:57 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedmuller.jl
> +The ECC Zoo has an [entry for this family](https://errorcorrectionzoo.org/c/reed_muller)
Thanks!

2024-03-22 00:57 UTC, Krastanov commented on src/ecc/codes/classical/reedmuller.jl
> +    row_matrices = [reduce(vmult, [xi[i + 1] for i in S], init = ones(Int, 2^m)) for s in 0:r for S in combinations(0:m - 1, s)]
I imagine the 2^m will overflow quickly. Could you add a check in the constructor that throws an error if m is too big?

2024-03-22 00:58 UTC, Krastanov commented
This looks really great, thank you for contributing it! I have one very minor comment, but otherwise this seems ready to merge.

2024-03-22 01:23 UTC, Fe-r-oz commented
> This looks really great, thank you for contributing it!

Thank you! I learned a lot as well!

2024-03-22 01:27 UTC, Krastanov commented
there was another thing I fixed in the last commit. You were calling `collect`, which can be an extremely expensive operation. Directly calling `length` is cleaner. I will wait for the tests and merge. Thank you!

2024-03-22 04:55 UTC, Krastanov commented
Thank you for the addition!

2024-03-22 04:55 UTC, merged