Surface code
QuantumSavory/QuantumClifford.jl pull request #246
Opened 2024-03-22 04:12 UTC by royess

The PR adds surface codes, which are tailored toric codes that require less boundary connectivity,

- Implement surface codes based on existing toric code implementation.
- Implement a specially tailored 9-qubit surface code.
- Improve the docstrings for the toric code and add its reference paper.

2024-03-22 08:14 UTC, royess commented
I have fixed an overwrite bug; now, most CI tasks are passed. I noticed some failures, but they seem to be unrelated to this PR. 

@Krastanov, could you help review this PR? Thanks!

2024-03-22 20:57 UTC, Krastanov commented on src/ecc/codes/toric.jl
> +|--1-(Z)-2--|
these diagrams should be in code blocks (backticks), otherwise they will render very weirdly in the html docs.

2024-03-22 21:32 UTC, Krastanov requested changes
Thanks! This looks great!

2024-03-22 21:32 UTC, Krastanov commented on src/ecc/codes/surface.jl
> +parity_checks(c::Surface9) = S"
I do not think we need a separate `Surface9` code.

2024-03-22 21:32 UTC, Krastanov commented on src/ecc/codes/surface.jl
> +"""The surface code [fowler2012surface](@cite), which is a tailored toric code with only the nearest neighboring connections in a 2D plane.
Fowler should probably not be the first reference, they are not the ones that discovered the code. But they can be a reference added elsewhere in the docstring.

If I get this right (I might not), this is the bad option for surface codes. I have not checked the tableau very carefully, but consult these two:

- I see at https://errorcorrectionzoo.org/c/surface that the code is `[[2L²-2L-1, 1, L]]`
- or at https://errorcorrectionzoo.org/c/rotated_surface is `[[L²,1,L]]` which is two times better

It is perfectly valid to implement first this code, we should have it. But we should probably comment on this and warn people that they should probably be using the rotated surface code.

2024-03-22 21:32 UTC, Krastanov commented on src/ecc/codes/surface.jl
> +parity_checks(c::Surface9) = S"
oh, I misunderstood. This is not simply an instance of the surface code you have already implemented. It makes sense to have this one, but probably under a different name and with a docstring that explains what it is. Maybe the name can be `Tomita25`

2024-03-22 21:32 UTC, Krastanov commented on test/test_ecc_decoder_all_setups.jl
> +        Surface(9,9)
Adding your `Surface9` code (or however it would be name) to all tests would make sense.

2024-03-23 01:59 UTC, royess commented on src/ecc/codes/surface.jl
> +parity_checks(c::Surface9) = S"
A different name would be better, I agree.

If we keep the convention that the number in the name is the qubit number, `Tomita9` probably would be a better name.

2024-03-23 02:40 UTC, royess commented on src/ecc/codes/surface.jl
> +"""The surface code [fowler2012surface](@cite), which is a tailored toric code with only the nearest neighboring connections in a 2D plane.
> If I get this right (I might not), this is the bad option for surface codes.

I am unsure whether the rotated surface code should be considered a better option. 

The `[[L²,1,L]]` mentioned in the link (https://errorcorrectionzoo.org/c/rotated_surface) refers to a small 9-qubit code I previously implemented as `Surface9`. I don't expect this "advantage" to remain when the number of qubits gets large. 

Basically, the rotated surface code is designed to save qubits. That probably should come with some sacrifices in error tolerance or error threshold. (Also, it brings some subtlety to the transversal H gate, if I remember correctly.)

So, for a solution, I suggest we do as follows:

- Add a mention of the rotated surface code in `Surface`'s docstring.
- Re-name Tomita's 9-qubit code (old name: `Surface9`) as `RotatedSurface9` to serve as an example of the rotated surface code.
- (We may consider leaving the rotated surface code for arbitrary size to the future PRs.)

2024-03-23 03:08 UTC, royess commented on src/ecc/codes/surface.jl
> +"""The surface code [fowler2012surface](@cite), which is a tailored toric code with only the nearest neighboring connections in a 2D plane.
For clarity, the term surface code seems ambiguous in various literature. In general, the surface code family can contain the toric code and many of its variants.

The code I implemented in this PR should be more precisely called "planar surface code." However, people usually use the simpler name "surface code." I should probably clarify this in the docstring to avoid ambiguity.

2024-03-23 03:10 UTC, royess commented on src/ecc/codes/toric.jl
> +|     |     |
That makes sense. Thanks!

2024-03-23 03:10 UTC, royess commented on test/test_ecc_decoder_all_setups.jl
> +        Surface(9,9)
That makes sense, thanks!

2024-03-26 00:51 UTC, Krastanov commented
- Let's stick to the name "Surface".
- If the 9-qubit example you have is simply an instance of the rotated surface code, let's delete it -- no need to have a single instance of a family without having the family.

2024-03-26 00:52 UTC, Krastanov commented on docs/src/references.bib
> +@article{kitaev_fault-tolerant_2003,
for consistency, I prefer if we keep all the names in "google scholar" format, e.g. `kitaev2003fault` here.

2024-03-26 00:52 UTC, Krastanov commented on src/ecc/codes/surface.jl
> +"""The surface code [fowler2012surface](@cite), which is a tailored toric code with only the nearest neighboring connections in a 2D plane.
I mostly agree. Let's keep the name `Surface` and if the 9-qubit one is just an instance of the rotated surface family, let's just delete it for now.

2024-03-26 01:17 UTC, royess commented
Thanks for your suggestions! The new commit removed the 9-qubit (rotated) Surface code and did the aforementioned formatting.

2024-03-26 01:28 UTC, royess commented on docs/src/references.bib
> +@article{kitaev_fault-tolerant_2003,
Fixed, thanks!

2024-03-27 00:00 UTC, Krastanov commented on src/ecc/codes/surface.jl
> +```julia
Could you turn this into a doctest, so that it is executed when testing? It helps keep the docs in sync with implementation (e.g. if at some point we have a reason to default to a different canonical form).

2024-03-27 00:10 UTC, Krastanov requested changes
This looks awesome! I made some minor style suggestions and a request to plug the code example docs into the test runner, but otherwise this is good to merge.

2024-03-27 00:10 UTC, Krastanov commented on src/ecc/codes/toric.jl
> +```
same comment about making it a doctest

2024-03-27 00:10 UTC, Krastanov commented on src/ecc/codes/surface.jl
> +```julia
Could you turn this into a doctest, so that it is executed when testing? It helps keep the docs in sync with implementation (e.g. if at some point we have a reason to default to a different canonical form).

2024-03-27 00:10 UTC, Krastanov commented on src/ecc/codes/toric.jl
> +Faces like (1,3,5,6) have X checks, and crosses like (1,2,5,7) have Z checks.
```suggestion
Faces like `(1,3,5,6)` have X checks, and crosses like `(1,2,5,7)` have Z checks.
```

2024-03-27 00:10 UTC, Krastanov commented on src/ecc/codes/surface.jl
> +"""The planar surface code refers to the toric code [kitaev2003fault](@cite) in a 2D lattice with open boundaries.
```suggestion
"""The planar surface code refers to the code [kitaev2003fault](@cite) in a 2D lattice with open boundaries.
```
Minor phrasing: It is not "toric" if it has open boundaries.

2024-03-27 00:10 UTC, Krastanov commented on src/ecc/codes/surface.jl
> +Illustration of a 3x2 surface code, where qubits are located on the edges:
```suggestion
Illustration of a 3×2 surface code, where qubits are located on the edges:
```

Minor typography polish, using the unicode "times" symbol instead of the letter x.

2024-03-27 00:10 UTC, Krastanov commented on src/ecc/codes/surface.jl
> +The surface code has open boundary conditions compared to the toric code. To this end, we remove qubits (denoted by "o") and parity checks on the right and bottom sides.
```suggestion
The surface code has open boundary conditions, unlike the toric code. To this end, we remove qubits (denoted by "o") and parity checks on the right and bottom sides.
```

2024-03-27 00:10 UTC, Krastanov commented on src/ecc/codes/surface.jl
> +Faces like (1,4,7) have X checks, and crosses like (1,2,7) have Z checks. Due to the removal of the bottom and right sides, we have some 3-qubit checks on the boundaries.
```suggestion
Faces like `(1,4,7)` have X checks, and crosses like `(1,2,7)` have Z checks. Due to the removal of the bottom and right sides, we have some 3-qubit checks on the boundaries.
```

2024-03-27 00:10 UTC, Krastanov commented on src/ecc/codes/toric.jl
> +It's important to note that the toric code has periodic boundary conditions, which means that the top and bottom sides are essentially glued together, as are the left and right sides.
```suggestion
It is important to note that the toric code has periodic boundary conditions, which means that the top and bottom sides are essentially glued together, as are the left and right sides.
```

Minor style change. In modern American English, no one cares about this, but I try to stick to the older "no contractions" style.

2024-03-27 01:50 UTC, royess commented on src/ecc/codes/surface.jl
> +```julia
That makes sense, thanks!

2024-03-27 13:55 UTC, merged