implementation of quantum Reed-Muller code
QuantumSavory/QuantumClifford.jl pull request #247
Opened 2024-03-23 21:27 UTC by Fe-r-oz

Prof. Stefan,

Adding the implementation of **quantum Reed-Muller(QRM)** codes. [Paper ](https://arxiv.org/pdf/quant-ph/9608026.pdf)followed is by the Steane who discovered them.

- The algorithm is built straight from the paper. The math is closely followed to construct the algorithm and meet the constrainets on` t, n+k` (total rows), etc. 
- It is found the `isCSS` function that we implemented for CSS codes is insufficient to test whether QRM codes are CSS. This is because of the Logical Y operators we have in QRM because of Dx and Dz. Please see the sample implementations in paper for better context. As you see the two implementations below, you will see that the `has_x `and `has_z` checks in `test_iscss.jl `does not fully describe QRM. 
- The algorithm is 95 - 97% complete at the moment. Just needs extra constraints, tests etc. 
- Unlike Reed Muller where we can compare the rank with bionomial coefficient formula, no such link is presented here on paper for QRM for testing. I will find something that connects with rank after reading more papers. 
- Two implementations are attached. Matrix Notation of RM (G1, G2) is different: order of rows is diferent in the papers that follow it. Also, for Dx the constraint is construct G1 and Dx is such a way that minimum Hamming distance is `2^t.` This is followed and there are many combinations to make sure this condition.
- This paper presents slighly different way of representing the classical RM matrix but later papers on RM as of 2020 follow different represention. 
- On a small note, I have changed the notation to RM (m, r) instead of RM (r, m) to follow closely with the quantum version. I thought it would be better to this tiny change to avoid any confusion later as well.
- I believe there are some ambiguities such as it is said that minimum hamming distance is `2^t + 2^(t - 1)` but this holds for  tables (14), (16) and not for (18). 
- And he goes onto explain when code size falls to zero at k = 0, suboptimal codes, codes for which "the method fails for k = 0", etc. I have asked question on it as well. 

```
julia> parity_checks(QuantumReedMuller(1, 3))
+ XXXXXXXX
+ XXXX____
+ XX__XX__
+ X_X_X_X_
+ ZZZZZZZZ
+ ZZZZ____
+ ZZ__ZZ__
+ Z_Z_Z_Z_
+ Y_Y_____
+ Y__Y____
+ _Y_____Y

julia> parity_checks(QuantumReedMuller(2, 5))
+ XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
+ XXXXXXXXXXXXXXXX________________
+ XXXXXXXX________XXXXXXXX________
+ XXXX____XXXX____XXXX____XXXX____
+ XX__XX__XX__XX__XX__XX__XX__XX__
+ X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_X_
+ XXXXXXXX________________________
+ XXXX____XXXX____________________
+ XX__XX__XX__XX__________________
+ X_X_X_X_X_X_X_X_________________
+ XXXX____________XXXX____________
+ XX__XX__________XX__XX__________
 ⋮
+ Z___Z___Z___Z___Z___Z___Z___Z___
+ YYY_Y___________________________
+ YYY__Y__________________________
+ YYY___Y_________________________
+ YYY____Y________________________
+ YYY_____Y_______________________
+ YYY______Y______________________
+ YYY_______Y_____________________
+ YYY________Y____________________
+ YYY_________Y
```___________________
+ YY_Y___________________________Y

julia> size(parity_checks(QuantumReedMuller(2,5)))
(42, 32)

2024-03-24 06:12 UTC, Fe-r-oz commented
Some ambiguities are now clear. The code size does fall to 0 at t = 4, r = 2 given the constraints he has set. He was trying to explain this in his paper.

![equation(2)](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/649e8f32-b2f1-4853-a582-061a1d832ac1)

2024-03-24 18:36 UTC, Fe-r-oz commented
Improvements:
- The algorithm is now completed.
- The bounds are added to ensure code tractibility and validity.

Focus is now towards tests.

2024-03-25 18:22 UTC, Fe-r-oz commented
Improvements:

1. The Dx Generation is improved. It now closely follows with what is expected from the paper.
2. Initial Tests are added.

Main algorithm is now less resource expensive.  (40ish lines) 

The algorithm is based on 4 points [(Page 3, Page 4)](https://arxiv.org/pdf/quant-ph/9608026.pdf). How to generate
- G1
- G2
- Dx
- Dz

I have followed these point and the math presented closely.  Kindly confirm the algorithm implementation by comparing it from the paper. 

I have some ambigities about the cases where the method fails are pointed out by Steane, when the code size falls to zero, when it is suboptimal, and what it is less optimal, or close to optimal. Does this mean that being optimal is connected with the performance of the code itself? A suboptimal code then will perform less optimally in the tests as well.

2024-03-25 19:28 UTC, Fe-r-oz commented on src/ecc/codes/quantumreedmuller.jl
> +end
This is unnecessary. I can t - 1 or t and make one function.

2024-03-26 02:15 UTC, Fe-r-oz commented
@Krastanov Please review the PR when you find convenient and when the time is right. I re-read the paper several times so that the standard algorithm and math is closely followed.  Thanks!

2024-03-26 08:49 UTC, Fe-r-oz commented
> Does this mean that being optimal is connected with the performance of the code itself? A suboptimal code then will perform less optimally in the tests as well.

So, I did a little investigation and it founds out the it's correct that sub optimal and less optimal codes don't perform well with the distance test. I took the examples from the paper and found out that: This really solves the ambiguities!

What's shown below is the Dx and Dz, taking their bitwise OR. The whole point of generating these matrices, as told by paper is to reduce the min distance. Conclusion presented at the bottom: 

```
QRM (t, r) => (2, 5) SUB OPTIMAL

00000000000000000000000011111111 
00000000000000000000111100001111
--------------------------------
                    11111111111 = 12

00000000000000000000111100001111
00000000000000000011001100110011 
---------------------------------
                  111111  111111 = 12

00000000000000000011001100110011 
00000000000000000101010101010101
--------------------------------
                 111 111 111 111 = 12
00000000000000000101010101010101
00000000000011110000000000001111
--------------------------------
            1111  1 1 1 1  1111 = 12  

00000000000011110000000000001111
00000000001100110000000000110011
--------------------------------
          111111          111111 = 12

00000000001100110000000000110011 
00000000010101010000000001010101
--------------------------------
         111111           111111  = 12
 
00000000010101010000000001010101 
00000011000000110000001100000011
--------------------------------
      11 1 1 1 1       11 1 1 11 = 12  
     
00000011000000110000001100000011 
00000101000001010000010100000101
--------------------------------
     111      111      111      111  = 12
 
min distance = 12 sub optimal


QRM (t, r) => (2, 4) OPTIMAL
0000000000001111 
0000000000110011
                 = 6
---------------------
0000000000110011 
0000000001010101
                 = 6
---------------------
0000000001010101 
0000001100000011
                 = 7
---------------------
0000001100000011 
0000010100000101
                 = 6
---------------------
0000010100000101 
0001000100010001
                 = 6
---------------------
0001000100010001 
0000000000111100 
                 = 7

min distance = 6  optimal 


QRM (t, r) => (1, 3) OPTIMAL
00000011 
00000101
--------
         = 3
00000101 
00010001
--------
         = 3
00010001
00000110
         = 4

min distance = 3 optimal
```

That's why Steane point why there are _sub optimal_ codes, and codes that perform _less optimally_. He says that  ( 2, 5) is "_close to optimal_". 

In his words. "
- The codes are **optimal** (have maximal k for given n and d) for t = 1 [12], and
-  **close to optimal** for small t and r (comparing with the table of codes in [5], it is seen that [[32, 10, 6]] is close to optimal). 
- They are **far from optimal** for large t and r, but should form a good starting point for deriving other codes. "

2024-03-26 15:36 UTC, Fe-r-oz commented
Improvements:
- References for consultation are added as 1999 is way back and the recent papers have utilized slight different conventions. 
- Allocation free and efficient implementation of Steane's 1999 standard reference is presented. 
- Tests are added for optimal codes.

Now, it's ready for review!

2024-03-27 13:24 UTC, Krastanov requested changes
There are a few minor things, but otherwise this looks good.

I will need to run a few comparisons against code examples as a final review.

2024-03-27 13:24 UTC, Krastanov commented on src/ecc/codes/quantumreedmuller.jl
> +            throw(ArgumentError("Invalid parameters: t = 1, r = 2 is not quantum code as it does not satisfy Hx.Hz' + Hz.Hx' = 0 [steane1999quantum](@cite)."))
```suggestion
            throw(ArgumentError("Invalid parameters when attempting to construct a quantum Reed-Muller code. t = 1, r = 2 is not quantum code as it does not satisfy commutativity requirements."))
```

The citation would not render in an error message so I just removed it.

2024-03-27 13:24 UTC, Krastanov commented on src/ecc/codes/quantumreedmuller.jl
> +            throw(ArgumentError("Invalid parameters: r must be positive and < 7 and t >= 0 and < 7 in order to obtain a valid code and to remain tractable."))
```suggestion
            throw(ArgumentError("Invalid parameters when attempting to construct a quantum Reed-Muller code. We need  0<r<7 and 0≤t< 7 in order to obtain a valid code and to remain tractable."))
```

2024-03-27 13:24 UTC, Krastanov commented on src/ecc/codes/quantumreedmuller.jl
> +function codesize(t, r)
This function name can be a bit confusing, because it applies only to qRM codes. If you need this helper, rename it to something like `_codesize_qrm`.

2024-03-27 13:24 UTC, Krastanov commented on src/ecc/codes/quantumreedmuller.jl
> +function nplusk(t, r)
same comment about function name

2024-03-27 13:24 UTC, Krastanov commented on CHANGELOG.md
> +## v0.9.3 - 2024-03-24
We have not actually released `v0.9.1` yet, so all of the last few ones actually need to be under the same heading.

2024-03-27 13:24 UTC, Krastanov commented on test/test_ecc_reedmuller.jl
> -@testset "Test RM(r, m) Matrix Rank" begin
You have changed the name here, but it does not seem anything has changed about the implementation. It still reads `ReedMuller(r,m)` in the rest of the code files. What is this mismatch due to?

2024-03-27 13:24 UTC, Krastanov commented on src/ecc/codes/quantumreedmuller.jl
> +"""The family of quantum Reed-Muller codes, as discovered by Steane in his 1999 paper [steane1999quantum](@cite).
This does not include a `iscss` function. Are qRM codes always non-CSS? You made a comment about that above, but I do not understand your comment.

2024-03-27 13:24 UTC, Krastanov commented on src/ecc/codes/quantumreedmuller.jl
> +    Stabilizer(fill_array, extended_Hx, extended_Hz)
You can skip the `fill_array` argument. The `Stabilizer` has a constructor that just takes two matrices:

![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/a200f726-0100-4ae7-90d7-1115e6cb38eb)

2024-03-27 13:30 UTC, Fe-r-oz commented on src/ecc/codes/quantumreedmuller.jl
> +    Stabilizer(fill_array, extended_Hx, extended_Hz)
Indeed, you are right. I noticed this, line 62 and 63 are not required!

2024-03-27 13:34 UTC, Fe-r-oz commented on src/ecc/codes/quantumreedmuller.jl
> +function nplusk(t, r)
Thanks! I named them initially based on the formulas as reminder such  n+k that gives total rows. I will give the better names

2024-03-27 13:36 UTC, Fe-r-oz commented on test/test_ecc_reedmuller.jl
> -@testset "Test RM(r, m) Matrix Rank" begin
Yes, the implementation is not changed. It's the naming convention.
It's actually R(m, r) in the implementation, but I confused the naming them as R(m,r).  In the earliest papers such as Steane, they used (t,r). Also, in the research paper, they used (m,r) which is the same as (t,r).

2024-03-27 13:43 UTC, Fe-r-oz commented on src/ecc/codes/quantumreedmuller.jl
> +"""The family of quantum Reed-Muller codes, as discovered by Steane in his 1999 paper [steane1999quantum](@cite).
QRM (1, 3) when t =1, and r =3 is actually Gottesman [[8,3,3]] code which is not CSS. 

I believe QRM codes are not CSS given the Dx and Dx matrices that we used to construct QRM codes. They might look CSS since G1 is horizontally concatentated with zeros on first row, and G1 is concatentated with zeros in the second row, but the Dx and Dz in the last row, when they are combined into logical operators, it becomes non - CSS.

But ECC Zoo calls them CSS, that's why I commented it as ambiguity. I mean if (1,3) is a Gottesman code, all t=1 are gottesman code, then how can they be named CSS?

2024-03-27 13:51 UTC, Fe-r-oz commented
> I will need to run a few comparisons against code examples as a final review.

That would be helpful. When making comparisons, please note the slight change in the matrix representation that Steane Used.

Note how this matrix is represented. from Left to Right.
1 1 1 1 0 0 0 0
1 1 0 0 1 1 0 0
1 0 1  0 1 0 1 0
1 1 1 1 1 1 1 1  

But in Steane, it's represented from Right to Left!
1 1 1 1 1 1 1 1  
0 0 0 0 1 1 1 1 
0 0 1 1 0 0 1 1 
0 1 0 1  0 1 0 1 

![Screenshot from 2024-03-27 18-46-34](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/8e75b23f-6ecd-4aab-9028-24e94f4061e9)

For example, in this 2020 Paper the RM (1,3) code is same as RM (3,1) given m = t.

2024-03-27 14:02 UTC, Krastanov commented on test/test_ecc_reedmuller.jl
> -@testset "Test RM(r, m) Matrix Rank" begin
I do not think I understand. Currently, you have pieces of code that use the notation `(m,r)` and other pieces that say `(r,m)`. This seems inconsistent:
![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/6132cdec-d449-4114-bc45-cc0828270bcf)
![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/0651413c-9a1b-4af8-aede-0d30c55ce102)

2024-03-27 14:15 UTC, Fe-r-oz commented on test/test_ecc_reedmuller.jl
> -@testset "Test RM(r, m) Matrix Rank" begin
Yes, it's (m, r) every where. I introduced the change in naming convention in this PR to match with the most widely used conventon. Widely, the notation used is (m, r) not (r, m).

I will change everywhere to (m, r)!

2024-03-27 14:44 UTC, Fe-r-oz commented on test/test_ecc_reedmuller.jl
> -@testset "Test RM(r, m) Matrix Rank" begin
Adopted (m, r) instead of (r, m) naming convention!

2024-03-27 15:19 UTC, Fe-r-oz commented
I think it's the Steane notation that's out of place with other papers.

If we agree that m = 3, and r =1 (3, 1) provides matrix shown above, We can say it any way for RM (3 ,1) , (1, 3) , r here is 1, and m =3.

But if we assume that in steane paper, where he says r = 3 and t = 1 gives the matrix that RM (3,1) (or RM (1, 3), however we want to call it) gives where r = 1, not 3!  

There was no need to change the naming convention.

2024-03-27 15:45 UTC, Fe-r-oz commented
Thanks a lot for your suggestions!

2024-03-27 15:55 UTC, Fe-r-oz commented on src/ecc/codes/quantumreedmuller.jl
> +"""The family of quantum Reed-Muller codes, as discovered by Steane in his 1999 paper [steane1999quantum](@cite).
Please have a look at sample screenshot.

When Dx and Dz are written in Stabilizer notation, the rows that have Dx and Dz contains a lt of X,Y,Z it's not pure Xs or Zs, so it's not CSS.


![Screenshot_select-area_20240327205329](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/f9731c2e-827b-423f-b494-e2ac43ad1aec)

2024-03-27 17:39 UTC, Krastanov commented on test/test_ecc_reedmuller.jl
> -@testset "Test RM(r, m) Matrix Rank" begin
From the zoo:
![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/68e1715e-559d-4563-a2cf-6960e1ccea46)

According to the first of these paragraphs, the construction of a quantum RM code should be just to lines, reusing the implementation of the classical RM. According to the second paragraph, there is some non-CSS code that can then be derived by doing extra processing. Which one are you doing?

2024-03-27 17:46 UTC, Fe-r-oz commented on test/test_ecc_reedmuller.jl
> -@testset "Test RM(r, m) Matrix Rank" begin
I am following construction from the Steane Paper:

![Screenshot from 2024-03-27 22-44-46](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/45d43f2a-11ba-4c0b-90f0-a7fe1bc75bba)

The ECC zoo is citing Steane Paper.

2024-03-27 18:05 UTC, Krastanov commented on src/ecc/codes/quantumreedmuller.jl
> +"""The family of quantum Reed-Muller codes, as discovered by Steane in his 1999 paper [steane1999quantum](@cite).
Reading Steane's paper, equation 7 gives one family of codes and then equations 8 gives another family of codes:
![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/21cb0637-2219-48c7-b3ac-e45ca33c2387)

The first one is a CSS code and the second one is not. I think you have implemented the second one?

I have the impression that the ECC Zoo wiki calls the first one "quantum Reed Muller code" and the second one "modified quantum Reed Muller code". Maybe we can keep the same nomenclature and keep both?

Maybe we can name them `CSSReedMuller` and `SteaneReedMuller` here? The `SteaneReedMuller` is what you have here.

Also, if a subfamily of these codes is the Gottesman codes, let's add a check for that. E.g.
```
for something in whatever
    @test parity_checks(SteaneReedMuller(...)) == parity_checks(Gottesman(...))
end
```

If there are differing conventions about parity check order, you can use `canonicalize` to make them the same.

2024-03-27 18:06 UTC, Krastanov commented on src/ecc/codes/quantumreedmuller.jl
> +"""The family of quantum Reed-Muller codes, as discovered by Steane in his 1999 paper [steane1999quantum](@cite).
also, be careful, some of these use the generator matrix and some use the parity check matrix -- these are related but different

2024-03-27 19:03 UTC, Fe-r-oz commented on src/ecc/codes/quantumreedmuller.jl
> +"""The family of quantum Reed-Muller codes, as discovered by Steane in his 1999 paper [steane1999quantum](@cite).
That makes sense! I have implemented `SteaneReedMuller` non-CSS codes from (8). 

Thanks for your suggestions!

2024-03-27 19:30 UTC, Fe-r-oz commented on src/ecc/codes/quantumreedmuller.jl
> +"""The family of quantum Reed-Muller codes, as discovered by Steane in his 1999 paper [steane1999quantum](@cite).
> If there are differing conventions about parity check order, you can use `canonicalize` to make them the same.

I believe first we need to convert the generator matrix G to  parity check Matrix H, right?

![Screenshot_select-area_20240328002715](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/955f163e-8737-4456-856b-a542ae9f5ce2)

As directly using canonicize might not help?

```
Julia> parity_checks(QuantumReedMuller(1,3))
+ XXXXXXXX
+ XXXX____
+ XX__XX__
+ X_X_X_X_
+ ZZZZZZZZ
+ ZZZZ____
+ ZZ__ZZ__
+ Z_Z_Z_Z_
+ YXZ_____
+ Y_X_Z___
+ XZZ_X___

julia> canonicalize!(parity_checks(Gottesman(3)))
+ XZ_Y_YXZ
+ _XZY_XZY
- _ZXYZ_YX
- __ZZYYXX
+ ZZZZZZZZ

julia> canonicalize!(parity_checks(QuantumReedMuller(1,3)))

+ X__Z__ZX
+ _X_Z_ZZY
- __X___ZY
+ ___X_ZZX
+ ___ZXZ_X
+ ___Z_X_Y
- _____ZXY
+ Z__Z_ZZ_
+ _Z_Z_Z_Z
+ __ZZ__ZZ
+ ____ZZZZ

```

Thanks!

2024-03-27 19:56 UTC, Fe-r-oz commented on src/ecc/codes/quantumreedmuller.jl
> +"""The family of quantum Reed-Muller codes, as discovered by Steane in his 1999 paper [steane1999quantum](@cite).
Please have a look:

```
julia> (stab_to_gf2(canonicalize!(parity_checks(Gottesman(3)))))
5×16 Matrix{Bool}:
 1  0  0  1  0  1  1  0  0  1  0  1  0  1  0  1
 0  1  0  1  0  1  0  1  0  0  1  1  0  0  1  1
 0  0  1  1  0  0  1  1  0  1  0  1  1  0  1  0
 0  0  0  0  1  1  1  1  0  0  1  1  1  1  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1

julia> gf2_H_to_G(stab_to_gf2(canonicalize!(parity_checks(QuantumReedMuller(1,3)))))
5×16 Matrix{Bool}:
 1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
 1  1  0  0  1  1  0  0  1  1  1  1  0  0  0  0
 0  1  0  1  1  0  1  0  1  1  0  0  1  1  0  0
 1  1  1  1  0  0  0  0  1  0  1  0  1  0  1  0
 0  1  1  0  0  1  1  0  0  1  1  0  1  0  0  1

```
This is the same matrix as shown in the Figure(13). As explained in  https://github.com/QuantumSavory/QuantumClifford.jl/pull/247#issuecomment-2022825082, it's just differeing convention of matrix representation.

```
 stab_to_gf2(parity_checks(QuantumReedMuller(1,3)))
11×16 Matrix{Bool}:
 1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
 1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0
 1  1  0  0  1  1  0  0  0  0  0  0  0  0  0  0
 1  0  1  0  1  0  1  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  1  1  1  1  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  0  0  1  1  0  0
 0  0  0  0  0  0  0  0  1  0  1  0  1  0  1  0
 1  1  0  0  0  0  0  0  1  0  1  0  0  0  0  0
 1  0  1  0  0  0  0  0  1  0  0  0  1  0  0  0
 1  0  0  0  1  0  0  0  0  1  1  0  0  0  0  0
```

2024-03-27 20:20 UTC, Krastanov commented on src/ecc/codes/quantumreedmuller.jl
> +"""The family of quantum Reed-Muller codes, as discovered by Steane in his 1999 paper [steane1999quantum](@cite).
> I believe first we need to reduce the generator matrix G of SteaneRM to parity check Matrix H of Gottesman!

The tableaux is always "the parity check matrix". Sure, some cool constructions that use conjugate codes might use the generator matrix of one code as the parity check matrix of another code. But if the paper says the two classes of codes are the same (SteaneRM with some parameter value and Gottesman with some parameter value), then only their parity check matrices are to be compared. This library as a whole does not actually provide generator matrices at all.

The SteaneRM to Gottesman comparison test is still an important correctness check. If you have some difference in convention between the two ways you have constructed those, just account for the difference in the tests.

2024-03-27 20:21 UTC, Krastanov commented
A reminder, please make one big push, not a ton of small pushes after each change. Otherwise a lot of mail spam and unnecessary (and computationally heavy) test runs are being generated each time.

2024-03-27 22:08 UTC, Fe-r-oz commented on src/ecc/codes/quantumreedmuller.jl
> +"""The family of quantum Reed-Muller codes, as discovered by Steane in his 1999 paper [steane1999quantum](@cite).
I have changed to steane_convention and now the parity check Matrix H matches exactly with the one presented in Steane's Paper!
```

julia> stab_to_gf2(parity_checks(QuantumReedMuller(1,3)))
11×16 Matrix{Bool}:
 1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  0  0  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  1  1  0  0  1  1  0  0  0  0  0  0  0  0
 0  1  0  1  0  1  0  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  1  1  0  0  1  1
 0  0  0  0  0  0  0  0  0  1  0  1  0  1  0  1
 0  0  0  0  0  0  1  1  0  0  0  0  0  1  0  1
 0  0  0  0  0  1  0  1  0  0  0  1  0  0  0  1
 0  0  0  1  0  0  0  1  0  0  0  0  0  1  1  0

```

2024-03-27 22:38 UTC, Fe-r-oz commented
> if the paper says the two classes of codes are the same, then only their parity check matrices are to be compared. then only their parity check matrices are to be compared.


I have changed to steane convention of representation, so it will output the correct Stabilizer/H for values of t,r :)

I have a question about comparison of the two parity check matrices. How do I compare the two matrices when they have different sizes? Please let me know if I missed anything.

The SteaneRM provides at  t = 1, r = 3, this parity check Matrix H. This is exactly what is shown in the paper,

```
julia> stab_to_gf2(parity_checks(QuantumReedMuller(1,3)))
11×16 Matrix{Bool}:
 1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  0  0  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  1  1  0  0  1  1  0  0  0  0  0  0  0  0
 0  1  0  1  0  1  0  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  1  1  0  0  1  1
 0  0  0  0  0  0  0  0  0  1  0  1  0  1  0  1
 0  0  0  0  0  0  1  1  0  0  0  0  0  1  0  1
 0  0  0  0  0  1  0  1  0  0  0  1  0  0  0  1
 0  0  0  1  0  0  0  1  0  0  0  0  0  1  1  0
```

But H of Gottesman 3 is as follows:

```
julia> using QuantumClifford: canonicalize!; stab_to_gf2(canonicalize!(parity_checks(Gottesman(3))))
5×16 Matrix{Bool}:
 1  0  0  1  0  1  1  0  0  1  0  1  0  1  0  1
 0  1  0  1  0  1  0  1  0  0  1  1  0  0  1  1
 0  0  1  1  0  0  1  1  0  1  0  1  1  0  1  0
 0  0  0  0  1  1  1  1  0  0  1  1  1  1  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1

julia> stab_to_gf2(parity_checks(Gottesman(3)))
5×16 Matrix{Bool}:
 1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1
 1  0  1  0  0  1  0  1  0  0  0  0  1  1  1  1
 1  0  1  0  1  0  1  0  0  0  1  1  0  0  1  1
 1  0  0  1  0  1  1  0  0  1  0  1  0  1  0  1
```

2024-03-28 07:48 UTC, Fe-r-oz commented
> A reminder, please make one big push, not a ton of small pushes after each change. 

Thanks for the reminder!!

2024-03-28 09:18 UTC, Fe-r-oz commented
Improvements:
 - `_Steane_convention_qrm `is added to match exactly with steane way of representation!
- Tests for Gottesman Family are added. `Steane convention` for Gottesman (Table 14 of the paper) is used to represent H as `canonicalize! `or s`tab_to_gf2 `was reprsent different conventon from steane's. 
-  Named changed to `SteaneReedMuller ` as this is a non-CSS code
-  The `docstring` is carefully edited as well.

In Steane's convention, 
```
julia> parity_checks(SteaneReedMuller(1,4))
+ XXXXXXXXXXXXXXXX
+ ________XXXXXXXX
+ ____XXXX____XXXX
+ __XX__XX__XX__XX
+ _X_X_X_X_X_X_X_X
+ ZZZZZZZZZZZZZZZZ
+ ________ZZZZZZZZ
+ ____ZZZZ____ZZZZ
+ __ZZ__ZZ__ZZ__ZZ
+ _Z_Z_Z_Z_Z_Z_Z_Z
+ ______ZZ_X_X_XZY
+ _____ZXY_____ZXY
+ ___Z_X_Y___Z_X_Y
+ ___Y_Z_Y_Z_X___X
```

Thanks for your comments. I learned various new cool functions that we can use in QuantumClifford!

2024-03-28 18:38 UTC, Krastanov requested changes
There are a couple of places where I do not follow what the code or tests are doing and a few places where simplifications seem to be necessary.

2024-03-28 18:38 UTC, Krastanov commented on test/test_ecc_steanereedmuller.jl
> +
I am confused by this check. Why is it so elaborate? Shouldn't it be simply:

```
for some_parameter in some_list
    @test parity_checks(SteaneReedMuller(...)) == parity_checks(Gottesman(...))
end
```

2024-03-28 18:38 UTC, Krastanov commented on test/test_ecc_steanereedmuller.jl
> +
The hardcoded matrices you compare to are a bit dangerous. How can one know they are correctly copied from wherever they are copied?

2024-03-28 18:38 UTC, Krastanov commented on test/test_ecc_steanereedmuller.jl
> +function generate_gH(t, r, Hx, Hz)
What is this for? Seems very complicated.

2024-03-28 18:38 UTC, Krastanov commented on src/ecc/codes/steanereedmuller.jl
> +function _steane_convention_qrm(mat)
What is this for? Any reason to prefer one convention over the other? Generally, I would prefer simpler code, even if it leads to a slightly different convention.

If this is for testing purposes (e.g. to compare a code of different family with different conventions), then it should live in the test file.

2024-03-28 18:38 UTC, Krastanov commented on test/test_ecc_steanereedmuller.jl
> +    for (t, r) in [(1, 3), (2, 4)]
Why are only these parameters tested?

2024-03-28 18:38 UTC, Krastanov commented on src/ecc/codes/steanereedmuller.jl
> +end
A lot of file-ending issues again. Set your editor to take care of these. See this for explanation https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2024-03-28 18:38 UTC, Krastanov commented on test/test_ecc_steanereedmuller.jl
> +
The reason I am worried about "elaborate" tests, is because if the test is not simple then you also need to worry about whether there are bugs in the test itself.

2024-03-28 18:48 UTC, Fe-r-oz commented on test/test_ecc_steanereedmuller.jl
> +    for (t, r) in [(1, 3), (2, 4)]
(1,3), and (2,4) are optimal codes. Their minimum distance is 3 and 6. And the test checks that, by checking the matrix H and by formula.

I have explained this in detail here: https://github.com/QuantumSavory/QuantumClifford.jl/pull/247#issuecomment-2019847986

Steane has explained that (2,5) is a less optimal code. I included the tests for optimal codes that these are the codes that obey the minimum distance bound which is 2^t + 2^(t-1) that is set in his paper.

Please have a look at the comment. I have thoroughly investigated and explained that.

2024-03-28 18:51 UTC, Fe-r-oz commented on src/ecc/codes/steanereedmuller.jl
> +function _steane_convention_qrm(mat)
This is the standard convention that is used by Steane in his paper. If we don't use steane convention, people would be confused.  

By using this convention, it would help to maintain the code in the long run as it would be stabilizer can be readily verifiable from the Steane paper.  Please see this comment: 

I have explained this a bit further here: https://github.com/QuantumSavory/QuantumClifford.jl/pull/247#issuecomment-2022825082

2024-03-28 18:58 UTC, Fe-r-oz commented on test/test_ecc_steanereedmuller.jl
> +
The hardcoded matrix for j = 3 are taken from Steane's paper, **Table 15** where he represents the stabilizer for Gottesman [8,3,3]] code. 

Please https://github.com/QuantumSavory/QuantumClifford.jl/pull/247#issuecomment-2024103577

The reason that this test will not work is that the size of Parity Check Matrix of Steane-Reed-Muller Code is different from the size of the Gottesman codes for the corresponding values of j. 

> @test parity_checks(SteaneReedMuller(...)) == parity_checks(Gottesman(...))

Steane explains in Table 14, 15, that the Stabilizer (1,3) of Steane-Reed-Muller Code is the Gottesman Code for j =3. But they have different sizes.
This is because Steane has appended Dx and Dz matrices, and we can extract the Gottesman code for the corresponding  j  from the Stabilizer (1,3) of Steane-Reed-Muller Code. Please have a look at the paper as well. 

I have explained why canoncilize and stab_to_gf2 would help here because the Gottesman code has a different basis as we had to do row operations to get to the convention that is represented in Gottesman thesis . In steane's paper, he has used a different convention for representing Gottesman codes. And through that convention, he laids the concept that Gottesman codes are subset of when stabilizer has t=1, r=3, 4, 5 ..

2024-03-28 19:03 UTC, Fe-r-oz commented on test/test_ecc_steanereedmuller.jl
> +function generate_gH(t, r, Hx, Hz)
Since the Stabilizer of Steane-Reed-Muller code for t=1,  r=3 has a size of 11 x 16 and the size of Gottesman code for j =3 is 5x8. They can't be compared even if we do canonicallize or stab_to_gf2. 

So, we need to extract the code from the Stabilizer of Steane-Reed-Muller code. We note that Dx and Dz are used to minimize the minimum distance from 2^t to 2^t-1 so they serve that purpose. When we focus on Hx and Hx of the Stabilizer of Steane-Reed-Muller code, we can see how we can extract the Gottesman code! This is a general extraction routine that will work for any value of r = 3, onwards given that t=1.

2024-03-28 19:06 UTC, Fe-r-oz commented on src/ecc/codes/steanereedmuller.jl
> +end
I noticed these. Sorry, the file-ending issues will be removed. I didn't commit and push as that would have caused expensive tests.

2024-03-28 19:08 UTC, Fe-r-oz commented on test/test_ecc_steanereedmuller.jl
> +
Table 15 for Gottesman [[8,3,3]] is taken from Steane Paper: https://arxiv.org/pdf/quant-ph/9608026.pdf

2024-03-28 19:10 UTC, Fe-r-oz commented on test/test_ecc_steanereedmuller.jl
> +    for (t, r) in [(1, 3), (2, 4)]
Steane points out that the method he has described will result in less optimal codes, sub optimal codes along with the optimal codes. We can distinguish between the using the minimum distance test.

 The (1,3), (2,4) pass the min distance test because they are optimal codes, as and (2,5) is close to optimal, but as we increase the value of t and r, the codes becomes sub-optimal. This is also presented in the conclusion of his paper.

2024-03-28 19:31 UTC, Krastanov commented on test/test_ecc_steanereedmuller.jl
> +    for (t, r) in [(1, 3), (2, 4)]
> Please have a look at the comment. I have thoroughly investigated and explained that.

These comments will not be there when someone is trying to understand the tests. It is important to give this context to future readers in a succinct and easy to understand fashion.

2024-03-28 19:33 UTC, Krastanov commented on src/ecc/codes/steanereedmuller.jl
> +function _steane_convention_qrm(mat)
I disagree that this makes things easier. This makes things harder to understand and review.

Correctness checks should be based on automated tests and property checking, not on manual verification with something in a paper (on the other hand verifying with the paper is a good initial check during development). After all, how do you know the paper does not have a typo.

2024-03-28 19:35 UTC, Krastanov commented on test/test_ecc_steanereedmuller.jl
> +
> Steane explains in Table 14, 15, that the Stabilizer (1,3) of Steane-Reed-Muller Code is the Gottesman Code for j =3. But they have different sizes

Then compare the appropriate subsection of the code

> I have explained why canoncilize and stab_to_gf2 would help here because the Gottesman code has a different basis as we had to do row operations to get to the convention that is represented in Gottesman thesis . In steane's paper, he has used a different convention for representing Gottesman codes. And through that convention, he laids the concept that Gottesman codes are subset of when stabilizer has t=1, r=3, 4, 5

If there is some canonicalization necessary then `canonicalize!` and potentially reordering of the columns should be enough. This currently looks much too complicated to be trusted as a test.

2024-03-28 19:37 UTC, Krastanov commented on test/test_ecc_steanereedmuller.jl
> +function generate_gH(t, r, Hx, Hz)
Why is all of this necessary if you just need to extract some subtableau from the SteaneReedMuller code? You can just write `some_tableau[1:n, :]` to extract the first `n` rows.

2024-03-28 19:41 UTC, Fe-r-oz commented on test/test_ecc_steanereedmuller.jl
> +    for (t, r) in [(1, 3), (2, 4)]
Please see this comment as well when the code size (k = 0 falls to zero) : https://github.com/QuantumSavory/QuantumClifford.jl/pull/247#issuecomment-2016707379.

2024-03-28 19:41 UTC, Krastanov commented
Generally, aim to have the code be selfcontained. As you are preparing the pull requests you are making a lot of comments and separate commits which generate a lot of emails. I generally do not read these as it is difficult to distinguish what is important and what is just an autogenerated message or an unimportant tangential topic. Have your code be selfcontained so it can be understood on its own down the line, when someone is reading it in the future without having access to a long informal conversation in github (which would be difficult to read anyway).

2024-03-28 19:45 UTC, Fe-r-oz commented
> Generally, aim to have the code be selfcontained. I generally do not read these as it is difficult to distinguish what is important and what is just an autogenerated message or an unimportant tangential topic.

Thanks for your comments. I actually included those comments as notes as I read the steane paper as there were many points that were to be noted.  And as I explored the paper more, it gathered up more notes. I believe it's better to have notes in a word document than github conversations

2024-03-28 19:59 UTC, Fe-r-oz commented on test/test_ecc_steanereedmuller.jl
> +function generate_gH(t, r, Hx, Hz)
> You can just write some_tableau[1:n, :] to extract the first n rows.

>Then compare the appropriate subsection of the code

It's not just as simple extract as it would appear. Please see the the Stabilizer for Reed-Muller-Code for (1,3) and compare with the Gottesman Stabilizer that he has presented for [[8,3,3]], we can easily see that it's not just simply extracting rows. Does it seem that simple extraction `n` rows is work? 

 We have to carefully extract them, delete the Dx and Dz matrices, and then from the Gottesman rows. using canonicalize will not work in this case.  I have tested using canonicalize to see whether it works in this context or not before making the function.

And the function correctly outputs the tableaue that the Table 15 presents.

2024-03-28 20:01 UTC, Krastanov commented
You are free to keep notes however it is most convenient for you. Just make sure that things are available to the people that will be reading your code in the future, long after you have moved to other things (e.g. 10 or 20 years from now).

2024-03-28 20:07 UTC, Fe-r-oz commented on src/ecc/codes/steanereedmuller.jl
> +function _steane_convention_qrm(mat)
I have included the minimum distance test as a correctness test. Tests only works work correct codes, not the less optimal codes, sub optimal codes or the codes for which the method fails. All of this is pointed out by steane. 

I included the steane convention just to resemble with the way of the paper. If you don't want to include the convention, it's okay. 

Not using `steane_convention_qrm ` would changes the order and result the Gottesman code extraction as Steane as shown the Gottesman Code in his Convention. Please see the table **15**. https://arxiv.org/pdf/quant-ph/9608026.pdf

 And we extract rows without using the convention would result in more complication if we canonicalize. I have tried using the canoniclize and I have presented its output  in the comment:

```
 1  0  0  1  0  1  1  0  0  1  0  1  0  1  0  1
 0  1  0  1  0  1  0  1  0  0  1  1  0  0  1  1
 0  0  1  1  0  0  1  1  0  1  0  1  1  0  1  0
 0  0  0  0  1  1  1  1  0  0  1  1  1  1  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1

julia> stab_to_gf2(parity_checks(Gottesman(3)))
5×16 Matrix{Bool}:
 1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1
 1  0  1  0  0  1  0  1  0  0  0  0  1  1  1  1
 1  0  1  0  1  0  1  0  0  0  1  1  0  0  1  1
 1  0  0  1  0  1  1  0  0  1  0  1  0  1  0  1

```
This is how how steane represents Gottesman codes. Kindly please see the comment: https://github.com/QuantumSavory/QuantumClifford.jl/pull/247#issuecomment-2024103577

2024-03-28 20:12 UTC, Fe-r-oz commented on src/ecc/codes/steanereedmuller.jl
> +function _steane_convention_qrm(mat)
Gottesman codes can be extracted carefully if they are presented in the notation Steane represents the Stabilizer for Reed-Muller Codes. 

Please see:

![Screenshot from 2024-03-29 01-10-34](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/641ab13a-1c8d-44ff-a443-a949a4e12002)

2024-03-28 20:18 UTC, Fe-r-oz commented on src/ecc/codes/steanereedmuller.jl
> +function _steane_convention_qrm(mat)
` generate_gH(t, r, Hx, Hz)` takes the value of `t,` and r, along with `Hx `and `Hz` and outputs the Gottesman Codes. There is a reason why the parameters are Hz and Hx and why we are not not passing H directly. 

Simply extracting rows of the Stabilizer Tableaue will not work. This can be seen if we see both the stabilizer of SRM code and corresponding Gottesman code.

2024-03-28 20:26 UTC, Krastanov commented
It seems the following might be one of the main source of miscommunication is the following:

This PR provides the following parity check matrix
![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/ff8350ee-5fac-4b21-b5c1-03775e3a970b)

And the paper gives this for the corresponding generator matrix
![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/f411401e-3b64-4bf0-b52b-63e3c69f2bda)

There seems to be a mismatch here. If I am reading the paper correctly, you have confused the generator matrix and the parity check matrix.

2024-03-28 20:30 UTC, Fe-r-oz commented
> If I am reading the paper correctly, you have confused the generator matrix and the parity check matrix.

Nope, I have not because if we go to the next pages, he represents them as Parity check matrices, not Generator matrices:

Please see SRM (2, 4) , SRM (2, 5)

![Screenshot from 2024-03-29 01-28-35](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/c675c8fa-5039-4765-b947-f0e93078afd9)

2024-03-28 20:34 UTC, Krastanov commented
Whatever the paper is saying, your code is definitely not doing that. Check for instance the example I picked.

- Is `SteaneReedMuller(1,3)` supposed to be a valid code? What is its parity check matrix according to the paper?
- Why does `parity_checks(SteaneReedMuller(1,3))` has more rows than columns? A valid code should have fewer rows than columns.

2024-03-28 20:36 UTC, Fe-r-oz commented
> Whatever the paper is saying, your code is definitely not doing that. Check for instance the example I picked.

The code is definitely doing that. I can prove that pretty easily.

> * Is `SteaneReedMuller(1,3)` supposed to be a valid code? What is its parity check matrix according to the paper?
In the paper, Steane says the TOTAL ROWS are N +K. So, for t=1, r=3, the total rows must be 11

> * Why does `parity_checks(SteaneReedMuller(1,3))` has more rows than columns? A valid code should have fewer rows than columns.
Please see the answer above.

2024-03-28 20:38 UTC, Fe-r-oz commented
Please see:

![Screenshot_select-area_20240329013736](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/d04a7916-750c-4d2f-af92-7124245487a1)

2024-03-28 20:39 UTC, Krastanov commented
What your are talking about is the generator matrix, not the parity check matrix.

Please answer the following:

- Can the parity check matrix of a classical or quantum error correcting code have more rows than columns?
- Is that property fulfilled by the parity check matrices you have implemented here?

2024-03-28 20:49 UTC, Fe-r-oz commented
>>Why does parity_checks(SteaneReedMuller(1,3)) has more rows than columns?  

The stabilizer for 1,3 Does not have more rows than columns. Please see, the stabilizer does not have more rows than columns. 

```
ulia> stab_to_gf2(parity_checks(SteaneReedMuller(1, 3)))
11×16 Matrix{Bool}:
 1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  0  0  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  1  1  0  0  1  1  0  0  0  0  0  0  0  0
 0  1  0  1  0  1  0  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  1  1  0  0  1  1
 0  0  0  0  0  0  0  0  0  1  0  1  0  1  0  1
 0  0  0  0  0  0  1  1  0  0  0  0  0  1  0  1
 0  0  0  0  0  1  0  1  0  0  0  1  0  0  0  1
 0  0  0  1  0  0  0  1  0  0  0  0  0  1  1  0
```

Please explain to me when he says the **'Stabilizer of the  code',** what does he mean then? He has shown the method of how to construct the stabilizer for the Steane-Reed-Muller codes and I have followed the paper. 

The "stabilizer of the codes at the given (1,3), (2,4), (2,5) have following properties. 

![Screenshot_select-area_20240329014525](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/afab7a1f-23ae-4b83-bfab-b109f159bd46)

2024-03-28 21:42 UTC, Fe-r-oz commented
Rows of the Parity check Matrix for` SteaneReedMuller `codes are not greater than its columns.

I have attached a few examples: The Gottesman (3) is also shown.
julia> stab_to_gf2(parity_checks(SteaneReedMuller(1, 3)))
```
11×16 Matrix{Bool}:  11 
 1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  0  0  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  1  1  0  0  1  1  0  0  0  0  0  0  0  0
 0  1  0  1  0  1  0  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  1  1  0  0  1  1
 0  0  0  0  0  0  0  0  0  1  0  1  0  1  0  1
 0  0  0  0  0  0  1  1  0  0  0  0  0  1  0  1
 0  0  0  0  0  1  0  1  0  0  0  1  0  0  0  1
 0  0  0  1  0  0  0  1  0  0  0  0  0  1  1  0

julia> stab_to_gf2(parity_checks(SteaneReedMuller(1, 4)))
14×32 Matrix{Bool}:        
 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  1  1  1  1  0  0  0  0  1  1  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  1  0  0  1  1  0  0  1  1  0  0  1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  1  0  1  0  1  0  1  0  1  0  1  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1  0  0  0  0  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  1  0  0  1  1  0  0  1  1  0  0  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  1  0  1  0  1  0  1  0  1  0  1  0  1
 0  0  0  0  0  0  0  0  0  1  0  1  0  1  0  1  0  0  0  0  0  0  1  1  0  0  0  0  0  0  1  1
 0  0  0  0  0  0  1  1  0  0  0  0  0  0  1  1  0  0  0  0  0  1  0  1  0  0  0  0  0  1  0  1
 0  0  0  0  0  1  0  1  0  0  0  0  0  1  0  1  0  0  0  1  0  0  0  1  0  0  0  1  0  0  0  1

```

```
julia> stab_to_gf2(parity_checks(Gottesman(3)))

5×16 Matrix{Bool}:  
 1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1
 1  0  1  0  0  1  0  1  0  0  0  0  1  1  1  1
 1  0  1  0  1  0  1  0  0  0  1  1  0  0  1  1
 1  0  0  1  0  1  1  0  0  1  0  1  0  1  0  1
```

2024-03-28 22:28 UTC, Fe-r-oz commented on src/ecc/codes/steanereedmuller.jl
> +end
I have resolved the file ending locally. When the commt and push happens, these will be resolved.

2024-03-28 22:52 UTC, Krastanov commented
> The parity check matrix for 1,3 **Does not** have more rows than columns. Please see, the parity check matrix H does not have more rows than columns.

You are making a mistake in something pretty basic here. Please review some of the resources on error correcting codes before we continue with this conversation. 

Here is again the parity check tableau that your implementation is generating:

![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/1a7fe072-88f6-4266-b88a-d9ffd56a58b0)

This has 8 columns, corresponding to 8 qubits. It has 11 rows, corresponding to 11 parity checks. If this is a code, it would have `n = 8` physical qubits and `k = 8-11 = -3` logical qubits, which obviously does not make sense.

I guess you are looking at the matrix in binary (X and Z part side by side), but then you need two columns per qubit - one for the X operations and one for the Z operations.

2024-03-28 22:54 UTC, Krastanov commented
Moreover, the rows of your parity check matrix do not commute (e.g. the two last rows). This is another sign that the code is definitely wrong. I am actually very surprised that the tests did not catch this... I thought it was being checked automatically.

2024-03-28 22:57 UTC, Fe-r-oz commented
I am very surprised. It seems that you have not reviewd the Steane paper fully. 

Everything that I said is from Steane Paper. The implementation I present is correct.

Kindly please review the paper, all the equations and the properties that he presents. It seems you have skimmed everything I said and are not wiliing to see that

```

julia> stab_to_gf2(parity_checks(SteaneReedMuller(1, 3)))
11×16 Matrix{Bool}:
 1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  0  0  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  1  1  0  0  1  1  0  0  0  0  0  0  0  0
 0  1  0  1  0  1  0  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  1  1  0  0  1  1
 0  0  0  0  0  0  0  0  0  1  0  1  0  1  0  1
 0  0  0  0  0  0  1  1  0  0  0  0  0  1  0  1
 0  0  0  0  0  1  0  1  0  0  0  1  0  0  0  1
 0  0  0  1  0  0  0  1  0  0  0  0  0  1  1  0

julia> parity_checks(SteaneReedMuller(1, 3))
+ XXXXXXXX
+ ____XXXX
+ __XX__XX
+ _X_X_X_X
+ ZZZZZZZZ
+ ____ZZZZ
+ __ZZ__ZZ
+ _Z_Z_Z_Z
+ _____ZXY
+ ___Z_X_Y
+ ___X_ZZX




```

2024-03-28 22:59 UTC, Fe-r-oz commented
> This has 8 columns, corresponding to 8 qubits. It has 11 rows, corresponding to 11 parity checks. If this is a code, it would have `n = 8` physical qubits and `k = 8-11 = -3` logical qubits, which obviously does not make sense.

I guess the miscommnication is the how the stabilizer is used in QuantumCLifford and how Steane is presenting them. I agree this will have error when we do circuit encoding because of the logic that you are using.

2024-03-28 23:01 UTC, Krastanov commented
I will have to close this for now. If you want to reopen the discussion please be explicit in explaining the following:

- Can an error correcting code have parity checks that do not commute?
- Can an error correcting code have more parity checks than number of physical qubits?
- What is the difference between a generator matrix and a parity check matrix?

2024-03-28 23:01 UTC, closed without merging

2024-03-28 23:31 UTC, Fe-r-oz commented
> Can an error correcting code have parity checks that do not commute?

Commutativity property has to be satisfied. That's the reason why SteaneReedMuller (1,2) is not a quantum code.

>Can an error correcting code have more parity checks than number of physical qubits?
No.
 
What is the difference between a generator matrix and a parity check matrix?
Remember when you said,
> The tableaux is always "the parity check matrix. Agree?

So, this should give us H or G? 
```
julia> stab_to_gf2(parity_checks(Gottesman(3)))
5×16 Matrix{Bool}:  
 1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1
 1  0  1  0  0  1  0  1  0  0  0  0  1  1  1  1
 1  0  1  0  1  0  1  0  0  0  1  1  0  0  1  1
 1  0  0  1  0  1  1  0  0  1  0  1  0  1  0  1

```

Similarly,
this gives us the parity check matrix H for SteaneMullerCode:


Do you disagree that this is not the parity check Matrix? 
```
julia> stab_to_gf2(parity_checks(SteaneReedMuller(1, 3)))
11×16 Matrix{Bool}:
 1  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  0  0  1  1  1  1  0  0  0  0  0  0  0  0
 0  0  1  1  0  0  1  1  0  0  0  0  0  0  0  0
 0  1  0  1  0  1  0  1  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  0  0  1  1  1  1
 0  0  0  0  0  0  0  0  0  0  1  1  0  0  1  1
 0  0  0  0  0  0  0  0  0  1  0  1  0  1  0  1
 0  0  0  0  0  0  1  1  0  0  0  0  0  1  0  1
 0  0  0  0  0  1  0  1  0  0  0  1  0  0  0  1
 0  0  0  1  0  0  0  1  0  0  0  0  0  1  1  0
```
You asked me what's the parity check Matrix for parity_checks(SteaneReedMuller(1, 3))). You can see it above. 

SteaneReedMuller (1,3) 

n = 8
k = 3  (Please note that k = 3 based on the formula that is given in the steane paper)
![Screenshot_select-area_20240329041746](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/76a24dd5-bf5b-4309-a269-0c372e63f1db)

d = 3
The problem is the inherent definition of the Stabilizer and how it's used in the encoding. 

I have read the Preskill notes, I know the differences. It seems that you have issue with Steane construction of the Paper. 
![Screenshot_select-area_20240329042453](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/9142896f-333b-49cb-92bb-6ff03a270136)

I have followed his approach, but according to you, I have not followed his appraoch.
> Whatever the paper is saying, your code is definitely not doing that

You already have a bias and mistrust that I am not following his paper even when I say many times that I am.

2024-03-28 23:38 UTC, Fe-r-oz commented
Also, I believe the miscommunication arose because of the differeing conventions and how Steane approach the paper. 

That could be the reason. I am not sure why this miscommunication arose

2024-03-29 00:06 UTC, Fe-r-oz commented
I am curious what should be the Stabilizer output of `SteaneReedMuller `is t =1, r = 3 or at any instance if we don't follow the Steane approach? As per your comments, SteaneReedMuller(1,3) is wrong Stabilizer that he presents it in the paper.

2024-03-29 00:32 UTC, Fe-r-oz commented
Dear Professor,

I would like to open this request. My apologies for causing inconvenience.

2024-03-29 00:34 UTC, Krastanov commented
Fe-r-oz, I do not think we should attempt to do a GSoC together, I would not be an effective mentor for you. You are extremely talented, but without you contemplating the possibility that you can be wrong about something, I would not be able to trust that you have thoroughly checked your work. Both in this PR and in the previous PR on Gottesman codes you made mistakes, I pointed out the mistakes by focusing on fundamental properties that the codes have to obey, i.e. checks that are so universal that they should be true no matter the code, and you doubled down on saying that the papers say whatever you are saying. You certainly have implemented something based on these papers, but the interpretation of what you have implemented is wrong, the bigger picture understanding is missing.

In this particular case, I have multiple times already said that you are producing generator matrices instead of producing parity check matrices. You have not shown understanding of the difference between these, which would have been fine on its own, but doubling down on your claims without checking is not fine. There is nothing wrong with Steane's approach, but the approach you are implementing simply does not produce the parity check matrix (it seems it is an intermediary step to producing the parity check matrix).

I want to make sure that you get credit for the things you have already implemented. Please let me know how can I list you as one of the contributors at https://eccbench.areweentangledyet.com/contributors/

2024-03-29 00:40 UTC, Fe-r-oz commented
Dear @Krastanov ,

Please let's continue conversation on slack.

2024-03-29 02:46 UTC, Fe-r-oz commented
Please open the PR so that we can finish it . Please note that The PR on isCSS and classical ReedMuller went very well and I also want this PR to end well. 

I believe the way Steane notation presented his paper is the biggest source of miscommunication. 

I request your to please commit your time this summer as your mentorship is much needed. I am really committed as I tried best as I opened back to back 4 PRs in one month to demonstrate my commitment. Of course, I did mistakes in two PRs,  and I am grateful for your time and commitment. 

Unfortunately, in this PR, there was miscommunication, and I am sorry for that. I hope to continue working on this PR. 

Please open this PR, I will incorporate your comments, and will focus on the universal properties when making tests. Please be rest assured . Suddenly closing the PR might not be the best route, please re-open so it can be finished. 

Please don't punish me this severely for the mistake. I will readily improve and not repeat the mistakes.

2024-03-29 02:53 UTC, Fe-r-oz commented
> (it seems it is an intermediary step to producing the parity check matrix).

That's why I asked you yesterday whether we can convert Generator Matrices to Parity Matrices in Quantum Clifford.

I believe the algorithm is creating the Stabilizer of the code, based on the Generator Matrix, and the Tables 14, 16, 18 are all Generator Matrices.  

We need to convert them to parity check matrices and then generate the correct Stabilizer?

2024-03-29 03:11 UTC, Fe-r-oz commented
My assumption was that we can construct the Stabilizer in a Generator Matrix Notation, and we can use stab_to_gf2 to get the parity check matrix. But as you pointed out that the Stabilizer Tableau is the parity check. Also, in the implementations,, since we were using extended_hx and extended hz, as in CSS, I thought that Stabilizer actually is constructed in the Generator Matrix notation, since the Stabilizer constructor takes two input (Hx, Hz).  That's was the reason why I assumed Generator Matrix is used to construct the Stabilizer, and we can get the parity check matrix via function. Since the design method was about separating the Matrices with X operators (Hx) and Z operators (Hz), I thought the stabilizer presented the generator matrix since for example XXXXXXXX => 1 1 1 1 1 1 1 1  0 0 0 0 0 0 0 0

2024-03-29 10:24 UTC, Fe-r-oz commented
Dear @Krastanov

Please see this as well 

He and Steane is calling them parity-check matrices, but you are phrasing them as Generator Matrics!?

![Screenshot from 2024-03-29 15-19-34](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/f897407a-1713-4eef-8c83-14f35c099dbc)

If we follow the above definition, Steane's is presenting parity-check matrics not the Generator Matrices!

> And the paper gives this for the corresponding generator matrix

Paper is talking about Parity check matrices, not the Generator Matrices!
![Screenshot from 2024-03-29 15-21-23](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/63e13d4c-0734-4b26-a749-35e4413531fd)

Kindly Please let me now your comments.

2024-03-29 14:25 UTC, Krastanov commented
I am locking this after a private conversation with Feroz