adding Reed-Solomon codes to the ECC Module
QuantumSavory/QuantumClifford.jl pull request #254
Opened 2024-04-04 02:36 UTC by Fe-r-oz

- Adding Reed Solomon codes to the ECC Module
- Adding the tests for the reed module

TODO: convert Generator Matrix for Reed Muller codes to Parity check Matrix 
Add proper references

2024-04-04 03:07 UTC, Fe-r-oz commented
Classical Reed-Solomon codes are standardly defined in terms of generating their generator matrix, so added a function for generator matrix and also added a generator_matrix function in the `ECC.jl`

2024-04-04 13:14 UTC, Fe-r-oz commented
For documentation, these resources for consultation :
- https://codyplanteen.com/assets/rs/gf256_prim.pdf
- https://codyplanteen.com/notes/rs
- https://core.ac.uk/download/pdf/16697418.pdf

2024-04-04 13:17 UTC, Fe-r-oz commented
More specifically, Reed-Solomon codes: RS(255, 223) is the common instance that is used in many places

2024-04-04 18:16 UTC, Krastanov requested changes
This is a pretty impressive little group theory tool implemented here. My main concern, as discussed below, is future maintainability. I suspect you be interested in looking how this can be done more simply with Nemo.jl

2024-04-04 18:16 UTC, Krastanov commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
I am wondering whether it would be better to use Nemo here? It seems you have implemented quite a few group theory operations yourself, which is pretty cool, but it makes it difficult for others to debug in the future.

Including Nemo as a dependency is pretty expensive, so it makes sense to reimplement things by hand if they are small enough. But we actually already have Nemo as a dependency for other reasons, so there will be no cost to pay by using it here as well.

Separate question: how important is the precomputation for performance? Does it make much of a difference?

2024-04-04 18:18 UTC, Krastanov commented on src/ecc/codes/classical/reedsolomon.jl
> +abstract type ClassicalCode end
I thing this is already defined elsewhere. No need to define it again.

2024-04-04 19:59 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +            v = xor(v, 285)
In GF(256), which has 256 elements, the degree of the primitive polynomial needs to be 8 since 2^8=256.

 The primitive polynomial used to define GF(256) is indeed `x^8+x^4+x^3+x^2+1`, which corresponds to the binary representation 100011101.

The value 285 (which is 100011101 in binary) is chosen because it corresponds to the coefficients of the primitive polynomial. 

When performing the conditional XOR with 285, we effectively ensure that the result stays within the bounds of GF(256).

2024-04-04 19:59 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
There are several interesting points I would like to share l that I found during the standard algorithm implementation: 

**Part 1**
Firstly, Kindly please have a look at this thesis:
 (https://dspace.sunyconnect.suny.edu/server/api/core/bitstreams/4212944c-e90d-459a-b73a-2f1b67c69ee9/content) .

In summary, this thesis states that custom type of polynomials prove efficient then using Nemo.GF in this case,  Decoding algorithms for Reed-Solomon codes can be implemented very easily. 

We need to generate the entire tables as shown in the documents: 
- https://codyplanteen.com/assets/rs/gf256_prim.pdf
- https://codyplanteen.com/notes/rs
- https://core.ac.uk/download/pdf/16697418.pdf

By tables, I mean: https://github.com/brownan/Reed-Solomon/blob/master/ff.py (Please have a look)

 With this approach, we can easily decode RS codes using the standard `Euclideandivision `and `BerlekampMassey`

Also, please check out the generator matrix function and how we generate the generator polynomial: 
  ```
   xi = polynomial_xn(UInt8, i-1, rs.m) << rs.e
        G[:, i] = (xi + xi % g).coeff
```

 Here is the extract from **9.1.5 Reed-Solomon Code**, 

_Implementing a custom suite of finite field types and operations revealed several weaknesses of the Julia programming language. The Julia language has a data type, struct, which is used to create immutable types. If a struct contains a mutable type within it, such as a vector, elements of the vector can still be
changed despite the struct and the vector within being immutable. Since Julia is not object-
oriented and has no real concept of “private” variables, it is possible to change values in a custom type
that were supposed to be constant by design. The mutability issue of Julia is compounded by the fact that arguments are passed by reference by default. This is the case in many modern programming languages, but many of those (Java, C#) have a means of preventing function arguments from being modified. In Julia, the const qualifier does not prevent the contents of mutable types from being modified, only the reference from being changed. Such a language construct is all too reminiscent of “int *const err” and similar bugbears of C
code.

Beyond mutability issues, Julia allowed finite fields to be implemented clearly and concisely, with all common operations defined. Some difficulty was encountered implementing the getindex and setindex! functions for new types, as they are not well-documented in the Julia codebase.  Once finite fields were implemented, Reed-Solomon coding was not difficult. The ReedSolomon encoder is only a few lines long. Implementing the encoder did reveal some odd behavior of the Julia language, namely that in certain scenarios assigning a range of data to a row of a matrix that had equal size to that matrix row would fail silently. This is not a documented bug of the Julia language, but did appear in several distinct locations within the FEC code.

The Reed-Solomon decoder proved much more difficult to implement, and a pure Julia
implementation was not completed in the time allotted for this project. This failure had little to do with
the Julia language itself, as Reed-Solomon decoders are very complex [59]. Additionally, the reference
implementations studied did not use finite fields as language constructs per se, instead using integral
operands with special function calls for basic operation._

**Part 2**

There are already several approaches, even in Julia, that don't rely on Nemo. GF for these reasons. For Example: 
https://github.com/JuliaImages/QRDecoders.jl/blob/master/src/syndrome.jl
[QRDecoders.jl](https://github.com/JuliaImages/QRDecoders.jl/tree/master)

We don't need to worry about the bugs as I utilized the standard Polynomial class! that is used by

https://github.com/JuliaImages/QRCoders.jl/tree/master 
https://github.com/JuliaImages/QRCoders.jl/blob/master/src/polynomial.jl

I explored using Nemo first, but I don't think apart some fundamental basic operations mentioned above, we can exploit it the way we want for standard algorithm for Reed-Muller codes.

We can do something that's more general here!  This only one instance of RS codes namely `RS(225, 223),` Instead of defining the Tables for RS(225, 223), we can define for any `RS(n, k)`, that would be pretty awesome and it's very straightforward. And since we are following a standard approach, this can be easily followed in the papers as well.

2024-04-04 20:13 UTC, Krastanov commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
### concerning tables

Precomputing these tables is usually done for one of these reasons:
- (relatively bad reason, for developer convenience) the person does not want to bother with implementing the multiplication or inversion operation, so they just prepare a big multiplication table, at the cost of extra space requirements and relatively slow lookup
- (relatively good reason) the multiplication and inversion operations are expensive so they should be cached

### concerning the comment from the thesis

This is a pretty weird and not very factual comment. They seem to be unhappy that they can not implement typical object oriented style in julia. That is true, chiefly because in julia the typical C++/Python/Java style of inheritance-base object oriented programming is not idiomatic. But that is not even the only style of object oriented programming that exists, let alone a universally "best" style of programming

### concerning external approaches

If there is some other tool that can be reused here, that would be great, whether it is Nemo or something else appropriate. The point is that what is here is reimplemented from scratch, which is certainly a fun and gratifying intellectual exercise, but it leads to more code to read through and support in the future and more places where bugs can hide. In particular, given that this is a copy/reimplementation, if the previous resource is found to have a mistake in the future, that mistake will not be automatically fixed here.

2024-04-04 20:15 UTC, Krastanov commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
also, I am unsurprised that a QR code library does not want to depend on nemo and they are reimplementing things from scratch: their priority is to be a very small library with very few dependencies. But as I mentioned, we already depend on Nemo. A Nemo implementation would probably cut the number of lines necessary for implementation by a factor of 3 to 5, which is quite valuable.

2024-04-04 20:19 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
Thanks for your comments. In the coming days, I will introspect on your comments!

2024-04-04 20:27 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
Please keep the suggestions coming, I will read them and ponder over them! 

I will take sometime to consolidate my understanding.

Also, Please have a look at the developer topics in Nemo, There is some discussion about `Euclideandivision` and its pros and cons. 

https://nemocas.github.io/Nemo.jl/v0.26/developer/topics/

2024-04-04 20:34 UTC, Krastanov commented
Is this able to generate all RS codes or is there some limitation on the size? It seems 255 is hardcodded as the largest number of physical bits possible.

If I understand correctly, an RS code is unique defined by three integers that have to obey k<n<q (encoded message size, physical message size, and the order of the group we use to generate the code). q has to also obey q = 2^p.

Here q is fixed to 256 so only a particular set of RS codes is available, right?

2024-04-04 20:38 UTC, Fe-r-oz commented
> Is this able to generate all RS codes or is there some limitation on the size? It seems 255 is hardcodded as the largest number of physical bits possible.

Nope, this is only one instance of the ReedSolomon codes namely RS(255, 233). This can be easily extended to include all RS codes though

2024-04-04 20:42 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
Also, the division operations as well apart from multiplication and inversion

2024-04-04 21:10 UTC, Krastanov commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
My guess would be that Nemo implements fast operations and making the tables is unnecessary (but I have not checked).

The link you shared is of a very old version of Nemo (0.26, while today we are at 0.43)

2024-04-05 16:15 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
I checked out the `Nemo.FiniteFields` today. I would like to share the following interesting points I found today. But before that, some details I would like to share, and then I would like to ask some questions at the end

So, before asking my questions, I will lay out some details:

**Details**
Generator Polynomial g(x) for Reed Solomon Codes is given as

`g(x) = ( x - a^j0)(x -  a^(j0 + 1) . . . (x  - x^(j0 + 2*t - 1))  `
```

Let's suppose:

n = 7, t =2
k = n - 2t = 3

For GF(8) =  GF(2^3)

word    x^i mod p(x) where p(x) is primitive polynomial is p(x) = a^3 + a + 1
001      1     
010      a
100      a^2  
011      a^3  ≅ a + 1
110      a^4  ≅ a^2 + a
111      a^5  ≅ a^2 + a + 1
101      a^6  ≅ a^2 + 1

```


suppose we let  j0 =4, 

then `g(x) = (x - a^4)(x - a^5)(x - a^6)(x - a^0)`

After expansion, we get
`g(x)  = x^4 - (a^0 + a^6 + a^5 + a^4)*x^3 + [a^6 + a^9 + (a^5 + a^5)*(a^0 + a^6)]*x^2 - [a^6*(a^5 + a^4) + a^9*(a^0 + a^6)]*x + a^15`

The generator polynomial which should be output  after simplification is:
```

g(x) = x^4 + (a^2 + 1)*x^3 + (a^2 + 1)*x^2 + (a + 1) + a
is same as 
g(x) =  x^4 + a^6*x^3 + a^6*x^2 + a^3 + a
```
The question that might arise here is how are these coefficients and the terms simplified:  This is where the precomputed tables help in the non-Julia languages

**What we can do in Julia**

Firstly, we don't need to compute the table, everything can be done on fly as we can get the values as follows: 
```
julia> K, a = finite_field(2,3, "a")
(Finite field of degree 3 and characteristic 2, a)

julia> a^0
1

julia> a^1
a

julia> a^2
a^2

julia> a^3
a + 1

julia> a^4
a^2 + a

julia> a^5
a^2 + a + 1

julia> a^6
a^2 + 1
```

Now, we need to form generator polynomial g(x) for RS Codes:
`g(x) = ( x - a^j0)(x -  a^(j0 + 1) . . . (x  - x^(j0 + 2*t - 1))  `

for j0 =4 ,
we get   `g(x) = (x - a^4)(x - a^5)(x - a^6)(x - a^0)`

After expansion, we get
`g(x)  = x^4 - (a^0 + a^6 + a^5 + a^4)*x^3 + [a^6 + a^9 + (a^5 + a^5)*(a^0 + a^6)]*x^2 - [a^6*(a^5 + a^4) + a^9*(a^0 + a^6)]*x + a^15`

In Julia, using Finite Fields, we can easily **simplify the coefficients** of x^3, x^2 and also **a terms** like a^15 as follows.
```
coefficient of x can be simplified as:
julia> [a^6*(a^5 + a^4) + a^9*(a^0 + a^6)]
1-element Vector{FqFieldElem}:
 a + 1

coefficient of x^2 can be simplified as:
julia> [a^6 + a^9 + (a^5 + a^4)*(a^0 + a^6)]
1-element Vector{FqFieldElem}:
 a^2 + 1

coefficient of x^3 can be simplified as:
julia> a^0 + a^6 + a^5 + a^4
a^2 + 1

a^15 can be simplified as 
julia> a^15
a
```

Now, my questions are that given j0, we need to expand this

`g(x) = ( x - a^j0)(x -  a^(j0 + 1) . . . (x  - a^(j0 + 2*t - 1))  `

After expansion, we have:

`g(x)  = x^4 - (a^0 + a^6 + a^5 + a^4)*x^3 + [a^6 + a^9 + (a^5 + a^5)*(a^0 + a^6)]*x^2 - [a^6*(a^5 + a^4) + a^9*(a^0 + a^6)]*x + a^15`

and then we have to compute the coefficients of x along with the terms which don't have x since they can be simplified as shown above

**Questions**
Please provide pointers as to 1) how we can declare a such x , 2) how we can expand the polynomail, then 3) simply each coefficient of x (which we can do in julia with help of finitefields) and  terms of `a` (like `a^15 = a` after looking at the table) to get the resulting equation

`g(x) = x^4 + (a^2 + 1)*x^3 + (a^2 + 1)*x^2 + (a + 1) + a`

is same as 

`g(x) =  x^4 + a^6*x^3 + a^6*x^2 + a^3 + a`

2024-04-05 21:14 UTC, Krastanov commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
Not sure but it seems that

1. Is already in the example I gave earlier. To make the polynomial ring you can just use `P, x = gf2⁸[:x]`
2. the polynomial is probably always expanded in this representation, if not there would be something about how to do it in the Nemo documentation, or we can ask the Nemo developers on discourse/slack
3. the field terms are always automatically simplified

2024-04-05 21:35 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
In order to explore these 3 questions I mentioned above, I checked out` Polynomial.jl` to explore whether it can be used to form g(x) and correctly expand it.  The thing to keep is mind is that `a`term are `Finite Fields elements`. 

Only defining `g(x) i`n terms of `Polynomials` that can be correctly multiplied and expanded meaning

this
`g(x) = (x - a^4)(x - a^5)(x - a^6)(x - a^0)`

into this can only happen via Polynomials multiplication and expansion
`g(x)  = x^4 - (a^0 + a^6 + a^5 + a^4)*x^3 + [a^6 + a^9 + (a^5 + a^5)*(a^0 + a^6)]*x^2 - [a^6*(a^5 + a^4) + a^9*(a^0 + a^6)]*x + a^15
`
But, `a` is a FiniteField element, not a Polynomial. 

```
using Polynomials 
 Polynomial([0,1]) - a^4
ERROR: MethodError: no method matching -(::Polynomial{Int64, :x}, ::FqFieldElem)

we can't do x - a^4...
```

At the end, we need the correct expansion of `g(x) ,` that corresponds to the correct coefficients (these coefficient are actually of `FiniteFieldElementType`) so they can be simpified to get the `g(x).` The coefficients are actually the sums (or single) of `a` terms which are finitefield elements, only `finitefieldelements` can be simplified because of their structures.

But it seems that neither `Polynomials.jl `or symbolic `x `using `SymPy `would help since symbolic variables won't result in correction expansion, they way polynomials expands

```
julia> x = Sym("x")
x

julia> x*x
 2
x 


julia> Polynomial([0,1])*x
Polynomial(x*x)  , we want x^2, Sympy not helpful here

julia> Polynomial([0,1])*x*x
Polynomial(x^2*x),  we want x^3 , Sympy not helpful here

julia> P, x = K[:x]
(Univariate polynomial ring in x over GF(2, 3), x)

julia> Polynomial([0,1]) - x
ERROR: MethodError: no method matching -(::Polynomial{Int64, :x}, ::FqPolyRingElem)

```

We might be reaching the extent of this exploration?
I  have found a connection of generating `g(x)` without tables in principle but it might not be feasible given that a's are `finitefield` elements (coefficients of x)which are simplified only after they are in their correct expanded form.  `x` is not a `finitefield `element, but `x` is a polynomial, and `g(x) `is also a polynomial.

2024-04-05 21:39 UTC, Krastanov commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
Polynomials.jl is an unrelated library for polinomials over floating point numbers. I doubt it wouldbe of use for work with finite fields.

Nemo.jl has its own polynomial datastructures, specifically designed for work with algebraically more complicated objects.

These two libraries have very different goals.

2024-04-05 21:40 UTC, Krastanov commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
Same with SymPy.jl and Polynomials.jl: these two libraries have very different goals, are not meant to mix, and SymPy has its own polynomial object.

Really, all you need here is Nemo, no need for these other unrelated tools.

2024-04-05 21:41 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
> the field terms are always automatically simplified

The field terms can only be simplified only after they are expanded. Otherwise, we don't even know what the sums of fields terms are.

That depends on the value of j0, k, etc. Since, we get a distinct` g(x) = (x - a^4)(x - a^5)(x - a^6)(x - a^0)`.

This is just one example where j0 is 4 and the expansion looks like this:

`g(x)  = x^4 - (a^0 + a^6 + a^5 + a^4)*x^3 + [a^6 + a^9 + (a^5 + a^5)*(a^0 + a^6)]*x^2 - [a^6*(a^5 + a^4) + a^9*(a^0 + a^6)]*x + a^15 `

We actually need to expand g(x), and only after that we can simplify (which Nemo.FiniteFields can handle), not before we have g(x) in the expanded form.

2024-04-05 21:48 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
> the polynomial is probably always expanded in this representation, if not there would be something about how to do it in the Nemo documentation, or we can ask the Nemo developers on discourse/slack

Before reaching expansion, we have to actually form the polynomial generator g(x). The since a terms are finite field elements, and x is a polynomial terms, we have to write them like

`g(x) = ( x - a^j0)(x -  a^(j0 + 1) . . . (x  - x^(j0 + 2*t - 1)) `

 I tried Polynomial Ring as well, (same error shown above).

Maybe, the polynomial terms are automatically expanded, but we have to first form g(x) polynomial. We have to ask Nemo Developers about this. We can check the Nemo documentation as well.

2024-04-05 21:53 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
> We might be reaching the extent of this exploration?

There is no need to ask Nemo Developers. 

Polynomial Ring `x `and `a`  FiniteFieldsElements seem to work with addition. Not substraction.

```
addition work
julia> x + a^2 + a + 1
x + a^2 + a + 1

addition work
julia> x^2 + a^2 + a + 1
x^2 + a^2 + a + 1

julia> x^2 - a
x^2 + a  (why it comes out be plus)
```

2024-04-05 22:01 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
It somewhat works. But there is a catch. The `g(x)` is not the same as output shown in the textbooks.
In standard textbook, they calculate and simplyfy each coeficient to get these coefficients. 
But the one that Julia provides has different coefficients.

Standard Output: `g(x) =  x^4 + a^6*x^3 + a^6*x^2 + a^3 + a`

```
julia> x^4 - (a^0 + a^6 + a^5 + a^4)*x^3 + (a^6 + a^9 + (a^5 + a^5)*(a^0 + a^6))*x^2 - (a^6*(a^5 + a^4) + a^9*(a^0 + a^6))*x + a^15
x^4 + (a^2 + 1)*x^3 + x^2 + (a + 1)*x + a
```

for j0 =4
```
g(x)  =  x^4 + a^6*x^3 + a^6*x^2 + a^3 + a` (standard textbook)
g(x) = x^4 + (a^2 + 1)*x^3 + (a^2 + 1)*x^2 + (a + 1) + a `(standard textbook)
```

does not match with even though same expanded equation is used to check

`g(x) = x^4 + (a^2 + 1)*x^3 + x^2 + (a + 1)*x + a (Julia)`

2024-04-05 22:11 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
> 2a=0 for this field, so +a is the same as -a

Oh, Yeah! My bad. That's pretty basic point.

2024-04-05 22:18 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
> does not match with even though same expanded equation is used to check

Debugging the mismatch in the polynomial generators g(x) between the standard textbooks/solutions and what nemo providing:

There is mismatch is simplification of coefficients between GF and Polynomial Ring
```
julia> x^4 - (a^0 + a^6 + a^5 + a^4)*x^3 + (a^6 + a^9 + (a^5 + a^5)*(a^0 + a^6))*x^2 - (a^6*(a^5 + a^4) + a^9*(a^0 + a^6))*x + a^15
x^4 + (a^2 + 1)*x^3 + x^2 + (a + 1)*x + a

x^3 coeff not okay
julia> (a^0 + a^6 + a^5 + a^4)  , GF Simplification 
a^2 + 1 not okat
 
julia> (a^0 + a^6 + a^5 + a^4)*x^3 Polynomial Ring Simplification 
(a^2 + 1)*x^3 not okay

x^2 coeff okay
julia> (a^6 + a^9 + (a^5 + a^5)*(a^0 + a^6)) GF Simplification 
1; okay

julia> (a^6 + a^9 + (a^5 + a^5)*(a^0 + a^6))*x^2 Polynomial Ring Simplification 
x^2; okay

x^1 coeff okay
julia> (a^6*(a^5 + a^4) + a^9*(a^0 + a^6)) GF Simplification 
a + 1 ; okay

julia> (a^6*(a^5 + a^4) + a^9*(a^0 + a^6))*x Polynomial Ring Simplification 
(a + 1)*x;  okay

```

2024-04-05 22:41 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
Thanks for your comments. There was a lag in the comments maybe because this trail is too long as I see messages sometime later after they are uploaded. Anyhow, I read all of them now.

2024-04-05 23:55 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +const GF256 = let
There is no mismatch. I checked it now. It's working :)

2024-04-06 01:25 UTC, Fe-r-oz commented on src/ecc/ECC.jl
> +export parity_checks, parity_checks_x, parity_checks_z, iscss, generator_matrix,
When I do final commit, I will do this.

2024-04-06 01:29 UTC, Fe-r-oz commented
I would like to refer a youtube lecture for consultation, That really helped me in understanding math and concept of ReedSolomon codes for consulation when adding papers. Is it okay to add it in the docstring along with papers ?

Link: https://youtu.be/K26Ssr8H3ec?si=DOai-gnjveQMaq-p (Pedagogical lecture)

2024-04-06 01:31 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +end
I will make sure to leave one line after25 here. File ending needs to be helped properly.

2024-04-06 09:40 UTC, Fe-r-oz commented
Improvements:
- I have added three helper functions that people can use to play with RS codes. We are only concerned with generator polynomial, but for pedagogical purposes, one can create a custom message polynomial , and then corresponding parity check polynomial and codeword polynomials.
- Added all known examples in literature for Reed Solmon codes for testing purposes.
- using only Nemo for generation of Reed-Solomon codes

2024-04-06 14:01 UTC, Fe-r-oz commented
Sorry for four pushes instead of one.

2024-04-07 08:18 UTC, Fe-r-oz commented
Improvements:

1. Adding classical BCH codes as well. These codes are fully implemented in Nemo as well.
2. Tested the universal property of BCH codes as well!
3. Tested locally as well.

2024-04-07 19:57 UTC, Krastanov commented
It is impressive that the BCHs are also added now!

Just a quick advice on structuring PRs like this to make it easier to review. Here for instances, BCH is something sufficiently separate from the original contribution. It is a good idea to split such things into two PRs that can depend on each other, something like:

```
> git checkout -b first_contribution # create a branch for the initial work
> ... do all the implementation work and local testing
> git add .
> git commit -m "implementing first contribution"
> git push # make a pull request
> git branch -b second_contribution # create a branch on top of your current contribution
> ... do all the implementation work and local testing for the second contribution
> git add .
> git commit -m "implementing second contribution that depends on first contribution"
> git push # make a second pull request that depends on the first pull request being merged
```

This makes reviewing drastically easier as the reviewer needs to keep only one thing in their head.  But the contributor needs to be careful to make sure that modifications they make to the first PR get carried over (they need to rebase the second one on top of the first one occasionally).

No need to make any such changes here. Just a note for future reference.

2024-04-07 20:16 UTC, Fe-r-oz commented
> No need to make any such changes here. Just a note for future reference.

Dear Professor, Thank you for this advice and new information! I will keep this in mind for future reference.

2024-04-10 08:54 UTC, Fe-r-oz commented
Dear Prof, I request your attention to review this one, so that I can fully focus on more abstract convolutional.

Also, if you don't mind, I want give these slides a mention in the docstring: they are so nice:  https://web.ntpu.edu.tw/~yshan/BCH_code.pdf

2024-04-10 10:59 UTC, Krastanov commented
I will probably try to review the previous PR first, which wont happen until maybe the weekend.

2024-04-10 12:14 UTC, Fe-r-oz commented
Since this PR is fully implemented in Nemo with universal code properties proven,  it would be have been easy to review this PR first since convolutional is also based on Nemo.  

Convolutional is extending the concepts used here, so I wanted to discuss one approach with you.

I will revisit Steane-Reed-Muller as well for verification and correctness with paper as well.

2024-04-10 12:33 UTC, Fe-r-oz commented
My apologies, since you are very occupied, I don't think I have the opportunity to discuss to seek some guidance the about Direct sums in convolutional case at this time. I will try to work on my end to polish convolutional PR as well!

2024-04-14 10:03 UTC, Fe-r-oz commented
Set proper bounds for BCH codes instead of arbitraty max 500 limit.

Some outputs
n: block length
t: t bit error that can be corrected, t is error correction capability
```

julia> generator_polynomial(BCH(15,2))
x^8 + x^7 + x^6 + x^4 + 1

julia> generator_polynomial(BCH(15,3))
x^10 + x^8 + x^5 + x^4 + x^2 + x + 1

julia> generator_polynomial(BCH(15,1))
x^4 + x + 1

julia> generator_polynomial(BCH(7,1))
x^3 + x + 1

julia> generator_polynomial(BCH(7,2))
x^6 + x^5 + x^4 + x^3 + x^2 + x + 1

julia> generator_polynomial(BCH(7,3))
x^6 + x^5 + x^4 + x^3 + x^2 + x + 1

julia> generator_polynomial(BCH(7,4))
x^7 + 1
```

2024-04-14 10:07 UTC, Fe-r-oz commented
BCH

- Lowest value of n is 7 since lowest degree of finite field is r = 3. n is defined here as 2^r - 1.  Also, t must not be > 2^(r - 1) as well.

2024-04-14 10:27 UTC, Fe-r-oz commented
The double and triple BCH codes when t =2, and t =3 respectively for n = 15 can be verified from the outputs as well.
Their derivation is on Page4 and Page 5 of the slides here:  https://web.ntpu.edu.tw/~yshan/BCH_code.pdf

> julia> generator_polynomial(BCH(15,2))
> x^8 + x^7 + x^6 + x^4 + 1

> julia> generator_polynomial(BCH(15,3))
> x^10 + x^8 + x^5 + x^4 + x^2 + x + 1 

BTW, Stefan, Happy World Quantum Day!

2024-04-16 08:57 UTC, Fe-r-oz commented
Dear @Krastanov I am looking forward to your comments and review!

2024-04-18 16:06 UTC, Krastanov reviewed
This looks pretty neat. I have not checked these in significant detail yet, but something seems to be missing: how is one supposed to actually get a parity_check matrix here?

2024-04-18 16:06 UTC, Krastanov commented on src/ecc/ECC.jl
> +function generator_polynomial end
could you add a docstring explaining what this is

2024-04-18 16:06 UTC, Krastanov commented on src/ecc/codes/classical/bch.jl
> +            new(n, t)
```suggestion
        new(n, t)
```

2024-04-18 16:06 UTC, Krastanov commented on src/ecc/codes/classical/bch.jl
> +        end
```suggestion
        end
```

2024-04-18 16:06 UTC, Krastanov commented on src/ecc/codes/classical/reedsolomon.jl
> +            new(n, k)
```suggestion
        end
        new(n, k)
```

2024-04-18 16:25 UTC, Fe-r-oz commented
> something seems to be missing: how is one supposed to actually get a parity_check matrix here?

Reed Solomon Case
We can check the parity check polynomial. I have created two functions, namely` function _codeword_polynomial_rs(message, ck) `and` function _parity_check_polynomial_rs(n, k, x, message, gx)` that takes the generator polynomial and then using the equations given in the Giesel paper, find out the corresponding parity check polynomial.

BCH case
This generates the generator polynomial, and then is method to get to parity check matrix. Kindly please see the https://web.ntpu.edu.tw/~yshan/BCH_code.pdf (Pages 14 to 16). Please let me know your insights.

Actually, I ask the same question myself when writing the codes and asked the Nemo developers this question as well. From their response, it seemed there is no clear cut way to go from rings to matrices as per their description. I will forward their exact response.

2024-04-18 16:30 UTC, Krastanov commented
> BCH case This generates the generator polynomial, and then is method to get to parity check matrix. Kindly please see the https://web.ntpu.edu.tw/~yshan/BCH_code.pdf (Pages 14 to 16). Please let me know your insights.

I do not really have much insight here, I have not worked with these codes before. That resource seems to list explicitly how to construct the parity_check matrix, so that is good. This library just needs the parity check matrix -- for now it is not trying to provide much more.

2024-04-18 16:57 UTC, Krastanov commented
Page 14 talks about some alphas that define the code. Do you have them?

Page 17 talks about taking powers of alpha and then expressing them as binary column vectors. Can you do that?

It seems as long as these terms are defined, the operation is pretty easy, but I do not know what these terms are.

I will mark this as a draft for now, until the parity check matrices are figured out.

2024-04-18 17:07 UTC, Fe-r-oz commented
When I was working on these codes,  I asked the Nemo Developers this question:

>It's nice that we can generate generator polynomials via these methods in nemo toolkit when working with FiniteFieldsIt would be great to have some guidance about how to utilize these g(x) in the matrix form.

>Is there any way to represent these generator polynomials in the matrix form.  If I have them (gx) in matrix for, I can convert them to parity check matrices


In summary, I am not sure whether there is a method in Nemo or AA to actually write generator polynomial as full matrix form with coefficients being of the type FiniteField and Polynomials rings. 

To get around this, we can do operations on the g(x), and then get to parity check polynomial that that is still in the datatypes of Fields and Rings, not a binary parity check matrix.

This workaround is used in the paper: https://ntrs.nasa.gov/api/citations/19900019023/downloads/19900019023.pdf section 3.3.2 . Here, the author construct the message polynomial, and then the parity check polynomial for Reed Solomon Codes. For this reason, the two helper functions are described.

So, in the Reed-Solomon case, we can define the parity check polynomial. But I am not sure how to convert the polynomial representation into the corresponding matrix representation since in the doc of Nemo, there is no method for this.

Your Question
> Page 14 talks about some alphas that define the code. Do you have them?
The alphas are the roots of the generator polynomial. In the Reed Solomon case, the alphas are represented by a

For example:

```
g(x)  =  x^4 + a^6*x^3 + a^6*x^2 + a^3 + a` 
g(x) = x^4 + (a^2 + 1)*x^3 + (a^2 + 1)*x^2 + (a + 1) + a `
```

Your Question
>Page 17 talks about taking powers of alpha and then expressing them as binary column vectors. Can you do that?

My guess is that we can perform operations on g(x) of BCH to get the roots/zeros of the generator polynomial and multiply it with the message to get the parity check polynomial. But since the datatypes of alpha will be finite field and rings, of that form, my guess is that we can take the powers of the zeros of the polynomial.

I will investigate it further.

2024-04-18 17:11 UTC, Krastanov commented
> > Page 17 talks about taking powers of alpha and then expressing them as binary column vectors. Can you do that?
> 
> My guess is that we can perform operations on g(x) of BCH to get the roots/zeros of the generator polynomial and multiply it with the message to get the parity check polynomial. But since the datatypes of alpha will be finite field and rings, of that form, my guess is that we can take the powers of the zeros of the polynomial.
> 
> I will investigate it further.

I have the impression it is much simpler than this. If you already have alpha and you can already compute powers of alpha, it seems the only thing left is to figure out what the following means:

![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/7faf25c1-4772-42dd-99be-14453fa2100f)

2024-04-18 17:28 UTC, Fe-r-oz commented
>If you already have alpha and you can already compute powers of alpha, it seems the only thing left is to figure out what the following means:

Sounds interesting, but doesn't this assumes that we have constructed H as a matrix not as a polynomial, right? And that H matrix has zeros of the generator polynomial g(x) as elements which are of the types FiniteField Element/Polynomial Ring Element. 
![Screenshot from 2024-04-18 22-15-18](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/245fcd36-585a-4ad5-8093-bb1fa5de027e)


So, here we see this H matrix, but the elements of the matrix are of the type  FiniteField Element/Polynomial Ring Element since we are working with polynomial rings/finite fields. 

In Nemo/AA, since we can't represent the generator polynomial in a matrix form, so my question is that the above suggested method assumes we have the H in this matrix form after which we can perform the suggested operation, right?

In the Reed-Solomon case, we have alphas/zeros but Giesel handled the g(x) which is generator polynomial in polynomial notation, so after doing some operations such as taking mod of the polynomial which we can do in Nemo, we arrived at the parity check matrix. 

Here, we are trying to represent/get the H in a matrix representation, but I believe, with Nemo, we can play with generator polynomials in polynomial representation. 

Kindly please see Giesel https://ntrs.nasa.gov/api/citations/19900019023/downloads/19900019023.pdf section 3.3.2 and please let me know your thoughts. Thank you.

I will ponder about this as well. Thanks for your comments!

2024-04-18 18:01 UTC, Krastanov commented
> Sounds interesting, but doesn't this assumes that we have constructed H as a matrix not as a polynomial, right?

Not really. You can put whatever you wish in a two-axis array an call it a matrix. Sure, it will not have some fancy features that come from Nemo, but we do not want fancy features that come from Nemo, we just want a two-axis array of booleans.

Again, the one important thing to figure out is what does it mean to represent these alphas as binary vectors.

At the end, a parity check matrix for a classical code is a matrix of zeros and ones, not of fancier objects (although those fancier objects might be necessary to derive the matrix).

I skimmed through the Giesel reference, but I do not really know the topics they are discussing.

2024-04-18 18:44 UTC, Fe-r-oz commented
I agree. We have to leave the fancy stuff behind and come back to 1s and 0s!

2024-04-18 21:52 UTC, Fe-r-oz commented
>Again, the one important thing to figure out is what does it mean to represent these alphas as binary vectors.

I figured it out! Actually, It's pretty simple. I am not sure that method is actually present in Nemo/AA  to convert polynomial notation into tuple notation, so I will ask demo devs and then we can easily do the following

> ![image](https://private-user-images.githubusercontent.com/705248/323698180-7faf25c1-4772-42dd-99be-14453fa2100f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NzcxODMsIm5iZiI6MTcxMzQ3Njg4MywicGF0aCI6Ii83MDUyNDgvMzIzNjk4MTgwLTdmYWYyNWMxLTQ3NzItNDJkZC05OWJlLTE0NDUzZmEyMTAwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQyMTQ4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWYwMGVkOTYzNGIxY2U2YTg5YzgzMTU5NWRiYzY3ZGRlZjE2ZDg1YzA3ODVmOTZlOWM3Zjc0ZGE0YjhmODMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sAVd70KWklfj7LdnaCbZT0EpToXwu4UjSvFNcHcHCAk)

2024-04-19 11:14 UTC, Fe-r-oz commented
> Page 14 talks about some alphas that define the code. Do you have them?

Yes, it's done now. 
```
> parity_checks(BCH(15,2))
FqFieldElem[1 a a^2 a^3 a + 1 a^2 + a a^3 + a^2 a^3 + a + 1 a^2 + 1 a^3 + a a^2 + a + 1 a^3 + a^2 + a a^3 + a^2 + a + 1 a^3 + a^2 + 1 a^3 + 1; 
1 a a^2 a^3 a + 1 a^2 + a a^3 + a^2 a^3 + a + 1 a^2 + 1 a^3 + a a^2 + a + 1 a^3 + a^2 + a a^3 + a^2 + a + 1 a^3 + a^2 + 1 a^3 + 1]
```

> Page 17 talks about taking powers of alpha and then expressing them as binary column vectors. Can you do that?

Yes, for the corresponding Field Element, we can extract their coefficient vector as Bool as at the end of the day, we want a Boolean Matrix. 

What is shown below are m-tuples in column form corresponding to each Field Element from the fancy H matrix!
```
Bool[1 0 0 0]
Bool[0 1 0 0]
Bool[0 0 1 0]
Bool[0 0 0 1]
Bool[1 1 0 0]
Bool[0 1 1 0]
Bool[0 0 1 1]
Bool[1 1 0 1]
Bool[1 0 1 0]
Bool[0 1 0 1]
Bool[1 1 1 0]
Bool[0 1 1 1]
Bool[1 1 1 1]
Bool[1 0 1 1]
Bool[1 0 0 1]
Bool[1 0 0 0]
Bool[0 1 0 0]
Bool[0 0 1 0]
Bool[0 0 0 1]
Bool[1 1 0 0]
Bool[0 1 1 0]
Bool[0 0 1 1]
Bool[1 1 0 1]
Bool[1 0 1 0]
Bool[0 1 0 1]
Bool[1 1 1 0]
Bool[0 1 1 1]
Bool[1 1 1 1]
Bool[1 0 1 1]
Bool[1 0 0 1]
```

2024-04-19 11:48 UTC, Fe-r-oz commented
The parity check matrix of BCH code is now completed!

```
julia> parity_checks(BCH(15,2))
8×15 Matrix{Bool}:
 1  0  0  0  1  0  0  1  1  0  1  0  1  1  1
 0  1  0  0  1  1  0  1  0  1  1  1  1  0  0
 0  0  1  0  0  1  1  0  1  0  1  1  1  1  0
 0  0  0  1  0  0  1  1  0  1  0  1  1  1  1
 1  0  0  0  1  1  0  0  0  1  1  0  0  0  1
 0  0  0  1  1  0  0  0  1  1  0  0  0  1  1
 0  0  1  0  1  0  0  1  0  1  0  0  1  0  1
 0  1  1  1  1  0  1  1  1  1  0  1  1  1  1
```

2024-04-19 12:07 UTC, Fe-r-oz commented on src/ecc/ECC.jl
> +function generator_polynomial end
Does this sound good?

```
"""
# Generator Polynomial of BCH Codes

This function calculates the generator polynomial `g(x)` of a t-error-correcting BCH code of length `2m - 1` over the finite field GF(2).

Input Arguments:
- `m` (Integer): The positive integer defining the code length (`2m - 1`).
- `t` (Integer): The positive integer specifying the number of correctable errors (`t`).

Description:

The generator polynomial `g(x)` is the fundamental polynomial used for encoding and decoding BCH codes. It has the following properties:

1. Roots: It has `α`, `α^2`, `α^3`, ..., `α^(2t)` as its roots, where `α` is a primitive element of the Galois Field GF(2^m).
2. Error Correction: A BCH code with generator polynomial `g(x)` can correct up to `t` errors in a codeword of length `2m - 1`.
3. Minimal Polynomials: `g(x)` is the least common multiple (LCM) of the minimal polynomials `φ_i(x)` of `α^i` for `i = 1` to `2t`.

Minimal Polynomial:

- The minimal polynomial of a field element `α` in GF(2^m) is the polynomial of the lowest degree over GF(2) that has `α` as a root. It represents the simplest polynomial relationship between `α` and the elements of GF(2).

Least Common Multiple (LCM):

- The LCM of two or more polynomials `f_i(x)` is the polynomial with the lowest degree that is a multiple of all `f_i(x)`. It ensures that `g(x)` has all the roots of `φ_i(x)` for `i = 1` to `2t`.
```
```

2024-04-19 12:15 UTC, Krastanov commented
That looks pretty exciting. I will read through the implementation when it exits draft status. I suspect I will have some requests for inline documentation/comments to make sure future readers know what is happening.

2024-04-19 13:20 UTC, Krastanov commented on src/ecc/ECC.jl
> +function generator_polynomial end
That probably means the doc string should be more general and explain what the generator polynomial is in general, not specifically for BCH. Then each method can have its own docstring with more specific details for the specific code.

In other words, this here reads more like a docstring for one specific method, not for the initial `function generator_polynomial end` function declaration.

2024-04-19 13:30 UTC, Fe-r-oz commented on src/ecc/ECC.jl
> +function generator_polynomial end
Please checkout the general definition of generator polynomial:

```
"""
Generator Polynomial:

In a polynomial code, the generator polynomial `g(x)` is a polynomial of the minimal degree over a finite field F. The set of valid codewords in the code consists of all polynomials that are divisible by `g(x)` without remainder.

Description

- Defines the valid codewords in a polynomial code.
- Has minimal degree among polynomials with this property.
- Coefficients belong to a finite field (e.g., GF(2) for binary codes).
"""
```

2024-04-19 14:16 UTC, Fe-r-oz commented
> That looks pretty exciting. I will read through the implementation when it exits draft status. I suspect I will have some requests for inline documentation/comments to make sure future readers know what is happening.

Thanks. I am excited as well. 

I would like to thank these slides( people from Iraq!), they also had a working example for BCH(15, 2) so the following parity check matrix H was given as working example: 

Slides: https://uotechnology.edu.iq/dep-eee/lectures/4th/Communication/Information%20theory/2.pdf
Page 12
```
julia> parity_checks(BCH(15,2))
8×15 Matrix{Bool}:
 1  0  0  0  1  0  0  1  1  0  1  0  1  1  1
 0  1  0  0  1  1  0  1  0  1  1  1  1  0  0
 0  0  1  0  0  1  1  0  1  0  1  1  1  1  0
 0  0  0  1  0  0  1  1  0  1  0  1  1  1  1
 1  0  0  0  1  1  0  0  0  1  1  0  0  0  1
 0  0  0  1  1  0  0  0  1  1  0  0  0  1  1
 0  0  1  0  1  0  0  1  0  1  0  0  1  0  1
 0  1  1  1  1  0  1  1  1  1  0  1  1  1  1
```

2024-04-19 15:06 UTC, Fe-r-oz commented
Please checkout docstring/inline documentation for parity_checks for BCH code:
```
"""
H matrix (i.e. the parity-check matrix) of the BCH code is given as
1            a^1            a^2                   a^3             ...          a^(n - 1)
1         (a^3)^1          (a^3)^2            (a^3)^3             ...       (a^3)^(n - 1)
1         (a^5)^1          (a^5)^2            (a^5)^3             ...       (a^5)^((n - 1)
.                                                                                                       .
.                                                                                                       .
.                                                                                                       .
1       a^(2*t - 1)     a^(2*t - 1)^2      a^(2*t - 1)^3    ...       a^(2*t - 1)^(n -1) 

Note that the entries of H are elements in GF(2^m). Each element in GF(2^m) can be represented by a w-tuple over GF(2). If each entry of H is replaced by its corresponding m-tuple over GF(2) arranged in column form, we obtain a binary parity check matrix for the code
"""
```

2024-04-19 15:13 UTC, Krastanov commented
The output of `parity_checks` should be a binary matrix, not a matrix over some complicated field. Otherwise downstream users would not be able to use `parity_checks` in their software without special casing, which kinda defeats the purpose of having a pre-defined API. If you want to have this matrix-over-a-field function, it should have a different name (and potentially be private/unexported for now).

2024-04-19 15:14 UTC, Fe-r-oz commented
> The output of `parity_checks` should be a binary matrix, not a matrix over some complicated field. 

It is a binary matrix! The docstring is describing how to get to the binary matrix as done in the parity_checks code!

2024-04-19 15:18 UTC, Krastanov commented
Noted!

I would suggest putting this in the docstring for the code type, not for the `parity_check` method -- it would be easier to find it there and it will avoid making it sound like the parity check is not binary.

Reword it slightly, maybe something like "the parity check matrix can be obtained from the following matrix over field elements, after each field element is expressed as a binary column vector".

2024-04-19 17:18 UTC, Fe-r-oz commented
Searching for binary check matrix method for Reed Solomon Codes:

In the following slides/papers/books, there is no mention about binary parity check matrix for Reed-Solomon codes. There is mention of non-binary parity check matrix though.  Most of these on the internet discuss generator polynomial approach and some discuss non-binary parity check matrix. These are the following:

1) https://math.stackexchange.com/questions/3723530/construct-a-reed-solomon-code-find-the-parity-check-matrix
2)  https://web.ntpu.edu.tw/~yshan/RS_code.pdf
3) https://ericmoorhouse.org/handouts/reed_solomon.pdf 
4) https://ntrs.nasa.gov/api/citations/19900019023/downloads/19900019023.pdf
5) https://www.math.tecnico.ulisboa.pt/~pmartins/CTC/CTC21Notes9.pdf
6)  https://people.eecs.berkeley.edu/~venkatg/teaching/ECC-fall22/scribes/lecture05.pdf
7) https://books.google.com.pk/books?hl=en&lr=&id=3EK7EAAAQBAJ&oi=fnd&pg=PR13&dq=Reed+Solomon+codes&ots=wd3r6OuxEw&sig=8kQN9c-pMyDup01Sl0Z7fssBDFs&redir_esc=y#v=onepage&q=Reed%20Solomon%20codes&f=false
8)  https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=3b30a902c329ca393daec6df94b862d786f176c1
9) http://masters.donntu.ru/2010/fknt/yuriev/library/article8.pdf



However, I found this paper titled "Reed–Solomon Codes and Binary Transmission" 
Link: https://link.springer.com/chapter/10.1007/978-3-319-51103-0_7#:~:text=1%20Introduction,highest%20possible%20minimum%20Hamming%20distance.

This seems expensive: _As a practical example, we will consider the (256, 234, 23) extended RS code. Representing each  symbol as a binary 8 tuple the RS code becomes a (2048, 1872, 23) binary code._ 

Kindly please have a look at this paper when convenient. This paper says that RS codes are not suited for binary-channel. I think that's the reason why people don't discuss about their binary parity check matrices in the above [1-10] sources in pedagogical setting.

Please consider providing your thoughts before or after BCH review.

2024-04-19 17:28 UTC, Krastanov commented
I will not be able to help with reading through these materials.

For what is worth, a (2048, 1872, 23)  binary code is not particularly large. It is normal to work with binary codes for size even up to 50_000.

This seems to have been marked for review. Is everything finished in it?

2024-04-19 17:45 UTC, Fe-r-oz commented
> This seems to have been marked for review. 

Thanks for your thoughts.  Just please have a tiny look at this paper: https://link.springer.com/chapter/10.1007/978-3-319-51103-0_7#:~:text=1%20Introduction,highest%20possible%20minimum%20Hamming%20distance! Your insights could be valuable. All the other sources were provided for reference. 

> Is everything finished in it?
BCH is done. Now, I am moving onto parity_checks for RS codes. Would like to review BCH now or all at once? I marked it for review for BCH. Please let me know as you find comfortable

2024-04-19 17:51 UTC, Krastanov commented
Generally I prefer to review completed PRs. That is pretty common in most projects.

It is normal to ask for feedback while something is a draft, but that is a pretty different dynamic from a final review, hence that distinction being useful.

It is also reasonable to split PRs in smaller pieces if you want each reviewed separately (that usually leads to faster reviews too and some projects have it as an explicit requirement).

For the moment I will turn this back into a draft. Re-request a review when it is ready for complete review (or split it into smaller PRs if you prefer).

2024-04-19 17:56 UTC, Fe-r-oz commented
Alright. No problem! Actually, I don't know how to split PRs into smaller ones, so let's go with complete review.

On a small note, Kindly please consider providing me a green signal/confirmation so that I can work on implementing these huge binary matrices! Have I selected the right paper? Is my approach right? are questions I am considering.
Link: : https://link.springer.com/chapter/10.1007/978-3-319-51103-0_7#:~:text=1%20Introduction,highest%20possible%20minimum%20Hamming%20distance!

2024-04-19 18:05 UTC, Krastanov commented
Regrettably, I am not an expert in these constructions. I do not know whether you have selected appropriate sources.

2024-04-19 18:12 UTC, Fe-r-oz commented
Is it okay to submit another PR for BCH code ? BCH is completed and ready for review! BCH code is very different from Reed Solomon code. Maybe it's better to have to different PRs.

This PR can be solely for the Reed-Solomon code, I will read the paper and relevant people in the coming days for the reed solomon case.

2024-04-19 18:16 UTC, Krastanov commented
yes, an easy way to do that would be:

```
git checkout -b newbranchname
# delete all of the stuff you do not want in the new PR; I would suggest deleting the BCH stuff
git add .
git commit -m "some message"
git push # and make a new pull request
git checkout oldbranchname
# delete all of the stuff you do not want in the current PR; I would suggest deleting the non-BCH stuff
git add .
git commit -m "some message"
git push # and this pull request will become focused only on BCH stuff
```

2024-04-21 13:28 UTC, Fe-r-oz commented
The [paper]( https://link.springer.com/chapter/10.1007/978-3-319-51103-0_7#:~:text=1%20Introduction,highest%20possible%20minimum%20Hamming%20distance) is reliable! I started reading the paper and found interesting points:

Excerpt from the paper:

------------------
_Reed–Solomon codes are maximum distance separable (MDS) codes and have the highest possible minimum Hamming 
distance. The codes have symbols from F_q with parameters (q - 1, k, q - k) ._ 

_They are not binary codes but frequently are used with q = 2^m , and so there is a **mapping** of residue classes of a primitive polynomial with binary coefficients and each **element of  GF(2^m)**  is represented as a **binary m-tuple**._ 

-------------------
I think in the docstring I would have to mention all these details that since RS codes are inherently non-binary, we are mapping them to boolean field for Binary Transmission Process.

2024-04-21 15:11 UTC, Fe-r-oz commented
As per the paper, we expand these field matrices into binary to get parity check matrix! Nemo really powerful!
```
[a a a a a a a a a a a a a a a a a a a a a a a a a a a a a
a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2 a^2
a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3 a^3
a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4 a^4
a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 a^2 + 1 
a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a a^3 + a
a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 a^4 + a^2 
a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 a^3 + a^2 + 1 
a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a a^4 + a^3 + a 
a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 a^4 + 1 
a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 a^2 + a + 1 
a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a a^3 + a^2 + a 
a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 a^4 + a^3 + a^2 
a^4 + a^3 +a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 a^4 + a^3 + a^2 + 1 
a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1 a^4 + a^3 + a^2 + a + 1
a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1 a^4 + a^3 + a + 1]

```

2024-04-22 01:24 UTC, Fe-r-oz commented
I did it! I followed the Springer Book/Paper. 

I will set up proper docstring as here we also have a Field Matrix that gets expanded to Boolean Field!
```
println(H4)
Bool[1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0; 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0; 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0; 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0; 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1; 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1 1 1 0 0 0 1 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 1 1 0 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0; 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1 1 1 0 0 0 1 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 1 1 0 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 0 1 0 0 1; 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1 1 1 0 0 0 1 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 1 1 0 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0; 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1 1 1 0 0 0 1 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 1 1 0 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0; 0 0 0 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1 1 1 0 0 0 1 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 1 1 0 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0; 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0; 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 1; 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0; 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 1 0 1 0 0 1; 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 0 0 0 1 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 0 0 0 0; 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 1 1 1 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 0 1 0 1 1 0 0 1 1; 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 0 1 0 1 1 0 0 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 1 1 1 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1; 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 0 1 0 1 1 0 0 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 1 1 1 0 1 0; 0 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 1 1 1 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 0 1 0 1 1 0 0 1 1 0 1 1 0 1; 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 0 1 0 1 1 0 0 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 1 1 1 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0; 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 1 1 1 1 0 0 0 1 0 1 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0 1 1 1 1 0 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0; 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 1 1 1 1 0 0 0 1 0 1 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0 1 1 1 1 0 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 1 1 1 1; 0 0 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 1 1 1 1 0 0 0 1 0 1 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0 1 1 1 1 0 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1; 0 0 0 1 0 0 0 1 0 1 1 1 1 0 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 1 1 1 1 0 0 0 1 0 1 0 1 1 1 1 0 1; 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 1 1 1 1 0 0 0 1 0 1 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 0 1 1 1 1 0 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1 0 1 0; 1 0 0 0 0 1 0 1 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 1 0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 0 1 0 1 1 1 0 1 1 1 0 1 1 0 0 0 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0 0 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 0 1 0 1 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 0 1 0 0 1 0 0 0 0 1 0 1 0 1 1 1 0 0 1 1 0 1 1 0 0 0 1 1; 0 [...]

2024-04-28 18:09 UTC, Fe-r-oz commented
Results:

```
Test Summary:          | Time
ecc_decoder_all_setups | None  25.4s
Test Summary: | Pass  Total  Time
ecc_encoding  |  238    238  0.6s
Test Summary: |  Pass  Total  Time
ecc_gottesman | 24562  24562  0.2s
Test Summary:  | Pass  Total  Time
ecc_reedmuller |   19     19  0.7s
Test Summary:   | Pass  Total  Time
ecc_reedsolomon |   95     95  5.9s
Test Summary: | Pass  Total  Time
ecc_syndromes |  176    176  3.2s
Test Summary: | Pass  Total  Time
ecc_throws    |    4      4  0.0s
Test Summary: |Time
precompile    | None  0.2s
┌ Warning: The operation is of a type that can not be unified, defaulting to slower runtime dispatch
│   typeof(g) = NoiseOp{UnbiasedUncorrelatedNoise{Float64}, 1}
└ @ QuantumClifford ~/Desktop/New/b11/QuantumClifford.jl/src/sumtypes.jl:77
┌ Warning: The operation is of a type that can not be unified, defaulting to slower runtime dispatch
│   typeof(g) = NoiseOp{UnbiasedUncorrelatedNoise{Float64}, 1}
└ @ QuantumClifford ~/Desktop/New/b11/QuantumClifford.jl/src/sumtypes.jl:77
Test Summary: | Pass  Total  Time
pauliframe    |   90     90  5.1s
Test Summary: | Pass  Total  Time
allocations   |   39     39  6.5s
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: running doctests.
[ Info: Skipped ExpandTemplates step (doctest only).
[ Info: Skipped CrossReferences step (doctest only).
[ Info: Skipped CheckDocument step (doctest only).
[ Info: Skipped Populate step (doctest only).
[ Info: Skipped RenderDocument step (doctest only).
Test Summary: | Pass  Total   Time
doctests      |    1      1  14.9s
Skipping Base.active_repl
Skipping Base.active_repl_backend
Test Summary: | Pass  Total   Time
aqua          |   11     11  19.9s
     Testing QuantumClifford tests passed 
```

2024-04-30 00:19 UTC, Fe-r-oz commented
```
julia> H1 = vcat(HField[1:1, :], HField[3:end, :])
15×30 Matrix{FqFieldElem}:
 1  1                    1                    …  1                  1
 1  a                    a^2                     a^4 + a^2 + a      a^3 + 1
 1  a^2                  a^4                     a^4 + a^3 + 1      a^3 + a + 1
 1  a^3                  a^3 + a                 a^4 + a^2 + 1      a^4 + a^3 + 1
 1  a^4                  a^3 + a^2 + 1           a^2 + a            a^3 + a^2 + a + 1
 1  a^2 + 1              a^4 + 1              …  a^4 + a^3 + a + 1  a^4 + a^3
 1  a^3 + a              a^3 + a^2 + a           a^4 + a^3 + a^2    a^2 + a
 1  a^4 + a^2            a^4 + a^3 + a^2 + 1     a^4 + 1            a^4 + a + 1
 1  a^3 + a^2 + 1        a^4 + a^3 + a + 1       a^4 + a^2          a^4 + a^3 + a^2 + a + 1
 1  a^4 + a^3 + a        a + 1                   a^4                a^4 + a^3 + a^2
 1  a^4 + 1              a^3 + a^2            …  a                  a^2 + a + 1
 1  a^2 + a + 1          a^4 + a^2 + 1           a^3 + 1            a^4 + a^3 + a
 1  a^3 + a^2 + a        a^4 + a^3 + a^2 + a     a^4 + a^2 + a + 1  a^4 + a^2
 1  a^4 + a^3 + a^2      a^4 + a^2 + a + 1       a^3 + a^2 + a + 1  a^2 + 1
 1  a^4 + a^3 + a^2 + 1  a^4 + a^2 + a           a^3 + a^2          a^3
```
ReedSolomon (30, 15) Before Binary Expansion:

![Screenshot_select-area_20240430051551](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/20002619-3867-4d83-97c5-4c2076a5799c)

```
julia> GF2, a = finite_field(2, 4, "a")
(Finite field of degree 4 and characteristic 2, a)

julia> a^29
a^3 + 1

julia> a^27
a^3 + a^2 + a + 1

julia> a^25
a^2 + a + 1

julia> a^5
a^2 + a

julia> a^28
a^3 + a^2 + 1

julia> a^26
a^3 + a^2 + a

julia> a^14
a^3 + 1

julia> a^13
a^3 + a^2 + 1

julia> a^5
a^2 + a

julia> a^6
a^3 + a^2

julia> a^13
a^3 + a^2 + 1

```

2024-05-02 20:13 UTC, Fe-r-oz commented
Some of your review suggestions from the BCH apply here as well so converting it back to draft for a while.

This will save your time and effort during the first round of review.

2024-05-03 14:39 UTC, Fe-r-oz commented
I have inclued an example of expanded binary parity check matrix from the paper. It's somewhat huge, it has 75 rows and 150 columns after binary expansion. Good thing is that I have checked it's minimum hamming distance and rank as per formulas. 

I have taken the suggestions from BCH Code review and applied them here. This will save your time when doing code review, I hope.

2024-05-04 11:56 UTC, Fe-r-oz commented
Applying BCH codereview suggestions:

As per one of your suggestion to also include some example of actual binary H which can be referred to, I have tested this expanded matrix using parity_checks(ReedSolomon(...)) in the test file.

Writing this message for reference with regards to lines 92 to 148 of test file.

![Screenshot from 2024-05-04 16-44-40](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/83737861-8e71-45a9-bfae-a83b4fa9d4a4)

2024-05-05 10:34 UTC, Fe-r-oz commented
Hi Stefan,

Thanks to your suggestions in the previous code review in the other PR, I have significantly improved this PR. I have applied all of your suggestions here as well. 

I will wait a day and then convert it to open from draft status.

2024-05-12 11:51 UTC, Fe-r-oz commented
I have set this up for review! Suggestions about docstring style are added from BCH review. 

There is rendering issue with matrices, but they are in alignment in the src files when seen locally.

2024-05-13 10:59 UTC, Fe-r-oz commented
Added the cyclic test and Singleton Bound test for Reed Solomon Codes to polish the PR.

2024-05-20 04:18 UTC, Krastanov requested changes
This looks pretty good! My comments are mainly on documentation and tests. I want to run a couple more checks, but it seems this is pretty close to ready.

2024-05-20 04:18 UTC, Krastanov commented on docs/src/references.bib
> +  journal={Downloaded from URL http://www. informit. com/content/images/art. sub.--sklar7. sub.--reed-solomo-n/elementLinks/art. sub.--sklar7. sub.--reed-solomon. pdf},
this journal entry seems misformatted

2024-05-20 04:18 UTC, Krastanov commented on src/ecc/codes/classical/reedsolomon.jl
> +You might be interested in consulting [geisel1990tutorial](@cite), [wicker1999reed](@cite), [sklar2001reed](@cite), [berlekamp1978readable](@cite), [tomlinson2017error](@cite), [macwilliams1977theory
let's stick to citable sources for now, e.g. no youtube link. Also, in general, if you include a link, make sure it is properly formatted as hyperlink, not as text.

2024-05-20 06:39 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +Fixed generator polynomial scheme vs variable generator polynomial scheme: Only in this construction scheme using fixed generator polynomial `g(x)`, RS codes are a subset of the Bose, Chaudhuri, and
We can add it as a doctest. This shows that using the fixed generator_polynomial scheme, the degree of the g(x) == n - k == 2 * t ,implying there are subset of BCH codes as this same relationship holds for the BCH codes provided that we are using BCH view of defining the generator polynomial for Reed Solomon codes.

```
# RS(7, 3), RS(15, 9), RS(255, 223), RS(160, 128), RS(255, 251), (255, 239) and (255, 249) codes. 
    test_cases = [(7, 3), (15, 9), (225, 223), (160, 128), (255, 251), (255, 239), (255, 249)]
    for (n, k) in test_cases
        m = ilog2(n + 1)
        t = div(n - k, 2)
        # Using fixed generator polynomial construction scheme for defining generator polynomial, `g(x)`, of RS codes, `degree(g(x))` == 2 * t == n - k. 
        @test degree(generator_polynomial(ReedSolomon(m, t))) == 2 * t == n - k
    end
```

2024-05-20 06:39 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +This function applies Reed-Solomon codes for binary transmission using soft decisions (see section 7.3)[tomlinson2017error](@cite). For significant coding gain, code length is typically restricted to
Excerpts from the Book: 

RS codes applied to the binary transmission channel will now be considered using unquantised soft decision decoding. The best decoder to use is the modified Dorsch decoder, discussed in Chap. 15, because it provides near maximum likelihood decoding. However when used with codes having a significant coding gain, the code length needs to be typically less than 200 bits.

Using the first `x - 1` columns of the field parity-check matrix (HField), using `j = 0`, and setting `α₀, α₁, α₂, ..., αₓ ₋ ₁` to  `α⁰, α¹, α², ..., αˣ ⁻ ¹` in the parity-check matrix are set equal to the powers of a primitive element α of the Galois Field `GF(x)`, a cyclic code can be constructed for efficient encoding and decoding. 

So, the last three columns of HField are erased and this provides us with the Field Matrix HSeed. That's is why s_symbols = 3 and they referred to it as a shortened `[[2ᵐ + 1 - s, k, 2ᵐ ⁺ ¹ - s - k]]` MDS code.

I will add the reference to Dorsch Decoder.

2024-05-20 06:40 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +Soft Decision Decoding: In some communication systems, the received signal might not be a simple 0 or 1 but have a certain level of "softness" indicating the likelihood of being a 0 or 1. The benefit
I see what you mean. Please refer to the above comment for clarification.

2024-05-20 06:41 UTC, Fe-r-oz commented on test/test_ecc_reedsolomon.jl
> +using Test
The generator polynomial of BCH codes and ReedSolomon codes are both cyclic and they both have degree 2 x t so I tested the cyclic property and the degree property. (meaning degree == 2*t).

According to Nemo devs, We can't explicitly compare their generator polynomials by calling BCH's generator_polynomial because their polynomails rings don't coincide, meaning BCH codes are defined of univariate polynomial ring of GF(2), whereas ReedSolomon codes are defined over univariate polynomial rings of GF(2, m).  

I was indeed thinking of adding explicit examples but we have this potential limitation in Nemo that polynomails rings must coincide. In ReedSolomon case, the only way to access the primitive coefficients a is by defining the polynomail ring over GF(2,m) so that anything similar to this is possible gx*= (x - a ^ i). 

In the code terms, this looks like:
```
# Reed Solomon case
julia> GF2ʳ, a = finite_field(2, 4, "a")
(Finite field of degree 4 and characteristic 2, a)

julia> P, x = GF2ʳ[:x]
(Univariate polynomial ring in x over GF(2, 4), x) 

BCH case
julia> GF2ʳ, a = finite_field(2, 4, "a")
(Finite field of degree 4 and characteristic 2, a)

julia> GF2x, x = GF(2)["x"]
(Univariate polynomial ring in x over GF(2), x)
--
Reed Solomon gx examples
julia> generator_polynomial(ReedSolomon(4, 2))
x^4 + (a^3 + a^2 + 1)*x^3 + (a^3 + a^2)*x^2 + a^3*x + a^2 + a + 1

julia> generator_polynomial(ReedSolomon(3, 2))
x^4 + (a + 1)*x^3 + x^2 + a*x + a + 1

julia> generator_polynomial(ReedSolomon(5, 2))
x^4 + (a^4 + a^3 + a^2 + a)*x^3 + (a^2 + a)*x^2 + (a^3 + 1)*x + a^4 + 1
--
BCH gx examples
julia> generator_polynomial(BCH(4, 2))
x^8 + x^7 + x^6 + x^4 + 1

julia> generator_polynomial(BCH(4, 3))
x^10 + x^8 + x^5 + x^4 + x^2 + x + 1

julia> generator_polynomial(BCH(5, 3))
x^15 + x^11 + x^10 + x^9 + x^8 + x^7 + x^5 + x^3 + x^2 + x + 1

As seen above, the generator_polynomails of these two codes have different structure, meaning RS is defined taking into consideration explicitly the primitive element a in the g(X) = (X - α¹)(X - α²)(X - α³) ... (X - α²ᵗ) which means in Nemo, this is defined over a polynomal ring that does not coincide with BCH polynomial ring as in BCH, as seen above, we don't take into consideration any coefficients made by primitive elements a. 
```

2024-05-20 06:41 UTC, Fe-r-oz commented on test/test_ecc_reedsolomon.jl
> +    # Examples taken from [http://hscc.cs.nthu.edu.tw/~sheujp/lecture_note/rs.pdf].
Alrighty.

2024-05-20 06:41 UTC, Fe-r-oz commented on test/test_ecc_reedsolomon.jl
> +    end
All these cases are iterated over in the above test.

This was just to show all the specific examples of the ReedSolomon codes that I did found over literature/internet. I thought let's all the examples of these RS codes that I can find in the literature in the test as well

2024-05-20 06:42 UTC, Fe-r-oz commented on docs/src/references.bib
> +  journal={Downloaded from URL http://www. informit. com/content/images/art. sub.--sklar7. sub.--reed-solomo-n/elementLinks/art. sub.--sklar7. sub.--reed-solomon. pdf},
I added the citation from google scholar, let me see to it again.

2024-05-20 06:49 UTC, Fe-r-oz commented on test/test_ecc_reedsolomon.jl
> +end
Alright. I will make a `utils_test_ecc.jl `.

2024-05-20 06:55 UTC, Fe-r-oz commented on test/test_ecc_reedsolomon.jl
> +            @test d <= n - k + 1
The singleton bound test was not mentioned in the Springer Book about whether their designed distance after 3-level quantization for Shortened ReedSolomon codes exactly match the singleton bound for the construction scheme presented in the book.

2024-05-20 07:03 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +You might be interested in consulting [geisel1990tutorial](@cite), [wicker1999reed](@cite), [sklar2001reed](@cite), [berlekamp1978readable](@cite), [tomlinson2017error](@cite), [macwilliams1977theory
That makes sense.

2024-05-20 07:06 UTC, Fe-r-oz commented on test/test_ecc_reedsolomon.jl
> +            s_symbols = 3
Noted.

2024-05-20 07:08 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +    2. Column expansion: The elements in each column of `HFieldExpanded` matrix are converted to binary representations by substituting powers of a primitive element (`α`) in the Galois Field `GF(2ᵐ)
HSeed is Shortened ReedSolomon Code, so I will make sure that not refer to code in the documentation.

2024-05-20 08:56 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +Soft Decision Decoding: In some communication systems, the received signal might not be a simple 0 or 1 but have a certain level of "softness" indicating the likelihood of being a 0 or 1. The benefit
The paragraph on Soft-Decision decoding is redundant and unnecessary as I have mentioned the relevant details in Shortened MDS Section.  I will remove this parapraph as it's general.

2024-05-20 09:16 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +This function applies Reed-Solomon codes for binary transmission using soft decisions (see section 7.3)[tomlinson2017error](@cite). For significant coding gain, code length is typically restricted to
I will add this short line to explain why s_symbols  is set to 3.

The variable s_symbols is set to 3 because the last three columns of the field parity check matrix HF​ are erased. By using the first x−1 columns of HF​, assigning  j = 0  and setting α₀, α₁, α₂, ..., αₓ ₋ ₁ to α⁰, α¹, α², ..., αˣ ⁻ ¹ , where α is a primitive element of GF(x). This approach allows for the construction of a cyclic code, which offers advantages in the implementation of encoding and decoding.

2024-05-20 10:24 UTC, Fe-r-oz commented on test/test_ecc_reedsolomon.jl
> +    end
I have added them as doctest and removed them from here.

2024-05-20 12:16 UTC, Krastanov commented on src/ecc/codes/classical/reedsolomon.jl
> +This function applies Reed-Solomon codes for binary transmission using soft decisions (see section 7.3)[tomlinson2017error](@cite). For significant coding gain, code length is typically restricted to
As a reference you can simply have a paper or a page from a textbook, no need to include more text on it.

put the `s_symbol` in a comment, not in the docstring

2024-05-20 12:18 UTC, Krastanov commented on test/test_ecc_reedsolomon.jl
> +using Test
If the RS codes a just a subset of the BCH codes, can you just compare parity check matrices?

2024-05-20 13:14 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +This function applies Reed-Solomon codes for binary transmission using soft decisions (see section 7.3)[tomlinson2017error](@cite). For significant coding gain, code length is typically restricted to
Alrighty.

2024-05-20 13:16 UTC, Fe-r-oz commented
There is docstring error that  `: special characters "#{}()[]<>|&*?~;" must be quoted in commands. 

Please let me know that how to define proper doctests as I have never written them before. 

```
```jldoctest
julia> using Nemo: degree
julia> using QuantumClifford.ECC: ReedSolomon, generator_polynomial
julia> test_cases = [(7, 3) (15, 9) (225, 223) (160, 128) (255, 251) (255, 239) (255, 249)];
julia> for (n, k) in test_cases
           m = ilog2(n + 1)
           t = div(n - k, 2)
           degree(generator_polynomial(ReedSolomon(m, t))) == n - k == 2 * t
       end
```
```

2024-05-20 15:02 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedsolomon.jl
> +Fixed generator polynomial scheme vs variable generator polynomial scheme: Only in this construction scheme using fixed generator polynomial `g(x)`, RS codes are a subset of the Bose, Chaudhuri, and
Please see this comment for clarification: https://github.com/QuantumSavory/QuantumClifford.jl/pull/254#discussion_r1606757811

2024-05-20 15:07 UTC, Krastanov commented on test/test_ecc_reedsolomon.jl
> +using Test
I must be misunderstanding something. Are the type of RS codes implemented here a special case of BCH codes? If they are, there should be some mapping of parameters that gives you the same parity check matrices (they might not be the same exact parameter values, but there would be a one-to-one mapping).

2024-05-20 15:28 UTC, Fe-r-oz commented on test/test_ecc_reedsolomon.jl
> +using Test
I think RS code presented in the Springer book 'Error-Correction Decoding and Decoding" not special case of BCH codes. The chapter 07 "Reed–Solomon Codes and Binary Transmission" does not mention that they are related to BCH codes. It constructs a type of RS codes namely Maximum Distance Separable (MDS) codes. The book is focused on the binary transmission of the shortened MDS RS codes by forming field matrix of shortened MDS code then expanding into boolean field.

2024-05-20 15:51 UTC, Fe-r-oz commented on test/test_ecc_reedsolomon.jl
> +using Test
I think it's appropriate to rename `extended-Reed-Solomon-MDS` rather than `Reed-Solomon`.

The book says that: We will consider augmented, extended RS codes constructed from GF(2^m). The
length is 2^m + 1 and these are Maximum Distance Separable (MDS) codes with parameters (2^(m + 1), k, 2^m+1 − k). Moreover, the general case is that augmented, extended RS codes may be constructed using any Galois Field G F(q) with parameters (q+1, k, q+2−k) [6]. 

I will add the citation [6] as well.

There is paper on extending MDS codes that have similar material on how  to extend MDS codes: https://www.unb.ca/faculty-staff/directory/_resources/pdf/sase/alderson/mds-codes.pdf

2024-05-20 18:30 UTC, Fe-r-oz commented
This PR is actually an implementation of `ExtendedReedSolomonMDS ` rather than `ReedSolomon` codes. So, I have removeed the generator polynomial of ReedSolomon codes as that leads to misunderstanding for the readers. I will open a new PR that will focus purely on `Reed Solomon` codes in the future. 

ECC Zoo has some details about Extended Generalized Reed Solomon codes: https://errorcorrectionzoo.org/c/extended_reed_solomon) which are related to `ExtendedReedSolomonMDS`. 

I will remove unnecessary references about ReedSolomon codes since we are not dealing with them at this time.  The documentation is significantly improved to avoid any misunderstandings as well.

2024-05-21 13:59 UTC, Fe-r-oz commented
Hi, @Krastanov, I took the time to conduct further reading and have curated this especially for you to provide a thorough overview!

I asked myself this question that in order to implement PR on Reed Solomon codes (better to call it  `GeneralizedReedSolomon`), what does their parity check Matrix look like? 

After some more digging, I have found the answers and also clear differences which are as follows:

### ExtendedReedSolomonMDS

This PR is implementing family of Augmented, Extended RS-MDS `(ExtendedReedSolomonMDS) `codes with parameters `[[ 2^m + 1, k , 2 ^ (m + 1) - k]].`  ECC Zoo has some details about Extended Generalized Reed Solomon codes: https://errorcorrectionzoo.org/c/extended_reed_solomon) which are related to` ExtendedReedSolomonMDS. `

I am implementing this following parity check matrix in `Shortened `version of `(ExtendedReedSolomonMDS)` :

From Page 171 of Springer Book: Error Correction Coding and Encoding

![Screenshot from 2024-05-21 18-06-22](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/c16dd3c2-f661-48c2-981b-274b1f68cf67)

### Generalized ReedSolomon

On the other hand, Reed Solomon codes have the following Parity Check Matrix. This represent `GeneralizedReedSolomon codes ` and it's H matrix is similar to BCH matrix. Huffman say that these codes (given by parity check matrix below) are subfamily of BCH codes. ECC Zoo has detail on these codes: https://errorcorrectionzoo.org/c/generalized_reed_solomon.

Note: It is not the Reed Solomon codes per se but Generalized Reed Solomon codes that are related to the BCH codes. BCH codes are subfield subcodes of GRS codes according to ECC Zoo.

From Page 177 of Huffman Book: Fundamentals of Error Correcting Codes

![Screenshot from 2024-05-21 17-45-44](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/fc2fe86a-0196-4811-867e-9722e6eda81a)


Parity check Matrix of BCH codes is given below:  This H is is similar to the the above Generalized Reed Solomon H.  

![Screenshot from 2024-05-21 18-16-34](https://github.com/QuantumSavory/QuantumClifford.jl/assets/93876775/e34f1515-b609-4265-8236-e1e79e89e5d8)

Hopefully, this explain the differences! 

Best,

2024-06-06 07:52 UTC, Fe-r-oz commented
For the sake of brevity, better name is `ShortenedMDS` instead of `ExtendedReedSolomonMDS`. 

Ultimately, the authors construct the family of `[[2ᵐ + 1 - s, k, 2ᵐ ⁺ ¹ - s - k]]` ShortenedMDS first shortening the `ExtendedReedSolomonMDS`.

Then they massively expanding each row in a `m x m` matrix and then expanding each element of each row further into `m` column tupe.

I have also started exploring regular Reed Solomon codes  (in later PR), they are non-binary so we don't use GF(2) base field or GF(p ᵐ)  where p is not 2. In this regard, a special subcase of q-ary BCH (non-binary BCH) is non-binary ReedSolomon code.

Macwillians book shows that we use a non-binary base field, say GF(4), GF(5) and then end up with a GF(2) matrix, but it require further consultation with the book. I also started discussing this Macwillians method with Nemo devs as well.

2024-06-22 01:03 UTC, Krastanov requested changes
I have not reviewed this in detail at all. Here are some superficial stylistic comments until I find the time to get back to this.

2024-06-22 01:03 UTC, Krastanov commented on test/test_ecc_bch.jl
> +
Spurious whitespace -- avoid introducing spaces or tabs at the end of lines as they pollute the git log. You can probably set up your editor to automatically clear those up.

2024-06-22 01:03 UTC, Krastanov commented on test/test_ecc_shortenedmds.jl
> +- Employing `3-level` quantization of the channel bits and erasing entire symbols if any of their constituent bits are erased can improve the performance of RS codes. Shortened Maximum Distance Separ
mentioned in a couple of other PR, mentioning here for completeness:

- classical codes are usually denoted with a single set of square brackets, not doubled
- no need for parentheses around n, k, and other single-letter scalars

2024-06-22 01:03 UTC, Krastanov commented on src/ecc/codes/classical/shortenedmds.jl
> +"""
this docstring is not attached to anything

2024-06-22 01:03 UTC, Krastanov commented on src/ecc/codes/classical/shortenedmds.jl
> +"""
This probably should be part of the documentation of the code type, not of the parity checks functions (given that this function has methods for many other codes as well, which would make it very messy to read if each method has its own docstring)

2024-08-03 23:23 UTC, Krastanov requested changes
Same frustrating situation like with the other PR, due to the recent rework of the test suite: this needs a rebase. Apologies for the inconvenience :(

2024-11-24 22:55 UTC, Fe-r-oz commented
This can be revived soon if classical MDS codes are required , closing for now.

2024-11-24 22:55 UTC, closed without merging