Adding classical binary Golay codes to the ECC Module
QuantumSavory/QuantumClifford.jl pull request #276
Opened 2024-05-17 13:44 UTC by Fe-r-oz

There are two members of classical Golay Binary codes in the literature, namely the [[24, 12, 8]] and [[23, 12, 7]]. The latter can be obtained by puncturing the former. The former is described via Huffman construction method.

2024-06-20 06:15 UTC, Fe-r-oz commented
Kindly please review these short PRs @Krastanov 🙏🏼. The sequence of review of PRs can be 277, 276, 254. Thank you 🙏🏼

2024-06-22 00:56 UTC, Krastanov requested changes
Thanks, this is pretty cool!

Here are a couple of minor comments. I have not reviewed the tests in detail yet.

2024-06-22 00:56 UTC, Krastanov commented on src/ecc/codes/classical/golay.jl
> +The family of classical binary Golay codes were discovered by Edouard Golay in his 1949 paper [golay1949notes](@cite), where he described the binary `[[23, 12, 7]]` Golay code.
The double square bracket notation is usually for quantum codes. For classical codes folks usually use single bracket `[23,12,7]`.

2024-06-22 00:56 UTC, Krastanov commented on src/ecc/codes/classical/golay.jl
> +1. Binary `[[23, 12, 7]]` Golay code: The perfect code with code length `(n)` 23 and dimension `(k)` 12. Minimum distance is 7, implying it can detect or correct up to 7 errors. By puncturing in any
No need to put n and k in parenthesis

2024-06-22 00:56 UTC, Krastanov commented on src/ecc/codes/classical/golay.jl
> +1. Binary `[[23, 12, 7]]` Golay code: The perfect code with code length `(n)` 23 and dimension `(k)` 12. Minimum distance is 7, implying it can detect or correct up to 7 errors. By puncturing in any
Distance of 7 does not imply it can correct up to 7 errors. It can correct up to 3 errors if the distance is 7.

Golay should be capitalized.

2024-06-22 00:56 UTC, Krastanov commented on src/ecc/codes/classical/golay.jl
> +1. Binary `[[23, 12, 7]]` Golay code: The perfect code with code length `(n)` 23 and dimension `(k)` 12. Minimum distance is 7, implying it can detect or correct up to 7 errors. By puncturing in any
I do not understand the comment about a parity check matrix = [24,12,8].

Matrix should not be capitalized.

2024-06-22 00:56 UTC, Krastanov commented on src/ecc/codes/classical/golay.jl
> +Parity Check Matrix `(H)`: `H` is defined as follows: `H₂₄ = [I₁₂ | A']` where `I₁₂` is the 12 x 12 identity matrix and `A` is a bordered reverse circulant matrix.
On wikipedia they seem to be implying that this is the generator matrix, not the parity check matrix.

2024-06-22 00:56 UTC, Krastanov commented on src/ecc/codes/classical/golay.jl
> +Punctured Code: All punctured codes are equivalent. Adding an overall parity check to `H₂₃` recovers `H₂₄`.
This probably needs an elaboration. I am not sure what "all punctured codes are equivalent" means.

2024-06-22 00:56 UTC, Krastanov commented on src/ecc/codes/classical/golay.jl
> +        if !(n ∈ [23, 24])
This is minor, but a tuple would be a better choice than a list here (the compiler can inline and not allocate tuples, but it is not smart enough to do it with vectors)

2024-06-24 06:52 UTC, Fe-r-oz commented on src/ecc/codes/classical/golay.jl
> +Parity Check Matrix `(H)`: `H` is defined as follows: `H₂₄ = [I₁₂ | A']` where `I₁₂` is the 12 x 12 identity matrix and `A` is a bordered reverse circulant matrix.
There two notations people use either H= [I | A], G =  [A| I], or  H= [A | I ], G =  [I | A] where I is identity matrix and A is the bordered reverse circulant matrix. 

In this [paper,](https://www.researchgate.net/figure/Parity-check-matrix-for-24-12-Extended-Golay-code-6_fig1_356873687) H is described as H= [I | A]. [This website]( https://www.maplesoft.com/applications/Preview.aspx?id=1757) also describes it as H = [I |A ].  

Golay Codes are [self-dual](https://cseweb.ucsd.edu/classes/fa21/ece259-a/Lectures/lecture09-handout.pdf) (C = C⊥) ,  [H](https://mathworld.wolfram.com/GolayCode.html) = [A | I ],  G = [I | A]. H and G are canonically equivalent as we take their reduced row echelon form.

Wikipedia describes G = [ I| A ], so H = [A| I ].  Wolfram Mathwork follows this notation as well: https://mathworld.wolfram.com/GolayCode.html

Huffman and Pless Book (Section 1.9) formulation of binary Golay Codes is used.  I will add generator to make it clear which notation we are following and a test of self-duality.

2024-06-24 06:55 UTC, Fe-r-oz commented on src/ecc/codes/classical/golay.jl
> +Punctured Code: All punctured codes are equivalent. Adding an overall parity check to `H₂₃` recovers `H₂₄`.
I took it from this except from Huffman and Pless book:

"It turns out, as we will see later, that all these punctured codes are equivalent. By Exercise 59, adding an overall parity check to one of these punctured codes (in the same position which had been punctured) gives exactly the same G 24 back.

Exercise 59: Prove that if G 24 is punctured in any coordinate and the resulting code is extended in the same position, exactly the same code G 24 is obtained. Hint: See Exercise 27."

In less fancy terms, this [paper](https://arxiv.org/pdf/1811.06246) mentions punturing as deleting one coordinate position from the reverse circulant matrix (deleting one column -- they deleted the last one) to make the [23, 1, 7] Golay code.

Adding a test about would be exciting.

2024-06-24 14:29 UTC, Fe-r-oz commented
Should I add [[23, 1, 7]] [quantum Golay code](https://arxiv.org/pdf/1106.2190) here as well? It will take max 20 lines. This code is self-dual, perfect CSS code.

Applications of this code:
1) Magic State Distillation
2) Implement all the Clifford Gates transversally

####  Except from the paper

"""
The[ paper](https://arxiv.org/pdf/1106.2190)  describes that the code is self-dual, and the X and Z stabilizer generators can both be given by the following eleven 23-character strings:
```
. 1 . . 1 . . 1 1 1 1 1 . . . . . . . . . . 1
1 . . 1 . . 1 1 1 1 1 . . . . . . . . . . 1 .
. 1 1 . 1 1 1 . . . 1 1 . . . . . . . . 1 . .
1 1 . 1 1 1 . . . 1 1 . . . . . . . . 1 . . .
1 1 1 1 . . . 1 . . 1 1 . . . . . . 1 . . . .
1 . 1 . 1 . 1 1 1 . . 1 . . . . . 1 . . . . .
. . . 1 1 1 1 . 1 1 . 1 . . . . 1 . . . . . .
. . 1 1 1 1 . 1 1 . 1 . . . . 1 . . . . . . .
. 1 1 1 1 . 1 1 . 1 . . . . 1 . . . . . . . .
1 1 1 1 . 1 1 . 1 . . . . 1 . . . . . . . . .
1 . 1 . . 1 . . 1 1 1 1 1 . . . . . . . . . .
```
Here, the 1s in a row either all indicate Z operators or all indicate X operators, and dots indicate I operators.
"""

We can go with the first one as it take 65 gates which is least expensive. The paper implements them with 57 CNOTs.

```
parity_checks(c::QuantumGolay) = S"X_X__X__XXXXX__________
                                   XXXX_XX_X____X_________
                                   _XXXX_XX_X____X________
                                   __XXXX_XX_X____X_______
                                   ___XXXX_XX_X____X______
                                   Z_Z_Z_ZZZ__Z_____Z_____
                                   ZZZZ___Z__ZZ______Z____
                                   ZZ_ZZZ___ZZ________Z___
                                   _ZZ_ZZZ___ZZ________Z__
                                   Z__Z__ZZZZZ__________Z_
                                   _Z__Z__ZZZZZ__________Z"

julia> naive_encoding_circuit(s8)
65-element Vector{QuantumClifford.AbstractOperation}:
 sCNOT(12,6)
 sCNOT(12,7)
 sCNOT(12,11)
 sCNOT(18,6)
 sCNOT(18,8)
 sCNOT(18,11)
 sCNOT(19,8)
 sCNOT(19,9)
 sCNOT(20,6)
 sCNOT(20,8)
 sCNOT(20,9)
 sCNOT(20,10)
 sCNOT(20,11)
 sCNOT(21,8)
 sCNOT(21,9)
 sCNOT(21,10)
 sCNOT(21,11)
 ⋮
 sZCX(3,17)
 sHadamard(4)
 sZCX(4,6)
 sZCX(4,9)
 sZCX(4,12)
 sZCX(4,13)
 sZCX(4,14)
 sZCX(4,15)
 sZCX(4,16)
 sHadamard(5)
 sZCX(5,7)
 sZCX(5,10)
 sZCX(5,13)
 sZCX(5,14)
 sZCX(5,15)
 sZCX(5,16)
 sZCX(5,17)


parity_checks(c::QuantumGolay)  =  S"X_X__X__XXXXX__________
                                   XXXX_XX_X____X_________
                                   _XXXX_XX_X____X________
                                   __XXXX_XX_X____X_______
                                   ___ZZZZ_ZZ_Z____Z______
                                   Z_Z_Z_ZZZ__Z_____Z_____
                                   ZZZZ___Z__ZZ______Z____
                                   ZZ_ZZZ___ZZ________Z___
                                   _ZZ_ZZZ___ZZ________Z__
                                   Z__Z__ZZZZZ__________Z_
                                   _Z__Z__ZZZZZ__________Z"

julia> naive_encoding_circuit(s9)
68-element Vector{QuantumClifford.AbstractOperation}:
 sCNOT(12,5)
 sCNOT(12,6)
 sCNOT(12,10)
 sCNOT(12,11)
 sCNOT(17,5)
 sCNOT(17,7)
 sCNOT(17,10)
 sCNOT(18,5)
 sCNOT(18,6)
 sCNOT(18,7)
 sCNOT(18,8)
 sCNOT(18,10)
 sCNOT(18,11)
 sCNOT(19,5)
 sCNOT(19,7)
 sCNOT(19,8)
 sCNOT(19,9)
 ⋮
 sZCX(2,16)
 sHadamard(3)
 sZCX(3,5)
 sZCX(3,8)
 sZCX(3,11)
 sZCX(3,12)
 sZCX(3,13)
 sZCX(3,14)
 sZCX(3,15)
 sHadamard(4)
 sZCX(4,6)
 sZCX(4,9)
 sZCX(4,12)
 sZCX(4,13)
 sZCX(4,14)
 sZCX(4,15)
 sZCX(4,16)

parity_checks(c::QuantumGolay) = S"Z_Z__Z__ZZZZZ__________
                                   ZZZZ_ZZ_Z____Z_________
                                   _ZZZZ_ZZ_Z____Z________
                                   __ZZZZ_ZZ_Z____Z_______
                                   ___ZZZZ_ZZ_Z____Z______
                                   Z_Z_Z_ZZZ__Z_____Z_____
                                   ZZZZ___Z__ZZ______Z____
                                   ZZ_ZZZ___ZZ________Z___
                                   _ZZ_ZZZ___ZZ________Z__
                                   Z__Z__ZZZZZ__________Z_
                                   _Z__Z__ZZZZZ__________Z"

julia> naive_encoding_circuit(s)
77-element Vector{QuantumClifford.AbstractOperation}:
 sCNOT(12,1)
 sCNOT(12,2)
 sCNOT(12,6)
 sCNOT(12,7)
 sCNOT(12,8)
 sCNOT(12,10)
 sCNOT(13,2)
 sCNOT(13,3)
 sCNOT(13,7)
 sCNOT(13,8)
 sCNOT(13,9)
 sCNOT(13,11)
 sCNOT(14,1)
 sCNOT(14,2)
 sCNOT(14,3)
 sCNOT(14,4)
 sCNOT(14,6)
 ⋮
 sCNOT(21,5)
 sCNOT(21,8)
 sCNOT(21,10)
 sCNOT(21,11)
 sCNOT(22,1)
 sCNOT(22,4)
 sCNOT(22,7)
 sCNOT(22,8)
 sCNOT(22,9)
 sCNOT(22,10)
 sCNOT(22,11)
 sCNOT(23,1)
 sCNOT(23,5)
 sCNOT(23,6)
 sCNOT(23,7)
 sCNOT(23,9)
 sCNOT(23,11)

parity_checks(c::QuantumGolay) = S"X_X__X__XXXXX__________
                                   XXXX_XX_X____X_________
                                   _XXXX_XX_X____X________
                                   __XXXX_XX_X____X_______
                                   ___XXXX_XX_X____X______
                                   X_X_X_XXX__X_____X_____
                                   XXXX___X__XX______X____
                                   XX_XXX___XX________X___
                                   _XX_XXX___XX________X__
                                   X__X__XXXXX__________X
                                   _X__X__XXXXX__________X"

julia> naive_encoding_circuit(s1)
88-element Vector{QuantumClifford.AbstractOperation}:
 sHadamard(1)
 sZCX(1,12)
 sZCX(1,14)
 sZCX(1,17)
 sZCX(1,20)
 sZCX(1,21)
 sZCX(1,22)
 sZCX(1,23)
 sHadamard(2)
 sZCX(2,12)
 sZCX(2,13)
 sZCX(2,14)
 sZCX(2,15)
 sZCX(2,17)
 sZCX(2,18)
 sZCX(2,20)
 sHadamard(3)
 ⋮
 sZCX(9,23)
 sHadamard(10)
 sZCX(10,12)
 sZCX(10,15)
 sZCX(10,18)
 sZCX(10,19)
 sZCX(10,20)
 sZCX(10,21)
 sZCX(10,22)
 sHadamard(11)
 sZCX(11,13)
 sZCX(11,16)
 sZCX(11,19)
 sZCX(11,20)
 sZCX(11,21)
 sZCX(11,22)
 sZCX(11,23)

```

2024-06-25 15:34 UTC, Fe-r-oz commented on src/ecc/codes/classical/golay.jl
> +Parity Check Matrix `(H)`: `H` is defined as follows: `H₂₄ = [I₁₂ | A']` where `I₁₂` is the 12 x 12 identity matrix and `A` is a bordered reverse circulant matrix.
> Huffman and Pless Book (Section 1.9) formulation of binary Golay Codes is used.

In the recent papers about [quantum Golay Code [[23, 1, 7]] ](https://arxiv.org/pdf/1106.2190)and [classical golay paper,](https://arxiv.org/pdf/1811.06246) the notation used for H = [A | I ] and G = [I | A]. This is same notation used by Wikipedia for G. 

Thus, let's use this notation rather than Huffman and Pless (which is currently used). This make sure the consistency of notation b/w classical and quantum codes.

2024-06-26 02:59 UTC, Fe-r-oz commented on src/ecc/codes/classical/golay.jl
> +Punctured Code: All punctured codes are equivalent. Adding an overall parity check to `H₂₃` recovers `H₂₄`.
I have added elaboration and a test:

Elaboration:
Puncturing and then extending any column in​ with an overall parity check `H₂₃` reconstructs the original parity check matrix `H₂₄`. Thus, all punctured codes are equivalent.

Test:
```

"""
Test the equivalence of punctured and extended code by verifying that puncturing the binary parity check matrix H₂₄ in any coordinate and then extending it by
adding an overall parity check in the same position yields the original matrix H₂₄.

Steps:
1. Puncture the Code: Remove the i-th column from H₂₄ to create a punctured matrix H₂₃. Note: H₂₃ = H[:, [1:i-1; i+1:end]]
2. Extend the Code: Add a column in the same position to ensure each row has even parity. Note: H'₂₄ = [H₂₃[:, 1:i-1] c H₂₃[:, i:end]]. Here, c is a column vector added to ensure 
each row in H'₂₄ has even parity.
3. Equivalence Check: Verify that H'₂₄ = H₂₄.
"""
function puncture_code(mat, i)
    return mat[:, [1:i-1; i+1:end]]
end

function extend_code(mat, i)
    k, _ = size(mat)
    extended_mat = hcat(mat[:, 1:i-1], zeros(Bool, k, 1), mat[:, i:end])
    # Calculate the parity for each row
    for row in 1:k
        row_parity = sum(mat[row, :]) % 2 == 1
        extended_mat[row, i] = row_parity
    end
    return extended_mat
end
    for i in 1:24
        punctured_mat = puncture_code(H, i)
        extended_mat = extend_code(punctured_mat, i)
        # Test equivalence
        @test extended_mat == H
    end
```

2024-06-29 01:51 UTC, Fe-r-oz commented
Thanks for helpful comments. Improvements include:
- test for self-duality of Golay 24, which is a self dual code. (1)
- test for cross-reference by comparing our construction of A circulant matrix with one given in a paper (Canonically, both should be same") (2)
- Add a test for puncturing and then extending any column in​ with an overall parity check H₂₃ reconstructs the original parity check matrix H₂₄. Thus, removing ambiguity of the previous statement about "all punctured codes are equivalent." (3)
- using [n,k, d] notation instead off [[n, k, d]] notation. (4)
- cross validation test (2) 
- `echelon_form` from Nemo is used in the tests as well!

2024-08-03 23:22 UTC, Krastanov requested changes
Same frustrating situation like with the other PR, due to the recent rework of the test suite: this needs a rebase. Apologies for the inconvenience :(

2024-11-29 09:15 UTC, Fe-r-oz commented
This PR is ready for review, thanks!

In general, these codes are helpful assistants for quantum codes, given their use in literature, so let's export them.

2024-12-20 15:39 UTC, merged

2024-12-20 15:39 UTC, Krastanov commented
Thank you for the contribution!