Significantly polishing PR #244, Adding more details from literature
QuantumSavory/QuantumClifford.jl pull request #277
Opened 2024-05-18 08:25 UTC by Fe-r-oz

Back then, I didn't had access to this book Fundamentals of Error Correcting codes by Huffman, that's why I skipped some details about Reed-Muller codes as now I am reading it now.

I have polished this PR #244 and added more details from the literature. This provides RM a complete introduction! Tested for all the cases.

@Krastanov Kindly please handle this small PR before reviewing Reed-Solomon! Thanks!

2024-06-15 07:38 UTC, Fe-r-oz commented on src/ecc/ECC.jl
> +using LinearAlgebra: I
This is to avoid conflict warnings like QuantumClifford and LinearAlgebra both use I.

2024-06-15 07:38 UTC, Fe-r-oz commented
Please review so that we can apply the fix as soon as feasible!

I have used reduced row echelon form test to compare all the cases of RecursiveReedMuller with ReedMuller,

`@test rref(generator(ReedMuller(r, m))) == rref(generator(RecursiveReedMuller(r, m)))`

The generator for RecursiveReedMuller is widely used as subroutine for construction of new quantum codes. Therefore, added this as well.

2024-06-22 00:43 UTC, Krastanov requested changes
This is a pretty helpful set of additional implementation for cross reference. I did a quick first round of review -- there are some stylistic requests for improvement and a couple of questions on definitions and correctness checks.

2024-06-22 00:43 UTC, Krastanov commented on src/ecc/ECC.jl
> +function generator end
What is `generator`? Probably needs a docstring. Do many families of codes have this defined for them?

2024-06-22 00:43 UTC, Krastanov commented on src/ecc/codes/classical/recursivereedmuller.jl
> +abstract type ClassicalCode end
This docstring does not seem to be meant for `ClassicalCode`

2024-06-22 00:43 UTC, Krastanov commented on src/ecc/codes/classical/recursivereedmuller.jl
> +        0 ≤ r ≤ m || throw(ArgumentError("Invalid parameters: r must be non-negative, r ≤ m and m - r - 1 ≥ 0 in order to obtain a valid code."))
m-r-1>=0 is not being tested here, right? Do you mean r<m instead of r<=m?

2024-06-22 00:43 UTC, Krastanov commented on src/ecc/codes/classical/recursivereedmuller.jl
> +function _recursiveReedMuller(r::Int, m::Int)
not sure if this docstring is at the correct function... The function cided in the docstring is not this one

2024-06-22 00:43 UTC, Krastanov commented on src/ecc/codes/classical/recursivereedmuller.jl
> +"""
This docstring is unnecessary if `RecursiveReedMuller` is already documented. We have document `parity_checks` at the location of the function declaration. No need to document every method with repetitive docstrings.

2024-06-22 00:43 UTC, Krastanov commented on src/ecc/codes/classical/reedmuller.jl
> +    2. `RM(m, m)`: This is the `mᵗʰ`-order `RM` code. It encompasses the entire field `F(2ᵐ)`, representing all possible binary strings of length `2ᵐ`.
Are these two special cases part of the test suite?

2024-06-22 00:43 UTC, Krastanov commented on src/ecc/codes/classical/reedmuller.jl
> +The dimension of `RM(m - r - 1, m)` equals the dimension of the dual of `RM(r, m)`. Thus, `RM(m - r - 1, m) = RM(r, m)^⊥` which indicates that the parity check matrix of `RM(r, m)` is the generator m
Are these properties part of the test suite?

2024-06-22 00:43 UTC, Krastanov commented on src/ecc/codes/classical/recursivereedmuller.jl
> +abstract type ClassicalCode end
Actually, there seems to be a much bigger problem. You are defining `ClassicalCode` in multiple locations. There is another abstract type like this defined in the next file.

2024-06-22 00:43 UTC, Krastanov commented on src/ecc/codes/classical/reedmuller.jl
> +        0 ≤ r ≤ m || throw(ArgumentError("Invalid parameters: r must be non-negative and r ≤ m. Additionally, m must be positive and < 11 in order to obtain a valid code and to remain tractable"))
The m<11 check is deleted (which seems like a good idea) but the error message does not seem to be updated to remove the unnecessary warning

2024-06-22 00:43 UTC, Krastanov commented on src/ecc/codes/classical/reedmuller.jl
> +"""
We should probably have one single `generator` docstring at the place the function is first introduced. No need to have a repetitive new docstring for it, if the `ReedMuller` type has already been documented well.

2024-06-22 00:43 UTC, Krastanov commented on src/ecc/codes/classical/reedmuller.jl
> +function parity_checks(c::ReedMuller)
similarly, no need for this docstring, same comment as mentioned a couple of times above

2024-06-22 00:43 UTC, Krastanov commented on test/Project.toml
> +RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
Nemo.jl seems to already provide a rref function (see http://nemocas.github.io/Nemo.jl/v0.6/matrix/#reduced-row-echelon-form ) -- let's use theirs, as it is a more established package that is less probable to disappear.

2024-06-22 00:43 UTC, Krastanov commented on test/test_ecc_reedmuller.jl
> -                                             1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0]
These are pretty suspicious. Were the previously implemented results wrong?

Are these examples supposed to be the generator matrices or the parity check matrices?

2024-06-22 00:43 UTC, Krastanov commented on test/test_ecc_reedmuller.jl
>  end
I am not sure I understand this function. What is it checking for?

2024-06-22 00:43 UTC, Krastanov commented on test/test_ecc_reedmuller.jl
> +            @test rref(generator(ReedMuller(r, m))) == rref(generator(RecursiveReedMuller(r, m)))
This is a really neat and helpful set of checks!

Why is there an if statement? What is the problem with m=r?

2024-06-22 01:48 UTC, Fe-r-oz commented on src/ecc/ECC.jl
> +function generator end
It's the Generator Matrix for Reed-Muller codes. In most of the papers, the people show the generator matrices instead of the parity check matrices.  

Also,  the code conversion paper used the generator for `recursivereedmuller `codes, so adding a function for generator

In the paper I used, the matrices they used were generators: https://arxiv.org/pdf/2002.03317. (Page 5) I read the paper carefully this time 👀

2024-06-22 01:49 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedmuller.jl
> +    2. `RM(m, m)`: This is the `mᵗʰ`-order `RM` code. It encompasses the entire field `F(2ᵐ)`, representing all possible binary strings of length `2ᵐ`.
Yep,` r` starts at `0` at ends at m, so we test both` (0, m) `and `(m, m)`

```
    for m in 3:10
        for r in 0:m
```

2024-06-22 01:54 UTC, Fe-r-oz commented on test/test_ecc_reedmuller.jl
> -                                             1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0]
The results were correct but I mistook generators matrices for parity check matrices. 

I found this out when I was reading the [code conversion paper ](https://arxiv.org/pdf/1112.2417)and authors were talking about 'generators' and soon I realized, I had implemented generator matrices. Sorry for this inconvenience.

2024-06-22 01:55 UTC, Fe-r-oz commented on test/test_ecc_reedmuller.jl
>  end
It's checking that the minimum hamming distance must be at least greater than/equal to `2^(m - r).`

2024-06-22 02:02 UTC, Fe-r-oz commented on test/test_ecc_reedmuller.jl
> +            @test rref(generator(ReedMuller(r, m))) == rref(generator(RecursiveReedMuller(r, m)))
If statement make sure that `r` is not  `< 0` since the new r for parity check matrix is` m - r - 1.`

We do check in struct whether r is less than 0, but since for parity check matrix, we select r as  `m - r - 1`, and m  as m `(m - r - 1, m)`, for some cases near larger values, `m - r - 1` is evaluated to `< 0 `

So, even with this set of checks  `0 ≤ r ≤ m`, it's possible to get   `m - r - 1` < 0 which shouldn't be the case. That's why I added the if check. Is there any better way to do this?

2024-06-22 02:10 UTC, Krastanov commented on src/ecc/codes/classical/reedmuller.jl
> +    2. `RM(m, m)`: This is the `mᵗʰ`-order `RM` code. It encompasses the entire field `F(2ᵐ)`, representing all possible binary strings of length `2ᵐ`.
These case are being generated as part of the tests for all RM codes, but the very special properties of these edge cases are not tested, are they? E.g. The fact that RM(0.m) is the repretition code and the fact that RM(m,m) are the entire field?

Such edge cases make for pretty good correctness tests.

2024-06-22 02:13 UTC, Krastanov commented on test/test_ecc_reedmuller.jl
> -                                             1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0]
The difference between parity check matrix and generator matrix is very big -- I would not say these were correct, this is a serious error that we should be careful to guard against. Are there any automated consistency tests that we can put it so that such errors are automatically detected in the future? (it is not enough to say that one would be careful in the future -- carefulness is never enough to protect against bugs)

For instance, do we automatically test that the number of rows and columns fulfills correctly the necessary relationships with code_n, code_k and others?

2024-06-22 02:14 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedmuller.jl
> +    2. `RM(m, m)`: This is the `mᵗʰ`-order `RM` code. It encompasses the entire field `F(2ᵐ)`, representing all possible binary strings of length `2ᵐ`.
Indeed. Explicit checks would be nice. I will add them.

2024-06-22 02:15 UTC, Krastanov commented on test/test_ecc_reedmuller.jl
>  end
But if the first row has a weight bugger than 2^(m-r) this would immediately return true, even if the second row has weight smaller than 2^(m-r)? Is that the intended behavior?

2024-06-22 02:19 UTC, Fe-r-oz commented on test/test_ecc_reedmuller.jl
> -                                             1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0]
> For instance, do we automatically test that the number of rows and columns fulfills correctly the necessary relationships with code_n, code_k and others?

Yeah, that makes sense. And during the time of implementation, we should check what's the parity checks method is returning, and have true or false. Similar to `isCSS,` maybe `isParityCheck `method.

2024-06-22 02:22 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedmuller.jl
> +The dimension of `RM(m - r - 1, m)` equals the dimension of the dual of `RM(r, m)`. Thus, `RM(m - r - 1, m) = RM(r, m)^⊥` which indicates that the parity check matrix of `RM(r, m)` is the generator m
I will add this explicit check of checking one dimension of `RM(m - r - 1, m)` to dual of `RM(r, m)`

2024-06-22 02:24 UTC, Fe-r-oz commented on test/test_ecc_reedmuller.jl
>  end
I think better to check all rows first, and then return `true` would be better.

2024-06-22 02:38 UTC, Fe-r-oz commented on src/ecc/codes/classical/recursivereedmuller.jl
> +        0 ≤ r ≤ m || throw(ArgumentError("Invalid parameters: r must be non-negative, r ≤ m and m - r - 1 ≥ 0 in order to obtain a valid code."))
m-r-1 is the r for parity check matrix. And r should be always >=0 (hence this condition: m-r-1>=0). 

I will add this check here.

2024-06-22 02:40 UTC, Fe-r-oz commented on test/test_ecc_reedmuller.jl
> +            @test rref(generator(ReedMuller(r, m))) == rref(generator(RecursiveReedMuller(r, m)))
>Is there any better way to do this? 

Rather than if statement during tests, better to include the check in the definition that `m - r - 1`.

2024-06-22 10:46 UTC, Fe-r-oz commented on test/Project.toml
> +RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
Nemo dev told me better to use `Nemo.echelon_form(QQ, matrix)` rather than `Nemo.rref` as latter is going be to removed in later versions.

2024-06-22 12:26 UTC, Krastanov commented on test/test_ecc_reedmuller.jl
>  end
Yup, that would be better, but I do not think that is what you function is doing, right?

If that is what it is supposed to be doing, the simplest fix is to check for failure in the loop and return false, and only if the whole loop finishes without a failure, you return true (kinda the opposite of what is happening here)

2024-06-22 12:29 UTC, Fe-r-oz commented on test/test_ecc_reedmuller.jl
>  end
I have fixed the entire function! I realized it. Exactly!

2024-06-22 21:07 UTC, Krastanov commented on src/ecc/codes/classical/reedmuller.jl
> +            throw(ArgumentError("Invalid parameters: r must be non-negative, r ≤ m and m - r - 1 ≥ 0. Additionally, m must be positive and < 11 in order to obtain a valid code and to remain tractable
I think this was in the previous review, but maybe I forgot to add it:

The argument error message and the check do not seem to actually match.

Also, isn't r ≤ m and m - r - 1 ≥ 0 equivalent to just r<m?

I think it is best to remove the <11 constraint. It seems a bit too stringent and it really depends on the amount of RAM the user has.

2024-06-22 21:11 UTC, Krastanov commented
I probably will be able to merge this shortly if I do not find any new issues besides what I just mentioned. Could you update the changelog so that it is ready for merge? Mention there is a bug fix to the parameter_checks matrix (if this was a public type this would have been a breaking change, so it is good to document these clearly)

2024-06-23 02:41 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedmuller.jl
> +            throw(ArgumentError("Invalid parameters: r must be non-negative, r ≤ m and m - r - 1 ≥ 0. Additionally, m must be positive and < 11 in order to obtain a valid code and to remain tractable
You mentioned in in the previous review.

`r > m` make sure that `r<m` because if  `r > m` error message will be thrown.


```
@test_throws ArgumentError ReedMuller(-1, 3)
@test_throws ArgumentError ReedMuller(1, 0)
@test_throws ArgumentError ReedMuller(4, 2)

@test_throws ArgumentError RecursiveReedMuller(-1, 3)
@test_throws ArgumentError RecursiveReedMuller(1, 0)
@test_throws ArgumentError RecursiveReedMuller(4, 2)
```

I will remove the  <11 constraint.

2024-06-23 02:44 UTC, Fe-r-oz commented on src/ecc/codes/classical/reedmuller.jl
> +            throw(ArgumentError("Invalid parameters: r must be non-negative, r ≤ m and m - r - 1 ≥ 0. Additionally, m must be positive and < 11 in order to obtain a valid code and to remain tractable
I forgot to update the argument error message, which is my mistake.

2024-06-23 02:52 UTC, Fe-r-oz commented
This was changelog of 244 "Implemented the classical Reed-Muller code"

I think RM was not exported, so I am not sure about Public Type/Breaking change part.

So, maybe `Bug fix to parity_checks(ReedMuller(r, m)) of classical Reed-Muller code along with RecursiveReedMuller code implementation for cross-reference`

Please feel free to update CHANGELOG accordingly.

2024-06-29 22:07 UTC, Fe-r-oz commented
###  Upcoming PR discussion

Good news, @Krastanov  :) 

Sometime ago, I discussed a paper about[ code conversion between Quantum Reed Muller code and Steane Code](https://arxiv.org/pdf/1403.2734). Turns out that the Quantum Reed Muller is really simple!  Now, I understand what ECCZOO is talking about in their [QRM page](https://errorcorrectionzoo.org/c/quantum_reed_muller)!

There is a lot of rigorous testing that I am planning to do with these quantum codes and I think the entire paper can be implemented as upcoming PR. The parameters of the QRM are: [[n = 2^m − 1, k = 1, d = 3]]. Now, this are CSS Quantum Reed Muller codes! 

Please checkout the two examples! Example of the popular 15 qubit QRM code that is used in magic state distillation: From visual inspection, we can see it as two copies to steane code.  Steanecode is QRM(3)

```
#notes
# RM(1,m): dual is RM(m -2, m), generator(RM(m -2, m)) = H_m
# Shortened RM_bar(1, m): first row and first column are deleted from generator(RM(1, m))
julia> RM14 = generator(RecursiveReedMuller(1, 4));

julia> RM24 = generator(RecursiveReedMuller(4 - 2, 4)); #dual

julia> QRM = CSS(RM14[2:end, 2:end], RM24[2:end, 2:end])
CSS(Bool[1 0 … 0 1; 0 1 … 1 1; 0 0 … 1 1; 0 0 … 1 1], Bool[1 0 … 0 0; 0 1 … 1 0; … ; 0 0 … 1 1; 0 0 … 1 1])

julia> Stabilizer(QRM)
+ X_X_X_X_X_X_X_X
+ _XX__XX__XX__XX
+ ___XXXX____XXXX
+ _______XXXXXXXX
+ Z___Z___Z___Z__
+ _Z___Z___Z___Z_
+ __Z___Z___Z___Z
+ ___ZZZZ____ZZZZ
+ ____Z_Z_____Z_Z
+ _____ZZ______ZZ
+ _______ZZZZZZZZ
+ ________Z_Z_Z_Z
+ _________ZZ__ZZ
+ ___________ZZZZ

julia> naive_encoding_circuit(parity_checks(Stabilizer(QRM)))

43-element Vector{QuantumClifford.AbstractOperation}:
 sCNOT(15,5)
 sCNOT(15,6)
 sCNOT(15,7)
 sCNOT(15,9)
 sCNOT(15,10)
 sCNOT(15,12)
 sHadamard(1)
 sZCX(1,5)
 sZCX(1,6)
 sZCX(1,8)
 sZCX(1,9)
 sZCX(1,11)
 sZCX(1,13)
 sZCX(1,15)
 sHadamard(2)
 sZCX(2,5)
 sZCX(2,7)
 ⋮
 sZCX(3,12)
 sZCX(3,13)
 sZCX(3,14)
 sZCX(3,15)
 sHadamard(4)
 sZCX(4,9)
 sZCX(4,10)
 sZCX(4,11)
 sZCX(4,12)
 sZCX(4,13)
 sZCX(4,14)
 sZCX(4,15)
 sSWAP(8,4)
 sSWAP(7,4)
 sSWAP(6,4)
 sSWAP(5,4)
 sSWAP(4,3) 
```

More exciting is this fact that QuantumReedMuller(3) is Steane Code. The proof is as follows: 
```

julia> RM13 = generator(RecursiveReedMuller(1, 3));

julia> RM23 = generator(RecursiveReedMuller(3 - 2, 3));

julia> QRM = CSS(RM14[2:end, 2:end], RM24[2:end, 2:end])
CSS(Bool[1 0 … 0 1; 0 1 … 1 1; 0 0 … 1 1; 0 0 … 1 1], Bool[1 0 … 0 0; 0 1 … 1 0; … ; 0 0 … 1 1; 0 0 … 1 1])

julia> QRM_steane = CSS(RM13[2:end, 2:end], RM23[2:end, 2:end])
CSS(Bool[1 0 … 0 1; 0 1 … 1 1; 0 0 … 1 1], Bool[1 0 … 0 1; 0 1 … 1 1; 0 0 … 1 1])

julia> Steane = Stabilizer(QRM_steane)
+ X_X_X_X
+ _XX__XX
+ ___XXXX
+ Z_Z_Z_Z
+ _ZZ__ZZ
+ ___ZZZZ

julia> canonicalize!(parity_checks(Steane7()))
+ X_X_X_X
+ _XX__XX
+ ___XXXX
+ Z_Z_Z_Z
+ _ZZ__ZZ
+ ___ZZZZ

julia> canonicalize!(parity_checks(Steane7())) == Stabilizer(QRM_steane)
true

```
I am very excited to work on this as soon as the RecursivePR is finished!

2024-07-09 11:14 UTC, Fe-r-oz commented
Hello @Krastanov, the quantum CSS Reed Muller code PR is ready but I am waiting for this one to be finished so that I can use the constructors introuced in this PR in next one! 

Please review this one so I can polish the next quantum code PR for review 😬 I am excited to submit quantum codes from classical codes finally!

2024-07-20 19:00 UTC, Fe-r-oz commented
Hello @Krastanov, just a small reminder that the current implementation of `ReedMuller` needs a bug fix as it's bad and ugly at the moment.  Please help review the PR so bug fix can be applied soon.

Thank you for the valuable feedback that helped improved the PR significantly.

In this PR, I have made sure to test two different representations (binomial polynomial rep vs recursive) for cross-reference and added several correctness tests and provided complete documentation.

2024-07-21 13:26 UTC, Fe-r-oz commented
I tried to rename the branch to `FixRM` instead of `PolishRM` and the branch got deleted! Hopefully it's restored. 

I was following your comments that "its good to document changes clearly" so I thought let's rename the branch. 🙄

2024-07-26 07:35 UTC, Fe-r-oz commented
Removing `CHANGELOG `to prevent merge conflicts.

```
changelog:

- **(fix)** Bug fix to the `parity_checks(ReedMuller(r, m))` of classical `Reed-Muller` code along with `RecursiveReedMuller` code implementation for cross reference.
```

2024-08-03 23:16 UTC, Krastanov requested changes
Regrettably, this needs a rebase after the recent rework of the test suite. Sorry for the runaround, I know this is pretty annoying.

2024-08-04 14:59 UTC, Fe-r-oz commented
No problem at all. `Testitems` is cool! 

Rebased. Thanks for the reminder.

2024-08-10 21:06 UTC, Krastanov requested changes
this looks great! Sorry for the slow review. After a few minor fixes to the docstrings it should be good to merge.

2024-08-11 04:38 UTC, Fe-r-oz commented on src/ecc/codes/classical/recursivereedmuller.jl
> +\end{bmatrix}
Thanks for your question! I have cross verified with repos that use ```math env for a lot of math expressions. When we use this, it seems we don't use double slashes, although, if we are not using, double slashes absolutely make sense.  Also, I checked - double slashes are not rendered within math environment.

Hopefully, we will see a pretty matrix with math in dev doc. I will cross verify from dev doc as well.

2024-08-11 05:29 UTC, Fe-r-oz commented
Thank you for your helpful suggestions. 

P.S. The `build` fail is due to upstream `Persistant tasks` test fail from `QuantumSavory.jl`.

2024-09-08 04:51 UTC, Fe-r-oz commented
@Krastanov, pinging for review.

2024-09-14 03:32 UTC, merged

2024-09-14 03:32 UTC, Krastanov commented
Thank you for fixing this