Concatenated quantum code
QuantumSavory/QuantumClifford.jl pull request #289
Opened 2024-06-11 15:04 UTC by royess

Implement the concatenated quantum code, which combines two quantum codes into a large one.

2024-06-11 15:17 UTC, royess commented
I am a bit unsure about the right way to write the `iscss` function for the concatenated quantum code.

A concatenated quantum can be either CSS or non-CSS. In this PR, I make `iscss` return true if the inner and outer codes are both CSS. This can make tests pass but is not a necessary condition in general; two non-CSS codes can also generate a CSS, concatenated code.

I would appreciate some input. Also, please help review this PR. @Krastanov

2024-06-13 14:36 UTC, Krastanov requested changes

2024-06-13 14:36 UTC, Krastanov commented on src/ecc/codes/concat.jl
> +function concat(c₁, c₂)
I think this should be just `parity_checks(Concat(c1, c2))`. I want to avoid introducing new single-purpose functions to the public API.

2024-06-13 14:36 UTC, Krastanov commented on src/ecc/codes/concat.jl
> +    iscss(c.c₁) && iscss(c.c₂) # but it is possible that c.c₁ and c.c₂ are non-css but c is css
we can return `nothing` for the unknown cases, we just need to document that possibility where `iscss` is originally declared

2024-06-13 14:36 UTC, Krastanov commented on src/ecc/ECC.jl
> +    concat,
I want to keep the public API as small as possible. Let's remove `concat` given that it is single purpose

2024-06-13 14:36 UTC, Krastanov commented on src/ecc/codes/concat.jl
> +Code concatenation of two quantum codes [concatenated1996knill](@cite)--the inner code c₁ and the outer code c₂.
```suggestion
`Concat(c₁, c₂)` is a code concatenation of two quantum codes [concatenated1996knill](@cite)

The inner code c₁ and the outer code c₂.
```

Otherwise c* is not defined. Also adding an empty line to separate header from rest of docstring.

2024-06-13 14:36 UTC, Krastanov commented on src/ecc/codes/concat.jl
> +The resulting code will have n = n₁ * n₂ qubits and k = k₁ * k₂ logical qubits.
```suggestion
The resulting code will have `n = n₁ × n₂` qubits and `k = k₁ × k₂` logical qubits.
```

2024-06-13 14:37 UTC, Krastanov commented
Converting back to draft to make it easier for me to track my review backlog. Do not hesitate to convert it back to non-draft and to ping me for another review.

2024-06-14 04:16 UTC, Krastanov commented on test/test_ecc_codeproperties.jl
> +        @test iscss(code) in (is_css_matrix(H), nothing)
I changed this from a list to a tuple to avoid allocations. Not important in this place, but a good habit to keep.

2024-06-14 04:16 UTC, Krastanov commented on src/ecc/codes/concat.jl
> +    return nothing # if c.c₁ or c.c₂ are non-CSS; in this case, `Concat(c₁, c₂)` can still be CSS
I added this because I prefer having explicit returns, otherwise the code is a bit more complicated to read.

2024-06-14 04:18 UTC, Krastanov commented on docs/src/references.md
> +- [concatenated1996knill](@cite)
the doc CI fails because this is the wrong ref name

2024-06-14 04:18 UTC, Krastanov commented on src/ecc/codes/concat.jl
> +`Concat(c₁, c₂)` is a code concatenation of two quantum codes [concatenated1996knill](@cite).
the doc CI fails because this is the wrong ref name

2024-06-14 13:51 UTC, merged