beginning of biased pauli noise for PF sim
QuantumSavory/QuantumClifford.jl pull request #295
Opened 2024-06-18 17:58 UTC by amicciche

This is the code that was mentioned in our Zulip messages. One note, it seemed to be that line 41 in the noise.jl, `    n = nqubits(s)` wasn't doing anything, so I went ahead and deleted that in addition to the functions I added. 

As mentioned over Zulip, because of the error, this code is untested, aside from being able to generate the object from the Julia REPL.

2024-06-19 11:48 UTC, amicciche commented
I'm now having this error when I try to use QuantumClifford:

![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/32377705/7a712fd5-4ad3-4f10-877c-0250d80a1549)

2024-06-19 12:53 UTC, Krastanov commented
it is fixed now

2024-06-21 22:02 UTC, amicciche commented
The `applynoise!()` that takes a `PauliFrame` seems to work correctly, however the way the constructors are written for `PauliError`, one can't do something like the following (which will probably a common enough case to warrant fixing):
![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/32377705/429506ae-150f-4962-a1e3-21a390e7e952)
I tried to fix this by changing Integer to Real on line 37 of noise.jl, but this caused an error. Here:
![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/32377705/38cfbebe-8e07-41a1-8118-5ca89b6dba03)

2024-06-22 00:05 UTC, Krastanov commented
What error did the change to Real cause?

2024-06-22 01:04 UTC, Krastanov commented
marking this as a draft just to make my review queue a bit more manageable. Mark it as finished when ready for review.

2024-06-22 11:48 UTC, amicciche commented
> What error did the change to Real cause?

When I change it to Real:
![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/32377705/b55b3754-5fb2-482b-8b10-2e26211e7f7a)

I get this error:
![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/32377705/bde44452-2604-4d0f-9473-795d5a2f2e50)

2024-06-22 12:24 UTC, Krastanov commented
Float is a Real so when you do `PauliNoise(x::Real, y::Real, z::Real) = PauliNoise(float(x), float(y), float(z))` you end up with infinite recursion.

A cleaner solution than both what I have written and what you have written is to specify the type for the constructor:
```
julia> struct A{T} a::T end

julia> A(a::Real) = A{Float64}(a)
A

julia> A(1)
A{Float64}(1.0)
```

Or even better, something that does not hardcode Float64

```
julia> struct A{T} a::T end

julia> function A(a::Real) 
           a = float(a)
           return A{typeof(a)}(a)
       end
A

julia> A(1)
A{Float64}(1.0)

julia> A(BigInt(1))
A{BigFloat}(1.0)
```

So the cleanest solution should be something along the lines of
```
function PauliNoise(px::Real, py::Real, pz::Real)
    px, py, pz = float.((px, py, pz))
    px, py, pz = promote(px, py, pz)
    T = typeof(px)
    return PauliNoise{T}(px, py, pz)
end
```

2024-06-22 14:12 UTC, amicciche commented
Ah, I see! I'll try to fix this later today, using what you suggested, thanks!

2024-06-23 04:18 UTC, amicciche commented
Your code worked as provided! Thanks! With that, I think everything works. I checked for a few codes that doing PauliError(qubit, p) after decoding results in the same logical vs physical error rate plots as PauliError(qubit, p/3, p/3, p/3). For some CSS codes, I also checked that the X and Z logical error corresponding to those simulations also matches doing PauliError(qubit, p*2/3, 0, 0) and PauliError(qubit, 0, 0, p*2/3)  correspondingly (and the other X/Z logical error is 0). Similarly, PauliError(qubit, 0, p*2/3, 0) gives the same performance as PauliError(qubit, p).

2024-07-02 13:48 UTC, Krastanov requested changes
could you also update the changelog

2024-07-02 13:48 UTC, Krastanov commented on src/noise.jl
> +    NoiseOp(PauliNoise(px,py,pz), [q])
```suggestion
    NoiseOp(PauliNoise(px,py,pz), (q,))
```

no need to allocate a vector

2024-07-02 13:48 UTC, Krastanov commented on src/noise.jl
> +
```suggestion
```

spurious whitespace

2024-07-24 18:37 UTC, Krastanov approved these changes

2024-07-30 03:02 UTC, merged