add random Clifford circuit codes
QuantumSavory/QuantumClifford.jl pull request #298
Opened 2024-06-20 02:21 UTC by royess

Add implementations of random Clifford circuit codes, whose connectivity can be all-to-all or brickwork in some dimensions.

Some notes:
1. While preparing this PR, I found that [this notebook](https://github.com/QuantumSavory/QuantumClifford.jl/blob/master/docs/src/notebooks/Stabilizer_Codes_Based_on_Random_Circuits.ipynb) have implemented a 1D brickwork random circuit codes. This PR provides more connectivity choices and uses `AbstractOperations[]` of sparse gates for the generated circuit, which should be more efficient and allow visualization.
2. I do not include random circuit codes in `ecc_decoder_all_setups` in this PR. The reason is that to ensure a good code parameter, the code has to contain more than 10 qubits, which exceeds the size that `TableDecoder` can efficiently handle. Random circuit codes are not CSS and are currently unsupported by `PyMatchingDecoder`.
3. For a reference, I did some more tests in [royess/qecc-devlog/test_random_circuit.ipynb](https://github.com/royess/qecc-devlog/blob/master/test_random_circuit.ipynb), including visualizing the encoding circuits and decoding via TableDecoder. In the future, we may consider including these contents as tutorials or documentation.

2024-06-20 02:36 UTC, royess commented
@Krastanov, please help review this PR; thanks! (The failed CI check is related to #245 )

2024-06-20 02:41 UTC, Krastanov requested changes
This is great! You mentioned how it does not work well with many decoders. How does it perform with belief propagation and OSD decoders?

2024-06-20 02:41 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +    arrange::NTuple{N,Int} where {N} # the spatial arrangement of qubits
you can turn these comments into per-field docstrings (julia supports per-field docstrings and they render better in various introspection tools).

2024-06-20 02:41 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +    function RandomCircuitCode(rng::AbstractRNG, n::Int, connect::Val{:alltoall}, ngates::Int, k::Int)
I think I prefer if all these inner constructors become normal constructors. It is valuable to still make it possible to access something like the default constructor, even if that constructor is undocumented and non-public.

But maybe I am missing some other reason to do that, just let me know.

2024-06-20 02:41 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +function random_brickwork_clifford_circuit(rng::AbstractRNG, arrange::NTuple{N,Int} where {N}, nlayers::Int)
Do we want to support periodic and non-periodic boundary conditions?

2024-06-20 02:41 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +    connect::Union{Val{:alltoall},Val{:brickwork}} # the gate connectivity
Do we want to support 2d brickworks (the qubits are layed out in a square lattice instead of a line)?

2024-06-20 02:41 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +    end
I am not super comfortable that all these constructors are nondeterministic. In my mind, a constructor is supposed to take some data and organize it in a nice datastructure.

I think these should not be constructors, rather `rand` methods. To make a random Int, you do not call the constructor Int(). You call `rand(Int)`.

On the other hand here you basically need `rand(RandomCircuitCode, params...)`, which is not the `rand` API either.

I guess this means that we need `random_circuit_code` function.

What are your thoughts on this?

2024-06-20 02:51 UTC, royess commented on src/ecc/codes/random_circuit.jl
> +    connect::Union{Val{:alltoall},Val{:brickwork}} # the gate connectivity
The 2d brickworks (or higher) are supported and can be constructed by passing `arrange=(5,5)`, for example. I think I should make this better documented.

2024-06-20 02:58 UTC, royess commented on src/ecc/codes/random_circuit.jl
> +function random_brickwork_clifford_circuit(rng::AbstractRNG, arrange::NTuple{N,Int} where {N}, nlayers::Int)
It will be easy technically.

I am unsure whether adding more options to `RandomCircuitCode::connect` will make the code a bit clumsy.

2024-06-20 03:23 UTC, royess commented on src/ecc/codes/random_circuit.jl
> +    end
I also think using a `random_circuit_code` will be better.

Further, we may also consider decoupling between (1) generating a random circuit and (2) constructing a code from a given encoding circuit. In this way, part (1) should be put outside the ECC submodule; part (2) can be a function that converts an encoding circuit to a code of type `AbstractECC`.

In this way, a struct type `RandomCircuitCode` also does not seem necessary. The public API will be `random_circuit(...)` and `AbstractECC(circ, encoding_qubits)`.

Will this be a better design?

2024-06-20 03:46 UTC, royess commented on src/ecc/codes/random_circuit.jl
> +    end
A downside of removing `RandomCircuitCode` is that one can no longer get the circuit from such a code, which is sometimes convenient.

Alternatively, we may still have such a type with a maybe better name, e.g., `CircuitCode`.

2024-06-20 04:16 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +    end
I do not think we should remove the struct, just the randomness in the constructor. `CircuitCode` sounds good.

2024-06-20 09:24 UTC, royess commented
> You mentioned how it does not work well with many decoders.

Actually, `TableDecoder` can give a rather low logical error rate, as I tested in [this notebook](https://github.com/QuantumSavory/QuantumClifford.jl/blob/master/docs/src/notebooks/Stabilizer_Codes_Based_on_Random_Circuits.ipynb).

However, we need random circuit codes with more than 10 qubits, e.g., 20 qubits, to ensure the randomly generated codes have a distance larger than 0. This will make `TableDecoder` inefficient and trigger warnings due to #291.

> How does it perform with belief propagation and OSD decoders?

BP and BP-OSD in `PyQDecoders.jl` (as well as earlier mentioned `PyMatchingDecoder` ) are not applicable to random circuit codes because they are non-CSS.

```
"Codes of type CircuitCode do not have separate X and Z parity checks, either because they are not a CSS code and thus inherently do not have separate checks, or because its separate checks are not yet implemented in this library."

Stacktrace:
 [1] parity_checks_x(code::CircuitCode)
   @ QuantumClifford.ECC ~/Documents/Repos/QuantumClifford.jl/src/ecc/ECC.jl:41
 [2] QuantumCliffordPyQDecodersExt.PyBeliefPropOSDecoder(c::CircuitCode; maxiter::Nothing, bpmethod::Nothing, errorrate::Nothing, osdmethod::Nothing, osdorder::Int64)
   @ QuantumCliffordPyQDecodersExt ~/Documents/Repos/QuantumClifford.jl/ext/QuantumCliffordPyQDecodersExt/QuantumCliffordPyQDecodersExt.jl:51
 [3] QuantumCliffordPyQDecodersExt.PyBeliefPropOSDecoder(c::CircuitCode)
   @ QuantumCliffordPyQDecodersExt ~/Documents/Repos/QuantumClifford.jl/ext/QuantumCliffordPyQDecodersExt/QuantumCliffordPyQDecodersExt.jl:50
 [4] PyBeliefPropOSDecoder(args::CircuitCode; kwargs::@Kwargs{})
   @ QuantumClifford.ECC ~/Documents/Repos/QuantumClifford.jl/src/ecc/decoder_pipeline.jl:297
 [5] PyBeliefPropOSDecoder(args::CircuitCode)
   @ QuantumClifford.ECC ~/Documents/Repos/QuantumClifford.jl/src/ecc/decoder_pipeline.jl:292
 [6] top-level scope
   @ ./In[27]:14
```

2024-06-20 13:16 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +function random_brickwork_clifford_circuit(rng::AbstractRNG, arrange::NTuple{N,Int} where {N}, nlayers::Int)
Sounds good, no need to change anything here, I like your approach. A bit more documentation would be helpful.

2024-06-22 21:32 UTC, Krastanov requested changes
a few more minor stylistic changes

2024-06-22 21:32 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +  For example, a 5×5 lattice will have `arrange = (5, 5)`.
Does this imply that the `connect` and `arrange` arguments are "correlated"? If that is the case, it would be better if it is a single argument. We can just stick to `arrange` maybe call it something like `lattice_dims`.

2024-06-22 21:32 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +but its conversion to LinearIndex is limited, not supporting non-one step.
TODOs should not be visible in the documentation.

Also, this TODO would be a breaking change if adopted, right? We should not merge things that already have the expectation that there will be a breaking change to them in the future.

2024-06-22 21:32 UTC, Krastanov commented on src/randoms.jl
> +    circ = QuantumClifford.AbstractOperation[]
Can this list be more concretely typed?

2024-06-22 21:32 UTC, Krastanov commented on test/test_ecc_base.jl
> +    CircuitCode => random_circuit_code_args
The formatting change here is not bad, but I would prefer if it is not done -- it makes reading `git blame` more difficult

2024-06-22 21:32 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +  For example, a 5×5 lattice will have `arrange = (5, 5)`.
nope, forget this, I misunderstood what you had written.

However, I am still not a very big fan of `arrange` because it sounds to me like the verb, not a contraction of `arrangement`. I see you use the word `dim` for something else. How about `lattice_size`?

2024-06-22 21:32 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +  For example, a 5×5 lattice will have `arrange = (5, 5)`.
But now I have also a completely separate problem. Don't `circ` and `encode_qubits` completely define the code? No need for `arrange` and for `connect`? The documentation of `random_circuit_code` can instead be more detailed and there should be a `See also: ` ref here.

2024-06-24 13:22 UTC, royess commented on src/ecc/codes/random_circuit.jl
> +  For example, a 5×5 lattice will have `arrange = (5, 5)`.
> However, I am still not a very big fan of `arrange` because it sounds to me like the verb, not a contraction of `arrangement`. I see you use the word `dim` for something else. How about `lattice_size`?

I agree with these new names, which are more clear.

> Don't `circ` and `encode_qubits` completely define the code? No need for `arrange` and for `connect`?

That is true.

I kept them thinking that `arrange` and `connect` may help in some potential future features. For example, we may want to accept `arrange` in CartesianIndex, as mentioned in the TODO below. But currently, they look redundant and should indeed better be moved.

2024-06-24 13:26 UTC, royess commented on src/randoms.jl
> +    circ = QuantumClifford.AbstractOperation[]
Do you mean by we should have `arrange::NTuple{N,Int} where {N<:Integer}`?

2024-06-28 23:59 UTC, Krastanov commented on src/randoms.jl
> +    circ = QuantumClifford.AbstractOperation[]
no, the list just does not need to be an abstract operation list. You are creating only one type of gates here.

2024-06-29 00:00 UTC, Krastanov commented
What is the current status?

2024-06-29 00:53 UTC, royess commented
I did not fully comprehend some of your previous review comments and was waiting for your further replies on them.

I will get this PR updated quickly.

2024-07-02 02:35 UTC, Krastanov requested changes
looks good, but there are a few stylistic changes that I would like, to make it a bit more in the style of the rest of the library

2024-07-02 02:35 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +end
I am not very comfortable with all these different methods. The brickwork and the alltoall methods barely have any overlapping signatures, at which point it does not really make sense to keep them as methods of the same function. I think it would be cleaner and less confusing to simply have two separate functions, the way you have two separate functions for generating random circuits.

2024-07-02 02:35 UTC, Krastanov commented on src/randoms.jl
> +function random_brickwork_clifford_circuit(rng::AbstractRNG, arrange::NTuple{N,Int} where {N}, nlayers::Int)
needs a docstring if it is exported

2024-07-02 02:35 UTC, Krastanov commented on src/randoms.jl
> +function random_all_to_all_clifford_circuit(rng::AbstractRNG, nqubits::Int, ngates::Int)
needs a docstring if it is exported

2024-07-02 02:35 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +"""
probably should have a `see also` section to the random circuit functions and to the struct

2024-07-02 02:35 UTC, Krastanov commented on src/ecc/codes/random_circuit.jl
> +code_n(c::CircuitCode) = prod(c.n)
I do not think the `prod` is necessary

2024-07-04 23:51 UTC, merged

2024-07-04 23:51 UTC, Krastanov commented
Wonderful! Thanks for the addition