Horizontal concatenation for Tableaus
QuantumSavory/QuantumClifford.jl pull request #304
Opened 2024-07-01 03:48 UTC by Fe-r-oz

For `hcat`, it seems we would need a something like this if we suppose that we have a s1 as 4x4 and s2 as 4x4 stabilizers

```
julia> hcat(s1, s2),
1-element Vector{Stabilizer{QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}}}:
 Stabilizer 4×8

julia> vcat(s1, s2)
2-element Vector{Stabilizer{QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}}}:
 Stabilizer 4×4
 Stabilizer 4×4
```
This will give method error was we are dealing with AbstractVectors 
```
julia> hcat(s1, s2)
1×2 Matrix{Stabilizer{QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}}}:
 Stabilizer 4×4  Stabilizer 4×4

```
I have added the if check that Tableus rows must be the same for horizontal concatenation.

```
julia> using QuantumClifford.ECC
julia> s1 = random_stabilizer(4)
+ X_XZ
+ X_ZX
- ZX_Y
+ _YXZ

julia> s2 = random_stabilizer(4)
+ _XYY
+ ZYXY
+ _YYX
- ZXYY

julia> vcat(s1,s2)
+ X_XZ
+ X_ZX
- ZX_Y
+ _YXZ
+ _XYY
+ ZYXY
+ _YYX
- ZXYY
```

I am trying to figure out what happends to the phase vector, In the vcat it is concatenated vertically which makes sense but in hcat, we don't want. We want the size of phase vector to remain the same but phases modified maybe 
```

julia> hcat(s1,s2)
+ + becomes + ? X_XZ_XYY
+ + becomes + ? X_ZXZYXY
+ - becomes - ? ZX_Y_YYX
- + becomes - ? _YXZZXYY
```

At the moment, `hcat` is not performing as expected

```
julia> using QuantumClifford.ECC
julia> s1 = random_stabilizer(4)
- X_XZ
- _YYX
- Y__X
- ZYXY

julia> s2 = random_stabilizer(4)
+ ZXYZ
- XX_X
- ZYZ_
+ _XXX

julia> s2 = random_stabilizer(2)
+ XX
- YZ

julia> hcat(s1, s2)
ERROR: ArgumentError: All Tableaus must have the same number of qubits for horizontal concatenation.
Stacktrace:
 [1] hcat
   @ ~/GitHub/QuantumClifford/QuantumClifford.jl/src/QuantumClifford.jl:929 [inlined]
 [2] hcat(::Stabilizer{QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}}, ::Stabilizer{QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}})
   @ QuantumClifford ~/GitHub/QuantumClifford/QuantumClifford.jl/src/QuantumClifford.jl:937
 [3] top-level scope
   @ REPL[6]:1

julia> s2 = random_stabilizer(4)
+ X_ZY
- XYZ_
- X__Y
+ ZZZX

julia> hcat(s1, s2) gives me the s1
- X_XZ
- _YYX
- Y__X
- ZYXY
```

I have trouble understanding what's `hcat` xzs is doing inside the vcat function, If xzs are horizontal arrays then horizontally concatenating them form a matrix which makes sense. Since xzs is an AbstractMatrix and hcating them (not sure whats hcat is doing, maybe we are creating a vector of matrices by hcatting then we can perform vcat by wrapper of stabilizers for vcat?  

```
function Base.vcat(tabs::Tableau...)
    Tableau(
        vcat((s.phases for s in tabs)...),
        tabs[1].nqubits,
        hcat((s.xzs for s in tabs)...)) ❓ 
end
```

Thanks for your help!

2024-07-01 04:00 UTC, Fe-r-oz commented
A very minor addition towards right track maybe, We need `sum(s.nqubits for s in tabs),` previouly I was doing`  tabs[1].nqubits,`

```
julia> s1 = random_stabilizer(4)
+ XX_X
- ZXZY
+ ZYX_
+ YYZ_

julia> s2 = random_stabilizer(4)
- _XYX
+ ZZZX
+ YYYZ
- YZX_

julia> hcat(s1, s2) # maybe right track
+ XX_X____
- ZXZY____
+ ZYX_____
+ YYZ_____

```

2024-07-01 04:29 UTC, Krastanov requested changes
Thanks for starting this draft. I left a few quick comments that hopefully would be of help.

You know, but just a reminder, this also will need to have tests.

2024-07-01 04:29 UTC, Krastanov commented on CHANGELOG.md
> +- Addition of a horizontal concatenation for Tableaus -- `hcat`.
It is a French word, so the plural is a bit weird: `tableaux`, not `tableaus`.

2024-07-01 04:29 UTC, Krastanov commented on src/QuantumClifford.jl
> +        throw(ArgumentError("All Tableaus must have the same number of qubits for horizontal concatenation."))
same spelling issue

2024-07-01 04:29 UTC, Krastanov commented on src/QuantumClifford.jl
> +    hcat((s.xzs for s in tabs)...))
I do not think this would actually work, as the `xzs` array is padded with zeros. Probably it would be necessary to first allocate the empty larger tableau and to insert the smaller tableaux at the appropriate indices. I think the `setindex` functions are already relatively efficient and can be used directly here.

2024-07-01 04:30 UTC, Krastanov commented on src/QuantumClifford.jl
> +    hcat((s.xzs for s in tabs)...))
you also see this in the example you have already posted as a comment above

2024-09-01 06:14 UTC, Fe-r-oz commented on src/QuantumClifford.jl
> +    hcat((s.xzs for s in tabs)...))
Thank you!

2024-09-01 07:52 UTC, Fe-r-oz commented on src/QuantumClifford.jl
> +    hcat((s.xzs for s in tabs)...))
Check out a rather coarse version:
```

julia> s1 = parity_checks(Steane7())
+ ___XXXX
+ _XX__XX
+ X_X_X_X
+ ___ZZZZ
+ _ZZ__ZZ
+ Z_Z_Z_Z

julia> hcat(s1, s1, s1, s1)
+ ___XXXX___XXXX___XXXX___XXXX
+ _XX__XX_XX__XX_XX__XX_XX__XX
+ X_X_X_XX_X_X_XX_X_X_XX_X_X_X
+ ___ZZZZ___ZZZZ___ZZZZ___ZZZZ
+ _ZZ__ZZ_ZZ__ZZ_ZZ__ZZ_ZZ__ZZ
+ Z_Z_Z_ZZ_Z_Z_ZZ_Z_Z_ZZ_Z_Z_Z
```

The above version does not tell us whether we are setting phases correctly. One has to be careful when setting phase information as follows:

```
julia> s1 = random_stabilizer(2)
- ZZ
+ XY

julia> s2 = random_stabilizer(2)
- ZY
- XX

julia> hcat(s1, s2)
- ZZZY
- XYXX

julia> hcat(s1, s2, s1, s1)
- ZZZYZZZZ
- XYXXXYXY

julia> hcat(s1, s2, s1, s2)
- ZZZYZZZY
- XYXXXYXX
```

I will add the tests for `hcat`, perhaps adding a small doctest as well.

2024-09-01 07:56 UTC, Fe-r-oz commented on src/QuantumClifford.jl
> +    hcat((s.xzs for s in tabs)...))
The `vcat` is for `Tableau` and `Stabilizer` both. So, `hcat` functionality for `Tableau ` will be added as well besides for `Stabilizer`.

2024-09-01 11:42 UTC, Fe-r-oz commented
> I left a few quick comments that hopefully would be of help.

Indeed. 

I have added tests, and doctests as well.

`hcat`
```
julia> using QuantumClifford

julia> s1 = random_stabilizer(4)
+ Z_YX
- ZZ_X
+ XZ_Z
- _XXY

julia> s2 = random_stabilizer(4)
+ Z__X
- Z_XX
+ ZZX_
+ XX_Y

julia> hcat(s1, s2)
+ Z_YXZ__X
- ZZ_XZ_XX
+ XZ_ZZZX_
- _XXYXX_Y

julia> hcat(s1, s2, s1, s2)
+ Z_YXZ__XZ_YXZ__X
- ZZ_XZ_XXZZ_XZ_XX
+ XZ_ZZZX_XZ_ZZZX_
- _XXYXX_Y_XXYXX_Y
```

2024-09-14 02:37 UTC, Krastanov requested changes
Thanks for this, it is a nice quality of life improvement. I left in a few minor comments.

2024-09-14 02:37 UTC, Krastanov commented on src/QuantumClifford.jl
> +Vertically concatenates `stabilizers`.
```suggestion
Vertically concatenates tableaux.
```

2024-09-14 02:37 UTC, Krastanov commented on src/QuantumClifford.jl
> +Vertically concatenates `stabilizers`.
There is a bit of a mismatch of documentation here. This is `vcat(::Tableau...)` while the docstring you have created showcases concatenation of `Stabilizer`

2024-09-14 02:37 UTC, Krastanov commented on src/QuantumClifford.jl
> +    cols = sum(map(tab -> size(tab, 2), tabs))
```suggestion
    cols = sum(map(nqubits, tabs))
```
a bit simpler

2024-09-14 02:37 UTC, Krastanov commented on src/QuantumClifford.jl
> +Horizontally concatenates `stabilizers`.
same comment as above -- this docstring is about Tableau, but the example in it is about Stabilizer

2024-09-14 02:37 UTC, Krastanov commented on src/QuantumClifford.jl
> +            newtab.phases[i] |= tab.phases[i]
Why this rule? Seems a bit arbitrary. Maybe we can use `phase = (phase+other_phase)%4` to mimic tensor product of Paulis

2024-09-14 11:42 UTC, Fe-r-oz commented
Thank you, all of your comments have been incorporated. Also, fixed the `JET` errors for `vcat` and `hcat`.

The `julia 1 - t=1 mac-os-latest` test error is not related to this PR. I think the PR is ready for review.

2024-09-27 04:08 UTC, Krastanov reviewed
This looks good! I added a TODO about some inefficiencies in this implementation, but they can be addressed separately after this is merged.

I will merge it tomorrow after tests pass, etc.

2024-09-27 13:41 UTC, merged