`inv` implementation for all subtypes of `AbstractCliffordOperator`
QuantumSavory/QuantumClifford.jl pull request #314
Opened 2024-07-12 12:25 UTC by Fe-r-oz

Functionality that we want 

```
julia> inv_op = inv(SingleQubitOperator(sHadamard(1)))
sHadamard on qubit 1
X₁ ⟼ + Z
Z₁ ⟼ + X

julia> expected_inv_op = sHadamard(1)
sHadamard on qubit 1
X₁ ⟼ + Z
Z₁ ⟼ + X

julia> inv(sHadamard(1))
sHadamard on qubit 1
X₁ ⟼ + Z
Z₁ ⟼ + X
```

I will add the twoqubit invs today as well.  Hope you find this plausible!

2024-07-12 12:33 UTC, Fe-r-oz commented
Locally the tests passes: I hope it will pass here as well.

```
julia> include("test_symcliff.jl")
Precompiling QuantumClifford
  1 dependency successfully precompiled in 27 seconds. 46 already precompiled.
Test Summary:            | Pass  Total  Time
Small symbolic operators |  270    270  2.7s
Test Summary:             | Pass  Total  Time
Convert between small ops |   59     59  2.4s
Test Summary:                   | Pass  Total  Time
SingleQubitOperator Inv methods |   14     14  0.1s
Test.DefaultTestSet("SingleQubitOperator Inv methods", Any[], 14, false, false, true, 1.720769482610657e9, 1.720769482702756e9, false, "/home/Desktop/New/inv/QuantumClifford.jl/test/test_symcliff.jl")
```

2024-07-12 12:36 UTC, Krastanov commented
> Locally the tests passes: I hope it will pass here as well.

Thanks! Generally, do not worry about reporting stuff like that. I will anyway wait for the CI to run, so no need to investigate things unless there is a problem.

2024-07-12 12:39 UTC, Fe-r-oz commented on test/test_symcliff.jl
> +@testset "SingleQubitOperator Inv methods" begin
Thanks. I was wondering how to make tests for the` inv `methods.  This helps!

2024-07-12 12:44 UTC, Fe-r-oz commented on src/symbolic_cliffords.jl
> +function inv(op::SingleQubitOperator)
Yeah, I wrongly thought that inv of `sPhase` is `sInvPhase `and `inv` of `sInvPhase `is `sPhase`, I think this is wrong.

It seems that Inv of `sPhase` should be `sPhase` and inv of `sInvPhase` should be `sInvPhase`

2024-07-12 12:46 UTC, Fe-r-oz commented
> a couple of notes

Thank you for these notes!

2024-07-12 12:48 UTC, Krastanov commented on src/symbolic_cliffords.jl
> +function inv(op::SingleQubitOperator)
My remark was not about sPhase and sInvPhase, but about SingleQubitOperator. It would be kinda silly if the sPhase inverse is not sInvPhase given their names, but admittedly naming conventions can be silly.

```
julia> using QuantumClifford

julia> CliffordOperator(sPhase(1),1)
X₁ ⟼ + Y
Z₁ ⟼ + Z

julia> CliffordOperator(sInvPhase(1),1)
X₁ ⟼ - Y
Z₁ ⟼ + Z

julia> CliffordOperator(sPhase(1),1) |> inv
X₁ ⟼ - Y
Z₁ ⟼ + Z

julia> CliffordOperator(sInvPhase(1),1) |> inv
X₁ ⟼ + Y
Z₁ ⟼ + Z
```

2024-07-12 12:52 UTC, Fe-r-oz commented on test/test_symcliff.jl
> +@testset "SingleQubitOperator Inv methods" begin
Please have a look at this: 

```
julia> inv(SingleQubitOperator(sHadamard(1)))
sHadamard on qubit 1
X₁ ⟼ + Z
Z₁ ⟼ + X

julia> inv(CliffordOperator(sHadamard))
X₁ ⟼ + Z
Z₁ ⟼ + X

julia> inv(sHadamard(1))
sHadamard on qubit 1
X₁ ⟼ + Z
Z₁ ⟼ + X

julia> inv(CliffordOperator(sHadamard)) == inv(sHadamard(1))
false

julia> inv(CliffordOperator(sHadamard)) == inv(SingleQubitOperator(sHadamard(1)))
false
```

2024-07-12 12:56 UTC, Krastanov commented on test/test_symcliff.jl
> +@testset "SingleQubitOperator Inv methods" begin
You are comparing different types. Convert them to the same type.

2024-07-12 12:58 UTC, Krastanov commented on test/test_symcliff.jl
> +@testset "SingleQubitOperator Inv methods" begin
Nothing to do with printing. They are just different types. We can in principle extend the equality checks to work even in such situations, but that is more of a question of style.

2024-07-12 13:00 UTC, Fe-r-oz commented on test/test_symcliff.jl
> +@testset "SingleQubitOperator Inv methods" begin
Thanks, I made a silly comment which does not make sense.

2024-07-12 13:07 UTC, Fe-r-oz commented on test/test_symcliff.jl
> +@testset "SingleQubitOperator Inv methods" begin
I hope this sounds good:

```
julia> CliffordOperator(inv(SingleQubitOperator(sHadamard(1))), 1) == inv(CliffordOperator(sHadamard))
true
julia> CliffordOperator(inv(SingleQubitOperator(sY(1))), 1) == inv(CliffordOperator(sY))
true
```

2024-07-12 13:27 UTC, Fe-r-oz commented
Thanks for your comments. Indeed, they helped to polish the PR. I hope this is alright now!

2024-07-12 13:29 UTC, Fe-r-oz commented on src/symbolic_cliffords.jl
> +function inv(op::SingleQubitOperator)
I hope that the changes to the tests are satisfactory now.

2024-07-12 14:13 UTC, Krastanov requested changes

2024-07-12 14:13 UTC, Krastanov commented on src/symbolic_cliffords.jl
> +function inv(op::SingleQubitOperator)
the issue about phases is not fixed. This does not work correctly if the phases in the `SingleQubitOperator` are nonzero (and these cases are also not tested). E.g. try generating a random `SingleQubitOperator` with nontrivial phases and check the result.

2024-07-12 14:13 UTC, Krastanov commented on src/symbolic_cliffords.jl
> +    else
This can probably be simplified significantly simply by reusing the constructor of `SingleQubitOperator` which already does this conversion. Copying all of this here causes a lot of duplication.

2024-07-12 14:13 UTC, Krastanov commented on test/test_symcliff.jl
> +    @test CliffordOperator(inv(SingleQubitOperator(sX(1))), 1) ==  inv(CliffordOperator(sX))
let's do these with less repetition. Something like:

```
for gate_type in [...]
    @test CliffordOperator(inv(SingleQubitOperator...))==...
    @test CliffordOperator(inv(...)) ==...
end
```

Also, currently `SingleQubitOperator` with arbitrary phases is not tested.

2024-07-12 16:15 UTC, Fe-r-oz commented on src/symbolic_cliffords.jl
> +function inv(op::SingleQubitOperator)
Currently, I am working on the random_op stuff. Because, for random_op, sometime it works and sometime it does not

```
julia> using Random

julia> random_op = random_clifford1(Random.GLOBAL_RNG, 1)
SingleQubitOperator on qubit 1
X₁ ⟼ - Y
Z₁ ⟼ + Z

julia> inv(random_op)
sPhase on qubit 1
X₁ ⟼ + Y
Z₁ ⟼ + Z

julia> inv(SingleQubitOperator(random_op))
sPhase on qubit 1
X₁ ⟼ + Y
Z₁ ⟼ + Z

```

2024-07-12 16:21 UTC, Krastanov commented on src/symbolic_cliffords.jl
> +function inv(op::SingleQubitOperator)
It does not work when phases are nontrivial because you do not take care of phases in your implementations of inv. By phases I mean the signes in front of each row. See how inv takes care of these in the case of CliffordOperator

2024-07-12 16:33 UTC, Fe-r-oz commented on src/symbolic_cliffords.jl
> +function inv(op::SingleQubitOperator)
Thanks a lot. I will check that out CliffordOperator. Sorry for taking too much of your time today.

2024-07-12 17:59 UTC, Fe-r-oz commented on src/symbolic_cliffords.jl
> +function inv(op::SingleQubitOperator)
Thank you once again, I check out line by line `linalg.jl`, and then formed the fix. I hope it's okay.

```
    for i in 1:1000
        random_op = random_clifford1(Random.GLOBAL_RNG, 1)
        @test CliffordOperator(inv(random_op), 1) == inv(CliffordOperator(random_op, 1))
        @test CliffordOperator(inv(SingleQubitOperator(random_op)), 1) == inv(CliffordOperator(random_op, 1))
    end
```

2024-07-12 18:16 UTC, Krastanov requested changes

2024-07-12 18:16 UTC, Krastanov commented on src/symbolic_cliffords.jl
> +import Base: inv
This is imported multiple times in different files. It should be done only once.

Also, this function is from LinearAlgebra, not from Base.

It would probably be easier to simply not import it explicitly like that and just do `function LinearAlgebra.inv(` like done here https://github.com/QuantumSavory/QuantumClifford.jl/blob/59e399d17ddb1430482ed343d221680754b54bf0/src/linalg.jl#L6

2024-07-12 18:16 UTC, Krastanov commented on src/symbolic_cliffords.jl
> +inv(op::AbstractSingleQubitOperator) = inv(SingleQubitOperator(op))
having the previous set of enumerated concrete inversion rules would probably be better and more highly performant. This general approach is necessary only for the generic operator `SingleQubitOperator` which can have arbitrary phases

2024-07-12 18:16 UTC, Krastanov commented on src/symbolic_cliffords.jl
> +    return SingleQubitOperator(c)
this seems like an appropriate and simple way to set it up

2024-07-12 18:16 UTC, Krastanov commented on test/test_symcliff.jl
> +    for i in 1:1000
let's drop this to just 10

Running a million tests makes sense during development. When things are finished and we are setting up tests that will be executed for every single commit, it would be good to try to make sure they do not take a ton of time.

2024-07-12 18:17 UTC, Fe-r-oz commented on src/symbolic_cliffords.jl
> +    return SingleQubitOperator(c)
Yeah, I was doing it wrong all this time. Thank you for pointing in the right direction.

2024-07-12 18:19 UTC, Krastanov commented on src/symbolic_cliffords.jl
> +    return SingleQubitOperator(c)
phases is true by default, it is not necessary to specify it

2024-07-12 18:19 UTC, Krastanov commented on src/symbolic_cliffords.jl
> +    return SingleQubitOperator(c)
and I do not think `op.q` is correct there. It should just be 1

2024-07-12 18:20 UTC, Krastanov commented on test/test_symcliff.jl
> +        @test CliffordOperator(inv(SingleQubitOperator(gate_type(1))), 1) == inv(CliffordOperator(gate_type))
what happens if it is not `gate_type(1)` but `gate_type(rand(1:100))`? The `inv` will probably not work as currently written

2024-07-12 19:11 UTC, Fe-r-oz commented on test/test_symcliff.jl
> +        @test CliffordOperator(inv(SingleQubitOperator(gate_type(1))), 1) == inv(CliffordOperator(gate_type))
I think using `compact=true` helps solve this error ` gate_type(rand(1:100)) `works with `compact ==true`

```
 DimensionMismatch: Set a larger `n`, otherwise the `SingleQubitOperator` can not fit in the allocated `CliffordOperator`. Use `compact=true` if you want to discard the target index.
  Stacktrace:
   [1] CliffordOperator(op::SingleQubitOperator, n::Int64; compact::Bool)

```

2024-07-12 19:15 UTC, Krastanov commented on test/test_symcliff.jl
> +        @test CliffordOperator(inv(SingleQubitOperator(gate_type(1))), 1) == inv(CliffordOperator(gate_type))
Sure, but look at the actual gate you are creating when you run your current inverse. Is it even reporting to be on the same qubit?

2024-07-12 19:19 UTC, Fe-r-oz commented on test/test_symcliff.jl
> +        @test CliffordOperator(inv(SingleQubitOperator(gate_type(1))), 1) == inv(CliffordOperator(gate_type))
Nope, It's reporting on the 1st qubit!

2024-07-13 05:11 UTC, Fe-r-oz commented on src/symbolic_cliffords.jl
> +inv(op::AbstractSingleQubitOperator) = inv(SingleQubitOperator(op))
Using this helps avoid the error like

```
julia> CliffordOperator(inv(sX(1)), 1)
ERROR: MethodError: no method matching inv(::sX)
Closest candidates are:
  inv(::Nemo.AcbMatrix)
   @ Nemo ~/.julia/packages/Nemo/TFa9Y/src/arb/acb_mat.jl:441
  inv(::Nemo.QQMatrix)
   @ Nemo ~/.julia/packages/Nemo/TFa9Y/src/flint/fmpq_mat.jl:479
  inv(::Nemo.FqRelPowerSeriesRingElem)
   @ Nemo ~/.julia/packages/Nemo/TFa9Y/src/flint/fq_default_rel_series.jl:512

julia> CliffordOperator(inv(SingleQubitOperator(sX(1))), 1)
X₁ ⟼ + X
Z₁ ⟼ - Z
```

2024-07-13 05:11 UTC, Fe-r-oz commented on test/test_symcliff.jl
> +        @test CliffordOperator(inv(SingleQubitOperator(gate_type(1))), 1) == inv(CliffordOperator(gate_type))
As you said, for `gate_type(rand(1:100)), `it does not work. It only works for `n=1 `when `compact=true`, otherwise, the target index is discarded.  If I don't used compact, I get error like "You are trying to convert a multiqubit `CliffordOperator` into a symbolic `SingleQubitOperator`. So, I think compact is to be used, but it discared the target index. 


```
julia> CliffordOperator(inv(SingleQubitOperator(sX(1))), 3) =>ok
X₁ ⟼ + X__
X₂ ⟼ + _X_
X₃ ⟼ + __X
Z₁ ⟼ - Z__
Z₂ ⟼ + _Z_
Z₃ ⟼ + __Z

julia> CliffordOperator(inv(SingleQubitOperator(sX(1))), 2) =>ok
X₁ ⟼ + X_
X₂ ⟼ + _X
Z₁ ⟼ - Z_
Z₂ ⟼ + _Z

julia> CliffordOperator(inv(SingleQubitOperator(sX(1))), 1) => ok
X₁ ⟼ + X
Z₁ ⟼ - Z

julia> CliffordOperator(inv(SingleQubitOperator(sX(2))), 3) => not ok
X₁ ⟼ + X__
X₂ ⟼ + _X_
X₃ ⟼ + __X
Z₁ ⟼ - Z__
Z₂ ⟼ + _Z_
Z₃ ⟼ + __Z

julia> CliffordOperator(inv(SingleQubitOperator(sX(3))), 3) => not ok
X₁ ⟼ + X__
X₂ ⟼ + _X_
X₃ ⟼ + __X
Z₁ ⟼ - Z__
Z₂ ⟼ + _Z_
Z₃ ⟼ + __Z

julia> inv(CliffordOperator(sX(3), 3)) => ok
X₁ ⟼ + X__
X₂ ⟼ + _X_
X₃ ⟼ + __X
Z₁ ⟼ + Z__
Z₂ ⟼ + _Z_
Z₃ ⟼ - __Z

julia> inv(CliffordOperator(sX(2), 3)) => ok
X₁ ⟼ + X__
X₂ ⟼ + _X_
X₃ ⟼ + __X
Z₁ ⟼ + Z__
Z₂ ⟼ - _Z_
Z₃ ⟼ + __Z
```

2024-07-13 08:18 UTC, Fe-r-oz commented on test/test_symcliff.jl
> +        @test CliffordOperator(inv(SingleQubitOperator(gate_type(1))), 1) == inv(CliffordOperator(gate_type))
Fixed the error, Everything is okay now! 

```
julia> CliffordOperator(inv(SingleQubitOperator(sX(1))), 3)  =>ok
X₁ ⟼ + X__
X₂ ⟼ + _X_
X₃ ⟼ + __X
Z₁ ⟼ - Z__
Z₂ ⟼ + _Z_
Z₃ ⟼ + __Z

julia> CliffordOperator(inv(SingleQubitOperator(sX(2))), 3)   =>ok
X₁ ⟼ + X__
X₂ ⟼ + _X_
X₃ ⟼ + __X
Z₁ ⟼ + Z__
Z₂ ⟼ - _Z_
Z₃ ⟼ + __Z

julia> CliffordOperator(inv(SingleQubitOperator(sX(3))), 3)  =>ok
X₁ ⟼ + X__
X₂ ⟼ + _X_
X₃ ⟼ + __X
Z₁ ⟼ + Z__
Z₂ ⟼ + _Z_
Z₃ ⟼ - __Z

julia> inv(CliffordOperator(sX(3), 3))   =>ok
X₁ ⟼ + X__
X₂ ⟼ + _X_
X₃ ⟼ + __X
Z₁ ⟼ + Z__
Z₂ ⟼ + _Z_
Z₃ ⟼ - __Z

julia> inv(CliffordOperator(sX(2), 3))   =>ok
X₁ ⟼ + X__
X₂ ⟼ + _X_
X₃ ⟼ + __X
Z₁ ⟼ + Z__
Z₂ ⟼ - _Z_
Z₃ ⟼ + __Z

```

2024-07-13 08:34 UTC, Fe-r-oz commented on src/symbolic_cliffords.jl
> +inv(op::AbstractSingleQubitOperator) = inv(SingleQubitOperator(op))
Oh, I see your point now. I will revert to concerte inversion rules.

2024-07-17 15:04 UTC, Krastanov approved these changes

2024-07-17 20:00 UTC, merged

2024-07-17 20:00 UTC, Krastanov commented
Thanks for the contribution!

2024-07-18 00:21 UTC, Fe-r-oz commented
Thanks for the feedback!