`inv` implementation for `TwoQubitOperator`
QuantumSavory/QuantumClifford.jl pull request #315
Opened 2024-07-13 16:35 UTC by Fe-r-oz

Desired Functionalty to address https://github.com/QuantumSavory/QuantumClifford.jl/issues/286

```
julia> inv(sCNOT(1, 2))
sCNOT on qubit1 (1,2)
X₁ ⟼ + XX
X₂ ⟼ + _X
Z₁ ⟼ + Z_
Z₂ ⟼ + ZZ

julia> inv(sCPHASE(1, 2))
sCPHASE on qubit1 (1,2)
X₁ ⟼ + XZ
X₂ ⟼ + ZX
Z₁ ⟼ + Z_
Z₂ ⟼ + _Z
```
Added a new TwoQubitOp namely `sInvZCrY` because of the following:

`sInvZCrY`  and `sZCrY `have the same dynamic like we see with `sPhase `and `sInvPhase` for `SingleQubitOperator.`

```
julia> CliffordOperator(sZCrY)
X₁ ⟼ - YY
X₂ ⟼ + ZX
Z₁ ⟼ + Z_
Z₂ ⟼ + ZZ

julia> inv(CliffordOperator(sZCrY))
X₁ ⟼ + YY
X₂ ⟼ + ZX
Z₁ ⟼ + Z_
Z₂ ⟼ + ZZ

julia> inv(sZCrY(1, 2))
sInvZCrY on qubit1 (1,2)
X₁ ⟼ + YY
X₂ ⟼ + ZX
Z₁ ⟼ + Z_
Z₂ ⟼ + ZZ

julia> sZCrY(1, 2)
sZCrY on qubit1 (1,2)
X₁ ⟼ - YY
X₂ ⟼ + ZX
Z₁ ⟼ + Z_
Z₂ ⟼ + ZZ

julia> inv(sInvZCrY(1, 2))
sZCrY on qubit1 (1,2)
X₁ ⟼ - YY
X₂ ⟼ + ZX
Z₁ ⟼ + Z_
Z₂ ⟼ + ZZ

julia> sInvZCrY(1, 2)
sInvZCrY on qubit1 (1,2)
X₁ ⟼ + YY
X₂ ⟼ + ZX
Z₁ ⟼ + Z_
Z₂ ⟼ + ZZ
```
Note: 

`sInvZCrY `fails the following test 

https://github.com/QuantumSavory/QuantumClifford.jl/blob/59e399d17ddb1430482ed343d221680754b54bf0/test/test_symcliff.jl#L59-L60

so I have filtered it out for the moment so that there are not two many spam emails about failing tests. I am seeking your guidance on this. 

Hope my attempt is okay.

2024-07-26 07:30 UTC, Fe-r-oz commented
Removing the `CHANGELOG` to prevent any future merge conflicts. The assumption is that if the `CHANGELOG` is removed, then there would not be merge conflicts until the time of review arrives:

```
Changelog:
-  `inv` implementation for two-qubit "symbolic" Clifford operators (subtypes of `AbstractTwoQubitOperator`).

```

2024-08-03 18:49 UTC, Krastanov requested changes
This looks pretty good. Just some questions on tests.

2024-08-03 18:49 UTC, Krastanov commented on test/test_symcliff.jl
> +    for op in filter(x -> x != sInvZCrY, subtypes(QuantumClifford.AbstractTwoQubitOperator))
We should not exclude some gates from tests.

2024-08-03 18:49 UTC, Krastanov commented on test/test_symcliff.jl
> +    for gate_type in [sCNOT, sZCX, sZCY, sZCZ, sXCX, sXCY, sXCZ, sYCX, sYCY, sYCZ, sSWAP, sCPHASE, sZCrY, sInvZCrY]
this should just test all two-qubit gates by using `subtypes` as done above

2024-08-03 19:40 UTC, Fe-r-oz commented on test/test_symcliff.jl
> +    for gate_type in [sCNOT, sZCX, sZCY, sZCZ, sXCX, sXCY, sXCZ, sYCX, sYCY, sYCZ, sSWAP, sCPHASE, sZCrY, sInvZCrY]
The reason for that is that unlike `SingleQubitOperator`, we don't have a `TwoQubitOperator` subtype.

2024-08-03 19:42 UTC, Fe-r-oz commented on test/test_symcliff.jl
> +    for op in filter(x -> x != sInvZCrY, subtypes(QuantumClifford.AbstractTwoQubitOperator))
`sInvZCrY ` fails the following test:

```
 s = random_destabilizer(2) 
 @test sop*s == cop*s == tcop*s == ccop*s 
```

2024-08-03 20:02 UTC, Krastanov commented on test/test_symcliff.jl
> +    for gate_type in [sCNOT, sZCX, sZCY, sZCZ, sXCX, sXCY, sXCZ, sYCX, sYCY, sYCZ, sSWAP, sCPHASE, sZCrY, sInvZCrY]
There is, you have even used it in the other test. `AbstractTwoQubitOperator`

2024-08-03 20:03 UTC, Krastanov commented on test/test_symcliff.jl
> +    for op in filter(x -> x != sInvZCrY, subtypes(QuantumClifford.AbstractTwoQubitOperator))
That probably means that the implementation of `sInvZCrY` is wrong!

2024-08-03 20:03 UTC, Krastanov commented
Some of the fixes to this are in https://github.com/QuantumSavory/QuantumClifford.jl/pull/332

2024-08-03 20:28 UTC, Fe-r-oz commented on test/test_symcliff.jl
> +    for op in filter(x -> x != sInvZCrY, subtypes(QuantumClifford.AbstractTwoQubitOperator))
My bad. The implementation is wrong. Thanks to Tommy for the fix.

2024-08-03 20:45 UTC, thofma commented
I am not sure if mine is correct either. There was a test run, where the same test failed: https://github.com/QuantumSavory/QuantumClifford.jl/actions/runs/10230399157/job/28305153327.

2024-08-03 21:03 UTC, Fe-r-oz commented
Thanks, Tommy,  your fixes are correct!  I had messed phases calculation for `sZCrY `that was causing the error.

2024-08-03 21:10 UTC, Fe-r-oz commented
I think since the that test is random, it fails not occassionally twice here: https://github.com/QuantumSavory/QuantumClifford.jl/actions/runs/10230867371/job/28306163953?pr=315 and https://github.com/QuantumSavory/QuantumClifford.jl/actions/runs/10230867378/job/28306164119?pr=315

2024-08-03 21:20 UTC, Fe-r-oz commented on test/test_symcliff.jl
> +    for gate_type in [sCNOT, sZCX, sZCY, sZCZ, sXCX, sXCY, sXCZ, sYCX, sYCY, sYCZ, sSWAP, sCPHASE, sZCrY, sInvZCrY]
As you suggested, using `subtypes(AbstractTwoQubitOperator)` instead of naming alll the gates.

2024-08-03 23:07 UTC, Krastanov commented on test/test_symcliff.jl
> +end
these tests are not being executed (they are not within the testitem)

2024-08-03 23:08 UTC, Krastanov commented on test/test_noisycircuits.jl
> +    @testset "SparseGat" begin
SparseGate (typo)

2024-08-04 02:59 UTC, Fe-r-oz commented
After the fixes were applied from #332, the frequency of this test failing reduced from ALL to 2. 
 
```
 s = random_destabilizer(1)
Expression: sop * s == cop * s == tcop * s == ccop * s
   Evaluated: 𝒟ℯ𝓈𝓉𝒶𝒷
- Y_
+ _Z
𝒮𝓉𝒶𝒷
+ Z_
+ _X == 𝒟ℯ𝓈𝓉𝒶𝒷
+ Y_
+ _Z
𝒮𝓉𝒶𝒷
+ Z_
+ _X == 𝒟ℯ𝓈𝓉𝒶𝒷
+ Y_
+ _Z
𝒮𝓉𝒶𝒷
+ Z_
+ _X == 𝒟ℯ𝓈𝓉𝒶𝒷
+ Y_
+ _Z
𝒮𝓉𝒶𝒷
+ Z_
+ _X

```
During recent test run, it failed in [Downgrade](https://github.com/QuantumSavory/QuantumClifford.jl/actions/runs/10231734222/job/28307993731?pr=315)which caused the build to fail along with the other[ here](https://github.com/QuantumSavory/QuantumClifford.jl/actions/runs/10231734225/job/28307994111?pr=315). Problem seems to be one phase sign destab `(z1)`

2024-08-04 06:14 UTC, Fe-r-oz commented
Hi, Tommy, Your suspicion was correct! I really appreciate your comment. There was a tiny error in your fix which was that phases` (~iszero((x1 & z1 & ~ x2) | (x1 & z2))) `for `sInvZCrY` was causing a very few tests to fail. It was mostly correct with just one truthtable entry not accounted for! That is why we saw most tests pass and few (1 or 2) fail.

```
#The correct truthtable for InvZCrY
julia> for i in 0:15
                  s=S"YY//ZX//ZI//ZZ"
                  d=tuple(Bool.(digits(i,base=2,pad=4))...)
                  s[1,1]=d[1:2]
                  s[1,2]=d[3:4]
                  println("$(Int.(d)) $(phases(CliffordOperator(sInvZCrY)*s)[1]÷2)")
              end
(0, 0, 0, 0) 0
(1, 0, 0, 0) 0
(0, 1, 0, 0) 0
(1, 1, 0, 0) 1
(0, 0, 1, 0) 0
(1, 0, 1, 0) 0
(0, 1, 1, 0) 0
(1, 1, 1, 0) 0
(0, 0, 0, 1) 0
(1, 0, 0, 1) 1
(0, 1, 0, 1) 0
(1, 1, 0, 1) 1
(0, 0, 1, 1) 0
(1, 0, 1, 1) 0
(0, 1, 1, 1) 0
(1, 1, 1, 1) 1

# helper function
julia> # Define the transformations
       function transform(x1::Bool, x2::Bool, z1::Bool, z2::Bool)
           yy = x1 && x2  # Resulting YY term for X1
           zx = x2  # Resulting ZX term for X2
           z1_new = z1  # Z1 remains Z_
           zz = z2 && z2  # Resulting ZZ term for Z2
           return yy, zx, z1_new, zz
       end

transform (generic function with 1 method)

julia> function calculate_phases()
           for i in 0:15
               d = tuple(Bool.(digits(i, base=2, pad=4))...)
               x1, x2, z1, z2 = d[1], d[2], d[3], d[4]
               yy, zx, z1_new, zz = transform(x1, x2, z1, z2)
               
               # Use the simplified boolean formula for phase calculation
               phase = x1 && !z1 && (x2 || z2)

               println("$(Int.(d)) $(Int(phase))")
           end
       end
calculate_phases (generic function with 1 method)

julia> calculate_phases()
(0, 0, 0, 0) 0
(1, 0, 0, 0) 0
(0, 1, 0, 0) 0
(1, 1, 0, 0) 1
(0, 0, 1, 0) 0
(1, 0, 1, 0) 0
(0, 1, 1, 0) 0
(1, 1, 1, 0) 0
(0, 0, 0, 1) 0
(1, 0, 0, 1) 1
(0, 1, 0, 1) 0
(1, 1, 0, 1) 1
(0, 0, 1, 1) 0
(1, 0, 1, 1) 0
(0, 1, 1, 1) 0
(1, 1, 1, 1) 0 

# This last entry was skipped by the phase: ~iszero((x1 & z1 & ~ x2) | (x1 & z2)) . It skipped the last condition of truthtable.

julia> function correct_phase()
                 for i in 0:15
                     d = tuple(Bool.(digits(i, base=2, pad=4))...)
                     x1, z1, x2, z2 = d[1], d[2], d[3], d[4]
                     yy, zx, z1_new, zz = transform(x1, x2, z1, z2)
                     
                     # Use the simplified boolean formula for phase calculation in the form of ~iszero()
                     phase = ~iszero((x1 & z1 & ~x2 & ~z2) | (x1 & ~z1 & ~x2 & z2) | (x1 & z1 & ~x2 & z2) | (x1 & z1 & x2 & z2))

                     println("$(Int.(d)) $(Int(phase))")
                 end
             end
correct_phase (generic function with 1 method)

#correct phase
julia> correct_phase()
(0, 0, 0, 0) 0
(1, 0, 0, 0) 0
(0, 1, 0, 0) 0
(1, 1, 0, 0) 1
(0, 0, 1, 0) 0
(1, 0, 1, 0) 0
(0, 1, 1, 0) 0
(1, 1, 1, 0) 0
(0, 0, 0, 1) 0
(1, 0, 0, 1) 1
(0, 1, 0, 1) 0
(1, 1, 0, 1) 1
(0, 0, 1, 1) 0
(1, 0, 1, 1) 0
(0, 1, 1, 1) 0
(1, 1, 1, 1) 1
```

Hopefully, Now all the failed tests will not be related to `sZCrYInv`. `Downgrade`, and `build` passes.

2024-08-04 08:08 UTC, thofma commented
I think the error was that I tried to simplify it. Glad to hear that it works now.

2024-08-05 17:37 UTC, Krastanov approved these changes

2024-08-05 17:58 UTC, merged

2024-08-05 18:01 UTC, Krastanov commented
Thank you! You are added to the bounty list -- look out for an email towards the end of the month.