improvements to `apply!` and `dictvaltype`
QuantumSavory/QuantumClifford.jl pull request #346
Opened 2024-08-22 20:39 UTC by Fe-r-oz

Improving `dictvaltype` and `apply!`. 

If you want to submit an unfinished piece of work in order to get comments and discuss, please mark the pull request as a draft and ping the repository maintainer.

**Please address only one topic or issue per pull request! Many small PRs are much easier to review and merge than one large PR.**

Before merging, all changes and new functionality should be marked in the CHANGELOG file, but feel free to just leave your CHANGELOG notes in the PR description, to avoid merge conflicts with other requests modifying that file. The maintainer will add these CHANGELOG notes for you if you do so.

Before considering your pull request ready for review and merging make sure that all of the following are completed (please keep the clecklist as part of your PR):

- [x] The code is properly formatted and commented.
- [x] Substantial new functionality is documented within the docs.
- [x] All new functionality is tested.

If possible, keep your git history not too wild (rebase and squash commits, keep commits small and semantically separated) so that review is easier.

2024-08-22 21:00 UTC, Fe-r-oz commented
This pr implements a safe version of `apply!`

P.S. There is no `ref[]` due to which there was test error in non-cliff nonclifford quantum optics test branch. commented that out for a time being.

2024-08-22 21:17 UTC, Krastanov commented
Ah, this is great, much easier to work with! Thanks for setting it up this way. Now it is not even necessary to worry about squashing commits (mostly), because it is on top of another branch. Request a review whenever you feel it is ready.

Indeed, do not worry about the changelog check at all.

2024-08-23 06:01 UTC, Fe-r-oz commented
Please review!

2024-08-23 17:07 UTC, Krastanov commented
Hi, Feroz! Please be more careful with review requests -- here for instance you made a review request but then you continued making changes. It is better to wait a couple of days before making a review request to make sure you are done with your changes. Of course, this is not a big deal, especially if it happens just occasionally, however with your pull requests this is pretty common. Your contributions are appreciated, but reviewing is a significant investment of time, so I need to be selective when I start reviewing things.

2024-08-23 17:17 UTC, Fe-r-oz commented
Apologies for that. I really your time and your patience. Sorry for these annoying commits towards the very end.

2024-09-14 04:50 UTC, Krastanov requested changes
looks like a good start. I left in some initial comments

2024-09-14 04:50 UTC, Krastanov commented on test/test_nonclifford_quantumoptics.jl
> -        end
These tests should not be skipped. Do they run?

`ref[]=...` and `@show` can be deleted

2024-09-14 04:50 UTC, Krastanov commented on src/nonclifford.jl
> +        for ((Pₖ,Pₗ), w) in zip(gate.paulis, gate.weights) # the channel
Where do the names `k` and `l` come from? Are they just arbitrary indices? Previously they meant `left` and `right`. Either one is fine, just want to make sure I understand the naming convention

2024-09-14 04:50 UTC, Krastanov commented on src/nonclifford.jl
> +            end
What was actually changed here? It looks like just renaming without changing any of the formulas? I prefer to avoid such renaming for the sake of renaming as it makes looking through the git history more difficult (and it makes reviewing more difficult as I can not figure out whether there was a real change or just renaming)

2024-09-14 04:50 UTC, Krastanov commented on src/nonclifford.jl
>  end
this can altogether be deleted and `valtype` can be used directly in its place

2024-09-14 04:50 UTC, Krastanov commented on src/nonclifford.jl
> +julia> apply!(sm, CliffordOperator(sHadamard))
just use `tHadamard` instead of converting `sHadamard`

2024-09-14 04:50 UTC, Krastanov commented on src/nonclifford.jl
> +    end
just set that as the default value, no need to have `nothing` as an option

2024-09-14 04:50 UTC, Krastanov commented on src/nonclifford.jl
> +    end
i.e. `prune_threshold::Float64=nothing`

2024-09-14 04:50 UTC, Krastanov commented on src/nonclifford.jl
> +            if abs(χ′) >= prune_threshold
no need to do this twice. Remove this one and keep only the original pruning done outside of the loop

2024-09-14 05:50 UTC, Fe-r-oz commented on test/test_nonclifford_quantumoptics.jl
> -        end
Yup, all of these tests pass now that `expect` was was fixed. `expect `was after this, so at this moment in time I skipped it. But, now they all should pass!

2024-09-14 05:59 UTC, Fe-r-oz commented on src/nonclifford.jl
> +            end
Oh...,  I thought I had reverted back to the old convention. I will undo this.

2024-09-14 09:22 UTC, Fe-r-oz commented
Thank you, addressed all of your comments. I think it's ready for review.

2024-09-15 15:16 UTC, Krastanov requested changes
Almost there! Some minor cosmetic things left.

2024-09-15 15:16 UTC, Krastanov commented on src/nonclifford.jl
> +            newdict[(dᵢ′,dⱼ′)] = get!(newdict,(dᵢ′,dⱼ′),0)+χ′
Why is the `get!` necessary? I thought `DefaultDict` would just provide a `0` by "default".

2024-09-15 15:16 UTC, Krastanov commented on src/nonclifford.jl
> +function apply!(state::GeneralizedStabilizer, gate::AbstractPauliChannel; prune_threshold::Float64=1e-14)
We should not hardcode `Float64` here. The storage format might be different.

Also, let's me a bit more liberal and change the default to `1e-10`

2024-09-15 15:16 UTC, Krastanov commented on src/nonclifford.jl
> +apply!(state::GeneralizedStabilizer, gate::UnitaryPauliChannel; prune_threshold::Float64=1e-14) = apply!(state, gate.paulichannel; prune_threshold=prune_threshold)
```suggestion
apply!(state::GeneralizedStabilizer, gate::UnitaryPauliChannel; prune_threshold::Float64=1e-14) = apply!(state, gate.paulichannel; prune_threshold)
```

keyword arguments permit this short notation if the variable names match

2024-09-15 18:10 UTC, Fe-r-oz commented
Thank you for your suggestions. I think this is ready for review.

2024-09-27 03:35 UTC, merged

2024-09-27 03:35 UTC, Krastanov commented
Thanks!