Loc comm embed
QuantumSavory/QuantumClifford.jl pull request #351
Opened 2024-08-30 19:51 UTC by IsaacP1234

Adding logical_operator_canonicalize, commutavise, and embed functions, as well as SubsystemCodeTableau datastructure and minor performance improvements for groupify and normalizer.

2024-09-04 19:18 UTC, Krastanov commented
@IsaacP1234 , would it be possible to fix the merge conflicts before I proceed with a review?

2024-09-04 21:30 UTC, IsaacP1234 commented
Thank you for your explanation and solution Feroz.

@KDGoodenough when you get chance, could you fork the latest version of QuantumClifford and create a branch that I can fork as described by Feroz? I can also fork the repository myself if that would make more sense @Krastanov

2024-09-05 00:46 UTC, Krastanov commented
This is a bit roundabout and unnecessary.

Isaac, if you do not want to bother with git, just make a new branch from the latest master branch and copy over your code, make sure it is your latest implementation and submit a new PR.

If you prefer to do it the "proper way", make a new branch from the latest master branch and cherry pick ("cherrypick" is the name of a git command) the commits from this branch that you care about and submit a new PR.

Another "proper way" would be to go back to a clean commit of yours and use an interactive rebase. Your git history is a bit messy so this would probably be a bit difficult.

There is no need for Kenneth to make new forks of anything. If you do want to follow Feroz's suggested approach, all the branches and commits referred to in his post are public so you can do all the steps yourself. But that is just one out of many ways you can do this.

Lastly, you can also simply fix the merge conflicts here without doing cherrypicks or rebases or anything like that. The merge conflicts seem reasonably small, so this solution might be easiest.

2024-09-06 04:28 UTC, IsaacP1234 commented
Thank you, I resolved the conflicts here on Github. 

I will write a changelog when review is complete. 

Additionally, for the SubsystemCodeTableau datastructure, what should (de)stabilizerview and logicalx/zveiw return when their respective category is empty? For example, when the result of logical_operator_canaonicalize contains no operators that commute with all other operators, what should (de)stabilizerview return? Currently, I just have them return an n-qubit PauliOperator.

2024-09-06 04:39 UTC, KDGoodenough commented
For logical_operator_canonicalize, note there always exist one operator that commutes with everything, no matter the input --- the identity operator. For the other cases ((de)stabilizerview and logicalx/zview), one can make a similar argument, I believe.

2024-09-06 12:25 UTC, Krastanov commented
For the stabilizer part of the tableau (the part that commutes with the logical views), are you returning a generating set or all elements of the group? If it is a generating set, I would suggest keeping the same conventions as in `MixedDestabilizer` and just return a tableaux with zero rows:

```
julia> s = MixedDestabilizer(S"XX ZZ") # A full rank tableau
𝒟ℯ𝓈𝓉𝒶𝒷
+ Z_
+ _X
𝒮𝓉𝒶𝒷
+ XX
+ ZZ

julia> logicalxview(s)


julia> logicalxview(s) |> typeof
Stabilizer{QuantumClifford.Tableau{SubArray{UInt8, 1, Vector{UInt8}, Tuple{UnitRange{Int64}}, true}, SubArray{UInt64, 2, Matrix{UInt64}, Tuple{Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}}, true}}}

julia> length(logicalxview(s))
0

```

2024-09-08 00:39 UTC, IsaacP1234 commented
I think the tests are failing for reasons unrelated to my code. The Julia-1/Ubuntu tests fail when testing noisy circuits, which don't seem to overlap with my code, and the jet tests are classified as 'broken', but it doesn't seem like it involves my code based on the output. the Buildkite fails on the downstream tests on a test labeled "piracy", which also seems separate from my code. 

If any of these errors are related, let me know and I will fix them. If not, the code is ready for review.

2024-09-08 19:46 UTC, Krastanov requested changes
I did a quick first round of review. I have a couple of minor comments on the code, but most of my comments are on documentation. The implementation looks great, and it seems it will be pretty useful for Kenneth's work. Some work still to do on making sure that other people can use this by reading the documentation (maybe Kenneth can help with some of the docs).

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +represented.
I do not think `logical operator canonical form` is a known thing in the field. Could we document this a bit more, with definitions and explanations for why this is interesting and useful, maybe a few doctest examples?

Check with Kenneth on this, maybe ask him to help with the documentation for it.

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +    tab::Tableau
Parameterize the tableau type (same as MixedDestabilizer for instance), to ensure type information is not lost here.

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +end
```suggestion
    return SubsystemCodeTableau(tab, index, length(s), m, (index-1)/2)
end
```

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +Base.length(t::SubsystemCodeTableau) = length(t.tab)
Is this used somewhere? Given the complicated internal structure, I am reluctant to define a "homogenous" length function as I am not sure what it would mean semantically. If it is not used, let's delete it.

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +end
No need to repeat the docstrings. Each one of these functions already has a docstring. Here you are defining new methods for these pre-existing functions. If the methods are novel or differing in some way, it makes sense to add new docstrings, bug given that these are just repeats of the already existing docstrings, they are not needed.

The help file will already give you the docstrings defined earlier.

You can just remove all four docstrings here.

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
>  end
Why is this changed? What would it have done before/after the change?

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +-iX_
The presence of an `i` phase is very suspicious to me. A @KDGoodenough , could you check if this is correct?

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +julia> tab(logical_operator_canonicalize(QuantumClifford.Tableau([P"XX", P"XZ", P"XY"])))
we should just make `Tableau` and `T_str` public. The documentation should not refer to code and structures that are not public, so if this is necessary for your example, we should consider exporting the appropriate symbols.

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +<A₁, B₁, A₂, B₂, ... Aₖ, Bₖ, Aₖ₊₁, ... Aₘ> where two operators anticommute if and only if they
The order of operators does not seem correct anymore

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +Returns the generating set as a data structure of type [`SubsystemCodeTableau`](@ref).
Mention the four different view functions that can be used to access this structure

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +    loc = QuantumClifford.logical_operator_canonicalize(t)
```suggestion
    loc = logical_operator_canonicalize(t)
```

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +as well as return a list of the indices of the added qubits.
Could you significantly expand this into multiple sentences and definitions? Currently, it is one long sentence and it is pretty difficult to understand.

Could you also add a comment on what this is useful for? Is there a reference for this? Probably check with Kenneth about documenting it a bit more.

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +function commutavise(t)
mentioned elsewhere as well, but let's bikeshed the name a bit. Currently it is not very clear what it means and whether there is a precedent for this name (precedent is not necessary, but it helps)

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +        ind+=1
Why do you need the `dummy`? I think the following two are equivalent:

```
dummy[j] = ...
```

```
commutative[ind, j] = ...
```

More generally though, I have the impression that a lot of this code (at least all of the inner loops) can be replaced with just 4 calls to `puttableaux!`: https://github.com/QuantumSavory/QuantumClifford.jl/blob/e51a142d8c6b8300cfa1b417b677c7e349a1bb0b/src/project_trace_reset.jl#L746

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +function embed(t::QuantumClifford.Tableau)
needs a different name, check with Kenneth as well

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +julia> embed(QuantumClifford.Tableau([P"XX"]))[1]
making Tableau public (and just using the `T` macro)

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +second returned array from the normalizer, the original set is produced.
Add references to the related functions which you are talking about (e.g. commutavise).

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +second returned array from the normalizer, the original set is produced.
This is a bit difficult to follow. Could you rewrite it with shorter sentences and fewer pronouns/references ("original set", "returned array", etc are pretty difficult to follow). Maybe introduce names / letters and some definitions.

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +    state, d2 = QuantumClifford.commutavise(norm)
```suggestion
    com, d1= commutavise(t)
    norm = normalizer(com.tab)
    state, d2 = commutavise(norm)
```

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +but can be included by setting `phases = true`.
```suggestion
but can be included by setting `phases=true`.
```

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +    return QuantumClifford.Tableau(norm)
```suggestion
    return Tableau(norm)
```

2024-09-08 19:46 UTC, Krastanov commented on test/test_group_tableaux.jl
>              s_test = copy(s)
@KDGoodenough , could you check that this file makes sense (the test file)?

2024-09-08 19:46 UTC, Krastanov commented on src/grouptableaux.jl
> +    loc = zero(QuantumClifford.Tableau, length(t), nqubits(t))
```suggestion
function logical_operator_canonicalize(t:: Tableau)
    loc = zero(Tableau, length(t), nqubits(t))
```

2024-09-09 02:54 UTC, IsaacP1234 commented on src/grouptableaux.jl
>  end
If groupify is given a non-minimal generating set of length k, finding the minimal generating set of length n and then finding the full group of length 2^n lets the function create a tableau of length 2^n rather than 2^k and then deleting excess rows, saving a lot of allocation time as n <k.

2024-09-09 02:58 UTC, IsaacP1234 commented on src/grouptableaux.jl
> +-iX_
This is happening because the function multiplies `PauliOperators` together to reduce anticommutivity. resulting in i phases when Paulis like `XXY` and `XXZ` are multiplied together. If desired, I can eliminate these `i` phases from the final output.

2024-09-10 12:46 UTC, Krastanov commented on src/QuantumClifford.jl
> +    logical_operator_canonicalize, commutavise, embed, SubsystemCodeTableau,
let's use the following name for `logical_operator_canoninicalize` to keep in similar to the other canonicalize methods we have:

```
canonicalize_noncomm
```

2024-09-10 12:56 UTC, Krastanov commented on src/QuantumClifford.jl
> +    logical_operator_canonicalize, commutavise, embed, SubsystemCodeTableau,
let's, for now, change commutavise to `commutify` to keep it in sync with simplify or lambdify or sympify

2024-09-12 02:34 UTC, IsaacP1234 commented on src/grouptableaux.jl
> +as well as return a list of the indices of the added qubits.
It is used in the 'matroid_parent' function. By comment, do you mean as a comment in the code or a line in the documentation?

2024-09-12 02:40 UTC, IsaacP1234 commented
@KDGoodenough I have rewritten the documentation for `canonicalize noncomm`, `commutify`, and `matroid_parent` to be more clear, but is there anything about the functions or the theory behind them that I should include in the documentation?

2024-09-12 12:25 UTC, Krastanov commented on src/grouptableaux.jl
> +as well as return a list of the indices of the added qubits.
In the docs. And in terms of use, do mention `matroid_parent` but more generally mention why one would use it in principle.

2024-09-12 12:26 UTC, Krastanov commented on test/test_group_tableaux.jl
>              s_test = copy(s)
oh, no need to make Tableau public then, but in various examples switch to `@T_str` instead of the more complicated construction of Tableau that you are using.

2024-09-15 20:53 UTC, IsaacP1234 commented
I think I have completed all the requested changes, but I am not aware of more uses of `commutify` aside from `matroid parent` to add to its documentation. @KDGoodenough are there any I should add?

Additionally, should I add the newly-referenced papers to references.md?

2024-09-16 05:25 UTC, KDGoodenough commented
@IsaacP1234 I think it's good like this! There's not too much work (yet!) that uses this commutify business. My guess would be that yes, it would be good to add these references to the .md file as well, but Stefan would know better.

2024-09-16 23:57 UTC, IsaacP1234 commented
Changelog: 

- New error correction tools:
     - `canonicalize_noncomm` function to find a generating set with minimal anticommutivity
     - `SubsystemCodeTableau` data structure to represent the output of `canonicalize_noncomm`
     - `commutify` function to find a commutative version of a non-commutative set of Paulis with 
     minimal changes
     - `matroid_parent` function to, for set of Paulis that doesn't represent a state, find a version 
     that does.

2024-09-27 20:17 UTC, Krastanov requested changes
Finally got around to reviewing this. Thank you for all these additions and apologies for the long delay.

First, I made a few changes myself, but either github is having its usual reliability problems or you have set some security features a bit higher and I can not push to your branch.

Before you continue, could you please make sure that you pull the changes from this branch: https://github.com/QuantumSavory/QuantumClifford.jl/tree/loc-comm-embed

I tried to make each commit small and self-explanatory -- please check the commits I have added one-by-one to see why they were added.

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +function SubsystemCodeTableau(t::Tableau)
Why is this constructor necessary? It is a pretty expensive one. Should this not be a part of the `canonicalize_noncomm` function itself.

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +Base.copy(t::SubsystemCodeTableau) = SubsystemCodeTableau(copy(t.tab))
This is a very expensive way to make a copy as you are redoing a ton of computation. It would be better if this just copies over the various indices as well.

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +                group[i+1] *= gen_set[digit_order]
`mul_left!(group, gen_set, i+1, digit_order)` would be drastically faster (it will be in-place, avoiding a lot of allocations).

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +-iX_
yup, let's just remove the phases

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +                            t[k] = t[j] *t[k]
`mul_left!`

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +                            t[k] = t[i] *t[k]
`mul_left!`

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +                            t[k] = t[j] *t[k]
with `phases=false`

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +                            t[k] = t[i] *t[k]
with `phases=false`

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +julia> tab(canonicalize_noncomm(T"XX XZ XY"))
add a show method like for MixedDestabilizer so we do not need to call `tab`

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +                group[i+1] *= gen_set[digit_order]
By the way, does this function work correctly if there are terms with non-trivial phases?

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +                if !(t[i] in loc || -1 *t[i] in loc || 1im *t[i] in loc || -1im * t[i] in loc)
This will probably be extremely slow (especially the phase modification and check... maybe zero out all the phases at the very start to not worry about this). That way it can be one single check instead of 4.

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +                if !(t[j] in loc || -1 *t[j] in loc || 1im *t[j] in loc || -1im * t[j] in loc)
same comment about cost of check

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +    return SubsystemCodeTableau(loc)
Can you give the constructor more information so it does not run all that expensive processing and searching?

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +    to_delete = []
something more like `nqubits+1:nqubits+k` would be much simpler and faster

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +1-element Vector{Any}:
these should be ranges or vectors of ints, not vectors of any

2024-09-27 20:17 UTC, Krastanov commented on src/grouptableaux.jl
> +Any[]
these should be ranges or vectors of ints, not vectors of any

2024-09-27 20:28 UTC, Krastanov commented
by the way, to verify my claims about speed, you can use `BenchmarkTools` and the `@benchmark` macro

2024-09-30 18:35 UTC, IsaacP1234 commented on src/grouptableaux.jl
> +                group[i+1] *= gen_set[digit_order]
If there are non-real phases it doesn't work because it uses `minimal_generating_set` which only accepts real phases. Should I rework it to work with imaginary phases or specify in the docs that it only accepts real phases?

2024-09-30 19:11 UTC, IsaacP1234 commented on src/grouptableaux.jl
> +                group[i+1] *= gen_set[digit_order]
Additionally, there doesn't seem to be any method of `mul_left!` that can multiply a single row of a `Tableau` or `Stabilizer` by a Pauli. Just indexing doesn't change the original structure.

2024-10-02 04:29 UTC, Krastanov commented on src/grouptableaux.jl
> +                group[i+1] *= gen_set[digit_order]
just writing down what we discussed in the call: just add a kwargument phases=false, and throw an error if someone tries to run phases=true with some message about it not being implemented

For `mul_left!` could you please just add a new method for it, basically just making a second more general version of this one in the same file https://github.com/QuantumSavory/QuantumClifford.jl/blob/4e06c0184a6ccef4894bb3790310ce84cd6a54f5/src/mul_leftright.jl#L166

I think it would be just
```
@inline function mul_left!(s::Tableau, m, t::Tableau, i; phases::Val{B}=Val(true)) where B
    extra_phase = mul_left!((@view s.xzs[:,m]), (@view t.xzs[:,i]); phases=phases)
    B && (s.phases[m] = (extra_phase+s.phases[m]+s.phases[i])&0x3)
    s
end
```
and then do `tab(stabilizer)` wherever you call it

2024-10-25 02:46 UTC, merged

2024-10-25 02:47 UTC, Krastanov commented
Finally merged! Thanks so much!