Bug fix to StackOverflowError for `md ⊗ S"X"` where `typeof(md)` is `MixedDestabilizer{...}`
QuantumSavory/QuantumClifford.jl pull request #354
Opened 2024-09-07 07:37 UTC by Fe-r-oz

With this fix, `sm ⊗ S"X"`  from #260 will be added without any worry of StackOverflow error.

- [x] The code is properly formatted and commented.
- [x] Substantial new functionality is documented within the docs.
- [x] All new functionality is tested.
- [x] All of the automated tests on github pass.

_P.S. Pondering about more tests for this._

Local Output w.r.t Task 4.
```
     Testing Running tests...
skipping gpu tests (set GPU_TESTS=true to test gpu)
Starting tests with 1 threads out of `Sys.CPU_THREADS = 4`...
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: running doctests.
[ Info: Skipped ExpandTemplates step (doctest only).
[ Info: Skipped CrossReferences step (doctest only).
[ Info: Skipped CheckDocument step (doctest only).
[ Info: Skipped Populate step (doctest only).
[ Info: Skipped RenderDocument step (doctest only).
WARNING: using LinearAlgebra.I in module QuantumClifford conflicts with an existing identifier.
Skipping Base.active_repl
Skipping Base.active_repl_backend
Test Summary: |   Pass   Total     Time
Package       | 285936  285936  7m19.9s
     Testing QuantumClifford tests passed 
```

2024-09-07 08:06 UTC, Fe-r-oz commented
Tasks Completed:

- [x] MixedDestabilizer ⊗ Stabilizer: `md ⊗ S"X"`
- [x] Stabilizer ⊗ MixedDestabilizer:` S"X" ⊗ md`

2024-09-08 07:22 UTC, Fe-r-oz commented
I think it is correct to say the resulting `MixedDestabilizer` resulting from ` md ⊗ S"X`" should pass the `mixed_destab_looks_good` to ensure a consistent `MixedDestabilizer`.

2024-09-14 06:14 UTC, Krastanov requested changes
Half of this is on the correct path, but the other half presents complication we can avoid. Look into `promote_rule` if you would like to complete this PR.

2024-09-14 06:14 UTC, Krastanov commented on src/linalg.jl
> +    return foldl(⊗, conv_ops)
I do not realy understand what this does. The `promote_type` and `convert` don't do anything because everything defaults to `AbstractStabilizer`:

```
julia> promote_type(typeof(S"X"), typeof(MixedDestabilizer(S"X")))
QuantumClifford.AbstractStabilizer

julia> convert(QuantumClifford.AbstractStabilizer, S"X") |> typeof
Stabilizer{QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}}

julia> convert(QuantumClifford.AbstractStabilizer, MixedDestabilizer(S"X")) |> typeof
MixedDestabilizer{QuantumClifford.Tableau{Vector{UInt8}, Matrix{UInt64}}}
```

2024-09-14 06:14 UTC, Krastanov commented on src/linalg.jl
> +    return foldl(⊗, conv_ops)
Yeah, this modification here is not affecting anything yet, because `promote_rule` is not defined. The change is not bad, it should be kept, but one needs to define a `promote_rule` first

2024-09-14 06:14 UTC, Krastanov commented on src/linalg.jl
> +tensor(s::Stabilizer, md::MixedDestabilizer) = tensor(md, s)
These are unnecessary (and not scalable as solutions because we need them for all other types of state objects).

Instead of this, one just needs to define promote rules.

2024-09-14 22:57 UTC, Fe-r-oz commented
Thank you, `promote_rule`  was very helpful. Addressed all of your comments.

I think the PR is ready for review.

2024-09-15 15:28 UTC, Krastanov requested changes
There are some conceptual errors here about how to convert between different representations -- they are pretty fundamental to what each of the types actually means.

I also suggested a few simplifications.

2024-09-15 15:28 UTC, Krastanov commented on src/QuantumClifford.jl
> +Base.convert(::Type{<:Stabilizer{T}}            , x::MixedStabilizer{T}        ) where {T<:Tableau} = Stabilizer(tab(x))
This would result in a nonsense object -- a stabilizer with non-commuting rows

2024-09-15 15:28 UTC, Krastanov commented on src/QuantumClifford.jl
> +Base.promote_rule(::Type{<:MixedDestabilizer{T}},  ::Type{<:MixedStabilizer{T}}) where {T<:Tableau} = MixedDestabilizer{T}
I do not agree with many of these rules. A MixedStabilizer can not be converted to Stabilizer.

From special to general the conversions would be (missing a lot of type parameterizations):

```
Stabilizer, T<:Union{MixedStabilizer, Destabilizer, MixedDestabilizer} -> T
Destabilizer, MixedDestabilizer -> MixedDestabilizer
MixedStabilizer, MixedDestabilizer -> MixedDestabilizer
```

2024-09-15 15:28 UTC, Krastanov commented on src/linalg.jl
> +- __ZX
A lot of these examples are repetitive without much pedagogical value. Doctests should be good documentation (that happens to be tested for correctness), not unit tests. These make more sense as actual unit tests.

2024-09-15 15:28 UTC, Krastanov commented on src/QuantumClifford.jl
> +Base.convert(::Type{<:MixedDestabilizer{T}}     , x::MixedStabilizer{T}        ) where {T<:Tableau} = MixedDestabilizer(Stabilizer(tab(x)))
All of these `convert`s can be implemented as something much simpler, e.g. `convert(::T, x::AbstractStabilizer) where {T<:Type{S}, S<:AbstractStabilizer} = S(x)` because we already have the constructors implemented. I probable screwed up some of the type syntax or names of types, but this is the rough idea.

2024-09-15 15:49 UTC, Fe-r-oz commented on src/QuantumClifford.jl
> +Base.promote_rule(::Type{<:MixedDestabilizer{T}},  ::Type{<:MixedStabilizer{T}}) where {T<:Tableau} = MixedDestabilizer{T}
Thank you, I agree with you.  I will remove the nonsensical rules. Also, incorporate your last comment about not missing the type parameterizations. 

`tensor(MixedStab(...), S"X")` causes stack overflow error if a user wants to cause it, so most of the nonsensical rules were to avoid the stack overflow errors. But yeah, they result in nonsense objects which I completely overlooked. Sorry about that.

2024-09-17 09:09 UTC, Fe-r-oz commented on src/QuantumClifford.jl
> +Base.promote_rule(::Type{<:MixedDestabilizer{T}},  ::Type{<:MixedStabilizer{T}}) where {T<:Tableau} = MixedDestabilizer{T}
Thank you very much for `special to general` conversions https://github.com/QuantumSavory/QuantumClifford.jl/pull/354#discussion_r1760077101, I have added them as instructed.

2024-09-17 14:20 UTC, Fe-r-oz commented
Thank you, my previous attempt was just so bad... I have removed all the nonsense and incorporated your comments. Specifically, I have revamped the promote rules based of your description.  I had some complication using `Base.convert(::Type{S}, x::AbstractStabilizer) where {S <: AbstractStabilizer} = S(x.tab)` because the `MixedStab` and` MixedDestab` requires `rank` parameter as well.  I simplified convert following the spirit of simplification as well.

Hopefully, this attempt is satisfactory and less awkward.

2024-09-27 03:59 UTC, merged

2024-09-27 03:59 UTC, Krastanov commented
Thank you!