Lifted and lifted product codes via Hecke's GroupAlgebra
QuantumSavory/QuantumClifford.jl pull request #356
Opened 2024-09-09 16:12 UTC by royess

This PR aims to provide lifted and lifted product code construction.

Compared with the previous approach #312, the group algebra (or, group ring) functionality is replaced with the one provided by Hecke, which would benefit the maintenance. I have made the Hecke-dependent codes as an extension, named `QuantumCliffordHeckeExt`.

During implementation, there are the following adjustments concerning other parts of the repository:
1. I have made changes to handle redundancy in parity checks. Previously, it was assumed in many places that `code_n == code_k + code_s`. This holds if the parity-check matrix does not have redundant rows. But with redundancy, as usually the cases for lifted product codes, this does not hold and will cause problems.
2. I have relaxed some code property checks, also related to the redundancy.

Besides, when building circuits from subcircuits, I replace list unpacking with `vcat` because the former will trigger promotion errors when the number of gates gets large.

2024-09-09 20:55 UTC, Fe-r-oz commented
Hi, please have a look at the classical Lifted Product codes [here](https://esabo.github.io/CodingTheory/dev/Tutorials/Weight%20Reduction/#Lifted-Products): They are also constructed using Oscar Framework. Maybe adding a test of canonical equivalence of parity check matrices generated by these two constructors can serve as a useful correctness check. There are `Generealized bicycle`, `Hyperbicycle` etc. codes [here](https://esabo.github.io/CodingTheory/dev/Quantum/product_codes/) in `CodingTheory.jl` as well.  Maybe they can also serve as useful correctness tests. I have also referred (above) to a tested implementation of BBQLDPC codes which can also serve as a correctness check as well. Hope you will find these comments useful.

2024-09-10 02:00 UTC, royess commented
@Krastanov I made some small changes to make the tests pass. I think it is now ready for review. Thank you!

2024-09-14 04:57 UTC, Krastanov requested changes
I have not had time to make an actual review, but here are a couple of quick comments.

2024-09-14 04:57 UTC, Krastanov commented on Project.toml
> +QuantumCliffordHeckeExt = ["AbstractAlgebra", "Hecke"]
This means that the user needs to import both `AbstractAlgebra` and `Hecke` for things to work. Given that `AbstractAlgebra` is already a dependency due to Nemo, I thing it is best to just add it as an explicit dependency (so that users can access the codes just by typing `using Hecke`)

2024-09-14 04:57 UTC, Krastanov commented on src/ecc/codes/lifted_product.jl
> +    ext = Base.get_extension(QuantumClifford, :QuantumCliffordHeckeExt)
You do not need to make such a check here. Just make sure that your extension adds a new method to `QuantumClifford.ECC.two_block_group_algebra_codes`.

The trick done here is necessary only for structures and their constructors, not for functions.

2024-09-15 08:19 UTC, royess commented
Thanks for your comments! I have made them fixed.

2024-09-26 21:24 UTC, merged

2024-09-26 21:25 UTC, Krastanov commented
Congrats on the merge! This is pretty awesome work.