noncliff: fixes jet errors
QuantumSavory/QuantumClifford.jl pull request #362
Opened 2024-09-17 17:45 UTC by Fe-r-oz

This PR aims to make sure there are no JET caused by `nonclifford.jl`. There were 3 JET masquerading as 1 JET error caused by using `zip(pc.paulis, pc.weights)` in three `for` loops related to `PauliChannel`.  The fix does remove these JET errors, I have cross verified it running JET. 

- [x] The code is properly formatted and commented.
- [x] Substantial new functionality is documented within the docs.
- [x] All new functionality is tested.
- [x] All of the automated tests on github pass.

2024-09-26 21:36 UTC, Krastanov requested changes
Thanks for this! Could you rebase it? There have been other changes to these files (e.g. currently the error count is 11 and Nemo and AbstractAlgebra are already excluded) so it is pretty difficult to know what is happening here.

2024-09-26 21:44 UTC, Fe-r-oz commented
This is the noncliff branch and the 11 JET errors changes have not been introduced to the noncliff branch. The noncliff branch is behind the master branch. I am kind of confused with the rebase.

2024-09-27 00:11 UTC, Krastanov commented
ah, you are right, that makes sense. Disregard the rebase if it is causing troubles

2024-09-27 00:36 UTC, Fe-r-oz commented
Thanks. The rebase didn't changed the src code, just jet count from 25 to 24.

2024-09-27 02:20 UTC, merged

2024-09-27 02:20 UTC, Krastanov commented
thanks!