Haah's cubic code using abelian group ℤ₃ˣ³ via Hecke's Group Algebra
QuantumSavory/QuantumClifford.jl pull request #388
Opened 2024-10-10 20:49 UTC by Fe-r-oz

This PR aims to implement Haah's cubic code, a cousin of Generalized Bicycle code as mentioned in https://errorcorrectionzoo.org/c/generalized_bicycle.

- [x] The code is properly formatted and commented.
- [x] Substantial new functionality is documented within the docs.
- [x] All new functionality is tested.
- [x] All of the automated tests on github pass.
- [ ] We recently started enforcing formatting checks. If formatting issues are reported in the new code you have written, please correct them. <small>There will be plenty of old code that is flagged as we are slowly transitioning to enforced formatting. Please do not worry about or address older formatting issues -- keep your PR just focused on your planned contribution.</small>

2024-10-11 09:27 UTC, Fe-r-oz commented
I think this is ready for review, @krastanov. Thanks!

Brief context: For GB codes , `n%l+1` is used for GroupAlgebra (GA) indexing to indicate the cyclic nature for single cyclic group. This is same as doing  `n%dim(GA)+1.` This works as here, we have a single cyclic group of order l, so total order is l which can be acquired using `dim(GA)`.  

In Haah cubic code case, the total order is `l³`, hence using `n%dim(GA)+1` is appropriate since `dim(GA)` would give `l³` because here, direct product of three cyclic groups ( `total order = lxlxl`) is the requirement. Also, The CI errors are unrelated to this PR.

2024-11-05 13:20 UTC, Krastanov requested changes
Another great addition, thank you! I left in a few comments.

2024-11-05 13:20 UTC, Krastanov commented on ext/QuantumCliffordHeckeExt/lifted_product.jl
> +Haah’s cubic codes [haah2011local](@cite) can be viewed as GB codes
```suggestion
Haah’s cubic codes [haah2011local](@cite) can be viewed as generalized bicycle (GB) codes
```

2024-11-05 13:20 UTC, Krastanov commented on ext/QuantumCliffordHeckeExt/lifted_product.jl
> +```
see also: bicycle_codes, generalized_bicycle_codes

2024-11-05 13:20 UTC, Krastanov commented on ext/QuantumCliffordHeckeExt/lifted_product.jl
> +function Haah_cubic_codes(a_shifts::Array{Int}, b_shifts::Array{Int}, l::Int)
```suggestion
function haah_cubic_codes(a_shifts::Array{Int}, b_shifts::Array{Int}, l::Int)
```

a bit on the fence about this change, but it seems more consistent with other naming conventions in the library

2024-11-05 13:46 UTC, Fe-r-oz commented
The CI is failing on master due to this: 

https://github.com/QuantumSavory/QuantumClifford.jl/blob/45e9f4d64c902ba95ae5bedc1e59895f552147c4/ext/QuantumCliffordHeckeExt/lifted_product.jl#L253-L256

This was fixed with the the see also.

2024-11-05 14:57 UTC, Krastanov commented
> The CI is failing on master due to this:
> 
> https://github.com/QuantumSavory/QuantumClifford.jl/blob/45e9f4d64c902ba95ae5bedc1e59895f552147c4/ext/QuantumCliffordHeckeExt/lifted_product.jl#L253-L256
> 
> This was fixed with the the see also.
> 
> Edit: It seems that theCI is not failing due to the extra spaces, I thought it would cause error when checking docstring.

that fix is still nice to have!

I think it is failing because there are still a few spots with the old capitalization of the name of the code

2024-11-05 15:25 UTC, Krastanov commented
marking as draft to make it easier for me to track what needs review

2024-11-05 16:31 UTC, Fe-r-oz commented
The PR is ready for review. Thank you! 

It was indeed the old capitalization in some places that was causing the CI  errors.

2024-11-05 16:41 UTC, Krastanov commented on ext/QuantumCliffordHeckeExt/lifted_product.jl
> +julia> c = Haah_cubic_codes([0, 15, 20, 28, 66], [0, 58, 59, 100, 121], 6);
```suggestion
julia> c = haah_cubic_codes([0, 15, 20, 28, 66], [0, 58, 59, 100, 121], 6);
```

2024-11-05 17:08 UTC, merged