add missing method for two-block group algebra (2BGA) codes
QuantumSavory/QuantumClifford.jl pull request #389
Opened 2024-10-14 08:00 UTC by Fe-r-oz

This PR aims to add the missing method for the two-block group codes. Reference Table 1: https://arxiv.org/pdf/2306.16400. I have verified all the appropriate code instance using this new method as well. I have created a test file for this as well. 

@royess, just pinging you for reference. 

Also, there was a typo, 2GBA was used, instead of 2BGA, fixed this as well.

- [x] The code is properly formatted and commented.
- [x] Substantial new functionality is documented within the docs.
- [x] All new functionality is tested.
- [x] All of the automated tests on github pass.
- [x] We recently started enforcing formatting checks. If formatting issues are reported in the new code you have written, please correct them. <small>There will be plenty of old code that is flagged as we are slowly transitioning to enforced formatting. Please do not worry about or address older formatting issues -- keep your PR just focused on your planned contribution.</small>

2024-10-14 09:18 UTC, Fe-r-oz commented
This is good to go from my POV @Krastanov

P.S. The failing tests are unrelated to this PR.

2024-10-14 10:47 UTC, royess commented
I think there is already a `generalized_bicycle_codes` that does exactly the same thing. So I do not get the point why we need this.

2024-10-14 11:08 UTC, Fe-r-oz commented
Oh... My bad. I knew this fact, but somehow overlooked it because working on two separate things simultaneously.

Rebased this PR  fixing the typo and verifying the test cases from aforementioned paper. Thanks.

2024-11-05 04:02 UTC, Krastanov requested changes
This is a great addition, thank you! I am a bit confused about where it is placed. Would it not make more sense in `generalized_bicycle_codes`?

2024-11-05 04:02 UTC, Krastanov commented on test/test_ecc_2bga.jl
> +end
I am a bit confused: these are "generalized_bicycle_codes". Shouldn't the test file be called "test_ecc_generalized_bicycle_codes.jl"?

2024-11-05 04:02 UTC, Krastanov commented on ext/QuantumCliffordHeckeExt/lifted_product.jl
> +
This seems like a docstring that should go in the function `generalized_bicycle_codes`, not in `two_block_group_algebra_codes`

2024-11-05 07:04 UTC, Fe-r-oz commented on test/test_ecc_2bga.jl
> +end
You are right.

2024-11-05 07:06 UTC, Fe-r-oz commented on ext/QuantumCliffordHeckeExt/lifted_product.jl
> +
You are right. Let's put in docstring of BG codes.

In addition, GB codes are a subset of only abelian 2BGA codes. 2BGA codes are formed by a general, finite group. Also, this test is rather relaxed in a sense that this is not a test for 2BGA codes, only abelian version of 2BGA and also because the original paper used small groups to create 2BGA codes which is done in https://github.com/QuantumSavory/QuantumClifford.jl/pull/406, and this is more like a subset test for GB codes.

2024-11-05 13:14 UTC, merged