implement Bivaraite Bicycle codes as subset of 2BGA
QuantumSavory/QuantumClifford.jl pull request #399
Opened 2024-10-21 07:47 UTC by Fe-r-oz

This PR implements the Bivaraite Bicycle code as subset of 2BGA codes. This is canonically equivalent to #372. This is the third construction method for these codes.

- [x] The code is properly formatted and commented.
- [x] Substantial new functionality is documented within the docs.
- [x] All new functionality is tested.
- [x] All of the automated tests on github pass.
- [x] We recently started enforcing formatting checks. If formatting issues are reported in the new code you have written, please correct them. <small>There will be plenty of old code that is flagged as we are slowly transitioning to enforced formatting. Please do not worry about or address older formatting issues -- keep your PR just focused on your planned contribution.</small>

2024-10-21 10:09 UTC, Fe-r-oz commented
This PR is ready for review @Krastanov, Thank you!

Tasks Completed:

- [x]  `bivariate_bicycle_codes`  API
- [x] Documentation and Docstring
- [x] Testing via `test_ecc.jl` that calls all other tests such as `test_decoder_all_setups.jl`
- [x] Reproducing three different tables from 3 separate papers 

After this PR is finished, I will add a canonical equivalence test to #372 using the `bivariate_bicycle_codes` API defined here to test the following: ` BB using LP code as parent == BB using 2BGA code as parent. ` They both are equivalent.
```mermaid
graph TD
    subgraph A[LP]
        B[2BGA]
        subgraph B[2BGA]
            C[BB]
        end
    end
```

2024-10-29 07:34 UTC, Fe-r-oz commented on ext/QuantumCliffordHeckeExt/lifted_product.jl
> +function bivariate_bicycle_codes(A::Vector{GroupAlgebraElem{FqFieldElem, GroupAlgebra{FqFieldElem, FinGenAbGroup, FinGenAbGroupElem}}}, B::Vector{GroupAlgebraElem{FqFieldElem, GroupAlgebra{FqFieldEle
We can make this more readable as follows:

```
function bivariate_bicycle_codes(A::VectorGroupAlgebraElem, B::VectorGroupAlgebraElem, GA::FqFieldFinGenAbGroupElemGroupAlgebra)
```
by defining these `const` types `VectorGroupAlgebraElem` and `FqFieldFinGenAbGroupElemGroupAlgebra` in `types.jl`.

2024-11-05 04:26 UTC, Krastanov requested changes
This is probably the addition I am most excited about of the ones I reviewed today. Thank you for looking into it. I have a question about the API design choices.

2024-11-05 04:26 UTC, Krastanov commented on ext/QuantumCliffordHeckeExt/lifted_product.jl
> +julia> A = [x^3 , y^10 , y^17];
why write this down as `[x^3 , y^10 , y^17]` instead of `x^3 + y^10 + y^17` and use directly `two_block_group_algebra_codes`? What is the advantage of the list notation?

2024-11-05 06:43 UTC, Krastanov commented on ext/QuantumCliffordHeckeExt/lifted_product.jl
> +end
a followup on my previous question: if now this is all that is needed, why even have a separate function, why not just have `two_block_group_algebra_codes` and add this as yet another example in the docstring, similar to the other PRs you have on this family of codes

I might be wrong, maybe there is some benefit to keeping a separate function for this class of codes, but such a separate function would need something "special" when compared to `two_block_group_algebra_codes`

2024-11-05 06:48 UTC, Fe-r-oz commented on ext/QuantumCliffordHeckeExt/lifted_product.jl
> +julia> A = [x^3 , y^10 , y^17];
You are right. For regular abelian groups via Hecke's group algebra, we can use the list notation.

The advantage of list notation is when using finitely presented groups from Oscar with specific group presentations which is not related to this PR. 

```
julia> b_elts = 1 +  s + r^6 +  s^3 * r + s * r^7 +  s^3 * r^5;
ERROR: MethodError: no method matching +(::Int64, ::FPGroupElem)
The function `+` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:596
  +(::Oscar.StraightLinePrograms.Lazy, ::Any)
   @ Oscar ~/.julia/packages/Oscar/2lR8w/src/StraightLinePrograms/lazy.jl:98
  +(::Any, ::Oscar.StraightLinePrograms.Lazy)
   @ Oscar ~/.julia/packages/Oscar/2lR8w/src/StraightLinePrograms/lazy.jl:99
  ...

Stacktrace:
 [1] +(::Int64, ::FPGroupElem, ::FPGroupElem, ::FPGroupElem, ::FPGroupElem, ::FPGroupElem)
   @ Base ./operators.jl:596
 [2] top-level scope
   @ REPL[9]:1
```

2024-11-05 07:33 UTC, Fe-r-oz commented on ext/QuantumCliffordHeckeExt/lifted_product.jl
> +end
Thank you for these suggestions. I applied the `Oscar.FPGroup` list notation that Tommy introduced for specific stuff and applied it to `Hecke` out of curiosity for no particular reason.

2024-11-05 11:17 UTC, Fe-r-oz commented
Thank you for your suggestions. The PR is ready for review!

By the way, your 2BGA enhancement made the group algebra elements `A` and `B` look much prettier.

2024-11-05 12:50 UTC, merged