Check representation matrix commutation relation for the CSS orthogonality condition for 2BGA's Group Algebra
QuantumSavory/QuantumClifford.jl pull request #403
Opened 2024-10-23 22:18 UTC by Fe-r-oz

This PR implements the CSS orthogonality condition given by left and right representation matrix commutation relation of group algebra of the 2BGA code. This consistency check will be used in the `tests` PRs. This is inspired from insights from @thofma! 

Given that we are use a rich set of groups in the tests, this consistency test will be provide an additional crosscheck.

2024-10-24 03:57 UTC, Fe-r-oz commented
@Krastanov, This PR is ready for review. Thanks!  `check_repr_commutation_relation` will be used by the `tests` PRs to check the consistency of Group Algebra for 2BGA codes.

2024-10-25 02:58 UTC, Krastanov requested changes
This looks useful, thanks! I left a few questions below

2024-10-25 02:58 UTC, Krastanov commented on src/ecc/ECC.jl
> +    isdegenerate, faults_matrix, check_repr_commutation_relation,
let's not export it for now, just keep it as an internal check

2024-10-25 02:58 UTC, Krastanov commented on test/test_ecc_base.jl
> +@test check_repr_commutation_relation(GA) == true
Is this check expected to be used anywhere else if merged?

Also, you do not need to do `== true` -- the result is already a boolean

2024-10-25 08:01 UTC, Fe-r-oz commented
I have incorporated your suggestions, Thanks!

2024-10-29 04:13 UTC, Fe-r-oz commented on ext/QuantumCliffordHeckeExt/util.jl
> +    R_a = representation_matrix(b, :right)
typo, It should be `R_b` not, `R_a`

2024-10-29 05:20 UTC, Fe-r-oz commented on src/ecc/codes/lifted_product.jl
> +function check_repr_commutation_relation end
Move to `ECC\codes\util.jl` in ECC module

2024-11-05 04:05 UTC, merged

2024-11-05 04:05 UTC, Krastanov commented
thanks, this will be of great use throughout the tests