Simulate circuits containing PauliMeasurements using PauliFrames
QuantumSavory/QuantumClifford.jl pull request #412
Opened 2024-11-01 13:59 UTC by J-C-Q

This PR adds a layer of abstraction that uses option 2 of #411 to make it easier to simulate circuits containing PauliMeasurements using PauliFrames.

- The PauliFrame contractor adds an extra qubit (at the end), which then gets used as an ancillary qubits for the PauliMeasurements.
- The `apply!` function has a method for PauliMeasurements that basically reuses `ECC.naive_ancillary_paulimeasurement` to convert a PauliMeasurement to a list of gates (which already have `apply!` methods) that perform the measurement using the ancillary qubit.
- Since PauliMeasurement is parametric, add a `concrete_typeparams` method for PauliMeasurements to make `CompactifiedGate` possible. (I'm not sure if the one possible type parameter I specify here is exhaustive... probably not.)

2024-11-01 14:22 UTC, Krastanov requested changes
This is awesome, thank you!

I think we just need to add some tests (potentially including a test that uses `@allocated` to verify that memory is not churned).

2024-11-01 14:22 UTC, Krastanov commented on src/pauli_frames.jl
> +    apply!(frame, sMRX(n + 1, op.bit))
I think this should be `sMRZ`

2024-11-01 14:22 UTC, Krastanov commented on src/pauli_frames.jl
> +    stab = fastcolumn(zero(Stabilizer, frames, qubits + 1)) # TODO this should really be a Tableau
I agree with this change. I think now we need to update `show` and `nqubits` and maybe others. Thankfully, for `show` it can be as simple as using `@view frame[:,1:end-1]`

2024-11-01 14:22 UTC, Krastanov commented on src/pauli_frames.jl
> +    # this is inspired by ECC.naive_ancillary_paulimeasurement. Not sure if it's better to import and call that.
```suggestion
    # this is inspired by ECC.naive_syndrome_circuit
```

Better to keep it the way you did it here, as this is non-allocating while `naive_syndrome_circuit` would create a temporary array

2024-11-01 14:23 UTC, Krastanov commented on src/pauli_frames.jl
> +    stab = fastcolumn(zero(Stabilizer, frames, qubits + 1)) # TODO this should really be a Tableau
actually, we do not even have a show method implemented, so this probably only needs a correct `nqubits`

2024-11-01 15:43 UTC, J-C-Q commented on src/pauli_frames.jl
> +    apply!(frame, sMRX(n + 1, op.bit))
Of course...

2024-11-01 17:02 UTC, J-C-Q commented on src/pauli_frames.jl
> +    stab = fastcolumn(zero(Stabilizer, frames, qubits + 1)) # TODO this should really be a Tableau
I subtracted the ancillary qubit in the `nqubits(f::PauliFrame)` function. I think that should be fine.

2024-11-01 17:31 UTC, Krastanov commented
The test failures happen due to this: https://github.com/QuantumSavory/QuantumClifford.jl/blob/f69e49ccfb91d7fd85bda16a846c34d22c500399/test/test_ecc_syndromes.jl#L33-L36

The cleanest way to fix this is probably to do `mul_left!(tab(naive_frames), pₙ)` instead of `mul_left!(naive_frames.frame, pₙ)`

with a newly defined

```
tab(p::PauliFrame) = @view p.frame[:,1:end-1] # to account of the buffer ancillary qubit
```

2024-11-01 18:33 UTC, J-C-Q commented
Somehow this is more complicated because the `view` implementations for `PauliFrame`, `Stabilizer` and `Tableau` only allow one dimensional indexing as far as I can tell.

2024-11-01 18:40 UTC, Krastanov commented
darn, you are right. Thankfully, here we are adding a qubit at the very end, so there is still an easy workaround

```
tab(pf::PauliFrame{Stabilizer{Tableau{V,F}}, M}) where {V,F,M} = Tableau{V,F}(pf.frame.tab.phases, pf.frame.tab.xzs, nqubits(pf))
```

If I am not getting this wrong, the internal indexing utilities of `Tableau` will take care of skipping over the extra qubit. This would need some testing though

2024-11-04 14:34 UTC, J-C-Q commented
Sadly, this doesn't seem to work.

I guess the internal indexing doesn't skip over the last qubit. And removing it from the `xzs` reference is not feasible...

I don't think there are many other options... Probably, silently adding one extra qubits is not such a good idea.

2024-11-04 14:59 UTC, Krastanov commented
I still like the way you have set this up and I suspect there is something pretty minor left to fix. I should be able to look into it around the end of the week.

2024-12-20 20:44 UTC, Krastanov commented
finally got some time to look into this. Just as an FYI, the only example that causes errors are the LP118 family of LDPC codes (which also happen to be the largest codes we are considering, so it is probably related to some off-by-one error when we need more than 1 uint word to store the qubits)

2024-12-21 07:39 UTC, Krastanov commented
The fix ended up being extremely simple -- just adding a +1 to the size of a random pauli generated in one of the tests (due to the new buffer qubit). This is an internal detail that was used in the test, not breaking and public API.

But then I spent another hour or two adding extra tests just to make sure nothing was missed.

If the tests pass here, this should be merged and released shortly.

Thank you so much for the contribution! Do not hesitate to suggest other improvements as you play with this tool

2024-12-21 16:20 UTC, merged

2024-12-21 19:40 UTC, J-C-Q commented
Thank you for the incredible effort you put into this! Your dedication and hard work are truly appreciated. It was a pleasure to collaborate on such a fantastic project!