noncliff: add tests for conjugate destabs
QuantumSavory/QuantumClifford.jl pull request #413
Opened 2024-11-02 13:23 UTC by Fe-r-oz

This PR removes the TODO comment and add tests for conjugation. This PR is inspired from this comment: https://github.com/QuantumSavory/QuantumClifford.jl/pull/408#issuecomment-2452981604

2024-11-02 13:33 UTC, Krastanov requested changes
That would be very useful, thank you! I added a comment on a few improvements that can be made to make the tests more rigorous

2024-11-02 13:33 UTC, Krastanov commented on test/test_nonclifford_quantumoptics.jl
> +        for s in [S"X", S"Y", S"Z", S"-X", S"-Y", S"-Z"]
to make the tests more trustworthy we should have multi-qubit cases and cases of non-clifford operations -- it can be in a separate testset to keep this already nice testset easy to read. The extra testset can contain stuff like:

```
for n in [5, 10, 100]
    for g in [tHadamard, tPhase, pcT]
        eg = embed(g,...)
        sm = GeneralizedStabilizer(random_stabilizer(n))
        ...
```

2024-11-02 14:27 UTC, Fe-r-oz commented on test/test_nonclifford_quantumoptics.jl
> +        for s in [S"X", S"Y", S"Z", S"-X", S"-Y", S"-Z"]
`embed` is not defined for `CliffordOperator`, only for `PauliOperator`, so instead used: `enumerate_cliffords(4, clifford_cardinality(4))` for multi-qubit` CliffordOperators`. I hope you like it.

2024-11-02 14:53 UTC, Fe-r-oz commented
Thank you for your speedy comments and insights. That is much appreciated! 

I hope this is satisfactory. `n=100` crashed my PC so just used `n=10` max.

2024-11-02 17:39 UTC, Fe-r-oz commented on test/test_nonclifford_quantumoptics.jl
> +        for s in [S"X", S"Y", S"Z", S"-X", S"-Y", S"-Z"]
Instead of `embed` for `CliffordOperator`, we can use `CliffordOperator(sHadamard(2), 5)`... darn...

2024-11-03 14:34 UTC, Krastanov commented on test/test_nonclifford_quantumoptics.jl
> +        (5, [enumerate_cliffords(5, clifford_cardinality(5)), CliffordOperator(sHadamard(5), 5), CliffordOperator(sCNOT(2, 3), 5)])
this seems unnecessarily complicated. And the number of qubits is something that does not need to be specified separately

in particular, is there something special about `enumerate_cliffords(n, clifford_cardinality(n))` that you are picking this choice

I will submit a few simplification suggestions later today

2024-11-03 14:48 UTC, Fe-r-oz commented on test/test_nonclifford_quantumoptics.jl
> +        (5, [enumerate_cliffords(5, clifford_cardinality(5)), CliffordOperator(sHadamard(5), 5), CliffordOperator(sCNOT(2, 3), 5)])
> is there something special about enumerate_cliffords(n, clifford_cardinality(n)) that you are picking this choice

Nope. No particular reason for the choice of parameters for `enumerate_cliffords`.


Thank you!

2024-11-03 15:12 UTC, Krastanov commented on test/test_nonclifford_quantumoptics.jl
> +        (5, [enumerate_cliffords(5, clifford_cardinality(5)), CliffordOperator(sHadamard(5), 5), CliffordOperator(sCNOT(2, 3), 5)])
to keep in the spirit of having a random check you can also just do `enumerate_clifford(3, rand(1:clifford_cardinality(3)))`, but at this point it is just simpler to stick to `random_stabilizer`

2024-11-03 15:13 UTC, Krastanov commented
thanks for pushing through this, it is very helpful cleanup. Let's wait to see what the new tests say

2024-11-05 03:53 UTC, merged