embed for single-qubit Clifford Operator
QuantumSavory/QuantumClifford.jl pull request #415
Opened 2024-11-02 17:20 UTC by Fe-r-oz

The PR #413 revealed to us that we don't have `embed` for single-qubit  dense/symbolic Clifford Operator or two-qubit dense/symbolic Clifford Operator.  Thus, this PR attemps to define `embed` for single-qubit Clifford Operator, thereby addressing a chunk of #151

I hope that this attempt makes sense.

Before:

```
julia> tHadamard
X₁ ⟼ + Z
Z₁ ⟼ + X
```

After:

```
julia> embed(5, 3, tHadamard)
X₁ ⟼ + __Z__
X₂ ⟼ + __Z__
X₃ ⟼ + __Z__
X₄ ⟼ + __Z__
X₅ ⟼ + __Z__
Z₁ ⟼ + __X__
Z₂ ⟼ + __X__
Z₃ ⟼ + __X__
Z₄ ⟼ + __X__
Z₅ ⟼ + __X__
```

Before considering your pull request ready for review and merging make sure that all of the following are completed (please keep the clecklist as part of your PR):

- [x] The code is properly formatted and commented.
- [x] Substantial new functionality is documented within the docs.
- [x] All new functionality is tested.
- [x] All of the automated tests on github pass.
- [x] We recently started enforcing formatting checks. If formatting issues are reported in the new code you have written, please correct them. <small>There will be plenty of old code that is flagged as we are slowly transitioning to enforced formatting. Please do not worry about or address older formatting issues -- keep your PR just focused on your planned contribution.</small>

2024-11-02 19:56 UTC, Fe-r-oz commented
The PR is ready for review. Thank you!

2024-11-03 14:29 UTC, Krastanov requested changes
Thanks for looking into this. Do we need an embed for these though? They already work fine on arbitrary number of qubits, i.e. they are already implicitly embedded. You can run `apply!(stab, sCNOT(1,2))` on any size `stab` (if anything, an embed here would make thinks slower). You can not do that with `apply!(stab, tCNOT)` so an embed is needed. 

I guess adding this functionality makes sense just for completeness, but there should be a warning in the docstring that this is a bad way to do it.

Also, it seems there is a single docstring for one of the methods that includes what is supposed to be a docstring for the other method. This should be two separate docstrings (if they are method dosctrings).

Lastly, the single-qubit embed should still permit one-tuples as argument types for `i` to be consistent with the rest of the `embed` methods

2024-11-03 14:30 UTC, Krastanov commented
also, new functionality like this needs tests

2024-11-03 15:04 UTC, closed without merging

2024-11-03 15:04 UTC, Fe-r-oz commented
Thank you for your comments.

> Do we need an embed for these though? 

Actually, I considered closing this PR since the embedding is already handled implicitly. While it’s worth exploring alternative approaches while looking into #151, the final outcome here doesn’t offer much added value. 

Instead of adding code that SLOW DOWN performance || is a BAD way to do things || might introduce redundant checks, we can simply update the documentation to clarify that the embedding is implicitly supported.

This also seems like an inefficient use of your valuable review time.

So, let's just close it :)