noncliff: enhanced error message for inapplicable Project! of GeneralizedStabilizer
QuantumSavory/QuantumClifford.jl pull request #416
Opened 2024-11-03 07:01 UTC by Fe-r-oz

I have incorporated the relevant details from the paper to create an informed error message. This PR is inspired from this comment: https://github.com/QuantumSavory/QuantumClifford.jl/pull/355#discussion_r1826569150

I think we only need one `proj,` so removed `_proj₋ `or `_proj₊` in favor of `proj`. 

- [x] The code is properly formatted and commented.
- [x] Substantial new functionality is documented within the docs.
- [x] All new functionality is tested.
- [x] All of the automated tests on github pass.
- [x] We recently started enforcing formatting checks. If formatting issues are reported in the new code you have written, please correct them. <small>There will be plenty of old code that is flagged as we are slowly transitioning to enforced formatting. Please do not worry about or address older formatting issues -- keep your PR just focused on your planned contribution.</small>

2024-11-03 15:35 UTC, Fe-r-oz commented
The PR is ready for review. Please run it on the console to check if any further formatting changes are required. 

Thank you!

2024-11-05 14:31 UTC, Krastanov requested changes
looks good! I will do some minor rewording on the next round of review, but first check out below for how this can be packaged a bit more neatly into Julia's error handling mechanism.

2024-11-05 14:31 UTC, Krastanov commented on src/nonclifford.jl
> +project!(::GeneralizedStabilizer, ::PauliOperator) =
this can be done a bit more neatly using `MethodError` and a registered error hint.

E.g. throw `throw(MethodError(f, (sm,p)))` where sm and p are the arguments to this function.

Then use `register_error_hint` to register the additional explanation message: https://docs.julialang.org/en/v1.12-dev/base/base/#Base.Experimental.register_error_hint

2024-11-05 15:24 UTC, Krastanov commented
marking as draft to make it easer for me to track what needs review

2024-11-05 23:59 UTC, Fe-r-oz commented on src/nonclifford.jl
> +project!(::GeneralizedStabilizer, ::PauliOperator) =
Thanks so much for the suggestion!

2024-11-06 00:13 UTC, Fe-r-oz commented
Thank you! I have incorporated your comments and checked the output on console. 

Thank you for rewording as you see fit!

2024-11-08 21:14 UTC, merged

2024-11-09 08:08 UTC, Fe-r-oz commented
Thank you for polishing the PR!