noncliff: add copy, == for GeneralizedStabilizer, UnitaryPauliChannel
QuantumSavory/QuantumClifford.jl pull request #419
Opened 2024-11-03 21:09 UTC by Fe-r-oz

This PR is inspired from this comment: https://github.com/QuantumSavory/QuantumClifford.jl/pull/355#discussion_r1826568457

2024-11-03 21:48 UTC, Krastanov requested changes
That is very useful, thank you! I have a minor worry about the use of deepcopy, explained below.

2024-11-03 21:48 UTC, Krastanov commented on src/nonclifford.jl
> +Base.copy(p::UnitaryPauliChannel) = deepcopy(p)
using `deepcopy` as an implementation of `copy` is a bit dangerous. It frequently works fine, but if you have views into some other memory it can produce unexpected results. The more boilerplate-heavy "Constructor on copied slot entries" is much safer here.

2024-11-03 22:43 UTC, Fe-r-oz commented on src/nonclifford.jl
> +Base.copy(p::UnitaryPauliChannel) = deepcopy(p)
My bad...

2024-11-03 23:06 UTC, Fe-r-oz commented on src/nonclifford.jl
> +Base.copy(p::UnitaryPauliChannel) = deepcopy(p)
Since tuples are immutable, I used `p.weights` or `p.paulis` instead of `copy(p.weights)`, `copy(p.paulis)` etc.

2024-11-04 14:34 UTC, Krastanov requested changes
You encountered an interesting quirk of julia when you were trying to copy a tuple. See the comment I added below.

2024-11-04 14:34 UTC, Krastanov commented on src/nonclifford.jl
> +Base.:(==)(p₁::UnitaryPauliChannel, p₂::UnitaryPauliChannel) = p₁.paulis==p₂.paulis && p₁.weights==p₂.weights
The tuples might be immutable, but the objects they contain are not-necessarily immutable. E.g. if I do something stupid like `mul_left!(p.paulis, some_other_pauli)` on a copied `p`, the original `p` would also be modified. I am stupid to do that to begin with, but nonetheless I would be right to be surprised that modifying the copy modified the original as well.

More generally, let the compiler worry about immutability unless you know for a fact that the compiler is doing a bad job. The compiler can figure out when immutability guarantees let it reuse memory:

Lastly, you are probably doing this because `Tuple` does not have a `copy` method. That is a frustration I have with julia -- the story behind it can be found starting in this discussion: https://discourse.julialang.org/t/why-can-i-deepcopy-nothing-but-not-copy-nothing/112429 (in particular see the links by stevengj).

Anyway, to make sure this is an actual copy, the clunky but necessary `map(copy, p.paulis)` can be used.

2024-11-04 14:56 UTC, Fe-r-oz commented on src/nonclifford.jl
> +Base.:(==)(p₁::UnitaryPauliChannel, p₂::UnitaryPauliChannel) = p₁.paulis==p₂.paulis && p₁.weights==p₂.weights
Thank you for these insights! I avoided using `copy(p.paulis)` so it wouldn’t look stupid.

2024-11-05 03:21 UTC, merged

2024-11-05 03:21 UTC, Krastanov commented
thank you!