noncliff: Inner Product between two GeneralizedStabilizers
QuantumSavory/QuantumClifford.jl pull request #423
Opened 2024-11-07 10:06 UTC by Fe-r-oz

This PR implements the Inner Product between two Generalized Stabilizers. Inspired from V.Section B of the base paper.

2024-11-07 11:51 UTC, Fe-r-oz commented
The PR is ready for review. There is an unrelated doctest errors that were fixed in #416 that is why one extra CI-error.

Thank you!

2024-11-08 21:22 UTC, Krastanov requested changes
Thanks for starting this! I think there is a bit of a misunderstanding of what the paper is actually doing. The approach implemented here is exponentially slower than the appropriate algorithm from the paper.

2024-11-08 21:22 UTC, Krastanov commented on ext/QuantumCliffordQOpticsExt/QuantumCliffordQOpticsExt.jl
> +julia> using QuantumOpticsBase; using LinearAlgebra; # hide
do not hide these, otherwise the reader might not know how to run these examples

2024-11-08 21:22 UTC, Krastanov commented on ext/QuantumCliffordQOpticsExt/QuantumCliffordQOpticsExt.jl
> +    return real(tr(Operator(sm₁)' * Operator(sm₂)))
This just converts the two generalized stabilizers to density matrices. This is an exponentially expensive operation that does not seem to be implementing what is shown in the paper. This can be a useful correctness test in the test suite, but it is not an appropriate implementation for this library.

2024-11-08 21:22 UTC, Krastanov commented on test/test_nonclifford_quantumoptics.jl
> +        @test dot(sm, smcopy) ≈ 1
having tests that do not always use the same state on both sides would make this much more trustworthy

2024-11-22 02:22 UTC, closed without merging

2024-11-22 02:22 UTC, Fe-r-oz commented
> I think there is a bit of a misunderstanding of what the paper is actually doing.

Yup. The stabilizer union between two generalized stabilizers is a prerequisite for the original in-place implementation described in the paper. The algorithm relies on the subroutine detailed in Theorem 16, called 'stabilizer union.' I think we can leverage the` pauli_group` (G(U)), as part of the process involves decomposing the generators and checking their presence in G(U). Given this, it makes sense to close this for now and prioritize completing and submitting the stabilizer union implementation first.